== A Selection from the Life of William Dewsbury

I was conceived in sin and brought forth in iniquity,
and in that state I lived and delighted in pride and pleasures, in lightness and vanity,
as all do who are in that nature, until I was about eight years of age.
But even before that time, when I lived in vanity,
the light of Christ in my conscience witnessed against me and caused me trouble,
but I departed from this light, and followed the counsel of my own heart,
which led me into vanity, to live without the fear of God.

And about the time when I was eight years of age (in my natural birth),
the Word of the Lord came unto me, saying, "`I created you for My glory,
and an account you must give to Me of all your words and actions done in the body.`"
This word enlightened my heart and opened the book of conscience in me,
where all was written that I had ever done in the body since I had any remembrance.
And when I had read my condition in this book,
how I had lived without God who created me for His glory,
the Word of the Lord then came unto me again saying,
"`Shall the ax boast itself against him who chops with it?
Or shall the saw exalt itself against him who saws with it?
As if a rod could wield itself against those who lift it up,
or as if a staff could lift up, as though it were not wood!`"^
footnote:[Isaiah 10:15]
And by the power of this Word of the Lord that spoke in me,
my understanding was enlightened,
and my conscience bore witness that this was my condition.
Indeed, I had lifted up myself against the living God by living without His fear,
who created me to live in obedience to Him,
but I had lived in disobedience to Him until that day.

Then deep sorrow seized upon me,
and I knew not what to do that I might gain an acquaintance with the God of my life,
who created me for His own praise and glory.
I ceased from my vain conduct in which I had lived,
and began to read the Scriptures and other books,
and to mourn and pray to a God I knew not.
Nor did I know where He was, but expected to meet with Him outwardly,
looking up towards the firmament where my carnal mind imagined Him to be.
And this I had also heard from those who the world calls "`ministers`",
who I often went to hear,
and whose words did agree with my own carnal imaginations of God.
They said that God was above the skies,
and that they called "`heaven;`" but I felt the hand of the Lord within me,
executing justice upon the wicked nature in me.
And no matter which way I turned to seek Him in outward observations,
there the flaming sword turned, which was placed to guard the way to the tree of life,
and executed the righteous justice of God upon me.

So I remained before the throne of the Lamb,
reading in my mournful condition the sentence of condemnation,
which passed upon me from the glory of His presence.
In this condemned state I continued, and through ignorance of where God was,
or what His worship was, I strove to satisfy His justice in outward observations,
imitating what other saints had done in the Scriptures of truth,
sometimes in fasting and prayer,
which was the practice of Cornelius and others of the saints of the Most High God.
But notwithstanding all of my strict walking and careful observations,
in which I was seeking the kingdom of God, still I found Him not,
but the flaming sword always found me and cut me down.
Thus my sorrow increased, for I found none in my condition with whom I could speak.

Then it pleased the Lord to order my friends (in the flesh) to put me to watch sheep,
where I was retired from all company, and my mind was kept in a mournful state,
where my only relief was in mourning to a God I knew not,
nor could any tell me how to gain an acquaintance with Him.
This place where I dwelled (as to my outward man) was a town called Allerthorpe,
near Pocklington in Yorkshire.
But hearing of a people near Leeds that walked more strictly
in their religious profession then any where I was,
I had no rest in my spirit until my parents (in the flesh) sent me there to be an apprentice.
I cared not in what trade I might be placed,
so long as I could be among those who feared the living God,
and become acquainted with the God of my life, who had created me for Himself.
And this desire, that the Lord had raised up in me,
was answered when I was thirteen years old (in my natural birth),
for I was bound an apprentice to a clock-maker in a town called Holbeck, in Leeds.

And as I had heard, so I found it to be, for there was much speaking of God,
which they called preaching,
and much professing Him in words from the letter of the Scripture,
according to what the saints had formerly spoken forth,
imitating the saints practices in their carnal wisdom,
and seeking the kingdom of God in outward observations,
as I had done before I came there.
But I met with no one who could tell me what God had done
for their souls in redeeming them from the body of sin,
which I groaned under, and which separated me from the presence of God,
even though I walked strictly with them in their outward observations,
running to hear one man after another,
who they called "`ministers,`" and yet finding no rest or peace to my weary soul,
but only the flaming sword.
For the righteous law of God cried out in me for a perfect fulfilling of His righteousness,
and it met with me wherever I was,
so that I could find no peace in the worship that the world had set up,
or in receiving the bread and wine, which they told me were the seals of the covenant.
Indeed, it was long before I dared receive it, because I saw myself not prepared;
for the evil of my heart stood plainly before me.
And when at last I was about to receive it,
I sought the Lord to keep me by His power that I might receive it worthily.
And when I did, my desire was that the Lord would seal up His love to my soul;
but I found nothing sealed up to my soul by outward bread and wine.

Because of this, great fear seized upon my soul for a long time,
and Judas`'s condition was cast into my mind,
until at last it was shown to me that the seal of the covenant was the Spirit of Christ,
and no outward element;
and that the supper was the body and blood of Christ which the world does not know,
and neither did I at that time, but was made to wait for the manifestation of it to me.
Then I no longer dared to join with the world in that practice;
nor in their practice of singing David`'s conditions, which they called worship.
For the light in my conscience let me see the evil of my heart,
that I was not in David`'s condition.
The sense of this did stop my mouth, so that, while others were singing,
I mourned and wept for lack of the pure spirit that
David had experienced which caused him to sing.
Nor could I apply the promises of Scripture which they said belonged to me,
for I found no promise belonging to the nature in which I then lived,
but rather the wrath of God,
which I felt to abide on me for disobeying the counsel
made known to me by His light in my conscience.
And being ignorant that this light _was_ His counsel, I often departed from it,
and lent my ear to those without, men who said they spoke as the mouth of the Lord.
So I was deceived, and was made to err by their lies,
which drew me to seek the kingdom of God in outward observations,
even while the Word of the kingdom was within me,
executing the righteous justice of God upon my adulterous heart.

And this went on until I was greatly worn down, and my body was made so weak,
that I was not able to answer the expectation of
the man with whom the Lord had placed me,
though my conscience was clear, for I always did what I could.
And this man, in his wisdom from below, thought I was in a consumption,
and sometimes thought it best to send me away to my friends in the flesh,
and at other times desired to call upon the men whom the world calls doctors,
that they might apply some things to my body for my recovery;
but I was not free to let him, except for once when I feared giving offense.
For I knew my infirmity was the evil of my heart
which separated me from the presence of my God,
and how to be free from it, this none could tell me.

And when I found no help in outward practices, in reading, praying, hearing,
or meditating on what I heard, my sorrow and misery became so great,
that it constrained me to run to those whom the world calls ministers and professors,
and to whoever appeared to have the most acquaintance with God.
I asked them what I might do to be saved, and they spoke to me smooth things,
saying I must only believe in the name of Jesus Christ, and apply the promises;
but that Christ was to be found within me, I heard no one say.
And this only added to my sorrow,
for I was told to believe in a Christ that I could not find.

This was the time when the wars began in this Nation,^
footnote:[The English Civil War.
This was a series of conflicts between the Parliamentarians (also known as Roundheads),
led by Oliver Cromwell, and the Royalists (or Cavaliers),
who supported King Charles I. The conflict ended with the defeat of the Royalists,
the trial and execution of King Charles I in 1649,
and the establishment of the Commonwealth of England,
with Cromwell eventually becoming "`Lord Protector.`"]
and my eyes being still abroad,
I greatly desired to help my inward life by some outward means.
And those who were called ministers cried out for
men to go forth to help the Lord against His enemies,
and I was then willing to give my body unto death in obedience to my God,
in hopes to free my soul from sin, escape the wrath I lay under,
and at last gain acquaintance with Him.
So I joined with a little remnant that said they fought for the Gospel,
but when I was among them I found as much ignorance
of the Gospel as I had met with before.
No one told me what the Gospel was, but spoke only of the dead letter,
which is the outward testimony and declaration of the Gospel;
but the Gospel itself is Christ, who is the glad tidings to sinners.
But these men called the dead letter the Gospel, as I had often heard before,
so I found no rest for my soul among them.

Then I heard that there was a reformed Church in
Scotland who walked in the fear of the Lord.
So I journeyed to that country, and went to Edinburgh,
where I found nothing but formality,
for their teachers called the people to seek the kingdom of heaven in outward observations,
just as I had heard in England.
And when I had returned to England again,
I went among those who called themselves Anabaptists and Independents,
who were setting up an even more glorious image in outward observations,
saying they were the children of God; but I found I could not join with them,
for the cry of my soul was after the testimony of God`'s love.
And then the Lord revealed to me that His love could not be attained
by anything I could do in outward practices and observations;
and that no matter which way I turned in my carnal wisdom,
seeking the kingdom of God in outward things,
there the flaming sword would turn to meet me, guarding the way to the Tree of Life.
Indeed, it fenced me out, cut me down, and tore all of my fig-leave coverings.
It frustrated the mind that looked outward for the kingdom of Heaven,
and the ear that sought the Word of God from men.

And then my mind was turned within by the power of the Lord,
to wait for His counsel--His light in my conscience--to hear what He would say.
And at last the Word of the Lord came unto me and said,
"`Put your sword into your scabbard.
If My kingdom were of this world, then My children would fight.
Do you not know that if I had need,
I could have twelve legions of angels from My Father?`"
This word enlightened my heart, and unveiled the mystery of iniquity in me,
and made me to see that the kingdom of Christ was within,
that the enemies were also within and were spiritual,
and that the weapons used against them must be spiritual, that is,
they must be the very power of God.
Then I could no longer fight with a carnal weapon, against the outward man,
over interpretations of the dead letter, which they called the gospel.
And the Lord let me see me the deception of all the men in England
who were seeking the kingdom of Heaven in outward observations.
And so the Messenger of the covenant,
with the two-edged sword that proceeds from His mouth to slay His enemies,
came forth at that time and cut me down, and caused me to yield in obedience.
So I put my carnal sword back into its scabbard and left the army.

I then returned home to my outward habitation and calling,
and there labored with my hands,
my mind being continually turned within to wait upon the Lord in the way of His judgements.
And thus I began to witness in myself the inward administration of the law of Moses,
by which Cain is banished, Esau is reprobated, Pharaoh is plagued,
and the firstborn of Egypt is slain.
My will was brought into subjection to the Lord, to do with me what He desired;
to condemn if He saw fit, or to save me in His own free love.
And in this condemned state, I lay crying in the depth of misery for a time,
without any hope of deliverance by anything I could do to pacify the wrath of God,
until the administration of the Prophets made manifest to my soul
that there was redemption laid up for me in the Lord Jesus Christ.
Then, by the power of the Word of their testimony,
there was a secret hope raised up in me to wait for His coming;
and there I waited until the administration of John.
And truly I can testify, that of all that is born of a woman,
there is none greater than John;
for his administration is like a burning and a shining light,
and it uncovered even more of the mystery of iniquity in me,
and made manifest the true sense of my condition.
And then the cry of my condemned soul was great and could not be satisfied,
and I breathed and thirsted after Christ to save me freely through His blood,
or I would perish forever.

And in this condition I lay waiting for the coming of Christ Jesus,
who in the appointed time of the Father appeared to my soul,
as the lightning that flashes from the East to the West.
My dead soul heard His voice, and by His voice was made to live,
being born anew unto a living hope,
and sealed in the everlasting Covenant of life with His blood.
Then I witnessed the wages of sin to be death,
and the gift of God to be eternal life through Jesus Christ my Lord;
and I can testify together with the Scriptures,
that death reigns over all from Adam to Moses, and Moses until the Prophets,
and the Prophets until John, and from that day the kingdom of heaven suffers violence,
and the violent take it by force.
For truly, there is no rest to the soul until Christ be manifest in it.
Of this the Scriptures bear witness;
and I witnessed these Scriptures fulfilled in me in the year 1645.

Now, the two witnesses that stood before the God of the earth
had power to plague the earth with their judgments.
And having finished their testimony, the beast then ascended out of the bottomless pit,
made war against them, overcame them, and killed them,
and their dead bodies lay in the street of the great
city which spiritually is called Sodom and Egypt,
where also our Lord was crucified.
This Scripture was fulfilled in me in the year 1648.

And then the peoples,
tongues and nations of the earth made merry over the two slain witnesses;
and I saw the abomination that makes desolate, which is spoken of by Daniel the prophet,
standing in the holy place where it ought not to be.
And then I was led by the Spirit into the wilderness to be tempted of the Devil,
that I might experience the Scripture fulfilled, Luke 4:1.

And in that day and hour of temptation,
I witnessed the Scriptures describing Paul`'s condition fulfilled in me,
wherein he complained (as I then did) that he found a law
in his members warring against the law of his mind,
and that when he desired to do good, evil was present with him.
The sense of this caused me to cry out, "`Oh wretched man that I am!
Who shall deliver me from the body of this death?`"
And as I was crying to the Lord to free me from the burden that I groaned under;
the Word of the Lord came unto me saying, "`My grace is sufficient for you,
I will deliver you.`"
And by the power of His Word I was armed with patience to wait in His counsel,
groaning under the body of sin in the day and hour of temptation,
until it pleased the Lord to manifest His power to free me, which was in the year 1651.

And then the Spirit of life from God entered into the witnesses,
and they stood upon their feet, and great fear fell upon all that saw them.
And the temple of God was opened in Heaven,
and I saw in His temple the ark of His testament, and there was lightning, thunder,
earthquakes, and great hail.
And then Mystery Babylon the Great, the mother of harlots, the abomination of the earth,
which made all nations drunk with the wine of the wrath of her fornication,
was discovered in me, and God remembered her,
and caused the Lord`'s power to be manifest upon her.
For Jesus Christ was revealed from heaven in flaming fire,
pouring vials of wrath upon Babylon,
and rendering vengeance upon all in me that disobeyed His Gospel,
purging away the filthy nature that had taken possession of me,
with the spirit of judgement and with the spirit of burning.
So that through the righteous law of life in Christ Jesus I was made free, and am free,
from the body of sin and death.
For through these great tribulations my garments have been
washed and made white in the blood of the Lamb,
who has led me through the gates of the city into the new Jerusalem,
where nothing enters that defiles, or causes an abomination or a lie,
but only that which is written in the Lambs book of life,
where my soul now feeds upon the Tree of Life that
I had so long hungered and thirsted after,
which stands in the Paradise of God.
Here there is no more curse, and no more night,
but the Lord God and the Lamb is my light and life forever and ever.
And I now bear witness that I am regenerated and born again of the immortal seed,
and have partaken of the first resurrection, over which the second death has no power.

And this I declare to all the inhabitants in England,
and to all that dwell upon the earth, that God alone is the Teacher of His people,
and has given to everyone a measure of grace, which is the light that comes from Christ,
that checks and reproves for sin in the secret of the heart and conscience.
And all who will wait in this light which comes from Christ (which is
the free grace of God) for the power of Jesus Christ to destroy sin,
and to guide them in obedience to the light,
will certainly come to know the only true God and Father of lights, and Christ Jesus,
who is the way to Him.
And I bear witness to all the sons of men,
that I came not to the knowledge of eternal life by the letter of the Scripture,
nor by hearing men speak of the name of God;
but rather I came to the true knowledge of the Scripture
and the eternal rest by the Spirit of Jesus Christ,
the Lion of the Tribe of Judah, who alone is found worthy to open the seals of the book.
And I testify that no one else can do it,
for He alone opened the seals of the book in me,
and sealed it up to my soul by the testimony of His own Spirit,
according to His own promises, "`I will bind up the testimony,
and seal the law among My disciples,`"^
footnote:[Isaiah 8:16]
and "`I will write My law in their hearts, and put My spirit in their inward parts,
and they shall not depart from Me;
neither shall they need to teach every man his neighbor, and every man his brother,
for all shall know Me from the least of them to the greatest;
for I will be merciful to their unrighteousness,
and their sins and iniquities I will remember no more;`"^
footnote:[Jeremiah 31:31-34]
and, "`All your children shall be taught by the Lord,
and great shall be the peace of your children.`"
Of all these things the Scriptures bear witness,
and I witness these Scriptures fulfilled in me--praises, alleluia,
and eternal praises be unto You Lord God Almighty,
because You have taken Your great power and reigned.

And because it has been charged upon me in this my imprisonment
to give a reason for the hope of my calling,
I have here declared the work of the mighty God in revealing His Son in me,
in order to stop the lying mouth of the false accuser,
to clear the truth of all lies that have been laid upon it,
and to declare the truth as it is in Jesus to all souls who seek after it.
For the Lord has led me on my journey through the dark world,
where I passed through great tribulations (as formerly mentioned),
until I came to the end of that world,
and was made to rejoice over it in the power of my God.
Indeed, Paul wrote to those "`upon whom the ends of the world had come,`"^
footnote:[1 Corinthians 10:11]
which world lies in wickedness, and so hates and persecutes.
But to the eye that is kept single, which eye is not of this world, I bear my testimony,
that all may see that these are no "`seducing words`" or
"`blasphemies detrimental to the truth of the gospel,
and the peace of the nation,`" but rather words of truth and soberness,
for which I am kept in bonds in the common jail in Northampton,
and numbered among transgressors in the low prison,
with those arraigned for felony and murder,
waiting in rest and peace until the sufferings of the righteous seed be fulfilled.
And now, to all who are enemies to the truth of God,
persecuting it under a variety of false names,
this I declare and confess unto you in the presence of God:
that according to the Way which you call a seducing sect,
so I worship the God of my fathers,
and witness the fulfilling of all that is written in the law and the prophets.
He that is able to receive it, let him receive it.

And now, I say to every man and woman into whose hands this comes:
Behold and see how you have fallen from the state and condition in which you were created.
You were created in the image of God to delight in Him alone,
but you have fallen by obeying the counsel of the serpent,
and are driven out from the presence of God into the earth,
and there your mind feeds upon the dust of the earth, created objects which will perish.
Some delight in father and mother, some in wife and children, some in house and lands,
some in money and gold, some in food and drink, some in clothes and adornments,
some in lusts and pleasures, or in licentiousness, in vain and idle communication,
in foolish jesting and laughter, which is madness and folly,
and some in honor and promotion in this world.
And there are some that feed upon the bare letter of the Scripture, which is death,
seeking to comprehend God and Christ in their own wisdom according to what the saints
of the Most High God spoke forth from the life they enjoyed in Christ Jesus,
who was in them the hope of their glory.
But man, in his serpentine wisdom, pulls the saints words into his own understanding,
though he knows not the life and power of them in himself,
and so speaks a divination of his own brain, which is a riddle to his own heart;
and while he speaks to others, he himself is a cast-away.

So then, every man and woman in particular, deal justly with your own hearts!
Look and see where your hearts are, and in what they delight,
for it cannot be but that you delight in and feed upon some of these created objects,
if you cannot witness your heart changed by the eternal and powerful Word of Truth.
For you have been driven from the presence of God into the earth,
and the fruits which spring up in the cursed earth, which is in your hearts, are these:
self-love, pride, covetousness, anger, revenge, hastiness, disobedience, back-biting,
hard-heartedness, cruelty and oppression, lust and uncleanness, drunkenness, impatience,
and unbelief.
And in this nature you are kept from the paradise
of God by the Cherubim and the flaming sword,
which turns every way to guard the way to the Tree of Life.

Therefore, look to yourselves,
and let all examine what they have truly experienced of a return again unto God,
from the disobedience and evil of your hearts that has separated you from Him.
See what is the ground of your hope,
and by what power you are moved in your obedience unto God,
whether it be by the power of the first Adam, or by the power of the Second.
For if, upon your convincement of the evil of your ways,
you do not wait in the light (that showed you the evil) for power from
the Lord to depart from all evil that is made manifest by the light,
but rather run on in the wisdom of the first Adam into observations, doctrines,
practices and forms, you are yet alive in the first Adam,
sewing fig-leaves together to cover you nakedness.
Yes, you are patching a new piece of cloth onto an old garment,
putting new wine into old wineskins,
building a tower to reach unto God in Babylonish wisdom,
and in the end confusion will be your portion.
For in the day when the Lord comes to look for fruit,
you will be found a fruitless tree that cumbers the ground.
You will be Cain with his offering in the first nature,
and Esau seeking the birthright with tears,
and the only fruit in your bosom will be from Hagar the bondwoman,
for you regard not the glory of the Lord, and His fear is not before your eyes.

Therefore, every man and woman,
under whatever name or denomination you are--whether you be teachers of others,
or professors of words that other men gave forth from the
life and power of Christ that was in them--I say to you,
deal justly with your own hearts!
For if you expect life from your outward forms, doctrines and practices,
but are not guided by the light of Jesus Christ in your own conscience
(the light that guided the saints who gave forth the Scriptures),
then profess what you will, so long as you disobey the light, you are in the fall,
and the first Adam is yet alive in you.
Cain is not yet banished, nor Esau reprobated,
nor has the bondwoman and her son been cast out--all of which are
figures and types of the first nature which remains alive in you.
And here, your own will is your guide, and your heart is in the earth,
regardless what you profess.
You are yet a painted beast, made drunk with the wine of the harlot,
living above (and not under) the cross of Christ.
And all such will be found thieves and robbers,
who have not come in by the door Jesus Christ, but have climbed in another way.

The scribes and the Pharisees came this far in religion.
Yes, the rich young ruler kept the commandments of God from his youth,
but when he should have sold all for Christ, he went away sorrowful.
Paul came this far when he yet ravaged the church,
walking blameless according to the law, while persecuting Christ.
And all of your notions and strict observations according to the
letter are but a striving to get to the Tree of Life by your power,
but the Cherubim meets you, and the flaming sword turns every way to fence you out.

And if you have not yet come so far as to see yourself fenced
out from the presence of God in the birth of the first Adam,
then you are still in the death.
For death reigns over all from Adam to Moses, and Moses is until the prophets,
and the prophets are until John, and John is until Christ.
And if you cannot even witness a coming to Moses to be cut down by the law,
that Christ may be your life, then profess what you will,
you have not yet begun your journey,
nor taken one step in the straight and narrow way that leads to eternal life.

In Romans 7:9, Paul bears witness: "`I was alive once without the law,
but when the commandment came, sin revived and I died.`"
I say again, deal justly with your hearts,
and see what you have truly witnessed of your death with Christ
by the powerful Word of truth which enlightens the conscience,
and condemns sin in the flesh.
For everyone would gladly ascend with Christ to be partakers of life and glory,
but it is a stumbling block to be baptized with Him into His sufferings and death;
yet this must be known before you can sit with Him in heavenly places.
For it is they who suffer with Him that shall reign with Him, as Paul testifies.
And they who are dead with Him shall live with Him.
Therefore arise, you who sleep securely in the dust of the earth,
in your serpentine wisdom, with your mind feeding upon created objects that will perish!
Arise, and stand up for judgment, so that Christ may give you life.

This is required of you, O man, "`to do justly, to love mercy,
and to walk humbly with your God.`"^
footnote:[Micah 6:8]
So examine your heart, and deal justly with your own soul!
There is a light in your conscience, which light is from Christ.
Minding it will let you see the mystery of iniquity that lodges in your heart,
which is deceitful and desperately wicked.
This light is the very Word of God, which was from the beginning,
according as it is written in the outward testimony of the truth.

[quote.scripture]
____
In the beginning was the Word, and the Word was with God, and the Word was God.
He was in the beginning with God.
All things were made through Him, and without Him nothing was made that was made.
_In Him was life, and the life was the light of men._
And the light shines in the darkness, and the darkness did not comprehend it.^
footnote:[John 1:1-5]
____

Therefore, everyone arise out of your earthly wisdom,
and mind this light of life in your conscience,
and wait upon the power of the Lord in it,
and it will bring you to judgement before the throne of the Lamb,
where a righteous law will be opened in your heart that will cry
out in your earthly heart for righteousness and true judgement.
Yes, the book will be opened within you,
and in it you will read all that you have done in the body,
and will give an account for every idle word,
and receive your reward for what you have done,
which will be condemnation on all that disobeys and breaks the righteous law.
And then whatever way you shift and turn to find life in outward forms, words,
and practices,
there the flaming sword (which is the righteous law that
goes out of the mouth of the Lamb) will turn to meet you,
and cut you down.
And if you seek to hide yourself, as Adam did,
from the Lamb when He appears in your heart,
you will find that all of your fig-leaf prayers, tears, forms, doctrines,
and practices from the letter, will not cover your nakedness.
These served to cover your nakedness from the sight of men,
but now the Lord appears in your heart, and you cannot stand before Him.
Yes now, Cain in you is found out,
and is driven from the Lord as a fugitive and a vagabond,
notwithstanding his earthly sacrifice.
And Esau in you is reprobated, never to receive the blessing,
though he seeks for it with tears.
And now the bondwoman and her son are cast out,
and the first Adam is slain with the sharp sword,
and you are made to give up your soul to God, whose it is,
to do with you according to His will.
And here you are truly baptized with Christ into His sufferings and death,
a baptism where every power or help that you find in yourself perishes forever.
And this is called "`the administration of Moses,`"
where the flesh lies under the righteous law of God,
without any hope or help,
until the administration of the Prophets raises up a secret hope in your soul,
that looks for the coming of a Savior.

Now the Prophets are until John,
who is a burning and a shining lamp that lets you see the filthiness
of your heart and condemns the earthly man in you,
but also strengthens the hope in you that was raised up by the
Prophets to see the beauty and excellency of Jesus Christ,
which ravishes your lost and condemned soul so that you are willing to sell all for Him.
And now is the Scripture fulfilled in you, that every mountain and hill are laid low,
and the crooked ways are made straight, and the rough ways in you are made smooth,
and a way is prepared in the wilderness of self for the
salvation of God to be manifest in Jesus Christ.

And in the appointed time of the Father,
the Son of Man comes to your soul as lightning from the east to the west,
and causes your dead soul to hear His voice,
and offers it eternal life freely through His own blood.
And in this prepared condition your soul hears His voice,
and by the Word of His power it is made to live,
and is sealed up by the Holy Spirit of promise,
who bears witness with your spirit that you are His child.
And so you come to witness the second Adam to be a life-giving Spirit,
and Isaac the promised seed to be heir forever;
and you understand that the wages of sin are death, but the gift of God is eternal life,
and you see what it really is to be saved through faith in the Lord Jesus Christ,
and not of works lest any should boast,
and that he who has this hope in Him purifies himself, even as He is pure.
And here the love of Christ truly constrains you,
for you witness the work of regeneration made manifest,
and to follow the Lamb wheresoever He goes.

And now the love and life that you enjoy in Christ
Jesus constrains you always to deny yourself,
and you take up your cross daily to follow him.
And you have come back into the beginning, to live in the Lord,
guided by the powerful Word of faith--the light that shines
in your heart--which is the light of the city of God,
the New Jerusalem, to which you have come to worship the Father in Spirit and Truth.
And all who come to walk in the light of the New Jerusalem are the true Israel of God,
and are taught of God.
And in this city there is no need of the sun, neither of the moon to shine in it,
which are borrowed lights, outward dispensations, or teachings of men,
for the glory of the Lord God does enlighten His city, and the Lamb is the light thereof,
and the nations who are saved shall walk in His light,
and the kings of the earth bring their glory and honor into it.
And there shall by no means enter it anything that defiles,
or causes an abomination or a lie.
Its gates shall not be shut at all by day, for there shall be no night there.
And the Lord shall give them light, and in Him they shall reign forever and ever.
Hallelujah to the Highest.

[.signed-section-signature]
William Dewsbury

[.signed-section-context-close]
From the common jail in Northampton, 1655
