== Introductory Chapter

Design of the Work--The settlement of the Society of Friends,
an especial instance of Divine power manifested to the Church--Its
consequences seen in a reforming spirit--Discipline of the Society;
its origin, character, and objects.

The object contemplated by the present volume,
is to display the wonderful dealings of the Lord in the latter days,
to a portion of his militant church; and in doing this, to place before my readers,
whether belonging to the religious Society of Friends, or to other denominations,
a practical illustration of those principles, which,
by an especial extension of Divine regard,
were opened to the minds of a few obscure individuals,
and through their labours to many others, as those of vital and primitive Christianity.

The darkness which had overspread the hemisphere of the visible church,
previous to the period of the Reformation, was such, as to cause no surprise,
that a belief in immediate revelation, as held by the people called Quakers,
should have ceased to exist, since the days of the apostles and first Christians.
That any definite series of facts had arisen,
between that period and the middle of the sixteenth century,
on which the body of professed believers were likely to adopt an opposite conclusion,
does not appear to have been the case.
For although every influx of spiritual light,
which at intervals had with more or less force broken in upon the minds of individuals,
was from the only true Source of Light itself,
and tended to prepare them for something further;
the extraordinary train of circumstances which attended
the rise and settlement of the Society of Friends,
were such as rendered that event an era in church history.

To some of those circumstances,
constituting in their aggregate sense what may be justly called a religious phenomenon,
it is the design of the present work to draw the attention of the serious reader.
For, notwithstanding "`this thing was not done in a corner,`" and Friends have not been a
people whose principles have led them to hide their Lord`'s talent in a napkin,
or the light of their testimony under a bushel;
yet the various denominations of Christians, even at the present day,
are too little aware what abundant evidences of the Divine power and presence were vouchsafed
on the first gathering of this people into a distinct and visible community;
and how admirably they were thereby led forth and instructed
in the adoption of that beautiful order of church discipline,
which has been attended with so many and great advantages down to the present time.

Without question,
George Fox and his "`yokefellows`" witnessed in
a wonderful manner the overshadowing goodness,
power, and mercy of the great Head and High Priest of our profession:
for in His wisdom and by His grace,
notwithstanding every obstruction which was permitted to afflict them,
they "`triumphed gloriously,`" until at length their enemies were laid asleep.
Nor has it been in this respect alone,
that the experience of this people has run parallel with that of the primitive church;
but, with them also,
the cessation of persecution has been attended by a state of rest and security,
and even of lukewarmness and ease, which,
when compared with the zeal of their first days,
may in too general a way appear more like death than life.
There has been, however,
through such of their faithful successors as have
been raised up from one generation to another,
gradually spreading over the community at large, a measure of the same leaven,
wherewith the early Friends were so abundantly imbued;
even that which proclaimed "`peace on earth and good will towards men,`"
under the all-powerful influence of heavenly harmony and love.

Much has been said at various times, and much may continue to be said,
as to the supposed enthusiasm and even fanaticism of the first Friends.
If to be "`zealously affected in a good cause,`" in a day of thick darkness,
be enthusiasm, both they and the first Christians were indeed enthusiasts.
But the calling of the early Friends was of a very peculiar nature,
and one which was not assumed by themselves through
any choice or contrivance of their own:
they were, it may be truly said,
employed as instruments to lead the way into a new or further department of church reform,
and their appearance, in most respects, was therefore new and peculiar.
If, under such circumstances, to yield obedience to that measure of light,
in and by which individual duty was made known to them,
is to be branded with the term enthusiasm, or a worse name,
because by such obedience they were led into acts which the world accounted madness,
then they were enthusiasts truly.
And further, if such terms are to be attached to the operation of that efficacious faith,
by which its possessor is enabled to bear the contradiction of sinners against himself,
without fainting or weariness, then were the early Friends enthusiasts and fanatics.
Fanaticism and intolerance, however, are found to be often closely allied;
and accordingly, the real fanatics of those days were, in very many instances,
to be clearly detected among their opponents and their persecutors.

On the contrary, in the general course of their proceedings.
Friends acted under a degree of the influence of that holy "`spirit of power,
and of love, and of a sound mind,`" which so largely possessed the primitive believers;
and like these, the zeal of Friends in the main, will, on investigation,
be found to have been a well directed and a prudent, though a glowing and active zeal.
This assertion, notwithstanding,
leaves ample room in both cases for the admission of exceptions
to that standard of propriety of conduct which is now current;
but by no means, however,
for such as ought in fairness to attach discredit to the principles themselves,
or to their development among the body of the agents in the cause;
and they may be safely attributed to the fragile nature of the vessels,
in which that purifying power and faith was so wonderfully manifested.

One of the first objects against which this reforming spirit levelled its weapons,
was the system of modern church establishments,
and those numerous and manifest corruptions which existed amongst them,
and to which their several adherents, from various motives,
were so pertinaciously attached,--such of them, I mean,
as did not embrace these new views.
It was well said by one of the most enlightened and
experienced among the first members of this Society,
in reference to the brotherhood,--"`We are not persons that
have shot up out of the old root into another appearance,
as one sect hath done out of another, till many are come up one after another,
the ground still remaining the same out of which they all grew; but that +++[+++very]
ground hath been shaken and is shaking, destroyed and destroying,
removed and removing in us.
And the root of Jesse hath been made manifest in us,
and we have been transplanted by the everlasting power of life,
and a real change brought forth in us, out of +++[+++and separated from]
that spirit wherein the world lives and worships, into another spirit,
into which nothing which is of this world can enter.`"

An impression of this nature having taken deep hold,
having indeed become a principle of action in the minds of the early Friends,
we need not be surprised,
that they made war in righteousness with what was corrupt everywhere;
and they saw no inconsistency in judgment beginning
at what was reputed to be "`the house of God.`"
At one blow, therefore, under the conduct of their holy Commander,
who promised to lead his followers by his Spirit into all truth,
and doubtless both as regards their worship and their discipline,
they levelled all distinctions of laity and clergy, so called;
as having sprung up in and spread over the visible church,
just in proportion as a worldly spirit took the place of that heavenly influence,
under which it was first gathered.

That they had been brought to the effectual experience of this blessed influence,
"`according to the measure of the gift of Christ,`" Friends gave infallible proof;
and under it, as a gathered church, they met,
sitting down together in the name of Christ, to wait,
(each member in particular endeavouring to know its own place in
the body,) for the springing up of that divine life,
which could alone qualify any of them for the exercise of their several gifts.
And there are many remarkable instances on record,
of the tendering and refreshing operation of heavenly love and power,
by which they were often abundantly attended,
and their hearts at such seasons knit and united together.
There, Christ was all in all; and the hands or the head could not say to the feet,
"`We have no need of you;`" but every member had
his own responsible station and office in the body,
whether of silent exercise or vocal communication, either prophecy, exhortation, prayer,
or praise, for the instruction, edification, and comfort of the whole.
This was truly primitive and apostolical.

If such a work had been undertaken in the wisdom or contrivance of man,
or by mere imitation in a fanatic spirit, it would have been unmeaning, fruitless,
and dead.
But, as it was undertaken, it remains to be a pattern to future ages,
in relation to the manner in which it has pleased the Chief
Shepherd and Bishop of souls to visit his flock,
and appear "`in the midst of them,`" leading them forth out of
the death and formality of an empty yet wordy profession,
into the life and liberty of his own free Spirit.
Not that all other professors were wholly without life, even at that period,
as the writings of Friends most fully admit;
but formality and an outside profession were leading features of those times:
nor yet that the Life, in its immediate springing up,
is at the present day very demonstratively seen in the Society in question.
But the seed has been sown, the way has been cast up and made plain;
and if the impressions,
which were deeply stamped on the minds of its early and most devoted members,
had the seal of Truth for their origin,
notwithstanding appearances at present may not be the most promising,
their testimony will not be lost.

In attempting to level a distinction so unscriptural as that of laity and clergy,
Friends struck at the root of all lordliness in church government;
at the system of compulsory exactions for religious purposes; and at such a ministry as,
having man`'s appointment for its foundation,
assumed to itself exclusive privileges under a stipendiary system.
Such principles as are involved in these questions,
have at length taken strong hold on the attention of a large
portion of the community of the present day;
and it behooves those who would be accounted spiritual,
and who from conscientious motives are desirous of
adding their weight in favour of such positions,
to search diligently into the origin of those views,
towards which the eyes of all parties are more or less directed;
and which sooner or later must prevail, in the ordering of Divine Wisdom and Providence;
promising to be productive of changes in the condition
and circumstances of the church of our Redeemer,
to which few can look forward with indifference.
It therefore appears to be the more incumbent upon those,
who on religious grounds are interested in such anticipations,
with honesty and patience to examine the nature of their own foundation,
and the superstructure which has been raised upon it;
that they may ascertain for themselves, whether it is one with that,
against which "`the gates of hell`" can never prevail;--whether it will
stand the fiery trial which is to try every man`'s work;--in short,
whether their faith is such as overcomes the world, and leads its possessor forth,
often in a way most adverse to the will and wisdom of the creature;--a living faith,
such as removes mountains, gives them the victory, and to which they can,
as did the early Friends in an eminent degree, set their seal by suffering.

+++[+++The author of these pages,
having thus briefly adverted to the settlement of the Society of Friends;
as an eminent instance of the display of Almighty goodness, wisdom, and power;
and having glanced at one remarkable feature and effect attending their calling, namely,
that they were raised up to bear testimony to the very Truth as it is in Jesus,
and against all the innovation and degeneracy that had crept
in and prevailed throughout professing Christendom;
goes on to speak of the order of that building, and the government of that house,
which they believed themselves called upon to erect and establish
among those who were gathered into the same fellowship.^
footnote:[The Editor +++[+++John Barclay]
is by no means clear,
that this Introductory Chapter stands as the author would have let it go forth,
had he been spared to complete it.
It is quite an unfinished fragment of an essay.
The interest of the reader will be increased on learning,
that this was the very last effort of his pen; and that even on his sick bed,
but a few days before his removal hence,
was he engaged in penning some of these clear views
relative to the state of the militant church,
until the increase of fever rapidly overwhelmed the mental and bodily powers,
and hurried him away, not unprepared, as it is fully believed,
to join the church triumphant in heaven.]--Editor.]

The origin, character, and objects of the discipline or order of church government,
established in the Society of Friends,
and which has been justly admired for its simplicity, as well for its consistency with,
as for its adaptation to the nature and necessities of a Christian church,
may be best introduced to the general reader by the following statement,
extracted from their Rules of Discipline, recently published by the Yearly Meeting.

By the term discipline, we understand all those arrangements and regulations,
which are instituted for the civil and religious benefit of a Christian church:
the meetings of discipline are, of course,
for the purpose of carrying those objects into effect.
Their design was said by George Fox, to be--the promotion of charity and piety.

It cannot be said,
that any system of discipline formed a part of the original compact of the Society.
There was not indeed, to human appearance, anything systematic in its formation.
It was an association of persons who were earnestly seeking, yea,
panting after the saving knowledge of Divine Truth.
They were men of prayer, and diligent searchers of the holy Scriptures:
unable to find true rest in the various opinions and systems,
which in that day divided the Christian world, they believed that they found the Truth,
in a more full reception of Christ,
not only as the living and ever present Head of the church in its aggregate capacity,
but also as the Light and Life--the spiritual Ruler, Teacher,
and Friend of every individual member.

These views did not lead them to the abandonment of those doctrines,
which they had heretofore held in regard to the manhood of Christ,
his propitiatory sacrifice, mediation, and intercession.
They did lead them, however, to a less dependence upon man,
and to much inward retirement and waiting upon God, that they might know his will,
and become quick of understanding in the fear of the Lord;
yet were they very frequent in their meetings together for mutual edification and instruction,
for the purpose of united worship in Spirit and in Truth,
and for the exercise of their several gifts, as ability might be afforded by Him,
who has promised to be with the two or three disciples
who are gathered together in his name.

From these meetings,
in which the love of God was often largely shed abroad
in the hearts of those who attended them,
even when held in silence,
+++[+++which was by no means infrequently the case even in the early times,]
most of those ministers went forth, who in the earliest periods of the Society,
proclaimed to others the Truth as they had found it,
and called them from dependence on man,
to that individual knowledge of Christ and of his teachings,
which the holy Scriptures so clearly and abundantly
declare to be the privilege of the Gospel times.
As these views struck at the very root of that great corruption in the Christian church,
by which one man`'s performances on behalf of others
had been made essential to public worship,
and on which hung all the load of ecclesiastical domination and the trade in holy things;
so it necessarily separated those who had, as they believed,
found the liberty of the Gospel, from those who still adhered with pious regard,
or a mere ignorant and selfish attachment,
to that system which was upheld by the existing churches of the land.

Being thus separated from others, and many being every day added to the church,
there arose of course peculiar duties of the associated persons towards each other.
Christianity has ever been a powerful, active, and beneficent principle.
Those who truly receive it,
no more "`live unto themselves;`" and this feature and fruit of genuine
Christianity was strikingly exhibited in the conduct of the early Friends.
No sooner were a few persons connected together in the new bond of religious fellowship,
than they were engaged to admonish, encourage,
and in spiritual as well as temporal matters, to watch over and help one another in love.

The members who lived near to each other, and who met together for religious worship,
immediately formed, from the very law of their union,
a Christian family or little church.
Each member was at liberty to exercise the gift bestowed upon him,
in that beautiful harmony and subjection which belongs
to the several parts of a living body,
from the analogy of which the apostle Paul draws
so striking a description of the true church;
"`Ye are the body of Christ, and members in particular.`"

Of this right exercise of spiritual gifts, and thereby of an efficient discipline,
many examples are afforded in the history of the earliest period of the Society;
we shall select one,
which we believe may be considered as fairly illustrating the practice of early times.

Stephen Crisp in his Memoirs, speaking of his own state soon after his convincement,
which was in 1655,
and within a few years of the establishment of a meeting at Colchester,
the place of his residence, thus expresses himself:

"`The more I came to feel and perceive the love of
God and his goodness to flow forth upon me,
the more was I humbled and bowed in my mind to serve him,
and to serve the least of his people among whom I walked.
And as the word of wisdom began to spring in me, and the knowledge of God grew,
so I became as a counsellor of them that were tempted in like manner as I had been;
yet was kept so low, that I waited to receive counsel daily from God,
and from those that were over me in the Lord, and were in Christ before me,
against whom I never rebelled nor was stubborn;
but the more I was kept in subjection myself,
the more subject were evil spirits made to me,
and the more I was enabled to help the weak and feeble ones.
And the church of God in those days increased, and my care daily increased,
and the weight of things relating both to the outward
and inward condition of poor Friends came upon me;
and being called of God and his people to take the care of the poor,
and to relieve their necessities as I did see occasion,
I did it faithfully for divers years, with diligence and much tenderness,
exhorting and reproving any that were slothful, and encouraging them that were diligent,
putting a difference according to the wisdom given me of God,
and still minding my own state and condition,
and seeking the honour that cometh from God only.`"^
footnote:[Memoirs.
Stephen Crisp was an able minister of the Gospel among Friends in the early times.
There is a volume of his collected writings, to which is prefixed a journal of his life;
from that scarce volume has been compiled, by Samuel Tuke,
one which is worthy of a place in every Christian man`'s library.]

Thus, then, we believe it may be safely asserted,
that there never was a period in the Society,
when those who agreed in religious principles were wholly independent of each other,
or in which that order and subjection which may be said to constitute discipline,
did not exist.
But as the number of members increased, those mutual helps and guards, which had been,
in great measure spontaneously afforded, were found to require some regular arrangements,
for the preservation of order in the Church.

It was one of the earliest features of our religious economy,
to elevate the character of the female sex,
by recognizing them as helpers in spiritual as well as in temporal things;
holding in the former, as well as in the latter, a distinct place,
and having duties which more peculiarly devolved upon them.
For this purpose, meetings were established among them,
with a special regard to the care and edification of their own sex.

The history of these proceedings affords no small evidence,
that the spirit of a sound mind influenced the body in its earliest periods: contending,
as they did, for so large a measure of individual spiritual liberty,
and placing the authority of man, in religious matters,
in a position so subordinate to that of the one Great Head of the Church,
they nevertheless recognised the importance and necessity
of arrangements and of human instrumentality,
under the direction of the Spirit of Christ;
and they were led to establish a system of order at once so simple and efficient,
that notwithstanding the varying circumstances of the Society,
and the power of every annual meeting to alter it,
it has been found in its main particulars, adapted to those changes,
and it remains to this day essentially the same as
it was within forty years of the rise of the Society.

The statement then proceeds to notice the origin
and establishment of General and Quarterly meetings;
which latter were county meetings,
and "`appear to have had much the same office in the body,
as monthly meetings have now amongst us,`" namely,
the individual care and oversight of the members,
and of the particular meetings composing them.
The business of Quarterly Meetings now is, to watch over Monthly Meetings,
to which the latter make report of their condition by representatives,
in the same manner and with a similar relationship
as the former do to the General or Yearly Meeting.

It appears to have been with our Society as it had been with the primitive church,
that the care and provision for its poor members was amongst
the earliest occasions of disciplinary arrangements.
The occasion for this provision was much increased
by the cruel persecutions and robberies to which,
on their first rise, the Friends were almost everywhere exposed.
It was no rare occurrence, at that period,
for the father of a family to be thrown into a dungeon,
and for the house to be spoiled of the very children`'s beds and all their provisions.
Nor was it uncommon, to seek their entire proscription and ruin,
by refusing to deal with them.
Well may we say, with reverent thankfulness in reference to those times,
"`If it had not been the Lord who was on our side, when men rose up against us,
then they had swallowed us up quick, when their wrath was kindled against us.`"

The members of the persecuted Society were far from opulent;
but they proved themselves rich in charity as well as in faith and hope:
and the illustration of these virtues,
by the sacrifices which they made for the relief of their more afflicted associates,
and their unbroken constancy in the sufferings which
they endured for the testimony of a good conscience,
were doubtless amongst the practical arguments,
which at length extorted the commendation even of their enemies.

A second,
and perhaps contemporaneous object of the meetings for the discipline of the Society,
was the obtaining redress for those illegally prosecuted or imprisoned.
Though so patient in suffering, they deemed it their duty to apprize magistrates, judges,
and the government, of illegal proceedings,
and to use every legal and Christian effort to obtain redress.
Several Friends in London devoted a large portion of time to this object;
and regular statements of the most flagrant cases were sent to them,
and were frequently laid by them before the king and government.
Their constancy in suffering was hardly exceeded by their
unwearied efforts to obtain relief for their suffering brethren,
and for the alteration of the persecuting laws; and through these means,
the cause of religious liberty was essentially promoted.

A third object, which at a very early period of the Society, pressed upon its attention,
was the proper registration of births and deaths,
and the provision for due proceedings relative to marriage.
Their principles led them at once to reject all priestly intervention on these occasions;
and hence the necessity for their having distinct arrangements in regard to them.
In some of the meetings of earliest establishment,
regular registers are preserved from the year 1650 to the present time.
Great care was taken in regard to proceedings in marriage;
investigation as to the clearness of the parties from other marriage engagements,
full publicity of their intentions, and the consent of parents,
appear to have been recommended in early times as preliminaries
to the ratification of the agreement between the parties;
and this act took place publicly in the religious meetings of the Society.
Marriage has always been regarded by Friends, as a religious, not a mere civil compact.

The right education of youth,
the provision of suitable situations for them as apprentices or otherwise,
and the settlement of differences without going to law one with another,
were also among the early objects of the Society`'s care.

The last object of the discipline in early times, which we shall enumerate,
was the exercise of spiritual care over the members.
As the Society advanced, it was soon reminded of our Lord`'s declaration:
"`It must needs be that offences come!`"
United as they were, in the main, in true Christian fellowship, differences did arise.
Evidencing, as the Society did to a large extent, the fruits of the Spirit,
there were those who fell away from their Christian profession,
and walked disorderly;--and sound as was the body of Friends in Christian doctrine,
there were members who were betrayed into false doctrines
and vain imaginations;--and pure,
and spiritual, and consistent with true order and Christian subjection,
as were the principles of religious liberty advocated by the Society,
there were those who appear to have assumed them
under the false expectation of an entire independence.

To all these cases, the discipline was applied in very early times,
yet the spirit of tenderness, which breathes through the writings of George Fox,
in regard to the treatment of delinquents,
and which there is good reason to believe was practically illustrated
to a large extent in the conduct of the Friends of those days,
is worthy of especial notice.
In one of his epistles he thus writes:

"`Now, concerning gospel order,
though the doctrine of Jesus Christ requireth his
people to admonish a brother or sister twice,
before they tell the church; yet that limiteth none,
so as they shall use no longer forbearance.
And it is desired of all, before they publicly complain,
that they wait in the power of God,
to feel if there is no more required of them to their brother or sister,
before they expose him or her to the church.
Let this be weightily considered;
and all such as behold their brother or sister in a transgression, go not in a rough,
light, or upbraiding spirit to reprove or admonish him or her;
but in the power of the Lord and Spirit of the Lamb,
and in the wisdom and love of the Truth, which suffers thereby,
to admonish such an offender.
So may the soul of such a brother or sister be seasonably
and effectually reached unto and overcome,
and they may have cause to bless the name of the Lord on their behalf;
and so a blessing may be rewarded into the bosom
of that faithful and tender brother or sister,
who so admonished them.
And so keep the church order of the gospel,
according as the Lord Jesus Christ hath commanded; that is, if thy brother offend thee,
speak to him betwixt thee and him alone; and if he will not hear, take two or three;
and if he will not hear two or three, then tell it to the church.
And if any do miscarry, admonish them gently, in the wisdom of God,
so that you may preserve him, and bring him to condemnation,
and preserve him from further evils, which it is well if such do not run into;
and it will be well for all to use the gentle wisdom of God towards them in their temptations,
and condemnable actions; and with using gentleness, to bring them to condemn their evil,
and to let their condemnation go as far as their bad action has gone and no further,
to defile the minds of Friends or others; and so to clear God`'s Truth and people,
and to convert the soul to God,
and preserve them out of further evils:--So be wise in the wisdom of God.`"
