== Chapter III

1642+++.+++ Continuance of William Dewsbury`'s mental conflicts--In hopes of relief,
enters the Parliament army--Disappointment--Goes to Edinburgh--He
is inwardly instructed to leave the army--Returns home--His religious
feelings and openings--He is shown the only true source of all
saving knowledge and faith--Reflections--Remarks on immediate revelation.

These mysterious spiritual conflicts continued thus to exercise his mind for some years;
and we are now brought down to the time of the civil wars, about the year 1642,
when I suppose him to have been in his twenty-first year,
and the term of his apprenticeship drawing towards a close.
It was at this juncture, that William Dewsbury,
in common with many ardent but well-meaning persons, fell into a snare,
which the enemy of all righteousness, who was a murderer from the beginning,
laid for them, through the plausible reasonings of some,
who professed to be ministers of Christ.
These persons raised the cry of "`Curse ye Meroz,`" because
all were not so ready as they wished them to be,
in unsheathing the sword in the cause of civil and religious liberty;
which act they called, going up to the help of the Lord against the mighty.
With this bait, placed in so inviting a point of view to him, William Dewsbury was taken;
and his inducement to swallow it, was probably greater than that of some others,
from the peculiar state of mind he was then passing through.
His case was not dissimilar to that described in the 6th, 7th,
and 8th verses of the sixth chapter of the Prophet Micah.
He, like the individual there described, was ready to make any sacrifice for peace.
He was willing to give his body unto death, in obedience to the Lord,
if by such a measure it had been possible to free his soul from sin,
escape the condemnation he then lay under, and thus attain to the knowledge of God.
Therefore,
not at that time seeing the inconsistency of the sword among
Christians--of professing to be the servant of Christ,
and at the same time acting in a manner diametrically opposed both to his example,
his precept, and his Spirit;
and not then remembering that Christ came not to destroy men`'s lives, but to save them,
he joined that little remnant, as he calls it, who entered into the Parliament army,
and said they fought for the Gospel.

But, whichsoever way he turned himself at this period of his life,
disappointment appears to have been the fruit of his labour.
He entered the army under considerable expectation of meeting with fellow-travellers,
whose main pursuit was one with his own,
and whose minds had passed under similar baptisms.
In this, however, he was deceived.
He found as much ignorance of the Gospel in its real, its spiritual acceptation,
and of Christ, the glad-tidings of the Gospel, as he had ever met with before.
He therefore made a journey into Scotland,
in search of those who there walked in the fear of the Lord; and came to Edinburgh,
where, he tells us, he found nothing but formality;
the teachers calling to people to seek the kingdom of God in outward observances.
Wherefore he returned to England, and sought for Him whom his soul loved and longed for,
among the Anabaptists and Independents.
These, he tells us, "`said, they were the children of God,
and were setting up a more glorious image`" in outward things.
But he was not free to join them;
for it was the testimony of the love of God to his soul,
that he wanted and was in search of.

Then +++[+++says he,]
the Lord discovered to me,
that his love could not be attained to by anything
I could do in any of these outward observations;
and in all these turnings in my carnal wisdom, while seeking the kingdom of God without,
thither the flaming sword turned, to keep the way of the tree of life, fenced me from it,
cut me down, rent all my coverings,
and destroyed that mind which thus looked out to find the kingdom of heaven.
Then, my mind was turned within by the power of the Lord, to wait in his counsel,
the light in my conscience, to hear what the Lord would say.
And the word of the Lord came to me, and said, "`Put up thy sword into its scabbard;
if my kingdom were of this world then would my children fight: knowest thou not,
that if I needed, I could have twelve legions of angels from my Father?`"
Which word enlightened my heart, and discovered the mystery of iniquity;
it showed the kingdom of Christ to be within,
and that its enemies being within and spiritual,
my weapons against them should also be spiritual,--the power of God.

Favoured with these clear and Scriptural intimations,
of the will of the Lord concerning him,
William Dewsbury no longer hesitated as to the course that it was right for him to pursue.
And not feeling himself now at liberty to use the sword for the destruction of his fellow-creatures,
and that too under the mistaken notion of advancing the kingdom of Christ, (enthusiasm,
indeed, of a most dangerous character!) he put up his weapon again into its sheath,
and left the army.
Having happily accomplished this resolution, he turned his steps homewards,
and there laboured at his previous occupation of cloth weaver; but,
of his pursuits in trade he makes little or no mention,
and we are left to conjecture both as to their extent,
and his success and prosperity in regard to them.
He informs us, however, that his mind was inwardly engaged,
while labouring with his hands, in waiting on the Lord in the way of his judgments,
until his own will was brought into subjection to the will of the Lord.
Many Scripture types were from time to time opened to his understanding,
greatly to his own instruction; chiefly those which in the characters of Cain, Esau,
Pharaoh, Egypt, etc. set forth the condemnation that the man of sin is under,
showing how the carnal mind is not, neither can be, subject to the law of God.
Under an inward sense and feeling that he was himself
by nature involved in the same condemnation,
he was brought to the determination of unreservedly
casting himself upon the mercy of God in Christ Jesus,
and of yielding all up to His disposal, whatever that might be,
whether to condemn or to save him;
if the former should be consistent with the divine will, he could but acknowledge,
that it would be just; if the latter, it was of His free love.

About this time also it appears from some hints he has left on record,
that William Dewsbury received, greatly to his encouragement,
a satisfactory and clear insight into the nature of the
several dispensations of divine mercy to mankind,
beginning at Adam, and passing through the administration of Moses to that of John; but,
in what exact particulars, he does not very plainly state.
However, the result was, that while he lay in the "`condemned estate`" before mentioned,
bewailing himself in the depth of his misery,
without any hope of deliverance by anything he could do to pacify the wrath of God;
he was favoured with a clear evidence in the secret of his soul,
that there was free redemption laid up for him in the Lord Jesus,
and encouragement was ministered even in this condemned state, to wait for His coming,
who "`in the appointed time of the Father,`" says he, "`appeared to my soul,
as the lightnings from the east to the west, and my dead soul heard his voice,
and by his voice was made to live, who created me to a lively hope,
and sealed me up in the everlasting covenant of life with his blood.
Then I witnessed the wages of sin to be death,
and the gift of God eternal life through Jesus Christ, my Lord.
Death reigns over all from Adam to Moses, and there is no rest to the soul,
till Christ be manifested,--this the Scriptures witness;
and I witness these Scriptures to be fulfilled in me.`"

Before I proceed with the narrative,
it may possibly be advantageous to pause for a short time,
for the purpose of making a few reflections,
suggested by that portion of it which is now before the reader.
The experienced Christian will readily find some understanding
and relish of these passages presented to him,
which to other readers may be enveloped in a degree of obscurity.
Those who have passed through religious exercises
of a similar tendency with those of William Dewsbury,
will have little or no difficulty in reconciling such parts of his experience, which,
though they may not run in all respects parallel with their own,
are not the less instructive, and Scriptural, and true.
The foundation which was from the first laid in his mind
for the necessity of the great work of regeneration,
by that deep sense of the depravity and sinfulness of man,
is especially worthy of our notice; coupled as it is with the important fact,
that he learned this truth, as to his own particular,
from those powerful and deep impressions secretly made upon his mind,
without the intervention of the ordinary means of religious instruction.
Of this fact, he never appears to have entertained a doubt;
nor do I apprehend that it would be consistent with sound experience to question it.

In the succeeding pages the reader will be furnished, I trust,
with ample reason for concluding,
that those evidences of immediate communication to his mind,
which he esteemed to be divine,
and under which his faith was exercised from first to last,
fully warranted the strong language which he mostly employed,
in describing his views of the work of God on the soul,
and in conveying religious counsel,
whether reference be made to his early days or to the more advanced periods of his career.

For thus conveying their own experience with regard to inward, immediate revelation,
Friends were subjected to a load of unjust censure,
and the floodgates of controversy were opened upon them from almost every quarter,
exposing them to unmerited ridicule and abuse.
Many, even in this day,
entertain mistaken notions as to the views of the Society of Friends on this point,
which have led to the supposition,
that the doctrine is unsupported either by Scripture or by facts.
They however assert it to be founded on both: and what their belief really is,
may be stated without fear of contradiction from those,
who have been spiritually instructed in divine things.
For in the progress of the work of regeneration, which is not less a real and effectual,
than an inward and mysterious work, an understanding is given,
in and by which the "`new creature`" is enabled to
receive the mysteries of the kingdom of heaven.
Not however in their own wills,
and at all times when they sit down to search the Holy Scriptures;
but as those writings are opened to the mind and brought to their remembrance,
by Him who knows their state of growth, what it stands in need of,
and what it is able to bear.

It was in this way, as they were found walking in the obedience of faith,
that such men as William Dewsbury and many among the early Friends,
became well instructed in the things of God.
They found it needful for them to lay aside all their
attempts to acquire religious knowledge,
by the ordinary cultivation of their reasoning faculties alone.
They had no liberty to heap up their stores, even of Scriptural knowledge,
according to the common practice of others; on the contrary, in various instances,
they found it to be required of them, to renounce the knowledge they had so gained,
to unlearn Scripture as they had previously been taught it, and to wait,
in great self-abasement as at the feet of Jesus, which they did patiently and diligently,
to receive such an understanding as the natural man does not possess, and in which alone,
spiritual things, as handed to us in the Sacred Volume, can be rightly comprehended.

These views however did not prevent Fox, Penn, Penington,
Dewsbury and the body of Friends in the early times,
from placing an equally high value on the Holy Scriptures with their contemporaries.
They received these writings, no less than the high professors of their day,
as "`given by inspiration of God,`" and profitable
to those ends for which they were designed,
namely, "`for doctrine, for reproof, for correction, for instruction in righteousness;
that the man of God may be perfect, thoroughly furnished unto all good works.`"
And they believed them "`able to make wise unto salvation,
through faith that is in Christ Jesus.`"
But faith, in this sense, is a very comprehensive term.
Thus, William Dewsbury, in reply to one who was his opponent in a controversial pamphlet,
says, "`For the sake of the simple,
we do declare that which is witnessed by all the children of light,--that
the word of faith is in the heart and in the mouth,
and those who are guided by it, are kept pure.
Faith purifies the heart, whether they have the outward declaration, yea or nay.
And those who have the outward declaration, though they read it,
if they mind not the Word which is life and light, which gave forth the Scriptures,
do not live according to the Scriptures; for they who are not guided by the Word,
are without faith.
Faith comes not by a bare reading of the outward declaration;
but is the gift of God to his children, who diligently hearken to his Word,
which is life, and the life is the light of men.`"

Again, "`None come to the knowledge of the Father by reading the Scriptures,
if they come not to Christ, of whom they testify, and in whom the life is; who saith,
'`Search the Scriptures, for in them ye think to have eternal life,
and they are they which testify of Me;`' and he reproves all those,
who will not come to Him that they may have life.`"
Again, "`The Scripture is a true testimony of Him, who is the way to the Father.
'`None knows the Father but the Son, and he to whom the Son reveals him.`' Christ we own,
who was before the Scriptures, and is the authority of them;
for when he spake them forth, he spake as one having authority,
and according as Christ speaketh of the Scriptures, we own them in their place,
a true testimony of Him, who is the Way, the Truth, and the Life,
and no man cometh to the Father but by Him.`"

The preceding statement of doctrine, taken in conjunction with such practical results,
as the reader will meet with in the course of these pages,
will I trust convey a clear and correct idea of what the Society of Friends understand,
when they assert the continuance of inward, immediate revelation.
I will therefore proceed without further delay to the subjects of another chapter.

