== Chapter IV

[.chapter-synopsis]
* 1646+++.+++ William Dewsbury`'s inclination to preach
* He is admonished to wait until 1652
* Further spiritual exercises
* His declaration respecting the law of the Spirit of Life in Christ Jesus, its power and efficacy in his own case
* Remarks on William Dewsbury`'s qualification for the ministry.

By this time, 1646, William Dewsbury,
having experienced in himself the efficacy of the one saving baptism,
had begun to feel a strong engagement of mind,
inclining him to declare to others what the Lord had done for his soul; and was, in fact,
freely given up to proceed at once, when and as the Lord should order him,
upon the work of a preacher of the Gospel.
It however appears clear, that he had not then received the necessary commission,
which was to be communicated in due time.
For, as he was revolving the subject in his thoughts,
it is a circumstance no less remarkable than some which have been already related, that,
by the influence of the holy Spirit upon his understanding,
he was commanded to stay until the year 1652.
This lively impression was accompanied by a prophetic intimation, that,
at the time appointed,
there would be more hungering and thirsting raised
in the hearts of people after the Lord,
than was then the case.
In the obedience of faith, following these directions,
the nature of which he had by this time learned,
he continued for several years in the pursuit of his trade.
He also held religious meetings in his own house,
and in the neighbourhood where he was situated, until the appointed time arrived.
Meanwhile, it does not appear, from information which has come down to us,
that he was in the practice of exercising any vocal gift,
either at the said meetings or elsewhere.

While, however, in this state of suspense and dependence, as he informs us,
and before he was known to George Fox, he had to pass through various conflicts of mind,
and was deeply proved, for the trial of his faith,
which he had received of the Lord Jesus.
All this, no doubt, tended more fully to prepare him for the great work and service,
to which he was appointed.
The following are his own words on this point of his history.

[quote]
____
In that day and hour of temptation, I witnessed those Scriptures fulfilled in me,
of Paul`'s condition, wherein he complained as I then did.
I found a law in my members, warring against the law of my mind,
so that when I would do good, evil was present with me;
the sense of which caused me to cry,
"`Oh wretched man that I am! who shall deliver me from the body of this death?`"
And as I was crying to the Lord, to free me from the burden I groaned under;
the word of the Lord came to me, saying, "`My grace is sufficient for thee,
I will deliver thee.`"
And by the power of this word, I was armed with patience to wait in his counsel;
groaning under the body of sin in the day and hour of temptation,
until it pleased the Lord to manifest his power to free me, which was in the year 1651.

Thus through the righteous law of the Spirit of Life in Christ Jesus,
I was and am made free from the body of sin and death;
and through these great tribulations,
my garments are washed and made white in the blood of the Lamb,
who hath led me into the new Jerusalem,
where nothing enters that works abomination or makes a lie,
but that which is written in the Lamb`'s book of life.
Here my soul now feeds upon the tree of life,
which I had so long hungered and thirsted after, that stands in the paradise of God.
Here there is no more curse nor night;
but the Lord God and the Lamb are my light and life forever and ever!
And I witness that I am regenerated and born again of the immortal seed,
and having partaken of the first resurrection, over such the second death hath no power.

And this I declare to all the inhabitants of England,
and to all that dwell upon the earth, that God alone is the teacher of his people.
He hath given to every one a measure of grace, which is the light that comes from Christ.
It checks and reproves for sin, in the secret of the heart and conscience.
All who wait in that light, which comes from Christ, and which is the free grace of God,
for the power of Jesus Christ to destroy sin and to guide them in obedience to the light,
shall come to know the only true God and Father of light in Christ Jesus,
who is the way to him.
And this I witness to all the sons of men,
that I came not to the knowledge of eternal life by the letter of the Scripture,
nor by hearing men speak of the name of God.
I came to the true knowledge of the Scriptures and
the eternal rest which they testify of in Christ,
by the inspiration of the spirit of Jesus, the lion of the tribe of Judah,
who alone is found worthy to open the seals of the book.
____

The testimony,
from which the foregoing narrative of his spiritual progress is chiefly taken,
was written, as before stated, from Northampton jail in the year 1655,
after he found himself united to a people whom the Lord had raised up.
To these, his friends in Christ,
he thus impressively addresses himself at the close of the above piece:--

[.embedded-content-document.epistle]
--

[.salutation]
Dear Friends,

Whose minds are turned to the effectual light that comes from Christ,
all mind your own measure, and be content in what the Lord hath committed to you.
With the light,
judge that which would draw your minds to look forth at others`' conditions,
and in impatience to covet what the Lord hath given to them,
before it is manifest to you.
Be faithful every one in your own measure,
and in patience wait for the unlimited spirit of Christ, your life,
to open the seals of the book, and make known unto you the mystery of eternal life.
This he will daily reveal in you that are faithful in your own measures,
to follow the Lord in what he makes manifest to you,
whom he hath called into his vineyard at the ninth and eleventh hours.
Be faithful to the Lord, in walking in obedience to him in the light.
He will make a short work in the earth for his Seed`'s sake,
and your reward shall be rest and peace in the presence of God in Christ,
with those who came into the vineyard at the third and sixth hours,
and laboured in the heat of the day.
God Almighty be with you, his chosen servants and children;
and all in your measure keep in his power, bold, valiant, and faithful unto the end,
and +++[+++he will]
crown you with eternal glory in Christ, our Judge, Lord, and King; God over all,
blessed forever!
Amen.

--

The reader will now feel himself under no difficulty in forming a judgment,
both as to the view of Christian doctrine, and the degree of religious experience,
with which William Dewsbury entered upon the important
and arduous service of a minister of the Gospel.
It is evident that his fitness for such an office
depended not on education or artificial attainments;
on the peculiar bent of his mind, or the force of his genius,
but on the preparation the whole man had undergone,
while he lay as clay upon the wheel of the Great Potter.

Having, in that condition,
fully known in himself the utter impossibility of attaining to peace with his Creator,
so as to enjoy communion with him, without the mediation of a Saviour,
who as advocate with the Father,
could plead his own most precious blood as the price paid for the ransom of souls;
and impressed with the high importance of obtaining
the possession of the good things thus provided,
which are variously set forth in the Holy Scriptures,
and in testimony to the real enjoyment of which,
they afford so great a cloud of witnesses;
he was indefatigable in the pursuit of this one great object.
Christ!
Christ! was the incessant cry in the secret of his soul: Christ the bread of life,
the fountain of living waters!
It was not enough for him to be told, even in the language of Holy Writ,
that Christ was his Saviour and Redeemer,--that he had tasted death for every man,--that
he is the propitiation for the sins of all,--that he was manifested to take away our
sins,--and that he had actually borne our sins in his own body on the tree;--he could
see there was no inheritance of the promise for the first birth,
that corrupt nature which attaches to Adam and all his children in the fall,
under which he groaned,
and out of which he saw that Christ the Deliverer came to redeem us, and to set us free.
In consistency with this view, and deeply sensible of another Gospel truth,
too little accepted in its real and full import,
that "`unless a man be born again he cannot see the kingdom of God,`"--he
could take no comfort to himself short of a sensible evidence,
ministered to and received in that faith,
which is "`the substance of things hoped for,`" that this work of righteousness
was measurably brought about and making progress in his soul.

When, at length, this was felt to be the case,
which was not until after an intense struggling of corrupt nature, the carnal mind,
to preserve its own life,
he was the more encouraged to wait in the light which had manifested his real condition.
This he found to be no deceiver;
it never flattered his conscience into a delusive slumber, under the false apprehension,
that to believe in the outward testimony respecting Christ, to rely upon his merits,
and to take up with the form of a holy life,
without feeling the powerful virtue of his spirit, was sufficient,
or would make him one of the redeemed of the Lord.
He therefore waited, under a deep and obedient attention,
for the further unfoldings of this divine light, which, in his experience,
he found to be no other, than the grace of our Lord Jesus Christ.

There is nothing however in these views, that will warrant an apprehension,
that William Dewsbury set a low value on any branch of Christian doctrine,
especially that of the price paid for the ransom of souls.
On the contrary, we have already seen, that there is every reason for concluding,
he felt with more than an ordinary conviction,
the full force of those passages of Holy Scripture,
which most plainly set forth the one great offering for sin.
But, although he arrived at the clear and unquestionable evidence in his own mind,
that remission of sins through the blood of Jesus Christ was and is to be preached everywhere,
yet, with equal truth to support him in the conclusion,
he was constrained to bear witness,
that none can become partakers of the benefits of Christ`'s death,
but as they are leavened into a measure of his life;
which takes place in the obedient mind,
consistently with the testimony of John in his first epistle, "`If we walk in the light,
as he is in the light, we have fellowship one with another,
and the blood of Jesus Christ his Son cleanseth us from all sin.`"

There can be no doubt,
that the reason why so many professors of the Christian
name experience this cleansing but in part,
and therefore reject the doctrine of perfection,--a
perfect cleansing and a perfecting of holiness--is,
because this doctrine, which includes the daily bearing of the cross,
and the denial of self in all its deceitful workings, is so much lost sight of.
This, William Dewsbury, in common with the early Friends,
not to the exception of many at the present day, clearly saw:
and I believe there is a conviction of this truth on the minds of many persons,
who are not yet fully entered into that rest which is prepared for the people of God.

On this ground, it was the constant endeavour of this Friend, and the burden of his mind,
to direct people, in the exercise of his ministerial gift, whether by word or writing,
to the one only way by which man can become a partaker
of the inheritance of the saints in light.
He knew well, not as one who looked only into the perfect law of liberty,
but as one who continued therein,
and was a doer of the work,--that obedience to the
law of the Spirit of life in Christ Jesus,
is the indispensable condition of discipleship.
And, not daring to limit, as the reasoning mind is so apt to do, the Spirit of the Lord,
he knew that no required sacrifice of the corrupt will or inclinations of the mind,
however unaccountable to the creature, in relation to its nature or magnitude,
could be rejected,
without obstructing the work of righteousness and entailing the forfeiture of peace:
because it was not new for the foolish things to become the means
of confounding those which are esteemed wise in this world,
nor for the weak things to be employed to bring down the things that are mighty.
Of this William Dewsbury and the early Friends had large experience.

Thus prepared, and having first received a gift, and a distinct call to the work,
he went forth as a minister of the everlasting Gospel,
being enabled from his own knowledge of the word of Eternal Life,
to report to others how great things the Lord had done for his soul;
and the succeeding portion of our narrative,
will become the best comment on the degree of his qualification for this solemn engagement.
