== Chapter V.

[.chapter-synopsis]
* 1649+++.+++ His marriage
* His faith proved
* Assurance of support granted him
* George Fox and he meet and unite
* Is called to, and enters upon the ministry
* Previous prediction
* Thomas Thompson`'s testimonial of him as a powerful minister.

William Dewsbury appears to have entered into the
marriage covenant at an early period of his life;
and although I have not succeeded in meeting with
many particulars relative to this event,
from the best calculation I have been able to make,
I suppose it to have occurred about the twenty-sixth year of his age,
two or three years earlier than the date 1649, at which we have now arrived.
The facts which have come before me on this subject, may be related as follows.

Some time after William Dewsbury had entered into the army,
he heard accidentally of a young woman of York, who, like himself,
had suffered greatly from sorrow and distress concerning the state of her immortal soul;
so much so, that, as he was given to understand,
she was ready to despair of the Lord`'s mercy.
After due deliberation, it having arisen in his heart to pay her a visit,
he concluded to do so, and went.
In the course of conversation, they came to understand each other`'s spiritual condition,
which proved to be very similar, they having passed through the like exercises,
so that they found themselves nearly united in mind and judgment,
"`as in water face answereth to face.`"
They parted.
The narrative goes on to state, that some time after this, William Dewsbury married,
but fails in informing us,
whether the young woman in question was actually the object of his choice.
But, as the circumstances are related so closely in connection with each other,
and the marriage ceremony took place at York,
we may with some safety conclude in the affirmative.
The union was accomplished at a meeting of the Anabaptists,
with whom the young woman was associated in religious profession.
It is related to have been a season of divine regard; their children,
who are the historians in this instance, having often heard their father say,
that the hearts of those who attended the ceremony
were so overcome by a sense of the Divine presence,
that there were but few dry eyes in the room.

A circumstance, which immediately followed this interesting event,
and which proved a close trial of his faith, seems to show,
that when he took this important step his outward circumstances were by no means affluent.
His wife appears to have been a woman of considerable property in land,
of which she was unjustly deprived by her brother.
And although everything is said to have been clear respecting the proceedings,
and the case was submitted to trial,
yet the decision was against him,--the judge would not let him have the property.
As he was going home he met with the buffetings of the enemy,
who insinuated into his mind some misgivings for having married a well-bred woman,
whom he was now likely to bring to poverty.
In humiliation and lowliness of mind before the Lord, without yielding to the tempter,
he desired the Lord to make him content to be what he would have him to be; and,
in a moment, he was so filled with the presence of the Lord,
that he was not able to bear the weight of the glory that was upon him;
and he desired the Lord, if he had any service for him to do, to withdraw,
or he could not live; and he heard as it were a voice say, "`Thou art mine,
all in heaven and in earth is mine, and it is thine in me;
what I see good I will give unto thee, and unto thy wife and children.`"

Where he settled upon this consummation of his wishes, does not appear; but in 1655,
when brought before Judge Hale, as will be related hereafter,
his residence was at Wakefield, and he then had a family of three children.^
footnote:[The editor has since seen a letter dated 1657, signed by Ann Dewsbury,
his wife.]

It was in the year 1651,
that William Dewsbury first met that eminent minister and servant of Christ, George Fox,
who may be said to have been the chief instrument in gathering the Society of Friends.

The first interview which took place between them,
occurred at the house of lieutenant Roper, at Synderhill Green, near Balby in Yorkshire,
where George Fox was holding meetings,
soon after his liberation out of the dungeon of Derby jail.
There he had been cruelly and most unjustly confined for six months,
and for the previous six months in the house of correction:
in all twelve months close imprisonment.
He had however by that time been so successful in his preaching,
as to make many converts to his doctrine; and from Derby, after his discharge,
he passed through numerous places in the adjacent counties, visiting his friends,
and preaching repentance and the word of life to the people;
and many more were convinced.
Coming to Balby, where several of his friends resided,
William and Ann Dewsbury heard him preach at lieutenant Roper`'s;
where he was also met by Thomas Goodaire, James Nayler, Richard Farnsworth, and others.

"`At an evening meeting there,`" says George Fox,
"`William Dewsbury and his wife came and heard me declare the Truth.
And after the meeting, it being a moonlight night, I walked out into the field:
and William Dewsbury and his wife came to me into the field,
and confessed to the Truth and received it; and after some time, he did testify to it.`"
At the same time, I apprehend, we are not to understand from this,
that George Fox had much, if any thing,
to do with bringing over these Friends to the principles which he preached;
because the husband, at least, was of the same belief before they met;
of which possibly George Fox, when he wrote his account, was not fully aware.
The interview may be said to have afforded the parties an
opportunity of ascertaining the grounds of true fellowship.
For it is clear that William Dewsbury had been previously instructed in the same school,
and by the same Divine Teacher.
Sewel informs us that "`he was one of those who had already been immediately convinced,
as George Fox himself was; who, coming to him found himself in unity with him.`"

The time was now approaching,
for William Dewsbury to enter upon more active and public duties;
he had for a period perhaps of six years been living in the seclusion of domestic life.
He had married, had become a father,
and there was every reason why he should be desirous of "`providing
things`" needful and "`honest in the sight of all men.`"
With regard to his call to the work of the ministry,
there is no reason to believe that he received any commission
on that behalf until the latter part of 1652.

[quote]
____
I waited +++[+++he says,]
in the counsel of my God, in the calling where I was placed, until the year 1652.
And in the eighth month of the year, the word of the Lord came unto me, saying,
"`The leaders of my people cause them to err,
in drawing them from the light in their consciences, the anointing within,
which the Father hath sent to be their Teacher, and would lead them into all truth,
to seek the kingdom of God in observations, where it is not to be found.
So my people perish for want of bread: freely thou has received,
freely give and minister: and what I have made known unto thee in secret,
declare thou openly.`"--Which word constrained me, by the power of it,
to leave my wife and children, and to run to and fro to declare to souls,
where their Teacher is, the Light in their consciences:
of which the Lord hath given to every one a measure to profit withal,
for the exercise of the conscience towards God and men.
Waiting in the light for the power of Christ,
he would lead them up to the living fountains of waters,
where their souls would find refreshment in the presence of the Lord;
and their bread would be sure,
and their water never fail,--as the Lord has made manifest to my soul.
____

It will no doubt be remembered, that when William Dewsbury was commanded,
as already related, to delay his entering upon the work of the ministry until 1652,
the reason assigned to him was, that at that time,
there would be a greater hungering and thirsting
in the hearts of the people after the Lord.
That this was really the case, may be in part concluded from the fact,
of the great success which had attended the ministry of George Fox and other Friends,
who had begun, some time previous to that date, as ministers of the Gospel,
to exercise their several gifts.
As early as 1647 the doctrines of Friends began to be spread through Leicestershire,
George Fox`'s native county, and by the year 1648 through Warwickshire, Nottinghamshire,
Derbyshire, and the adjacent counties; in Yorkshire in 1651,
the date of George Fox and William Dewsbury`'s first interview;
in Lancashire and Westmoreland in 1652; in Cumberland, Northumberland, etc. in 1653;
and in London and most parts of the united kingdom in 1654.
John Whiting, in reference to the city of London, at the date last mentioned,
which was the first year that James Nayler and others visited it, says,
"`There was much running to and fro, and an increase of knowledge,
and a thirsting in many thousands,
for the breaking forth of the day of salvation and fulfilling of the promises.`"

It is an interesting circumstance, that I am able to lay before the reader,
so early a testimonial of the power and efficacy of William Dewsbury`'s ministry,
as we are furnished with under the hand of Thomas Thompson,
who was one of his first converts, and who soon became, as the account goes on to state,
a minister of the same word.
The circumstance is related as follows:--

[quote]
____
Now it came to pass about the sixth or seventh month of the year 1652,
we heard of a people raised up at or about Malton, who were called Quakers,
which was the first time I heard of that name being given to any people.
They were by most people spoken against;
but when I strictly inquired what they had to lay to their charge,
that might give cause for such aspersions as were thrown upon them,
I met with none that could justly accuse them of any crime;
only they said they were fantastical and conceited, and burnt their lace and ribbons,
and other superfluous things, which formerly they used to wear;
and that they fell into strange fits of quaking and trembling.--These
reports increased my desires to see,
and be acquainted with some of them; and in the eighth month of the aforesaid year,
I heard that the Quakers were come to Bridlington,
whereat I greatly rejoiced in my spirit,
hoping that I should get some opportunity to see them.

This was that faithful labourer and minister of the Gospel, William Dewsbury,
who then was ordered into these parts;
and on the fifth-day following I heard that they were come to Frodingham.
Being on my master`'s work in Brigham, I could not go in the day,
but determined to go in the night,
and would gladly have had some of my acquaintance to go with me;
but the night being very dark, none would go, so I went alone.
Coming into the room where William was, I found him writing,
and the rest of his company sitting in silence, seeming to be much retired in mind,
and fixed towards God; their countenances being grave and solid, preached unto me,
and confirmed what I had before believed, that they were the people of the Lord.
After a little time, William ceased writing, and many of the town`'s people coming in,
he began in the power and wisdom of God to declare the Truth.
And, O! how was my soul refreshed, and the witness of God reached in my heart!
I cannot express it with pen; I had never heard nor felt the like before;
for he spake as one having authority, and not as the scribes;
so that if all the world said nay, I could have given my testimony,
that it was the everlasting Truth of God.

In the same month, my mouth was livingly opened to declare the name of the Lord,
and preach repentance to the people;
and the work of the Lord prospered in the hands of his faithful servants.
I knew a bridle to my tongue, and was greatly afraid lest I should offend the Lord,
in thought, word, or deed:
and the word of the Lord was in me--"`Thou shalt not do thy own works,
nor think thy own thoughts, nor speak thy own words on this my holy day.`"
And though I suffered and went through many great exercises,
yet the Lord bore up my spirit, and carried me on, while I abode faithful to him,
to the praise of his own name.
But through reasonings,
and looking too much at my own inabilities and unfitness for so weighty a work,
the enemy sometimes prevailed to keep me in disobedience, and cast down my mind so low,
that my growth was thereby hindered for a time; yet did the Lord,
in his endless love to my poor soul, renew his visitations,
and my mouth was often opened in the congregations of his people,
to praise his worthy name.
In those days I often accompanied William Dewsbury, John Whitehead,
and sometimes James Nayler, and other early ministers,
to and fro in the East Riding of Yorkshire;
and the glorious presence and power of the Lord our God was richly with us,
to the overcoming of our souls, the comfort of his heritage,
and the praise of his own name.
____

The circumstances above related, appear to have occurred in part,
at the period immediately preceding that which has just been noticed
as William Dewsbury`'s first journey into the north-western counties.
