== Chapter VI

1652-3. William Dewsbury`'s first journey--Suffers abuse with other Friends--Is
almost killed at Sedbergh--Occurrences there--Epistle on Church Discipline.

It is uncertain whether William Dewsbury had settled with
his family at Wakefield as early as the year 1652,
or continued for a few years after his marriage at Allerthorpe.
But as Brigham and Frodingham, the scene of occurrences mentioned by Thomas Thompson,
at the close of the preceding chapter, are neighbouring villages to the latter place,
the probability seems on the side of this conclusion;
and the more so as no mention is made of Wakefield until the year 1655,
when it had become the place of his residence.
His first journey on a religious account as a minister, beyond this vicinity,
appears to have been in the latter months of the year 1652,
when he travelled into Westmoreland, Cumberland, and Lancashire;
and shared the common lot of other Friends in those days,
who were subjected to great sufferings for the truth`'s sake.

Our early Friends believed themselves required of the Lord,
at times to bear their testimony boldly against an unscriptural ministry and its fruits,
in the public national places of worship.
The following statement of facts from the pen of George Fox,
in which William Dewsbury`'s name occurs among others,
will give but a faint idea of the cruelty, the abuse,
and the persecution Friends at that time endured from this cause.
He says:--

After I was set at liberty, (that is,
from Carlisle jail,--a memorable instance of the triumph of truth over wickedness,
cruelty and falsehood,) I went to Thomas Bewley`'s,
where there came a Baptist teacher to oppose me; and he was convinced.
Robert Widders, who was with me, was moved to go to Coldbeck steeple-house;
and the Baptist teacher went along with him the same day.
The people fell upon them, and almost killed Robert Widders!
They took the Baptist`'s sword from him, and beat him sorely.
This Baptist had the inheritance of an impropriation of tithes,
and he went home and gave it up freely.
Robert Widders was sent to Carlisle jail; where having lain awhile,
he was set at liberty again.
William Dewsbury also went to another steeple-house, hard by;
and the people almost killed him, they beat him so.
But the Lord`'s power was over all, and healed them again.
At that day many Friends went to the steeple-houses,
to declare the truth to the priests and people, and great sufferings they underwent;
but the Lord`'s power sustained them.

It was in the course of this journey,
of which no further particulars have been preserved, that he was at Sedbergh,
as we are informed by George Whitehead; an eminent minister,
a voluminous writer in the controversies of those days,
and a zealous and diligent fellow-labourer with George Fox, William Penn, and others.
He tells us, that at Sedbergh in Yorkshire, on a market day, about the year 1653,
as William Dewsbury was publishing the truth at the market-cross,
and warning the people to turn from the evil of their ways to the grace of God,
the light of Christ in their consciences,
some rude persons endeavoured with violence to push him down.
And setting their backs against the high stone cross,
not aware most likely of its tottering condition, with their hands against him,
the cross gave way, and in its fall broke in pieces.
George Whitehead was at this time about sixteen years of age,
having been himself convinced of the truth of the
doctrines preached by Friends about a year before;
and he relates this occurrence as one which was noticed at the time as a remarkable
instance of the special providence of God attending William Dewsbury in his labours;
for notwithstanding the multitude of people collected to hear him,
not one was killed or even injured by the accident.

The numbers who attached themselves to the new Society,
being now rapidly on the increase,
it appears from the tenor of William Dewsbury`'s early epistles,
that circumstances soon arose among the first converts
to the doctrines preached by him and his fellows,
which proved the necessity of some kind of discipline for the mutual help of the members,
for the preservation of unity and good order in the churches,
and for the establishment of meetings, as the truth spread over new districts.

The two following addresses may serve, the one to illustrate the fact,
and the other to point out the manner in which he was led to supply this need.
The latter of the two only, is in his collected works,
where it stands the first in order of his epistles, having the date of 1653.
It contains, I apprehend,
the first outline on record of an attempt at a system
of religious discipline among Friends;
and it shows some considerable analogy to that which was many years
afterwards introduced by George Fox in a form much amplified,
and which has continued in operation in the Society to the present day.
In the introduction to the new edition of the Rules of Discipline
of the Religious Society of Friends with Advices,
I find the following statement, which bears directly on this point,
and gives countenance to the supposition which I
had entertained in regard to the epistle in question.--

Previously to the establishment of that regular system of discipline,
and of that mode of representation in the meetings for conducting it, which now exists,
there had been many general meetings held in different parts of the nation,
for the purpose of providing for the various exigencies of the Society.
How these meetings were constituted, it is not easy to ascertain.
The "`labourers in the Gospel,`" by whose instrumentality the church had been gathered,
appear to have taken the most prominent part in the proceedings of these meetings.

George Fox mentions in his journal,
that some meetings for discipline were settled in
the north of England so early as the year 1653.
The first general meeting of which we are aware that any records are extant,
was held at Balby, near Doncaster, in Yorkshire, in 1656;
and from this meeting a number of directions and advices were issued,
addressed "`To the Brethren in the North.`"
This document refers to most of the points,
which now form the main subjects of our discipline.
It contains instructions as to the Gospel order of proceeding with delinquents,
advices to husbands and wives, parents and children, masters and servants,
as to the discharge of their relative duties,
and also in regard to strict justice in trade,
and a cheerful and faithful performance of civil offices in the commonwealth.

Such being the result of an examination made into the origin of our discipline,
I conclude that those who have considered the subject,
will agree with me in attributing to the writer of the following epistle,
the credit of having made the first suggestions on that subject.^
footnote:[The editor has seen the original in William Dewsbury`'s handwriting:
it was evidently sent to George Fox, and received his signature,
after that of William Dewsbury, and is endorsed in George Fox`'s handwriting,
William Dewsbury to Friends.]

The prefatory address will show the high authority under which
William Dewsbury believed himself to be moving on this occasion.
It is as follows:

This is the word of the living God to his church
that he hath called and chosen out of the world,
to place his name in, to order and guide in his pure wisdom to his praise and glory,
who alone is worthy, God over all, blessed forever.

That in every particular meeting of Friends, there be chosen from among you,
one or two who are most grown in the power and life, and in discernment in the truth,
to take the care and charge over the flock of God in that place.
And this is the word of the living God to you who
are chosen:--Watch over the flock of God,
you to whom is committed the charge and care; and take the oversight thereof,
not by constraint but willingly, not for filthy lucre but of a ready mind.
I charge and command you in the presence of the living God,
not to rule as lords over God`'s heritage, but in the power of the Spirit in all purity.
Be examples to the flock, and see that order be kept in the church,
in constantly meeting together, according to the rule that hath been given forth,
that is to say, once a week, or more, if it may be, besides the first-day meeting.
And you are to have a general meeting with other Friends near you,
once in two or three weeks, as the Lord orders and makes way.

Be not slack and backward, but faithful to the Lord,
in improving every opportunity for Friends to meet; and,
in every town where Friends are scattered,
lay the charge and care on some Friends who are most grown in the truth,
to see that they meet together to wait on the Lord three or four hours,
as the Lord orders it, one night or two in the week.
And watch over one another with a pure, single eye,
to see that those who come amongst them walk orderly, according to what they profess.

And if any walk disorderly, let those to whom the care and charge is committed,
or any other who discerns them, and is moved to speak to them,
deal plainly with them in reproving them,
ministering to that which is pure in the conscience, for the restoring of them.
But, if they will not reform, acquaint two or three more who are most grown in the truth;
or you to whom the charge and care of the flock is committed,
with the other that did admonish them in tender love, admonish them again; and,
with plainness of speech, minister to that which is pure in their consciences,
to raise up the witness and to judge and cut down the deceit;
that their souls may be saved and their nakedness covered.
But if they still walk in disorder, when the church is met together, reprove them openly;
and if still they do not reform, but walk in their filthiness,
when the church is met together, in the name of the Lord Jesus Christ,
charge them to depart from amongst you.
So, cast them out, and have no union with them, not so much as to eat with them,
until they repent, and turn to the Lord, and walk in obedience to that which is pure.
If they do this, then receive them again:
but if they still walk on in the stubbornness of their wills,
and do not bend to that which is pure in their consciences, keep them forth,
that no filthy person dwell in the house of God.
Then will the blessing of the Lord God be with you.

And this is his word to you, see that there be not any in outward want in the church,
and that all walk orderly in their places and callings.
And if any root of bitterness spring up in any,
which causeth strife in their minds one against another, as soon as you know of it,
call such before you and examine the matter strictly;
and stand in the wisdom and power of God to guide you to judge the cause,
and end it in righteousness.
But if the cause be hard for you to discern,
and the measure you are grown to cannot discern between the parties, I charge you,
and command you, not to be hasty in the cause before you,
to order it in your doubtful and dark minds: "`for whatsoever is not of faith is sin.`"
But send for some who are more grown in discerning,
to judge the cause and end it in righteousness.

Then will deceit be judged, and strife kept out,
and the innocent set free to serve the Lord: and your union will be in Christ Jesus,
where you will bring forth fruit, abiding in him,
and through his blood you shall overcome the world in you and without,
and shall reign as kings upon the earth.
In the power of Christ you shall command the unclean spirit,
in all his appearances within you and without;
and he shall submit to the power of God in you, dwelling in Him who alone is power,
and to whom all glory belongs forever.

The pure spirit of the most high God, rest upon you,
whom he hath chosen to watch over his flock;
and his mighty power open the pure eye in you,
to discern and separate between the precious and the vile, the holy and the unholy;
and furnish you with courage and with boldness and
wisdom to rule in the power of his spirit,
to cut down all deceit, and to wash the disciples`' feet, in bowing to the pure +++[+++mind]
in the least appearance; and ministering to it,
to strengthen the desire raised up towards the name of the Lord,
until judgment be brought forth unto victory.
Then will you have unity together in that which is begotten of God, who reigns over all,
blessed forever.
Wisdom is justified of her children.

William Dewsbury

The other epistle to which allusion has been made, is dated 1653,
and was printed in London in 1654, as a tract, with three epistles of other Friends;
and appears to have been one of the first pieces circulated in the metropolis.
No reader will doubt its discovering strong symptoms of the need
of oversight and care among those to whom it was addressed.

Dear Friends,

I suffer with the imprisoned Seed unto which I was sent to preach the everlasting Gospel,
to the opening of your blind eyes, that you might see your lost estates;
how your immortal souls lie in the pit wherein there is no water;
and to bring them forth,
that they might stand in the liberty of my Father`'s
love in the free covenant of life in the Lord Jesus.

This covenant is to the Seed, which is pure and holy; it enlightens your understandings,
and lets you see every bypath and broad way, and cries behind you, "`This is the way,
walk in it,`" when you turn from the pure light which is in your consciences.
To the light in your consciences I appeal, which shall witness it.
Many of you have not been faithful in walking with the Lord,
since you heard the Gospel of your salvation.
I charge you in the presence of the Lord and by his power, to examine your consciences,
every one of you, which will witness with me.

I suffer amongst you, for the immortal Seed, that suffers in you.
I charge you, slight not the examination of your hearts, every one of you in particular.
I see who you are in whom the Seed suffers; in some under one deceit,
and some in another: and to the light of Christ in your consciences I direct you;
every one of you, dwell in the pure light which is in your consciences;
and you will see yourselves, and witness these lines to be from God,
before whom all is naked and bare.
I charge you by the Lord, hasten every one of you to meet the Lord,
in speedily reforming your ways.
Thou who art slothful, hearken to the light in thy conscience, and it will awaken thee;
and thou who art flown up into the air, to speak of that thou livest not in, hearken,
and it will stop thy mouth, and cause thee to lie low before the Lord.
Thou who art exalted above thy brother, be attentive to the light in thy conscience,
and it will pluck thee down and cause thee to serve him in love.
Thou who art delighting in the earth more than in the Lord thy God,
be attentive to the light in thy conscience,
and it will bring thy earthly mind to judgment, and rend thee from the earth.
And thou who art a self-lover, if thou save thyself and regard not thy brother,
be attentive to the light in thy conscience, and it will bring thee to self-denial,
and to love thy brother, to watch over him, and to suffer with him in his sufferings.

I charge you, in the presence of the everliving God,
that every one be faithful according to the measure of light,
the Lord hath given to profit withal,
in the exercise of your consciences towards God and men.
Let the light guide you in all your ways, and it will purge away the filth of the flesh:
so will the old man be put off with his deeds,
and the imprisoned Seed set at liberty in you.
Then, I shall no more come to you with a rod, as I am constrained to do at this time,
through your foolishness, who have departed from the pure wisdom,
to look abroad in the counsel of your own hearts.
For "`the rod is prepared for the back of a fool,`"
but "`the wise man`'s eye is in his head.`"
This eye is the light in your consciences: being guided by it,
it will lead you to Christ, who is the fountain of wisdom and knowledge.

Now, all you that walk in Him, denying yourselves freely,
I have unity with every one of you: be faithful in your measures,
that you may grow up together in the Lord Jesus, a peculiar people, a holy priesthood,
to offer up your souls and bodies a living sacrifice unto the Lord our God:
that he may guide you by his power to his praise and glory,
who alone is worthy to be feared and obeyed by all his saints forever and ever.

With love, I salute you all in the Lord, and to his power I commit you.
The Lord God Almighty enlighten your understandings, and bless you,
and guide you in wisdom, to watch over one another in love,
that the God of love may be exalted in all of you.

From William Dewsbury

December, 1653.
