== Chapter XIX.

1688+++.+++ William Dewsbury visits London--Attends Gracechurch street meeting--Sermon--Prayer.

Notwithstanding William Dewsbury`'s age, declining state of health,
and great infirmities, feeling himself a little strengthened,
and having an ardent desire once more to visit the
great city and to labour among Friends there,
he had faith to venture from home,
arriving in London in the third month of the year 1688.
He also entertained the hope of attending the Yearly Meeting of Friends,
which was to be held there on the 4th of the following month.
Soon after his arrival in the metropolis, namely, on the 6th of the third month,
he attended a meeting for worship at Gracechurch street,
where he preached the following powerful and impressive Sermon,
the only one of his which has been preserved.
It is given in Sewel`'s History.

My Friends, "`Except you be regenerated and born again,
ye cannot inherit the kingdom of God.`"
This is the word of the Lord God to all people this day.
This lies not in airy profession, and in vain imagination,
and whatsoever else it is that you deck yourselves withal:
you must every particular man and woman be born again,
else you cannot enter into the kingdom of heaven.
This was the doctrine of Christ,
in that prepared body wherein he appeared in the world and preached to Nicodemus.
This is a standing doctrine to this moment of time,
and will be so while any man breathes upon the earth; there is no other way,
no other gate to enter into life, but by this great work of regeneration.

Now, to enforce people to come to this great work,
and to set forward from earth to heaven--all being driven
out of paradise by the cherubim set with a flaming sword,
there is no returning to that blessed life,
but by the loss of that life that did grieve the Spirit of God,
and which caused man to be driven out.
There is no other way of return again, but by this new birth.
As you are all driven and forced out of paradise,
and the flaming sword and the cherubims are set to keep the way of the tree of life,
so you must return into the favour of God again, by the light of Christ.
You have line upon line, precept upon precept, here a little, and there a little,
to direct your minds to the light of Christ Jesus.
As the first Adam was made a living soul, so the second Adam is a quickening spirit.
This know for certain, no man or woman can be quickened,
and raised up into the life of the second Adam,
until the life of the first Adam be taken away.

So now, let every one of you deal plainly with your own hearts, +++[+++and inquire]
how you came to be slain to the life of the first Adam,
in which life there was a working of the mystery of iniquity in every part of man.
One cries "`Lo, here is Christ;`" another, "`Lo,
there is Christ;`" and every one is following his
own imagination about the letter of the Scripture;
this is still but the vain spirit of man, running and striving to recover himself;
and this is the cause there is so much profession of God,
and so little of his nature appearing among the sons and daughters of men.

Now, all that come to be regenerated, must come to the light of Christ;
there is no other way to it.
He will search your hearts, and try your reins, and set your sins in order before you,
and trace out the iniquities that compass you about.
You must see yourselves a lost people, a sinful people,
and so come to feel the weight of your sins upon your consciences;
there is no other way to come to life.
You will never complain of sin till you are burdened with it,
till you have a trumpet sounding in your ears, to awaken you,
that you may arise from the dead, that Christ may give you light.
There is no other way, dear people: you must bring your deeds to the light of Christ,
and abide the sentence of condemnation.
If you save your lives, you lose them; if you will lose your lives for Christ`'s sake,
there is no danger of your eternal life.
John the Baptist, Christ`'s forerunner declared,
"`I indeed baptize you with water unto repentance,
but he that cometh after me is mightier than I,
the latchet of whose shoes I am not worthy to unloose,
he shall baptize you with the Holy Ghost and with fire; whose fan is in his hand,
and he will thoroughly purge his floor, and will gather his wheat into his garner,
but the chaff he will burn with unquenchable fire.`"
Are you the better for reading the Scriptures, if you know not this fiery baptism,
which all must know who are regenerated?
Deceive not yourselves: Christ will appear in flaming fire,
and take vengeance on all them that know not God,
and that obey not the Gospel of our Lord Jesus Christ.

I stand here as a witness of the Lord of life this day:
there is no way for people to come to salvation,
but they must know Christ revealed in their hearts.
What is he doing, but rendering vengeance upon the carnal mind, self-pleasing,
and all inordinate affections;--he comes with vengeance to take away thy life;
he will baptize thee with the Holy Ghost, and with fire.
If thou knowest not this, thou art not a true Christian,
thou wilt never look death in the face with joy, nor go down to the grave with triumph.
If thou livest at home in the body, and fliest for thy life,
and will not be willing to lose thy life for Christ, if thou art called to it;
and if thou wilt not have Christ to wash thee, some for shyness,
and some for self-love will refuse this--if Christ does not wash thee,
thou hast no part in him.

You must come to Christ, to purify you in the fiery furnace:
the day of the Lord shall burn as an oven, as the prophet speaks.
This is a dreadful day, a day of vengeance, the day of the Lord Jesus Christ,
who redeemeth his people from their sins.
Zion is redeemed with judgment, and established with righteousness.
Do not make the way to heaven easier in your minds and imaginations than indeed it is;
and think it not sufficient to live in an outward observance of the ways of God.
If your own wills be alive, and your corruptions remain unmortified,
the judgment of God will be your portion: therefore, in the Lord`'s name,
come along with me; I am come to declare what I have heard and seen of the Father.
Come and examine thy conscience: hast thou brought thy deeds to the light?
Then thou hast received condemnation upon thyself, and thy haughtiness is bowed down,
and laid low, and thou seest thyself a poor miserable wretch, before the eternal God.

Whatsoever thou knowest of the mind of God, hast thou reformed thy ways?
Come along with me, and tell me what is the ground of thy faith and thy confidence.
Is it thy obedience and qualifications?
Because thy obedience is right, and thy qualifications right,
what use dost thou make of them?
Read the book of conscience: hast thou no ground for thy faith?
Thou hast put on the reformed faith, and liveth an unreformed life:
search and try thyself, man or woman.
Dost thou watch over thyself, and keep in a sense of thy dissolution,
notwithstanding all thy qualifications and partial reformation?
Dost thou strive to enter in at the strait gate, and the narrow way?
Here is the lost sheep thou seekest, the life of thy will, the life of the first Adam.
The justice of God will not suffer thee to make a saviour of thy duties and qualifications;
and to take God`'s jewels and deck thyself with them;
thou canst not be saved without the righteousness of God in Christ Jesus.
What saith thy conscience,
art thou brought to this change of thy mind and of thy conversation?
Are you all willing to part with your sins, with your pride and haughtiness?
are you willing to part with your vile affections?
This is the work of God`'s grace upon you.
Dost thou place thy confidence in thy duties and qualifications,
and takest God`'s jewels and ornaments and deckest thyself with them?
Thou tookest my jewels, saith the Lord, and didst play the harlot.
If thou return to the Lord, and humble thyself, and get through this difficulty,
thou wilt be happy forever.
This judgment of God, this flaming sword that turns every way,
will keep thee from returning to sin, and bring thee to Christ,
and cut thee off from all hope of salvation but by him,
and make thee to see the absolute need of a Saviour,
and that thy life is hid with Christ in God.

It is God`'s infinite goodness to men, that he will hide pride from them,
and humble them under his mighty hand.
This is the condition of poor creatures who are slain by the hands of the Most High.
How may I know when I am slain and baptized, and come to have sincerity?
They that have this baptism, enter into the heavenly life;
if you love the light of Christ Jesus, it will be thus with you.
God will make short work in the earth.
He will set thy sins in order before thee, and make thee watchful unto prayer,
and lead thee to holiness of life and conversation, and make thee abhor thyself,
and despise all the pomps and pleasures and vanities of this world.

When he hath adorned thee with his graces, then watch,
and in the light of Christ thou shalt see light, and that all thou hast done,
and canst do, is but thy duty.
All this thou oughtest to do; thou art God`'s creature,
and all this will not justify thee in order to thy eternal salvation,
for these services thou owest unto God.
If thou diligently wait thou shalt see more light;
then the sword that proceeds out of the mouth of Christ,
who is called "`the Word of God,`" will cut thee off from
all hopes of salvation from anything thou hast done,
from any of thy qualifications, from anything that thou canst do;
so that thou wilt be a hopeless soul, nothing in thine own sense and apprehension.
The power of the first Adam must die before him, and thou wilt cry out, "`I am a dead,
lost, and undone creature: yet there is a life hid with Christ in God for me,
but I can never have it, till I be slain into the will of God,
and become as a little child, stripped of all my own excellency that I have attained.
I must come to a sense of my own misery, and fall down at the foot of God.
When I am become as a little child,
humbled and slain as to my own will and confidence in my own righteousness,
I will not then question but I shall live a holy life,
but I will give all that life I had,
for that life which is hid with Christ in God:`" O! there are none come so far,
that ever miss of eternal life.

All shuffling people, that would have salvation by Christ,
and yet will not let him exercise his heavenly power, his princely,
glorious power to baptize them into his death, come short of salvation:
but all those who yield themselves up to Christ to be redeemed through judgment,
and are become as little children, these are in a happy state.
You know that our Lord Jesus Christ took a little child in his arms, and said,
"`Whosoever becomes not as a little child, cannot enter into the kingdom of heaven.`"
You must all become as little children, and depend upon the mercy and free grace of God;
you must all come to a holy resignation of your wills to God`'s disposal.
If you come to Christ as little children, and depend upon him,
you cannot miss of salvation; it is entailed upon such souls as hear the voice of Christ,
"`they that hear the voice of the Son of God shall live.`"

I stand here as a witness for the God of heaven,
I never heard the voice of Christ as his follower, until I was slain and baptized,
and lay as a little child under his heavenly chastisement.
As soon as ever my soul was brought to this, O! then,
the dreadful judgment was taken away, and the book of life was opened unto me,
and the Lord spake comfortably to me, "`I have loved thee with an everlasting love.`"
I was made a Christian through a day of vengeance, and of burning as an oven;
and the haughtiness and pride of man in me was brought low.
Now in this conformity to Christ`'s death, people may die into life,
and blessed are the dead that die in the Lord, for they rest from their labours,
and their works do follow them.
Away with all your own wills, and your pride, and haughtiness;
and your hypocrisy and deceit, and all dependency upon any qualifications of your own:
you must come to have your life separated from you, else you will all perish.
To those that will die with Christ, and be willing to die for him,
he is revealed as a Saviour.
He was before us in the days of his flesh, and complied with his Father`'s will;
he was nailed to the cross.
The Son of God, when he was come to the depth of his sufferings, cried out, "`My God,
my God, why hast thou forsaken me!`"
This was for thy sake, and my sake,
and every man`'s and woman`'s sake that do believe in him;
he drank the cup which his Father gave him to drink.
If it was done thus to the green tree, what shall be done unto the dry?
He went before us, and when he cometh again, he will take us to himself,
and take us from the filth of sin, that we may be made new creatures.

Except we be born again, we cannot enter into the kingdom of God,
and there is no becoming new creatures, until we be slain to the old man.
Thou must be slain to thy pride, and haughtiness, and the corruption of thy own will,
and all selfishness: thou must have God to burn it up in thee.
The Holy Ghost will destroy, and burn up nothing in thee,
but that which will bring an eternal fire upon thy soul.

"`Show me, thou whom my soul loveth, where is the path of life,
the footsteps of the flock of thy companions?
Why should I be as one that goes aside?`"
Every one that lives at home in the bosom of self, take this with you,
though you profess the truth, and live in an outward conformity thereunto,
yet if you secretly indulge your corrupt wills, and live a flesh-pleasing life,
and consult with flesh and blood, and are not rent off from your lusts,
you cannot enjoy the Lord of life: "`while I am at home in the body,
I am absent from the Lord.`"

The body of sin is a loadstone to draw you from the life of God,
and from glorying in the cross of Christ: this is flesh and blood,
and flesh and blood cannot inherit the kingdom of God.
For the Lord`'s sake, for your soul`'s sake, and for the sake of your eternal happiness,
put not off this work, but pursue it, and it will be perfected.
See how Christ is revealed in you by the Holy Ghost, and with fire.
God will redeem you by the spirit of judgment and burning:
it is not ranging abroad in your minds +++[+++that will do,]
but you must "`know that Christ is in you except ye be reprobates.`"
If he hath set your eyes and hearts upon himself,
and made you to water your couch with your tears; if he hath broken your sleep,
so as you have cried out, "`I shall be damned,
and never come to salvation;`" this will be your cry, it was once my cry;
O let not your eyes slumber, nor your eyelids take any rest,
till you be sure the Lord is your God.
If you find these qualifications, you are on your way,
otherwise you will be like a deceitful bow, and never abide in judgment.
If you reject the counsel of God against yourselves,
and refuse to be crucified with Christ, and to be baptized with his baptism,
you will never have life; but by his baptism,
and through the heavenly operation of his Spirit, if thou hast faith in Christ`'s name,
thou shalt be married to him in everlasting righteousness.
Salvation shall be brought to us, and eternal life be bestowed upon us;
even that life which is hid with Christ in God he will give to
every poor mournful soul that submits to his blessed will,
and believeth in the Lord Jesus Christ.

This is not a faith of our own making, nor a garment of our own embroidery,
but that which the Lord hath given to us.
O happy man or woman, that obtainest this gift of God!
O! who will not lose their lives for this everlasting life?
Who will not die for this eternal life?
Now, the matter lies in the death of your own wills: when you have done the will of God,
then watch that your own wills be slain, and that cursed self take not the jewels of God,
and his bracelets and ornaments, and bestow them upon self,
and paint and deck cursed self: and take not the members of Christ,
and make them the members of an harlot.
If you be dead to your own wills, you are risen with Christ,
and shall receive a resurrection to eternal life.

Crucify self, and set the world at naught, and trample upon it, and all the things of it,
and count them as dross and dung in comparison of Christ,
whom the Father hath revealed to be our life, in the days of our sorrow and mourning,
in the day of our calamity, in the day when we cried, "`Our hope is lost!`"
Thus it hath been with the holiest people on earth.
It is not by works of righteousness of thy own that thou canst be saved.
Christ comes to cut all these down, that thou mayst be ingrafted into him,
and justified by his grace.
Do not make this matter of talk, and say, I have heard this and that;
but look into your own hearts, and see what heavenly workings are there;
what there is of the power of the Lord Jesus, that hath made you to loathe this world,
and the inordinate love of the creature,
that you may enjoy all these things as if you enjoyed them not.
When we are slain and crucified to this world, we cannot but say,
"`My life is in Christ.`"
Then we come to ascribe nothing to ourselves, and all to Christ.
Here is a blessed harmony, broken hearts, melted spirits, and yet joyful souls;
poor creatures, who were mourning, and sighing,
and crying before the Lord in retired places, and yet rejoicing in Christ Jesus.
"`I am risen with Christ.`"
I said, "`My hope is cut off, I will lie down in thy will, O God;
do what thou wilt with me, it is in thy sovereign pleasure and free gift,
whether thou give me life or deny it to me.`"

There must be a resignation of ourselves to the will of God;
it was so with the Lord Jesus and it is so with every true saint of God.
You must be humbled as little children, before the judgment be taken away,
and the lovingkindness of God sealed upon your souls.
If you seek this work of God, you will find it; if you seek it upon your beds,
in all your labours and concernments, in all your stations and relations;
if you press after the new birth, you must use this world as though you used it not,
and live a married life as if you were unmarried,
for the fashion of this world passeth away.
This is not rantism.

But, let me tell you, a new world comes by regeneration.
A man is not lifted up in his own mind, but laid low in his own eyes:
he waits for the wisdom of God to govern him, and he is as a steward of the grace of God,
to give to them that stand in need.
When a man is regenerated and born again, he is as contented with bread and water,
as with all the enjoyments of this world:--What is the matter?
His own will is gone,
and put under his feet with whatsoever gives life to his vain desires and affections.
There is a harmony of all within, a man praising God, and blessing his holy name.
No entanglements shall draw away the heart from serving God and seeking his glory;
and if God shall call the husband from the wife, or the wife from the husband,
for the glory of his name, there is no complaining and crying out,
but giving them up and praising and blessing God,
when they are called to such an exercise.
If they are not called to that,
then they set their hearts to glorify God in their several places and stations;
they have full content in a blessed resignation.
Here their wills are slain, but they praise God they have no desire but, "`Lord,
thy will be done!`" always praising God,
always having the fear and the glory of God before their eyes.

All the mischief is hatched in pleasing men`'s own wills:
this is the counsel of every heart that Christ doth not govern.
Will you live as the Quakers?
Then you must live contemptibly, the mistress and the maid are "`hail fellows well met.`"
Every one must walk in humility, and live in acquaintance with the God of heaven.
She that is wrought upon by the same Spirit,
must with all diligence behave herself as becomes a servant of the Lord.
Here is now a new world, and the fashions of the old world are gone; pride, haughtiness,
crossness, and trampling upon one another, are all gone,
all slain through the operation of Christ.

What remains now,--Christ is in me, and we are all one in him.
Christ laid down his life for thee and me; now he reigns in me,
and he hath prepared my body to die for the truth,
as his prepared body was laid down for my sin.
It is a foolish profession, to make profession of Christ, and yet live in covetousness,
profaneness, sensuality, and the like.
They that are come to this heavenly birth,
seek the things that are above--thou canst do no other: make the tree good,
and the fruit will be good.
You must be ingrafted into the vine of God`'s righteousness:
O slight not the day of your visitation.
What was it to me to read of any being born again, until I was slain,
and knew the heavenly baptism of Christ Jesus?
Until I saw the flaming sword ready to slay me in every way, in every turning?
The light of Christ convinced me of sin, and his righteousness justified me,
and those works were abominable to me, which hindered my soul`'s passage to Christ.
Christ Jesus in marrying my soul to himself, did work effectually in me.
There is the testimony of Christ in me,
that he hath sealed up my soul to the day of my redemption.
Here is a certain passage, and a certain way which never any miss of,
who lose their lives for Christ.
If you be not ready and willing to lose your lives for Christ, you shall never come here:
the gate is strait, and the way is narrow,
none come hither but those that die into a heavenly oneness with Christ.
O Friends! let us empty ourselves, that Christ may fill us;
let us be nothing in our own eyes, that we may be all in him, and receive of his fulness.

I commend you to God`'s witness, that you may remember what hath been spoken among you:
but consider, if you do not hearken to it, it will follow you,
and be a plague to you to all eternity.
If you will not yield up yourselves to Christ, to this day that burns like an oven,
this fire you must dwell with when out of the body,
there will be no quenching of this fire forever.
If you be so wise as to resign yourselves up to Christ,
and come to him as little children, this will not hinder your earthly concerns.
Though the world may account thee a fool, yet thou hast that part of heavenly wisdom,
to do what thou dost as unto God.
Thou carriest +++[+++thyself]
to thy wife, as in the sight of God, that she may be sanctified to thee, and thou to her;
and thou carriest +++[+++thyself]
becomingly to thy children and servants, and thou wilt abound in grace,
and in every good work, which will be for thy eternal welfare.

O, I beseech you, people, for the Lord`'s sake,
wait for the light of Christ to guide you: learn of him to be meek and lowly,
then happy are you; for he dwelleth with the humble, but he beholdeth the proud afar off.
This new birth, which is a true work, a sincere and heavenly work, will make you +++[+++happy]
forever.
O make room for Christ in your hearts, or else he is never likely to dwell with you;
he loveth to dwell with the poor and humble and contrite spirit, but abhors the proud;
he will empty your souls, that he may fill them.

I commend you to God.
I have been long held in durance under great weakness; and I was restless,
until I could come up to this great city of London,
to preach the everlasting Gospel among you.
Pray, every one of you, turn inward; let not these words, passing through a mean vessel,
be as a bare empty discourse of truth to you, which you only hear;
and take no further care of your salvation.
Take heed of despising the light that shines in the midst of you:
press forward in the heavenly work, in the power of Christ Jesus,
even through judgment into death, and then he will give you eternal life.
The Lord confirm this, that it may rest upon your hearts,
that you may be dead to the things of the world.
We are not come to Mount Sinai, that genders to bondage, but "`we are come to Mount Zion,
the city of the living God, the heavenly Jerusalem,
and to an innumerable company of angels,
to the general assembly and church of the first born which are written in heaven,
and to God the judge of all, and to the spirits of just men made perfect,
and to Jesus the Mediator of the new covenant, and to the blood of sprinkling,
that speaketh better things than that of Abel.`"

This is the inheritance of the redeemed of the Most High; blessed be the name of the Lord!
Let us rest in hope, till he bring us to humility and lowliness of mind,
that he may clothe us with heavenly glory, according to his promise,
"`I will beautify my house with glory,`" saith the Lord.
This is the portion of a poor people, who cast themselves down before the Lord,
that he may lift them up and be all in all to them,
in whose blessed presence they shall have joy,
and rivers of pleasures at his right hand forevermore!

The following is the prayer, which he offered up after the preceding testimony.

Blessed and glorious God! thy presence and power is with thy people everywhere,
and thou art stretching forth thy almighty arm, for the salvation of thy chosen ones.
Thou art influencing their souls with thy grace and Spirit in their solemn assemblies.
We desire to extol and magnify thy great and excellent
name for all thy mercies and blessings.
We pray thee, bow down thy heavenly ear,
and hearken to the cries and supplications of thy people,
who are breathing forth the desire of their souls unto thee.
Thou art a God hearing prayers; supply their wants and establish their spirits,
and uphold them with thy free Spirit.
Crown all thy chosen ones with thy lovingkindness and tender mercy;
rend the cloud of darkness that hangs over us and take away the veil: bow the heavens,
and visit us with thy salvation, and reveal the mysteries of thy Truth unto us,
and in all our ways let us acknowledge thee, and do thou lead us in the way everlasting.

Righteous God of love! while we live on earth, let our conversation be in heaven,
where Christ our Mediator sits at thy right hand; let us follow his example,
who was holy, harmless, and undefiled, that we may sit in heavenly places with him.
Be thou a sun and shield to us in our earthly pilgrimage.
Whom have we in heaven, but thee; and there is none on earth that we desire besides thee.
Let us walk before thee in sincerity and truth,
and do thou conduct us in the way of truth and righteousness, by thy blessed Spirit.
Blessed be thy name for the light of thy saving truth, that hath shined in our minds;
and the light of thy countenance that hath been lifted up upon us in our meetings.
Thou hast furnished a table for thy people as in the days of old:
we cannot but admire thy great love and condescension towards us,
and extol and bless thy holy name for thy abounding
mercies and the riches of thy goodness to us.
We desire to give thee honour and renown,
and praise and thanksgiving for thy renewed mercies
and spiritual blessings in Christ Jesus,
for whom we bless thee, and in whom we desire to be found,
not having our own righteousness.
To Him, with thyself, and thy holy eternal Spirit, be glory forever.
Amen!^
footnote:[The editor may be singular in the remark he is about to make,
or carry his view of the subject beyond what others can follow him in,
even among the religious Society of which he is a member.
But he is not satisfied without observing,
with regard to the practice of taking down sermons
or prayers delivered in assemblies for divine worship,
that, in his opinion, the thing is improper.
{footnote-paragraph-split}
It may be pleaded,
that such declarations are recorded in the New Testament;
and also perhaps that ministers among Friends,
have even thought it right to set forth in their journals or writings,
some sketch of what they have had on particular occasions to communicate to the people.
But in these cases, the analogy is not by any means complete;
nor can these exceptions be safely held up as any precedent or rule.
{footnote-paragraph-split}
The
editor apprehends he sees in the practice,
a branch of that departure from primitive purity and simplicity,
which very early enveloped the church in a veil of dimness and delusion.
If Christian ministers and hearers, when met for divine worship,
are to know Christ to be in the midst of them by his Spirit, their President and Leader,
without whose fresh springs of help they can do nothing acceptably towards
God or towards one another,--how can any be engaged in endeavouring to
treasure up a stock of instruction against another time,
or for other circumstances than those,
under which they had been supplied according to the very hour of need?
As soon as we leave the sure ground of the immediate
extension of divine grace and favour to the mind,
as furnishing the sole impulse and qualification for instrumental labour,
the transition becomes very easy to recited sermons and forms of prayer.
Indeed the editor cannot doubt,
but that some of those ancient and beautiful compositions,
which form parts of the service of the Book of Common Prayer,
were actually brought forth under a precious degree of divine influence;
but the old enemy has contrived, by extolling these productions,
to lead away the minds of people from that inwardly searching exercise,
that individual labour, in which such words might have been rightly breathed forth,
and to settle them down in the use of a form, by way of helping their infirmities,
to the neglect of feeling after that strength which is "`made perfect in weakness.`"]
