== Chapter XIX

1688+++.+++ William Dewsbury is taken ill in London--Addresses a letter to the
Yearly Meeting--Returns home--His last hours--Address previous to the
close--His death and character--Testimony of his friends respecting him.

William Dewsbury continued in London until the 30th of the third month,
desirous of attending the approaching Yearly Meeting;
but having been taken ill soon after the meeting at which he had been so largely engaged,
and his disorder continuing to increase,
he addressed the following letter to his friends and then proceeded homewards.

Dear Friends and brethren; I did not know until last night,
but I should have been with you at the Yearly Meeting.
But it pleased the Lord to visit me with my ancient distemper,
which hath accompanied me many years in prison, and since I was released.
The distemper was so sharp upon me last night,
that I did not know whether I should live to see another day: but crying to the Lord,
he ordered and cleared my way to go into the country,
so I cannot be with you at the Yearly Meeting;
but desire the Lord to assist you with his blessed power and heavenly Life,
to bring in the scattered ones to their everlasting comfort, and his glory forever.
Amen!

And that it may be so with you, is the prayer of your loving brother,

William Dewsbury.

London, the 30th of the Third month, 1688.

Although he was favoured with strength to reach home, by short and easy journeys,
he only lived seventeen days after the date of the above letter.
About a week before he died, a few Friends being met in his chamber,
rising from his bed in great weakness of body, he addressed them as follows:

My God hath put it into my heart to bear a testimony in his name and blessed Truth.
I can never forget the day of his great power and blessed appearance,
when he first sent me to preach his everlasting Gospel,
and to proclaim the day of the Lord to the people.
And he confirmed the same by signs and wonders;
and particularly by a lame woman who went on crutches, where I with my dear brethren,
George Fox and Richard Farnsworth, were cast:
and as I cried mightily unto the Lord in secret,
that he would signally manifest himself at that time amongst us,
and give witness of his power and presence with us, Richard Farnsworth,
in the name of the Lord, took her by the hand, and George Fox after,
spoke to her in the power of God, and bid her stand up, and she did,
and immediately walked straight, having no need of crutches any more.
Therefore, Friends, be faithful, and trust in the Lord your God for this I can say,
I never since played the coward; but joyfully entered prisons as palaces,
telling mine enemies to hold me there as long as they could.
And in the prison-house I sang praises to my God,
and esteemed the bolts and locks put upon me as jewels;
and in the name of the eternal God I always got the victory.
For they could keep me no longer than the determined time of my God.

And, Friends, this I must once again testify to you in the name of the Lord God,
that what I saw above thirty years ago still rests as a testimony to leave behind me:
That a dreadful terrible day is at hand, and will certainly come to pass,
but the time when, I cannot say.
But all put on strength in the name of the Lord,
and wait to feel his eternal power to preserve you
through the tribulations of those days,
that approach very near;
in the sense of which I have often been distressed and bowed down in spirit,
with cries and tears to my God, for the preservation of his heritage.
And this I have further to signify, that my departure draws nigh; Blessed be my God!
I am prepared; I have nothing to do but die, and put off this corrupt mortal tabernacle,
this flesh that hath so many infirmities.
But the life that dwells in it ascends above all, out of the reach of death, hell,
and the grave: and immortality and eternal life are my crown forever and ever!
Therefore, you that are left behind, fear not, nor be discouraged,
but go on in the name and power of the Lord,
and bear a faithful and living testimony for him in your day.
And the Lord will prosper his work in your hand,
and cause his Truth to flourish and spread abroad.
For it shall have the victory, and no weapon formed against it shall prosper.
The Lord hath determined, it shall possess the gates of its enemies;
and the glory and the light thereof shall shine more and more until the perfect day.

He concluded with prayers to the Lord,
and with fervent breathings and supplications for all his people everywhere,
but more especially, for his dearly beloved Friends,
assembled at the Yearly Meeting in London;
and departed this life about a week afterwards, namely, on the 17th of the fourth month,
1688, at Warwick, and was buried the following day.

If we turn from this last stage of William Dewsbury`'s pilgrimage,
and from its triumphant close, to the earlier periods of his life,
we cannot fail to arrive at the conclusion, that he was a man of no ordinary character.
Those clear views of divine things, which attended his mind from first to last,
from infancy to old age, and which he undoubtingly received as a heavenly gift,
as the revelation of the grace and truth of Jesus Christ,--this inward sense,
it was his undeviating concern to obey and follow.
He truly received the Gospel neither of man, nor by man, neither was he taught it,
but by the revelation of Jesus Christ.
The ardour and sincerity with which William Dewsbury sought
after this divine understanding of divine subjects,
these secret impressions and convictions of divine
love visiting the mind and instructing it,
were very great, it must be acknowledged,
even for many years before his mind received full
satisfaction as to his salvation and peace with God,
and before he could be said to have arrived at an establishment in religion.
His after-course was indeed like the conduct of the
man who built his house upon the rock;
the very gates of hell could not prevail against him.
His mind was anchored,
and everything that happened to him only served
to confirm him in the way cast up before him.
He endured, as seeing Him who is invisible,
unchangeable;--he knew that his Redeemer lived,
and felt Him to be near who justified him.

How truly may it be said of William Dewsbury,
that he walked by faith and not by sight! even that faith by which "`the
elders obtained a good report,`" and which was to him as to them,
"`the substance of things hoped for, the evidence of things not seen.`"
On what other principle,
but the all-sufficiency of this divine faith,--faith in the presence
and power of Christ inwardly revealed,--can we account for his
deliberately entering upon that difficult and untrodden path,
persevering through all obstacles in it, meekly and patiently enduring contradiction,
triumphing over all difficulties, and becoming more than conqueror in the end?

Taking this view of William Dewsbury`'s character,
formed as it was on the model of apostolic faith,
there is no difficulty in accounting for any portion of his conduct,
however irreconcilable it might appear on other grounds.
Raised up by divine power for an especial service,
in which he had many a "`true yokefellow,`" and having submitted
to those deep baptisms indispensable in the great work of regeneration,
by which his own nature was changed, his corrupt will subdued,
the first Adam slain and the second Adam raised in him, a quickening spirit,
to bear sway and rule in all things; William Dewsbury consulted not with flesh and blood,
nor does it appear that he was at any period left in doubt
as to the course it was right for him to pursue.
Having once put his hand to the spiritual plough, he never again looked back.
If it was his, lot to suffer for the testimony of a good conscience, he never repined;
but, following the example of the Great Pattern,
"`committed himself to him that judgeth righteously.`"
The afflictions and persecutions he underwent, neither shook his faith, nor wearied,
nor offended him, because his foundation was on the rock: on this he stood.
If he triumphed,
it was as a servant who rejoices in his master`'s service and work--"`good
will to men,`"--and thus to increase his master`'s glory:
and self, through the power of redeeming love, having become of no reputation with him,
he invariably yielded, for his success,
the tribute of thanksgiving and praise to Him unto whom alone he felt that it did belong.

This our dear deceased brother +++[+++say his memorialists,]
was a man religiously concerned for the honour of God,
and had a great care upon his spirit,
that those who had believed and made profession of the truth,
might answer it in a holy and blameless life and conversation: which, he would often say,
"`could never be done by largeness of knowledge or strength of comprehension,
but by a real dying to their wills and affections, by the virtue of the daily cross.`"

He was one whom God raised up early in the morning of his glorious day,
and made an eminent instrument in his hand for the
publication of his mighty day and power;
preaching repentance in order to the remission of sins,
and bearing a faithful and universal testimony to the free grace of God to mankind.
The Lord was with him, and prospered him in his manifold sufferings, travels,
labours and exercises in the Gospel of Christ and word of his ministry.
Many were made sensible of the benefit of his labours,
to the good and welfare of their immortal souls.
For the Lord our God, in whose dread and zeal he laboured,
endued him with faith and courage, and with great boldness for his name and truth;
and he published the same in great plainness and in the simplicity thereof.

To the tender-hearted he was exceedingly tender;
but to the stubborn and lofty he was sharp and plain; admonishing them,
and declaring the righteous judgment of God against that state: waiting,
and endeavouring with much patience and long-suffering, the recovery of such,
who through the subtlety of the enemy had fallen
from truth and from unity with the people of God;
among whom he was sincerely devoted to maintain love and unity.
But when any made it their work to cause division and discord,
and to sow dissension among brethren,
he would plainly testify against them and reject them; and,
in the dread of the Lord`'s power,
thunder out God`'s judgment against their deceit and wickedness:--as
he did upon his last visit to London,
a few days before his departure out of the body, which he then told some of us,
was near at hand.

He was fervent and frequent in prayer to God for the good of his church,
and for the gathering of people to their true rest;
wherein we have had true unity with him.
And our souls, with many more, have been often refreshed and comforted with him.
His many deep sufferings for the truth,
and his faithful travels and labours are never to be forgotten.

And although the envy of wicked and unreasonable
men was very great and fierce against him,
he feared neither their malice, threats, nor blows;
but boldly went forth publishing the truth,
by testifying to that of God in all consciences.
And the hand of divine Providence did often deliver him
in a wonderful manner out of the hands of the wicked,
for his name`'s sake.

Finally, having faithfully served his generation, and finished his sufferings,
testimony and course with joy, he hath now obtained the crown immortal,
and is gone into the everlasting rest, from all his labours, and his works follow him,
with a blessed reward in the kingdom of glory and peace.^
footnote:[The preceding paragraphs form the greater part
of a testimony borne to his memory soon after his death,
to which are attached the names of six Friends, namely, George Whitehead,
Francis Camfield, Richard Pinder, Stephen Crisp, Richard Richardson, and James Parke.]
