== The Editor`'s Prefatory Address

The author of this volume having gone "`the way of all the earth,`"
and yielded up his spirit to the God of the spirits of all flesh,
it becomes my duty,
as the individual into whose hands the manuscript was
by him in a very peculiar manner consigned,
not only to lay before my readers some of the circumstances
under which the work now makes its appearance;
but also to give some brief account of my beloved and lamented friend,
whose unlooked-for translation from this state of being to a better,
I trust will prove on the minds of many as a seal to his labor of love.

However liable we all are in the present probationary condition,
to be mistaken in our estimates of men and things,
and even by the soothing snares of friendship in its purest forms,
to be led away from that unerring balance of the sanctuary, the judgment of truth;
yet surely there is some call upon me on the present occasion,
to bear my testimony to the riches of that grace, by which my friend was what he was:
and therefore I trust, that in attempting to perform this debt of love,
I shall be preserved from speaking unduly of the creature,
as well as from neglecting to ascribe the glory of
every good word and work to that Divine Source,
whose workmanship at the best we are, created in Christ Jesus unto good works. Eph. 2:10.
"`Died Abner as a fool dies?`"
said David, when he lamented the death of a valiant man.
And it has, in my best moments,
when greatly divested of personal or selfish considerations of my own loss,
even been cause of joy and gratitude to the Lord,
who gives and takes away in his admirable discretion and good pleasure,
that he saw fit to remove my dear friend,
while "`his bow abode in strength,`" while he had his armor so evidently girt about him;
when the spiritual weapons of the Christian`'s warfare
were even in his hands,--in the strength of his time,
in the clearness of his spirit;
having been thus manifestly carried through to the precise completion of an
undertaking that appeared to be laid upon him as his appointed duty,
and about which he had thought it due to the cause of the Gospel of
truth to lay out the energies and the prayers of his soul.

And how was it,
he was thus devotedly engaged in an almost unremitting manner for some months together,
abridging himself of every lawful indulgence, and putting all other claims than this,
of whatever kind they might be, into the smallest compass that duty would allow of;
without knowing, but as though he knew,
the very hours of his time were to be just
barely sufficient for this his last day`'s work.
Truly, "`the Lord`'s ways are higher than our ways,
and his thoughts than our thoughts;`" he knows the end from the beginning,
and orders all things in harmony and wisdom; nor will he permit his upright, faithful,
simple-hearted children,
who look up to him for counsel and strength in all their steppings,
materially to contravene his purposes, or widely to deviate from fulfilling,
even in the midst of all their manifold weaknesses, his holy will.
He keeps them in the hollow of his hand, he hides them under the shadow of his wing,
he heals all their backslidings,
he overrules everything that concerns them for their good, turning all to his own glory.

These musings of a mind, that has abundant cause to observe and extol the mercies of Him,
who is "`wonderful in counsel and excellent in working,`" will
not I trust be deemed irrelevant or unseasonable.

Ever since I have been capable of appreciating the purity and excellence of "`the
Truth as it is in Jesus,`" the character and productions of those departed ancients,
who first lifted up a standard to the nations in these latter days,
altogether so congenial, as I believe,
with the spirit and injunctions of our Holy Redeemer,
have been a subject of deep interest to me.
The author of the present volume had been for
years one with me in entertaining this interest:
we had often communed together on that remarkable era,
when the Society of Friends first became known as a distinct church;
and we had many times reciprocated the firm conviction,
that as the professors of the Christian name come back
to the simplicity and spirituality of the Gospel,
such writings and such characters are likely to be more
duly valued than has hitherto been the case.
If this was infatuation, it was a natural, an honest, a consistent infatuation.
We have need every one of us,
to be fully persuaded in our own minds respecting that which
makes for peace and edification in our belief and practice;
for,
"`he that doubts is condemned if he eat,`" and "`whatsoever is not of faith is sin.`"
Certainly, had I any real misgiving as to those things which may be known of God,
and to which through education or otherwise I found myself conforming,
it would seem due to my own soul and to that religious Society among whom I walked,
to take means of obtaining a solid and genuine satisfaction.

In the spring of the past year, I communicated to my beloved friend, the author,
a plan that had matured on my mind,
of reviving the writings of the early Friends in a form
accessible to their successors of every class;
believing too,
that many of these productions would be acceptable to the
spiritual followers of the Lord Jesus Christ in general,
whether themselves prepared or not to follow out
our Christian testimonies to their full extent.
My plan was almost anticipated by my friend, and cordially united with;
and in the further digestion of my arrangements,
he was always anxious to afford me all the assistance and encouragement in his power.
In the course of our frequent interchange of sentiment on this subject,
he conveyed to me the great value he placed upon the character of William Dewsbury,
and the strong desire he had to see a memoir of this worthy,
upheld in a manner consistent with his standing and the line of his testimony.
I besought him to take the matter home with him, and dwell upon it,
and see if this engagement did not devolve upon himself.
During part of the summer and autumn of the year, we were separated from each other;
when, on my return from a journey, he produced the manuscript of this volume.
Still, there was much to be done to it, before it could be prepared for the press;
and after bestowing further diligence in perfecting it,
in the freedom of unreserved friendship, he committed the whole to me,
charging me not to spare such suggestions as I
believed would tend to the object of his heart.
Some alterations I had proposed before it thus came into my hands,
and my meaning was uniformly accepted;
and I have good reason to believe from our long intimacy,
that such corrections as have been made since his removal,
would have been adopted equally with those that were submitted to his eye.
This course I deemed to be only justice to his memory and to myself,
in carrying forward the publication, under the peculiar circumstances of the case.
Some channels of inquiry for additional information even then remained unsearched;
these I have, since the author`'s decease, looked into,
and the result of my endeavors is marked out in
the ensuing pages to the notice of the reader,
by brackets enclosing such fresh matter.

With regard to the old work,
from which the epistles and some other papers are now reprinted,
the title thus stood:--"`The faithful testimony of that ancient servant of the Lord,
and minister of the everlasting Gospel, William Dewsbury, in his books, epistles,
and writings, collected and printed for future service.
London, 1689.`"
Like many of the works of that day, it is so indifferently got up,
that the correct import of some passages is not very plain,
and even admits of misinterpretation;
and as to those autograph letters of William Dewsbury`'s that have come under my notice,
while the writing is for the most part difficult,
the construction of the sentences is very far more so.
On this account,
it was requisite to make such transpositions and slight emendations
as might clear from obscurity the truths intended to be set forth,
and render them capable of appreciation.

It would seem scarcely needful for me to observe
to members of our own religious communion,
that the collected works of William Dewsbury were
published with the express concurrence of the Society,
and that they have been from time to time referred to,
both by them and by their adversaries, from that day to the present,
as conveying doctrine and exhortation well approved by the body at large.
With respect to such comments on these principles as appear interspersed
under the author`'s own hand throughout the present volume,
I trust they will very uniformly be found harmonizing
in no ambiguous manner with the tenor of the rest;
that he has put no false gloss by fair words upon these ancient, unalterable principles,
but has with all honesty and good judgment upheld and illustrated
them.--Here I would eagerly express some of the warmth of desire,
which has often pervaded my heart while engaged in revising these sheets,
that the professing members of a church,
so distinguished as ours has been by the protection and nurture of her Head and Husband,
may be encouraged by observing how memorably He has stood by her,
and by all her simply obedient children whose souls have been
true to Him:--He has indeed borne them as on eagles`' wings.
He has cherished them in his bosom.
This small volume is but a single evidence,
among very many that might be consulted by the inquiring mind,
all proving that Divine support and strength which uniformly
attended the uncompromising faithfulness of those,
who have gone before us in this Christian path and warfare.
And is not the same power ever near,
to counsel and to help his dependent little ones in every age,
to guide even into all truth, yes,
to preserve them from the most specious devices of our soul`'s enemy?
It is true, this cruel enemy and his instruments, would persuade us of this day,
that such immediate guidance is dubious and uncertain,
and that the way of the cross is too difficult and offensive to be trodden.
But how shall any of us,
who have tasted the lovingkindness and good
presence of the Lord Jesus Christ revealed in us,
for a moment listen to these suggestions?
How shall we turn aside from following on to know Him in these his heavenly visitations?
By these, he called and awakened us at the first,
touching and drawing our hearts after himself;
in this manner he brought us "`out of darkness into his marvelous light,`"
which we have indeed found to be the very "`light of life,`" cheering and
sustaining our drooping minds under every discouraging circumstance.
Hitherto he has helped us; we have found grace to help, sufficient grace,
according to all our times of need;
he has strengthened with the might of his Spirit our inner man,
--and just in proportion as we have patiently awaited on him
for the lifting up of his countenance upon us.
Shall we then as individuals or as a people forego our privileges,
shall we ever shift our ground, allow our feet to be beguiled to backsliding,
by in anywise accommodating ourselves to the low
views and false faith which so evidently abound?
Should we not rather be afresh incited by all that we read and hear,
observe and undoubtedly feel,
of the operation of the grace of Jesus Christ,--should we not
be animated to a grateful surrender of soul unto Him,
who has wrought, and is still willing to work in and for us great deliverances,
plenteous redemption!
Should we not be hereby engaged to cleave the more closely unto Him,
whose hand is not at all shortened, whose faithfulness has not failed,
and whose forbearances have been lengthened out, his mercies multiplied upon us!

It was thus, the youthful Dewsbury, while a poor shepherd boy,
sought to be acquainted with and to serve his Heavenly Shepherd,
his Almighty Father and Friend,--to know His voice from the voice of every stranger.
It was thus also, his biographer, the author of the present volume,
was concerned according to his line of things faithfully to
occupy with the measure of grace bestowed upon him;
earnestly desiring that hereby Christ, the giver of all grace,
might be magnified in his body, whether by life or by death.

[.signed-section-signature]
Edward Smith
