== The Life of William DewsburyChapter 1

William Dewsbury--Place of his Birth,
Allerthorpe--Early religious impressions--Mental conflicts--Occupation,
a Shepherd`'s boy--Apprenticed--Illness,
occasioned by conflict of mind--Unsuccessful in his search for
consolation through the religious experience of high Professors.

Among the numerous memorials which have been preserved of the lives, labors, sufferings,
and religious experience of the early members of the Society of Friends,
and which lie scattered through many volumes of their writings,
consulted in the present day to a limited extent only,
few have appeared to me to deserve preservation
more than those which relate to "`that ancient,
suffering servant of God and minister of Jesus Christ,`" William Dewsbury.

This Friend was born at Allerthorpe, a village near Pocklington,
in the East Riding of Yorkshire, early in the seventeenth century.
I have not been able to discover with certainty the year of his birth,
although his memorialist states, that he died in 1688, having lived to a good old age.
His parents appear to have been religious persons:
and no doubt were instrumental in cherishing that susceptibility of mind,
which formed at an early age a striking feature in his character.
His father died when the son was only eight years old; but,
prone to reflection as he was,
and not too young to be sensible of the loss he had thus sustained,
the impression did not pass off so quickly as is usual with children.
For while he was lamenting with tears over the solemn and affecting event,
he heard what appeared to him a voice, which said, "`Weep for yourself,
for your father is well.`"
So powerful was the effect produced on his mind by this extraordinary incident,
that from that time forward he spent many hours,
which in childhood are usually devoted to play, in prayer and fasting,
under a sense of his lost and undone condition.

It is not one of the least remarkable particulars in the life of William Dewsbury,
as was also the case with some others of the early Friends,
that almost in his very infancy, he was thus,
by a power not his own nor at his own command,
made deeply sensible of the depravity of our fallen estate.
As he advanced in years,
he became increasingly sensible of the corrupt propensities of his nature;
and this was his condemnation, that he lived without the knowledge or the fear of God;
and after many years`' reflection,
he had to lament the transactions even of his childish days,
although there is no reason to apprehend he
exceeded the ordinary levity of young persons,
or in his conduct went at all beyond what is commonly termed innocent at his age.
In this manner, he was given to see the indispensable necessity of that change of heart,
which in due time,
by yielding obedience to the further manifestations of
Divine light and grace upon his mind,
was fully brought about to his inexpressible joy; and which, under the Gospel,
is denominated a "`being born again of incorruptible seed, by the Word of God,
which lives and abides forever.`"

The materials for composing a biographical memoir of this Friend, are very scanty,
and by no means such as the weight of his character,
and the importance and extent of his labors, would lead one to desire.
In a memorial, however, which he wrote while in Northampton jail, in the year 1655,
the particulars of which confinement will be hereafter related,
he has left on record some interesting facts relative to his religious experience,
extending to the time at which he was then writing.
The tract in question was penned and circulated for general information,
"`To clear the truth from lies laid on it,`" and
"`to stop the mouths of false accusers.`"
And as one of the charges brought against him, and on which he was committed to prison,
was,
that he taught the people there was no "`original sin,`" he
introduces himself to his reader with the following language:--
"`I was conceived in sin and brought forth in iniquity;
and in that state I lived, delighting in pride and pleasure, in lightness and vanity,
as all do, who are in that nature, until I was about eight years of age.
Even before that time, the Light in my conscience did witness against me,
and caused some trouble in me.
But I departed from the light, and followed the counsel of my own heart;
which led me into vanity, and to live without the fear of God.
About the time when I was eight years of age,
the word of the Lord came to me,--'`I created you for my glory;--an account
you must give me for all your words and actions done in the body:`' which
word enlightened my heart and opened in me the book of conscience,
wherein was written all that I had done ever since I had had any remembrance.
When I had read my condition, how I had lived without God,
who had created me for his glory, the word of the Lord came unto me,
'`Shall the axe boast itself against him that hews therewith,
or shall the saw magnify itself against him that shakes it?
As if the staff should shake itself against him that lifts it up,
or the staff lift up itself as if it were no wood!`' And
by the power of the word of the Lord that spoke in me,
my understanding was enlightened,
and my conscience bore witness that such was my condition.
I had lifted up myself against the living God, in living without his fear,
who created me to live in obedience to Him; I, on the contrary,
had lived in disobedience until that day.
Whereupon, deep sorrow seized on me,
and I knew not what to do to get acquaintance with the God of my life.`"

That which lam now relating occurred between the ages of eight and thirteen;
at which early period of his life, was exemplified the Scriptural truth,
that it is sin which has made the separation between man and his God.
Under these powerful impressions,
William Dewsbury endeavored to alter the course of his life.
He ceased from what he was now led to consider his vain conduct,
in which he had hitherto lived; and became thoughtful and serious, far beyond his years.
He began to read the Holy Scriptures and other
books on religious subjects from his own choice,
and at the same time to mourn and pray to God; although, as the account states,
he had at that time received no clear understanding as to where He was to be found.
It is evident, however, that the mind of this youth,
under the quickening and heart-searching operations of divine grace,
was wonderfully opened to the sight of his spiritual condition.
With David, his soul was athirst for God, for the living God, and his cry, in effect was,
"`when shall I come and appear before God.`"
It was in vain,
that he diligently availed himself of such opportunities as were afforded him,
of learning, through the public teachers of religion and other outward means,
what he was thus anxious to know and to enjoy in himself.
For if his own mind had been sufficiently prepared for the reception of such knowledge,
the outward and carnal views of that class of persons
were not calculated to gratify his searching spirit.
He describes them as viewing the Savior with regard
only to his outward and visible appearance,
wholly losing sight of that which is inward and spiritual,
as abundantly set forth in the Holy Scriptures.
When he inquired of these professors for Christ,
whom beyond all things he desired to know, they told him his coming would be from heaven,
meaning the firmament above us, and casting their eyes upwards,
intimated in that significant way, to what point their own attention was directed.
Thus, these ministers of the letter,
failed in affording to the inquiring mind of the youthful Dewsbury, that instruction,
which his soul was longing for;
and the experience of many subsequent years proved to him beyond question,
that such a knowledge of the Father and the Son as is life eternal,
was not to be attained through such physicians of no value.
His strict attention to outward observances,
so often enforced by professors in an attempted imitation of the saints of old,
but not in the same spirit and life, in fasting, prayer,
and in various other particulars, as recorded of Peter, Cornelius, and others,
were equally unsatisfactory to him.
His soul was in trouble because of sin;
and he found that no sacrifices which he could make,
would avail to satisfy the Divine justice, or afford him peace.
On the contrary, as a child of Adam,
he had largely to partake of the consequences of the
transgression and fall of the parent of mankind,
in a deep sense of the alienation from God, which, immediately following that event,
descended upon his posterity.
In the sentence of condemnation which Dewsbury now felt within him,
and in the utter impossibility which he found, with all his endeavors,
of working out his own peace,
was opened to his understanding the mystery of the cherubim,
placed at the east of the garden of Eden, and bearing a flaming sword,
which turned every way, to keep the way of the tree of life: by which sword,
the righteous law of God, justice was executed upon the transgressing nature in him.

Until the thirteenth year of his age his occupation was chiefly that of a shepherd`'s boy,
and Allerthorpe continued to be his home.
This retired situation and way of life appear to have
been very congenial with the state of his feelings;
as it relieved him from the interruptions of company,
and afforded him an opportunity of indulging in secret meditation,
and in mourning and breathing after the saving knowledge of God.
But soon after this period, when his relations were thinking of putting him apprentice,
to learn some trade, he heard of a people called Puritans, near Leeds,
thirty miles from the place of his birth, who were said to fear the Lord,
and to walk with greater strictness of religious
profession than many with whom he had been acquainted.
Such was his hunger and thirst after righteousness, that he had no rest in his spirit,
until his parents (his mother having I suppose married
again) had succeeded in procuring a place there for him;
not at all regarding the nature of his employment, "`if,`" says he,
"`I might be among those who feared the living God;
and thus become acquainted with the God of my life, who created me for himself.`"

He was accordingly bound apprentice to a cloth weaver at Holdbeck near Leeds,
who proved to be a very sharp master:
but the Lord enabled him with much patience to endure his trials,
attended as they were by a considerable portion of ill health,
until the period of his apprenticeship was nearly expired.
In the mean time,
he continued to use all diligence in seeking that
knowledge for which his soul was greatly athirst,
and for lack of which he suffered much distress of mind.
He attended assiduously at the preaching of all the
chief teachers of religion in the neighborhood,
wrote down their sermons in short hand,
and went afterwards to their houses to discourse with them,
that if possible he might gain some satisfaction as to the subject of his anxiety.
But in this he found himself disappointed; the result proving to him,
that no outward profession of religion however high,
no knowledge of Scripture however complete in itself,
no attention to religious observances however strict,
could ever cleanse the soul from sin, or restore it to a Slate of acceptance with God.
"`He lacked Christ,`" the chief of ten thousand, the beloved of souls,
"`and without him he could not live.`"
The following are his own words.
Speaking of this serious people in the district about Leeds.

"`There was,`" says he, "`as had been reported, much speaking of God, called preaching,
and professing him in words, from the letter of the Scripture,
what the saints had spoken forth, thus imitating the saints`' practice in a carnal wisdom,
and seeking the kingdom of God in outward observations,
as I had done before I came there.
But I met with none who could tell me what God had done for their souls,
in redeeming them from the body of sin, which I groaned under,
and which separated me from the presence of God.
Although I walked strictly with them in their outward
observations and in running to hear one man after another,
called ministers, yet I found no rest nor peace to my weary soul.
The flaming sword, the righteous law of God,
cried in me for a perfect fulfilling of the law, and met me wherever I was;
so that I could find no peace in that worship of God the world
had set up,--such as receiving the bread and wine,
which they told me were the seals of the covenant.
It was long ere I dared to receive them, because I saw not myself prepared:
for the evil of my heart stood before me.
And when I was about to receive them, I sought the Lord to keep me by his power,
that I might receive them worthily; and when I did receive them,
my desire was that the Lord would seal up his will to my soul,
but I found nothing sealed to my soul therewith.
Then much fear seized upon me for a long time after;
and the condition of Judas was cast into my mind; until it was showed me,
that the seal of the covenant was the Spirit of Christ, and no outward element:
and that the supper was the body and blood of Christ which the world does not know,
nor did I at that time, but I was made to wait for the manifestation of it to me.`"

"`Then I dared join no more with the world in that practice;
nor in singing David`'s conditions, which they called singing psalms.
For the light in my conscience let me see the evil of my heart,
that I was not in David`'s condition; the sense of which stopped my mouth:
and while others were singing,
I mourned and wept for lack of the pure spirit that David had,
and which caused him to sing.`"

"`Neither was I able to apply the promises, which they told me belonged to me,
for I found no promise belonging to that nature; but the wrath of God abode upon me,
for my disobeying his counsel in me, the light in my conscience.
But being ignorant that it was his counsel, I departed from it,
and lent my ears to those who said they spoke from the mouth of the Lord;
and I was deceived, and thus caused to err by their lies,
who drew me to seek the kingdom of God in observations without.
But the word of the kingdom was in me,
and executed the righteous judgment of God upon my adulterous heart,
that took counsel and not at his mouth.`"

Under these exercises of mind, William Dewsbury`'s health gave way,
and he became so weak as to be unable with all his efforts, conscientiously exerted,
to answer the expectations of his master; who, thinking him to be in a consumption,
was inclined at one time to send him home to his relations; but on further reflection,
he judged it to be more prudent to take medical advice.
Dewsbury, however, being fully aware of the real cause of his malady,
and rightly concluding that it was no other than the evil of his own heart,
and the distress of mind there arising,
resolutely declined employing such means for his relief, with a solitary exception,
to avoid giving offense.
And when, after diligent search among the Puritans,
he was unable to find any who could apply a remedy to his spiritual malady,
he was constrained to make his case known to such as were esteemed in
the world as the most experienced ministers and professors;
and to ask them what he might do to be saved.
But they also proved to be physicians of no value; mere ministers of the letter.
They told him to believe in the name of Christ, and to apply the promises;
but to wait for "`the revelation of Jesus Christ`" in his own heart,
they never counseled him;
and it only added to his sorrow to be thus urged to believe in Christ,
when neither he at that time, nor his advisers, knew where he was to be found,
nor how believed in to the saving of the soul.
