== Chapter 6

1654+++.+++ William Dewsbury imprisoned at York--Circumstances attending
his apprehension--Malice of the constable--Pursued to Crake,
and there taken at midnight--His ill treatment--Endures three months`'
imprisonment--Innocence--Imprisoned at Derby--Refuses to leave the prison
without the magistrates`' intervention--Is thrust out accordingly--Brought
before the mayor at Leicester--Put out of the town,
but returns--Proceeds to Northampton--Thomas Andrews`'
treatment of him--Is seized by the high-constable,
but set at liberty--Francis Ellington convinced--
William Dewsbury is taken up on a charge of blasphemy,
and committed to the common jail.

In the first month, 1654, we find this faithful man at York.
He was cast into the prison of that city under the name of a seducer,
with the following accusation, namely,--"`for seducing the people of this nation,
and for suspicion of blasphemy and breaking the public peace,
in dispersing principles contrary to the truth of the Gospel and peace of the nation.`"
Edward Bowles, priest of York, was his accuser, who gave forth a paper,
charging him with being, in addition to the other allegations,
a ringleader of the persons called Quakers.
As the general court sessions were then being held,
this paper was delivered by the foreman of the grand jury to Hugh Wyndham,
who sat on the bench as judge of the criminal court.
He immediately granted a warrant in open court for the apprehension of Dewsbury.
The charges were serious, and the agitation of the public mind was at that time so great,
in consequence of a plot that was suspected against Cromwell,
that people were ready to believe without examination or proof:
nor was there much benefit in general to be derived from the
most straightforward explanation of facts and circumstances.

In the prosecution of his religious labors,
William Dewsbury had proceeded in the mean time to Tholthorpe, where the constable,
more like a ruffian than a peace officer, fell in with him.
While he was at a meeting, and engaged with others in the solemn act of waiting upon God,
the aforesaid officer rushed in upon them,
and with a manifest intention of injuring William Dewsbury,
twice attacked him with an iron fork; "`but,`" says he,
"`the Lord by his power chained him, and prevented his bloody intents.`"
Whether the fellow was over-awed by the calm, solemn,
and dignified deportment of the Friends, or whether from some other cause,
it is not easy to understand by what means he was
prevented from carrying the warrant into execution.
Thus disappointed, however, he proceeded to Kirby Hall,
the residence of Thomas Dickenson, a justice of the peace,
and there renewed his accusation,
and procured another warrant for Dewsbury`'s apprehension and imprisonment,
grounded in part on that issued previously by Judge Wyndham.

At Crake, a small town about twenty-five miles northwest of York,
he was apprehended by John Lockwood, the high-constable, to whose hands, it would appear,
the warrant had been committed.
This officer, very unlike the former one, willing to save himself trouble,
proposed his remaining with his friends that night, it being late,
on condition of their becoming bound for his appearance the next day.
But Dewsbury told them resolutely, that no man should be engaged for him,
neither desired he favor at their hands: and turning to the constable, said,
"`If you have power over the body, do with it what you have power to do.`"
But as the evening was advancing,
he bade him stay at his friend`'s house until the morrow;
whereupon he assured the officer of his readiness to go with him at the time appointed,
if the Lord pleased.

This little season of respite afforded him and his friends an
opportunity of sitting down together to wait upon God;
an exercise at all times profitable, but never more so than in straits and difficulties.
Thus engaged "`in the night season,
with many of the Lord`'s servants and children,`"
"`waiting on Him who is worthy to be waited upon,
and is good to the souls that wait upon him,
to the souls that seek him,`" and the night being far spent under this exercise,
they were surprised by the inhabitants of the town,
with the high-constable at their head,
(contrary to his own engagement,) who surrounded the house,
and attacking the doors and windows with great fury,
determined to have the disposing of Dewsbury themselves.
When, in their blind rage,
they had got this innocent servant of the Lord into their hand,
they urged him along the street, shouting from one ale-house to another,
until they had found one into which entrance could be obtained.
This done, they committed him to the custody of two men until the next day;
and in the morning, he was brought before Dickenson,
who being unable to prove anything against him, committed him to York Castle,
by virtue of the warrant previously issued by Judge Wyndham.

+++[+++In an original letter written from York Castle, the 2nd of the fifth month,
William Dewsbury speaks largely in commemoration of the Lord`'s dealings with him,
that he had seen much of his mighty power manifested,
in carrying him along in the service of the Gospel,
wonderfully preserving and upholding his outward man many times,
when he seemed given over to death;
and though the plots and snares of evil men had abounded against him,
yet were none of them allowed to prevail,--"`it pleased
my dear Father they had no power against me,
until I had been amongst all the Friends in the east part of Yorkshire.`"--Editor.]

Here, innocent of the commission of any real crime,
he was detained a prisoner until the general court sessions,
which occurred on the 22nd of the fifth month following,
when Judge Wyndham sat again upon the bench.
On that occasion, for the Truth`'s sake,
and that nothing might lay unjustly either upon the
holy cause itself or upon the sufferer for it.
Friends, always courting investigation in open trial,
anxiously interceded with the judge,
for the prisoner to have the same advantages that thieves and murderers were allowed,
namely, to meet his accusers face to face; and then,
if the transgression of any just law could be proved against him,
they were willing he should suffer for it, as he was also himself.
Nothing could be more fair than this; and publicly accused as he was,
and abused as he had been, he had a right to demand the protection of the law.
The judge promised him a fair trial, but broke his engagement:
for William Dewsbury was never, on those charges, brought before him, but,
at the conclusion of the court sessions, was cleared by proclamation,
and set at liberty on the 24th of the fifth month.

Thus did they treat this innocent man.
He was apprehended as a criminal,
abused as one whom the law had placed out of its protection,
committed to prison upon vague and empty and malicious charges,
without shadow or pretense of proof, detained there for a period of three months;
and then, without being afforded the opportunity of defending his character,
was set at liberty; no doubt, in order that his accuser, the priest Bowles,
might escape the disgrace,
which must have resulted from an impartial examination in open court.

+++[+++The following letter, addressed by William Dewsbury to Margaret Fell,
will be interesting to the reader, as conveying his own account of these circumstances.
It is copied from the original.--Editor.]

My dear Sister,

In the Lord Jesus, where my life is bound up with you,
and all my brethren and sisters in the Truth of God, in your family and elsewhere,
my love salutes you all in the Lord,
where my union is with you and your family and
all my Father`'s children thereaway and elsewhere.
Oh, the riches of the love of our God, who has created all things for his pleasure,
and has chosen us in his free love,
and has made us partakers of his riches which he has laid up for us in Christ Jesus;
which love overcomes all things, and constrains to give up soul and body,
a living sacrifice, unto the will of our heavenly Father,
to dispose of them according to the counsel of his own will,
who created them for his own glory, who alone is worthy of all glory, honor, power,
and praises forever!

Dear sister, great have been the plots of Haman`'s nature,
against the time of this court sessions, to get something against us,
to bring us under their law, that their wills might be satisfied;
but in all their works of darkness, our heavenly Father brought them to light.
I was moved to write to priest Bowles:
and the Lord smote him with such terror that he could
not tell what way to turn to cover his deceit;
for the terror of the Most High was upon him.
So he wrote to Oliver Cromwell; and when he sent the letter,
Cromwell expressed these words, when he read it,
'`They would have me to disown this people;
shall I disown them because they will not put off their hats?`'
And the high-sheriff came to me to clear Bowles;
but the power of the Lord cut the deceit in him, that he went from me in much rage,
and said I was the most diabolical fellow, with many other bitter expressions.
Then Bowles sent to Thomas Fairfax, who was once the general of the army; and told him,
he had brought him on in casting me into prison, and he might bring him off.
And thus the man did fly to the arm of flesh: but my God, who is my refuge,
pursued him with terror,
and caused fearfulness to surprise the hypocrite whichever way he went.
They gave forth great words, what they would do at the court sessions, as Haman did,
who built the gallows for Mordecai; but the power of the Lord trampled upon them,
and great fear surprised priest Bowles, the sheriff, and the judge;
that as they were in trouble, to accomplish their design to cast my body into prison,
+++[+++so they desired]
to cover me with lying aspersions, when they had it there;
and as the Philistines were plagued, while they had the ark of the covenant,
till they sent it back, so were they:
they dared not let me nor any of our friends come before them.
And as the Philistines sent the ark back the same way it came,
so were they who had cast me into prison by their false accusations,
forced to make open proclamation in the court, and in the castle-yard,
when the country was met together, that if any had anything against me, to speak;
thus clearing me of all these lying aspersions, they liberated me to go forth.
The Lord takes the wise in their own craft:
praises forever be unto his great and glorious name,
who is raising up his own Seed in the hearts of his children to obey his will,
and has kept us bold, valiant, and faithful in this day of trial.
Captain Bradford, and Friends who were called upon service at this court sessions,
have been kept bold, valiant, and faithful in their measure,
trampling upon proud flesh in its glory.

My dear sister, the Lord God of power is with you, who has chosen you in his love,
to bear witness of his great and glorious name; and his power rest upon you,
to the threshing down of all deceit,
that his tender plants may be watered with the streams of his love through you,
in the Lord Jesus, where you fare well, and there I am with you, your dear brother.

W+++.+++ D.

Being now "`delivered from the hands of unreasonable
men,`" he pursued his journey as the Lord directed him,
declaring his word in Cleveland and other parts of Yorkshire, through Nottinghamshire,
and so to Derby.
+++[+++It is satisfactory to be able here to introduce part of a short letter to a Friend,
which supplies us with some information with regard to
his travels in the ministry at this juncture.--Editor.]

God is opening a door for his truth in many great towns in Yorkshire,
where it has been kept out; as at Halifax, Leeds, York, Beverly, Hull;
and since my disposing of the family that was on me,
I have been pretty much in these great towns in my passing south, as Lincoln, Nottingham,
Newark, Oakham, Leicester,
Wellingborough,--large meetings in all parts,--a tender people are coming towards Zion,
who have stood off,--Newark the least.
At Leicester, we met at the castle a very large people; that night,
a large meeting at the White Hart Inn, where we lodge.
If God will, I shall be at a general meeting at Northampton the next third day,
and at Leicester the next first day after.

William Dewsbury had not, however, been at liberty more than a month,
before his lot was again cast within the walls of a prison.
For, as he was engaged in preaching to the inhabitants of Derby, he was seized,
and carried before the general sessions of the town, which were then holding.
This took place on the 24th of the sixth month.
When brought into court, one of the justices,
probably on account of his not taking off the hat, said to him,
magisterially enough no doubt, "`In whose presence do you now stand?`"
To which William Dewsbury, I should conclude, from his general character, not lightly,
but under a sense of its being proper at the time, replied,
"`In the presence of the everlasting God.`"
On this, the jailer was commanded to take him away, and put him in prison,
for disturbing the court, which was accordingly done.
Towards night, the mayor sent for him, to inquire of him, what he came to do?
He answered,
"`To declare the word of the Lord to the consciences of the inhabitants of Derby.`"
The mayor then asked him, if he would go out of the town?
This, Dewsbury refused to do, saying, "`When the Lord orders me to go forth,
then I shall go; till then, I shall stay.`"
The mayor then commanded him to be returned to the prison.
The next day, in the forenoon, one of the mayor`'s officers was sent to him, to say,
that if he would go out of the town, and promise not to return,
he would open the prison doors, and he might go forth; upon which, William Dewsbury,
who had by this time proved himself to be a man of no ordinary courage, said in reply,
"`Out of the town I shall not go, until I am ordered of the Lord;
and if you open the door, I shall not go forth of the prison,
till the man who said he had authority to put me in,
come by the same authority and take me out.`"
Most likely the prisoner suspected a trap: how it was with the mayor,
it is not easy to say.
Whether, conscious of his illegal proceedings,
he was intimidated by this resolute conduct on the part of William Dewsbury,
or whether he acted from some other motive, is not known; but it is at least curious,
that, shortly afterwards, the man under whose charge he was committed to prison,
was sent to discharge him; who took him by the arm, not with entreaty,
as was the case with Paul, when he was confined with Silas at Thyatira,
but with much anger put him forth, and delivered him to another officer.
This man had orders to put him out of the town; which he did,
charging him with many threatenings, to depart and not return.
But William Dewsbury, feeling himself to be moving under commands of a higher order,
and knowing that he was not in the transgression of any righteous law,
considered these but the words of vain men, and without regarding them,
returned forthwith and continued in Derby until he was free in his spirit to leave it.

When this time arrived, he pursued his journey to Leicester; and there,
on the 3d of the seventh month, being the first-day of the week,
a large number of the people were collected together to hear him,
to whom he declared the word of the Lord.
After his testimony was finished he proceeded to the public place of worship;
and when the speaker had done,
William Dewsbury preached the word of eternal life to the assembly,
who heard him with much attention.
But before he had finished his testimony, two officers laid hold of him,
and with violence carried him before the mayor of the town;
who committed him to prison without examination,
and therefore without proof of any illegal or disorderly act.
The next day, he was again brought before the mayor and another in authority,
who then examined him, but could find nothing that would warrant his detention.
They however commanded the keeper of the common jail to put him out of the town, and,
as the authorities of Derby had previously done,
strictly charged him "`to depart forth of their coasts;`" with many threatenings,
what they would do if he returned.
But as before, without regarding the threats of man,
in obedience to the command of the Lord,
he returned to finish his testimony to the inhabitants of Leicester,
of whose blood he had not previously felt himself clear.

As soon as William Dewsbury,
in submission to those impressions which he believed to be from the Spirit of Truth,
apprehended himself at liberty to leave Leicester,
he pursued his journey into Northamptonshire, and proceeded to Wellingborough,
on a visit to the flock of God scattered thereabout; where he tarried for a season,
finding many in that neighborhood whose minds were opened to
receive "`the word of life with much gladness of heart.`"
An occurrence took place in this town,
which ultimately occasioned him some months`' imprisonment at Northampton;
and will serve to show,
that his labors were so successful as to excite the
displeasure and jealousy of a resident priest there,
whose name was Thomas Andrews.
As he was passing along the street, near the dwelling of the latter,
the priest called to him, to "`give over deceiving the people,
lest the plagues of God should fall upon him.`"
To which Dewsbury replied, "`If you say I deceive the people, make it manifest,
wherein I deceive them.`"
He answered, "`You tell them there is no original sin.`"
Dewsbury then required him to say, whether he heard him say so.
But he, making no answer to that, the former told him,
he must either prove what he had accused him of,
or confess himself condemned of making a false accusation: he however hastened away,
without giving any answer.
About three weeks afterwards, namely, on the 29th of tenth month, 1654,
William Dewsbury having been absent from Wellingborough in the interval,
felt it to be his religious duty,
("`I was ordered of the Lord,`" says he,) to return to the place again;
and hearing there was to be a lecture in the house where Thomas Andrews was preacher,
who had thus falsely and publicly accused him, for the truth`'s sake he went there,
entered the house and stood in silence until Andrews had done preaching,
and had dismissed the people.
He then took the opportunity of exhorting the congregation,
who listened without opposition.
After this, addressing himself to the priest, he called upon him,
to make it manifest to the people, wherein he had deceived them, or to confess his error.
Without offering any reply, he again retreated, "`he fled away.`"

Notwithstanding the reasonableness of this conduct on the part of Dewsbury,
who was the offended party, he was haled out of the meeting-house,
by a man more zealous than discriminating, into the yard;
where he embraced the opportunity again afforded him,
of preaching to the collected multitude, they standing quietly to hear him;
until the high-constable made his appearance;
who seized and conducted him as a criminal into the market-place,
and threatened to bring a charge of blasphemy against him.
When it was found that nothing could be proved against him, he was liberated.
He retired to the house of his friend, Francis Ellington, and from an upper window,
preached to the people collected below, many of whom received the word in much love.
Ellington soon afterwards became his fellow-prisoner.

This Friend was an extensive wool manufacturer at Wellingborough.
The manner in which he became acquainted with William Dewsbury, was this.
In the pursuit of his business,
he happened to be at a fair at Harborough in Leicestershire, where he heard,
that a "`Yorkshireman`" was tarrying at a Friend`'s house in that town;
and that he was that day intending to hold a meeting,
in order to his declaring the word of the Lord to the people.
To this meeting Francis Ellington went,
and was effectually convinced that the word of
the Lord was really preached on this occasion.
Such was the power which attended,
that it enlightened his understanding "`to see the way of eternal life;
for which,`" says he, "`I had long sought in my imagination of the saints`' conditions.`"
When the meeting was over, yielding to a powerful impulse of religious unity,
he desired William Dewsbury, as the Lord`'s servant, to come home to his house,
as soon as he was free in his spirit so to do.
Which appears to have been the occasion of the present visit.

But to proceed with our narrative.
On the following day,
the constable having procured a warrant for the apprehension of "`one who is
commonly called a Quaker,`" came to the house of Francis Ellington;
and, notwithstanding the remonstrances of the latter,
against taking any person into custody on such a vague warrant as that in his possession,
for the name of the party to be arrested was not mentioned in the warrant,
the constable laid his hands on William Dewsbury, although Joseph Storr was also present,
and declared him to be the man he wanted, requiring him to go before a justice.
This he was compelled to do the same day.
He was conducted to the residence of Thomas Pentlow, who lived at Wilby, two miles off,
and who appears to have been a rigid persecutor.
Francis Ellington and Joseph Storr, willing to stand by their friend,
in his present trial, accompanied him to the house.
An additional reason why these Friends accompanied William Dewsbury was,
that they had also a complaint to make against a
woman in the service of the said justice,
who a few days before had annoyed Ellington and others by abusing them in the street,
and by throwing water, stones, and dirt at them.
The justice having examined William Dewsbury,
and found on his person some papers addressed to Cromwell, then Protector,
made out a court order, and sent him to the common jail at Northampton,
there to await the court sessions in the first month following.
As the court order, among other allegations,
was also said to contain a charge of blasphemy,
Dewsbury was the more earnest to obtain a copy; which reasonable demand was, however,
denied him.
As to the complaint against the woman,
which Ellington and his friends preferred before Justice Pentlow,
it procured them no redress.
After calling them to account, for being found on his premises, he told them,
the woman had served them right, for aught he knew, and he would do nothing against her;
and charged them to be forthcoming at the approaching sessions,
as he should send a constable for them,
that they might answer there for having come to his house.
One account states,
that Pentlow included Ellington`'s and Storr`'s names in the court order.
In consequence of such treatment,
Ellington a few day after wrote a letter to the justice,
which offended him still more deeply,
and was the ground of his shortly afterwards suffering for several
weeks in company with other Friends in Northampton jail.

+++[+++By a letter in William Dewsbury`'s handwriting, addressed to George Fox about this time,
it would seem there followed from the labors of this devoted servant "`a
great convincement,`" and an earnest desire prevailed among many,
for Friends to come amongst them; and he intimates his belief,
that a blessing will attend those, who being truly drawn and called,
give up to the service.
Another letter runs thus: "`Many dear people has our Father in these parts,
the harvest is great, mighty people our God is bringing forth hereaways,
to wait upon him for his wisdom to guide them to his praise and glory.`"
Nor is this from his own pen alone: John Whitehead, a zealous laborer,
writes to George Fox from Wellingborough, of "`a mighty thirst on every side,
great meetings, and many convincements.`"--Editor.]
