== Chapter 7

[.chapter-synopsis]
* 1655+++.+++ Letter of William Dewsbury
* Court Sessions
* His trial, with other Friends, before Judges Hale and Wyndham
* They refuse to enter into bonds, and are continued in prison
* Observations on the trial, with remarks on the times
* Apprehensions entertained respecting Friends
* Anecdote respecting George Fox and Colonel Hacker
* Two letters of Dewsbury`'s.

The following letter, under the hand of William Dewsbury,
contains a brief but somewhat detailed account
of circumstances respecting him at this period;
and will put the reader in possession of information connected
with the transactions of the preceding chapter,
which would otherwise be lacking, and could not be supplied from any other source.

[.embedded-content-document.letter]
--

[.salutation]
Dear Friends,

Be not troubled at the Lord`'s disposing of us,
in permitting the devil to cast us into prison;
for with you we are in the liberty of the spirit, in the unity which cannot be separated.
I have declared to you the Lord`'s ordering of us to his praise and glory.
On the 10th day of the eleventh month, Joseph Storr, my fellow-prisoner,
and I were carried from the prison to the sessions, which were holden at Northampton.
There were John Parker, who fined my brother, Thomas Aldam, and others called justices,
who were in great enmity against the truth.
But the witnesses, who had sworn against me, as they said, for blasphemy, did not appear.
The Lord smote them with terror; the lying spirit dared not appear.
They were confounded in that they charged against me;
and many friends appeared in much boldness for the truth; Justice Crutt and James Nagill,
who are great in the outward; their dwellings are in Bickering Park, Bedfordshire;
and one Edward Hackney, an attorney at Kettering in Northamptonshire.

There had not been above three meeting with me;
yet the enmity of John Parker and those with him, required bondsmen to be bound for me:
for they said I had written strange papers to the lord Protector,
and if I would not find men to be bound for me, I should go to prison again.
I then required of them, to read me any law I had transgressed; but they would not,
but called for bondsmen.
I answered.
There shall not any be bound for us; here are our bodies,
do with them what you have power to do.
They commanded the jailer to take us away.
We were not allowed to speak any more, but taken and put into prison;
and a copy of our court order we cannot have; but were denied both by the jailer,
and the men called justices, when it was demanded of them in open court.
But the wrath of man turns to the praise of God.
For the truth of God was much spread abroad that day,
and a mighty thirst was raised in the hearts of many towards the name of the Lord;
praises forever be to him, whose ways are past finding out.
He takes the wise in their own craft, and overturns them in their own devices,
to their shame and contempt; but to the glory of his name, who alone is worthy,
God over all, blessed forever!

[.signed-section-signature]
W+++.+++ D.

--

William Dewsbury, together with Joseph Storr, whose name was included in the court order,
for no other crime than that of being present at the examination of his friend,
being committed to prison, were confined there among thieves and murderers,
twelve steps under ground, until the quarter sessions on the 10th of the next month;
when, so far from receiving any mercy at the hands of the justices,
they were again refused a copy of their court order,
and committed to appear at the next court sessions about two months afterwards.
Francis Ellington was now added to their number, and Henry Williamson,
who had been sorely beaten and abused for attempting to speak to the people
at the public house of worship after the officiating priest had done,
was also sentenced to drink of the same cup.
The court sessions commenced the 10th of the first month, 1655, when the prisoners,
Dewsbury, Storr and Williamson, were brought to the bar,
before Judges Matthew Hale and Hugh Wyndham,
who were then associated in the same commission.
The following examination thereupon took place.

[.discourse-part]
__Judge Hale.__--Are you Dewsbury?

[.discourse-part]
__William Dewsbury.__--Yes, I am so called.

[.discourse-part]
__Judge Hale.__--Where do you live?

[.discourse-part]
__William Dewsbury.__--I have a wife and three children at Wakefield in Yorkshire.

[.discourse-part]
__Judge Hale.__--What came you into this country to do,
that you did not stay in your own country with your wife and children?

[.discourse-part]
__William Dewsbury.__--I stayed in that country with my wife and children,
until the Father revealed his Son in me,
and called me forth from my wife and children to declare his word of eternal life,
which he has manifested to my soul in the great work of regeneration,
in the new covenant of life in Christ Jesus.
I am sent to preach the everlasting Gospel to those that dwell upon the earth.

[.discourse-part]
__Judge Hale.__--I fear it is a delusion, and your own fancies, and not the truth.

[.discourse-part]
__William Dewsbury.__--Time will make it manifest.

[.discourse-part]
__Judge Hale.__--You draw people together, and act against ministry and magistracy.

[.discourse-part]
__William Dewsbury.__--As you stand in the presence of God,
take heed of hearkening to false accusations.
Ministry and magistracy, which are of God, I own:
but those who are called ministers of Christ, and walk contrary to Scripture, I disown.

[.discourse-part]
__Judge Hale.__--But who are they that walk contrary to Scripture?

[.discourse-part]
__William Dewsbury.__--They that abide not in the doctrine of Christ,
"`but have the chief place in the assemblies; stand praying in the synagogues,
love greetings in the market-places, and are called of men,
masters,`"--which practices Christ cried woe against; and they that walk in them,
walk contrary to Scripture.

[.discourse-part]
__Judge Hale.__--These are small things to speak of.

[.discourse-part]
__William Dewsbury.__--There is nothing small which the Lord commands.

[.discourse-part]
__Judge Hale.__--You say well.
(To the court.) What have you against these men?

[.discourse-part]
__William Dewsbury.__--That is what we would have manifested, what law we have transgressed.

[.discourse-part]
__Judge Hale.__--Produce what you have against them, and I shall proceed according to law.

[.discourse-part]
__Cleric of the Peace.__--Here are papers which Dewsbury and Storr had,
which are against the lord Protector.

[.discourse-part]
__William Dewsbury.__--The papers they took from me, which they say are against the lord Protector,
I was moved to write.
I sent one to him privately with care, in the fourth month in last year,
and the other has with care been privately delivered to him;
and privately I kept the copy of the papers,
until I was apprehended by virtue of a warrant granted by Justice Pentlow.
There was not any name in it, but it was for one whom he had in scorn called a Quaker:
and with that warrant, the constable had me before him.
He commanded the constable to see if I had any money; which was done,
and my money taken from me, and after a little time he gave it to me again.
Then they took those papers from me, which I had privately on me in a letter case,
which here they publish publicly as an evidence against me.

[.discourse-part]
__Judge Hale.__--Read the paper.
(When part of it was read.) Give over, that paper is not to be published.

[.discourse-part]
__William Dewsbury.__--It is not my mind they should be published.

[.discourse-part]
__Judge Hale.__--How dare you write to him in such high language, as from the Spirit of the Lord?

[.discourse-part]
__William Dewsbury.__--They in whom the Spirit of the Lord is, write from the Spirit,
and he that has not the Spirit of Christ is none of his.

[.discourse-part]
__Judge Hale.__--But I fear it is not from the Spirit, for many pretend the Spirit,
and the divine light, and revelations;
but how shall we know they are the truth according to the Scriptures?

[.discourse-part]
__William Dewsbury.__--The Scriptures cannot be known but by the pure divine light of Christ,
which enlightens every one that comes into the world;
of which pure light Christ has given to every one a measure, to try the spirits in them,
whether they be of God or not.
Every spirit that confesses Christ is come in the flesh, is of God;
but he that denies Christ is come in the flesh, is the spirit of antichrist.
And this light gave the Scriptures forth, which light leads to Christ,
who reveals the Father to the soul which gives up to be guided by him.
So the soul comes to know God by the revelation of Jesus Christ,
and they who walk in the spirit are known by their fruits in all their words and works.
The prophet Amos, had the spirit of the Lord,
and from the spirit declared the word of the Lord to the king of Israel,
but the people could not bear his words.

[.discourse-part]
__Judge Hale.__--You say well, if you do as you say; but this, it may be, will be expected,
and I think it will be fair, to give bail for your appearance at the next court sessions.

[.discourse-part]
__William Dewsbury.__--First make manifest what law we have transgressed, before bail be required.

[.discourse-part]
+++[+++After this the prisoners were set aside, and the judge proceeded to other business;
but in the evening, when the court was ready to break up,
the jailer asked the judge what he should do with those Yorkshiremen?]

[.discourse-part]
__Judge Hale.__--Bring them before the court.

[.offset]
+++[+++Which was done.
Then some in the court said,
"`Take off their hats;`" and two of their hats were taken off;
but as they were about to take off William Dewsbury`'s, the judge said,
"`Let it be on,`" and bade them put on the hats of the other two again,
which was done at his command.
He then spoke to William Dewsbury.]

[.discourse-part]
__Judge Hale.__--Now I see what you are, and your disguise and form of fair words is seen,
and you are not the man you pretend to be.

[.discourse-part]
__William Dewsbury.__--Disguises and formality I deny; but the power of God I own and witness,
in which I stand, and am subject to it, and to the ordinance of man for conscience sake.

[.discourse-part]
__Judge Hale.__--Now you are commanded: Take off your hat.

[.discourse-part]
__William Dewsbury.__--Honor is not in pulling off the hat,
but in obeying the just commands of God;
and my hat offends not any.
They who are offended at it, may take it off: I shall not resist them.
But there is no Scripture that expresses any honor to be in putting off the hat.

[.discourse-part]
__Judge Hale.__--What! must we do nothing but what is expressed in Scripture, for our apparel,
what we shall put on?

[.discourse-part]
__William Dewsbury.__--Yes, the Scripture says, Let your adorning be with modest apparel.

[.discourse-part]
__Judge Hale.__--Are you judge, that you stand covered and will not uncover, as other prisoners do?

[.discourse-part]
__William Dewsbury.__--What I do, God is my witness, I do it not in contempt to any,
but in obedience to the power of God for conscience sake.

[.discourse-part]
__Judge Hale.__--If you will not stand as prisoners, I will not do anything concerning you;
but here I found you, and here I shall leave you.

[.discourse-part]
__William Dewsbury.__--We have been above ten weeks in the low jail,
and no breach of any law found against us: we stand subject to the power of God,
whatever he allows you to do with us.

[.offset]
Thus far as relates to the present examination of William Dewsbury.

On the 12th of the same month, the Judges Wyndham and Hale being together upon the bench,
they called for the prisoners
Dewsbury, Storr, and Williamson.

[.discourse-part]
__Judge Wyndham.__--Take off their hats.

[.discourse-part]
__Judge Hale.__--Read the evidence against them.
+++[+++Which having been done as before.]
What say you, did you speak these words?

[.offset]
+++[+++William Dewsbury then related his encounter with the priest Andrews,
and the circumstances which led to the disturbance in the market-place at Wellingborough;
asserting the breach of the peace and the tumult to have been caused by his accusers,
and not by him.
The examination then proceeded.]

[.discourse-part]
__Judge Wyndham.__--Dewsbury, you are well known in the north and in Yorkshire;
there I have heard of you; but where were you born?

[.discourse-part]
__William Dewsbury.__--My natural birth was in Yorkshire.

[.discourse-part]
__Judge Wynhdam.__--Do you begin to cant?
Is there any other birth?

[.discourse-part]
__William Dewsbury.__--Yes.
"`Except you be regenerate and born again, you cannot see the kingdom of God.`"
Which birth I witness.

[.discourse-part]
__Judge Wynhdam.__--At what place in Yorkshire were you born?

[.discourse-part]
__William Dewsbury.__--At a town called Allerthorpe, nine miles from York, towards Hull.

[.discourse-part]
__Judge Wynhdam.__--Where have you been your time?

[.discourse-part]
__William Dewsbury.__--When I was thirteen years of age,
I was bound apprentice to a cloth maker in the west part of Yorkshire,
at a town called Holdbeck, near Leeds.

[.discourse-part]
__Judge Wynhdam.__--Did you serve your time?

[.discourse-part]
__William Dewsbury.__--I did stay till the time was nearly expired,
and then the wars began in this nation, and I went into the service of the parliament.

[.discourse-part]
__Judge Wynhdam.__--Do you deny all Popish tenets?

[.discourse-part]
__William Dewsbury.__--Popish tenets I deny;
and all tenets contrary to the pure doctrine of faith in the Lord Jesus Christ.

[.discourse-part]
__Judge Wynhdam.__--Do you own the Scriptures to be a rule to walk by?

[.discourse-part]
__William Dewsbury.__--The Scriptures I own;
and the pure light and power of Christ Jesus that gave them forth,
to guide in a holy conduct according to the Scripture;
and he that walks contrary to it is condemned by it.

[.discourse-part]
__Judge Wynhdam.__--Couldst you not stay in your own country, and keep your opinions to yourself;
but you must go abroad in the country, and in these parts, to delude the people,
and to make a disturbance?

[.discourse-part]
__William Dewsbury.__--Deluding I deny.
I would have you make manifest what delusion is.
But truth I witness; and the things I have heard and seen I am sent to declare;
which disturbs not the peace of any, but of those who walk not in the truth;
whose peace must be disturbed and taken away..

[.discourse-part]
__Judge Wynhdam.__--But if you and Fox had it in your power,
you would soon have your hands imbrued in blood.

[.discourse-part]
__William Dewsbury.__--It is not so.
The Spirit of Truth which we witness in us is peaceable,
and neither does violence nor sheds blood:
and the hands of all that are guided by the Spirit of Truth,
the light and power of Christ, are bound from offering violence, or shedding blood.

[.discourse-part]
__Joseph Storr__.--Their sufferings and stonings are well known in
this nation--and they never lift up a hand against any.

[.discourse-part]
__Judge Wynhdam.__--It is because you have not power;
but here is evidence against you for breaking the peace.
Will you give bond for your appearance at the next court sessions?

[.discourse-part]
__William Dewsbury.__--It is the liberty of the law of this nation,
that all who profess the faith of Christ Jesus,
may walk in uprightness to their faith in him, without any breach of the laws.
And I require,
a law may be read to us that the evidence brought against us is the breach of;
that by the law we may be convinced of transgression before any bail be required of us.

[.discourse-part]
__Judge Wynhdam.__--We are judges,
and we conceive and judge what is charged against you
to be a sufficient ground to require bail of you,
for your appearance at the court sessions.

[.discourse-part]
__William Dewsbury.__--Though you be judges, you are judges of a law,
and are to judge according to law,
which is your rule to judge by, and that law I would have you to read us;
and if we have transgressed it, judge us according to it.

[.discourse-part]
__Judge Wynhdam.__--You are transgressors of the law,
in that you are not subject to government and authority, refusing to pull off your hats.

[.discourse-part]
__William Dewsbury.__--We are subject to the government and the power of God,
and to the ordinance of man for conscience sake; but show us in Scripture,
which is a true testimony of the power of God, in which we stand,
that putting off the hat is required in subjection to authority;
and read us a national law, which is the ordinance of man, that requires such a thing.

[.discourse-part]
__Judge Wynhdam.__--It is the practice and custom of the nation.

[.discourse-part]
__William Dewsbury.__--The customs of the heathen are vain.

[.discourse-part]
__Judge Hale.__--From the evidence which has been read, we expect bond for your appearance,
as has been required, at the next court sessions.

[.discourse-part]
__William Dewsbury.__--We have not transgressed any law: if you know of any law broken by us,
let it be read, that we may know what bail is required for;
and what we are to answer at the next court sessions.

[.discourse-part]
__Judge Hale.__--What say you, Storr?
Will you enter into bond for your appearance at the next court sessions?

[.discourse-part]
__Joseph Storr.__--Where are those who have given evidence against me,
that I may answer to the particulars of those things charged against me.

[.discourse-part]
__Judge Hale.__--If you will give bail for your appearance at the court sessions,
then shall those that have informed against you appear face to face.

[.discourse-part]
__Joseph Storr.__--We are bound by a stronger tie than any outward bond.

[.discourse-part]
__Judge Hale.__--What say you, Williamson?
Will you enter into bond for your appearance at the next court sessions.

[.discourse-part]
__Henry Williamson.__--I am not of any ill behavior;
but am bound to good behavior by the power of God.

[.discourse-part]
__Judge Hale.__--If you will not find sureties, you must lie here till the next court sessions.
Look to them, jailer.

[.small-break]
'''

They were accordingly conducted back to prison,
and there confined eleven weeks in the nasty low jail, as before, among felons,
until another assize.
In the meantime several others of their friends were committed to prison.

Although it is difficult, no impossible, to reconcile such a result,
with the principles of straight-forward justice,
it is due to the judges and others in authority in those turbulent times,
and in particular to the character of Judge Hale, to observe,
that Friends then were not so well understood as they have been since.
This, in fact, was one of those instances,
in which too little discrimination was exercised,
and the innocent were accordingly made to suffer with and for the guilty.
For, notwithstanding it was then, as it has ever been,
a matter of religious principle among Friends, not to interfere in political questions,
nor to mix themselves up as partisans in the
agitations of the times about temporal things;
yet their free and uncompromising censure of many of
the principles as well as practices of the day,
rendered it difficult for superficial or prejudiced observers,
to distinguish their object from that of other classes of agitators.
And when it is remembered that the principles of
Friends respecting the national ministry,
both as to its appointment and its maintenance,
struck at the very root of the union of church and state, it is not to be doubted,
that many thought they had sufficient grounds for concluding,
that the views of this Society were unfriendly to the government itself.
This, however, could not sanction the many unjust and arbitrary proceedings under which,
as in the present instance, they were made to suffer; and there is reason to regret,
that the name of one, whose character stands so high as that of Judge Hale,
should be connected with a proceeding of that nature.
It is, nevertheless, very satisfactory to know, that at a later period,
when he was better informed,
his proceedings towards Friends wore a very different aspect.
It will still further illustrate the fact,
which has been pretty clearly displayed by the preceding trial,
that considerable fears of a political nature
were entertained respecting Friends at this time;
if the reader is informed, that while these matters were transacting in Northampton,
George Fox was no less a cause of apprehension in Leicestershire.
For he was about to hold a meeting at Whetstone, near Leicester, Colonel Hacker,
who afterwards suffered at Tyburn, as one of the judges of King Charles,
sent a company of horse to seize him,
on suspicion of his being engaged in a plot then in agitation against Cromwell.
In the course of the examination which followed, Needham, Hacker`'s son-in-law,
observed to his father, in reference to Fox, that he had reigned too long,
and it was time to have him cut off.
George Fox having remonstrated against such a surprising conclusion,
and declared his innocence, Hacker asked him if he would go home and stay there.
But he refusing to bind himself to do one thing or to refrain from another, Hacker said,
"`Then I will send you to my lord Protector tomorrow morning, by Captain Drury,
one of his lifeguards.`"
What follows is no less interesting than remarkable.
The next morning, when George Fox was delivered to Captain Drury,
he desired to speak to the Colonel before he went; which was allowed,
and he was brought to his bedside.
Hacker told him to go home, and keep no more meetings; which George Fox refusing to do,
he said, "`Then you must go before the Protector.`"
Whereupon George kneeled at his bedside, and prayed the Lord to forgive him:
for he looked on the Colonel`'s case to be like that of Pilate,
who would wash his hands of the guilt of the measure,
to which he was stirred up by the priests.
George Fox further told him to remember what he had then said,
when the day of his misery and trial should come
upon him--a day little anticipated by Needham,
when he made to his father the above-mentioned
observation respecting George Fox`'s career.
This is by no means a solitary instance of George Fox`'s foresight,
whencesoever it was derived.
Captain Drury, though a man of light behavior, and disposed to ridicule Friends,
conducted himself so far courteously to his prisoner,
as to allow him to visit William Dewsbury in the jail of Northampton,
when he passed through that town.

[.small-break]
'''

+++[+++The insertion, at the close of this chapter,
of parts of two original letters from William Dewsbury,
besides conveying further information as to him and his colleagues,
may tend to illustrate the foregoing sentiments of our author,
relative to the alarm which certainly at this juncture
took hold of the minds of the people at large,
but especially some classes,
whose church system seemed endangered by the rapid
spread of Friends and their principles through the land.
These letters are dated from Northampton common jail, the 3rd of the seventh month,
and 15th of the eighth month, 1655.

It seems that often, when their persecutors had got Friends into prison,
they found "`Jerusalem such a burdensome stone,`" as Dewsbury expresses it,
that they could "`not readily cast it off;`" the tendency of
which he describes as grinding them to powder.
They found and felt that they had wronged these oppressed people,
and how to deliver themselves of their prey, and deliver their own characters too,
was sometimes not an easy matter.
Friends feared the face of no man,
nor could be brought to bow to the corrupt wills of any, whether magistrates or others:
they stood to their testimony when they found
they must bear it for the Lord and his Truth,
against the deceit and oppression of man towards man in the things of God.
They could make neither unrighteous concessions nor mean compromises,
nor enter into recognizances, nor pay fines nor fees,
for doing what they considered their duty;
but were ever willing cheerfully to suffer for what nothing
short of this sense of duty could have induced them to do.
It appears by one of these letters, that the justices made use of the jailer,
to see if he could get any words from any of the prisoners, that could be construed,
as though they would enter into bonds for good behavior,
and intimated they should then forthwith be set at liberty.
But the jailer, though he would often meet others of the prisoners,
could not endure William Dewsbury`'s piercing eye and high-toned virtue,
often endeavoring to avoid him,
and would even run from him when he saw him coming towards him,
sooner than encounter him, and sometimes was not seen by him for more than a week.
This was the case with the person periodically
officiating as minister among the prisoners;
for Dewsbury had protested against him and his doctrine,
after he had delivered his discourse, on which, as he relates it,
"`fear surprised the hypocrite,`" so that "`he stood trembling,
and was not able to answer a word.`"
Upon this, the justices actually declared in the open court at the sessions,
that the minister "`dared not come to preach any more,
unless some course were taken with these Quakers;`" so
an order was given to lock them down in the dungeon,
which was done always after, during the hour of preaching.
Dewsbury adds:

[.embedded-content-document.letter]
--

"`The dread of our God is upon them, their heart fails them;
and their torment is daily increased, to see the Lord`'s work prosper,
which goes on in mighty power all over these parts, and all the nation over.
Friends grow in the power of our God.
They come from London, and many places on every side to visit us,
though they hear that they cannot be allowed to come at
us:--and the wisdom of our God is much in it,
who keeps them in patience, with boldness, to sit at the jail door,
for a testimony against them; which adds much to their torment.
The jailer threatens them;
and some are ordered of the Lord to go to the justices
to bear witness against their wickedness;
and every one would put it off from themselves, and deny what they have done.

We have all things we need in the outward: three in bonds with me maintain themselves,
two brothers, called Marmaduke and Joseph Storr, and one Francis Ellington,
who is by trade an upholsterer; and Thomas Goodair is in the town jail,
and maintains himself I have not been free to receive
any money of Friends here towards my necessities,
which has much confounded my adversaries,
that my life should be given up for their souls`' good,
and not to receive money of them to supply my needs:
but in some places I paid for what I needed, where they were not able.
As to some that had wealth,
but had parents who said they would be destroyed with receiving me,
and that their trading would fail in the world; contrary to their minds,
I was ordered of the Lord to pay them in full for what I had,
that the Gospel might not be burdensome.
I am supplied at all times with what I need, and so shall my wife and children be,
according to the word of the Lord, which was sealed to me eight or nine years ago,
when a house and garden grounds were taken from me by this persecuting spirit,
which then would not let me have the benefit of the law, but called me heretic, and said,
I might not be permitted to have an outward being in this nation.

Thomas Goodair was kept in the power and wisdom of our God,
in the day when he was brought before the rulers
of this town for a testimony against them.
Thomas Stubbs is in great service, and is preciously carried forth in the life.
Richard Farnsworth is come up amongst Friends in these parts;
much service the Lord has for him amongst them:
a great convincement there is upon many people,
and a great thirst wherever such Friends come; the harvest is mighty,
but the laborers are few;
pray the Lord of the harvest to send faithful laborers into his harvest.

--

[.offset]
The last of these communications, with some omissions, runs thus:--

[.embedded-content-document.letter]
--

[.salutation]
My dear sister,

Our Father has covered the faces of his enemies in these parts with shame,
and has exalted his Son over all their heads,--
they tremble before his power in his saints,
and our God has ordered them in wisdom.
Many he moves to come to visit us.
Captain Bradford, as he marched up to London, was allowed to quarter in the town,
and came to the jail door, to see if he might come to visit us in prison.
The jailer was very untoward at first, yet being somewhat afraid,
asked him if he had any command in the army; he answered him, '`What I have,
it matters not in this thing; for this I declare to you,
what command soever I have in the army, my sword shall not open the jail doors;
and if you do not open them, I shall not come in.`'
In meekness and patience he stood, until the Lord commanded the jailer`'s spirit,
that he let him come in; and in precious wisdom he was carried in the town,
which did much confound them; and the most of the time he stayed, he was with us,
and the prison was full of officers and soldiers.
In seventeen weeks before that time, few were permitted to come to us,
though some came about one hundred miles.
In the week following after Captain Bradford passed away, was the general sessions;
and there came certain Friends from Bristol, with our dear brother, John Audland,
and some from London, and Justice Crook, and certain others hereaway, who,
in the power of the Spirit of our God,
did tread on the heads of these that persecute him in his children,
that they trembled before the presence of the Most High.
Two young men, who are in bonds, were brought before the men that sat at the sessions,
and the Lord manifested his power in them,
that those called justices were confounded before all the people;
but the time of their freedom out of bonds was not yet come.
Here are certain precious hearts,
that have lived in great pleasures and honors in the world,
who are now laying them down willingly at the feet of Jesus:
I am moved to lay their case before you, that you may write to them.
Justice Crook`'s wife is a precious woman, and many other of the handmaids of the Lord,
who is carrying his work over all, where he sends his children.--Editor]

--
