== Chapter 8

[.chapter-synopsis]
* 1655+++.+++ Epistle
* Court Sessions
* Prisoners tried before Judge Atkins
* Refuses to enter into bonds
* Remanded to prison
* Detained six months.

During William Dewsbury`'s confinement in Northampton jail,
he did not spend his time in idleness; for besides several pieces,
which he wrote for the promotion of the cause he had so zealously espoused,
he also addressed epistles in various directions for the edification of the church,
and to supply the place of his personal labors,
in extensively publishing the truth to such as were prepared to receive it.
The whole of one, and parts of another of these epistles,
it is now my intention to lay before the reader.
The following extract from that which comes first in order,
and is of a very general character, will, I trust,
tend to edification,--bearing in mind that the point of the
piece is leveled against a paid and lifeless ministry.

[.embedded-content-document.epistle]
--

All people who desire to know the living God,
let the time past suffice in which you have followed men who have deceived you,
and cease from them; and turn to the true Prophet,
whom Moses the servant of the Lord declared the Lord God would raise up, Duet. 18:15,
his elect and chosen servant, to raise up the tribe of Jacob,
and to restore the preserved of Israel;
whom he has also given for a light to the Gentiles,
and to be his salvation to the ends of the earth.
Whom Isaiah the prophet also declared the Lord would raise up,
to open the fountain of life and salvation to all that thirst, chap.
Iv. 1, 2, and is now witnessed by all that hearken to his counsel.
He calls, '`Ho!`' to every one that thirsts, '`come you to the waters,
and he that has no money, come you buy and eat, yes,
buy wine and milk without money and without price.
Why do you spend your money for that which is not bread,
and your labor for that which satisfies not?
Hearken diligently unto me, and eat that which is good,
and let your soul delight itself in fatness.
Incline your ear and come unto me; hear, and your souls shall live;
and I will make an everlasting covenant with you, even the sure mercies of David.`'

All people, look no longer forth;
the glad tidings of the Gospel of eternal salvation are heard within,
in this day of the Lord`'s mercies, wherein he is teaching his people himself,
as was declared by the prophet Isaiah, chap 54 vs. 13,
and is now witnessed by all the children of light,
whose minds are turned within to wait on the Lord for his teaching,
to establish them in the covenant of life and peace.
He is performing his promise,
which he declared by his servant the prophet Jeremiah to all that wait on him; namely,
'`This shall be the covenant that I will make with the house of Israel, in those days,
says the Lord; I will put my law into their hearts, and write it in their inward parts,
and will be to them a God, and they shall be to me a people;
and they shall no more teach every man his neighbor, and every man his brother, saying,
Know the Lord,
for they shall all know me from the least of them unto the greatest of them,
says the Lord; for I will be merciful to their unrighteousness,
and their sins and their iniquities I will remember no more.`'

Therefore,
every one that desires to know the only true God and Jesus Christ whom he has sent,
turn your minds within and examine your hearts,
search and try your ways with the light that Christ Jesus has enlightened you withal,
that shows you what is sin; that pride and covetousness, lying and swearing,
dissimulation and cheating, vain and idle communications, foolish jesting and unbelief,
are sins.
These things you know to be sins in your own consciences,
by the righteous law of God in the heart, that reproves you for them in secret.
There is your teacher, the Spirit of the Lord within you: which,
in this mighty day of his power, he is pouring upon all flesh,
according to his promise declared by the prophet Joel, chap.
ii. 28, 29. This is now witnessed by his sons and daughters, who walk in the light,
and are led and guided by his spirit within them,
which keeps the conscience void of offense towards God and towards man.

Hearken, every one, diligently to the counsel of the Lord,
the light that witnesses for God in the conscience.
Give up to be guided by it; then you will need no more to be taught of men,
neither shall your teacher be removed into a corner any more;
but your eye shall see your teacher, and '`your ear shall hear a voice behind you, saying.
This is the way, walk in it,
when you turn to the right hand or to the left,`' as was declaimed by the prophet,
Isaiah 30:20, which is now witnessed.--This is the living word of God within you,
who has raised desires in you towards Him.
Every one in whom such desires are raised,
wait in the light and power which has raised the desires;
and the Lord will then strengthen you,
and give you power to wait on him in the way of his judgments, until the carnal, earthly,
sensual mind, which has led you to delight in lusts and pleasures,
and in created enjoyments, below God, be slain by the word of God within,
which is a sharp and two-edged sword, to slay the first man, which is of the earth,
earthy; and then will you come to witness a being '`the slain of the Lord.`'
The sentence of death will be passed upon the first man, who has led you from God,
and on all the strength, wisdom, and righteousness you had in him;
and in the power of the spirit, you will be brought,
in the true sense of the poverty of your spirits,
to hunger and thirst after the righteousness of God in Christ Jesus,
to prize and love him, and to judge and deny self with his light,
and in it to wait for his power to guide you in every word and work.

--

[.offset]
+++[+++The following letter of advice to an individual, of some station.
Judge Fell, of Swarthmore, the editor ventures to interpose between these two addresses.
It is copied from the original.]

[.embedded-content-document.letter]
--

[.letter-heading]
To Judge Fell.

[.salutation]
Friend,

That which calls for purity in you is dear to me, and with it I suffer,
which often secretly groans in you for deliverance.
And while you lend your ear to the pure counsel of the holy Seed,
you are almost persuaded to lay your crown in the dust at the feet of Christ,
who is Zion`'s King and Judge; and to follow him daily in the cross,
that you might come to the crown which your eyes in measure see is given to
all who are faithful in walking in obedience to the will of God.
And blessed would you be, if you did stand faithful in the counsel of God;
he would wholly persuade you by his unlimited power,
and guide you with boldness to deny yourself, and the wills of all men in the world.
To the pure light of Christ in your conscience I speak, which will witness me.
It is because you turn your ear from it to the enemy of your peace,
who draws you into consultations with flesh and blood,
which set before you the way of truth to be hard and strait to walk in,
that you are not able to walk faithfully in what is manifest to you.
And hearkening to this lying spirit,
it draws your mind to seek refreshment in the visible
things over which the Lord has made you steward,
and so to forsake the living mercies which the Lord God of heaven and earth
has manifested to his faithful children in your family and elsewhere,
who stand in his counsel.
In tender love to your soul,
his arm is stretched forth to embrace you in his free covenant of life in Christ.
If you diligently incline your ear to his counsel,
and wait for his power to guide you in perfect obedience to the measure received;
then would your talent be daily increased,
and victory witnessed over the power of the prince of this world,
to tread on his head in the power of Christ:
then would the wisdom of the Father be given, in the condition he has placed you,
to be a faithful steward over the unrighteous mammon, to use it in its right place:
and he would make you partaker of the true substance, Christ the fulness of all things.

Dear friend, as you regard the glory of the living God and the welfare of your soul,
and as you will answer before him, slight not the day of your visitation;
for the Spirit of the Lord will not always strive with you.
Be tender over the least motion of the Spirit of Christ; in it wait with boldness,
for Christ to guide you in all your ways, in faithful obedience to the will of God.
His eternal power bring you under the government of Christ in you,
to the praise and glory of the Father of lights, who is God over all, blessed forever.
In tender love to your soul I write, who am often with you in spirit,
and am known by name,

[.signed-section-signature]
William Dewsbury.

[.signed-section-context-close]
From the common jail in Northampton, 7th of Third month, 1655

--

The other epistle bears evidence of having been addressed
exclusively to the members of the newly gathered Society.
And while its design is, on one hand,
to encourage and strengthen the simple-hearted and faithful,
though among these might be the weak of the flock; on the other,
the language of rebuke is freely employed towards such as, through hastiness, impatience,
or unwatchfulness, were in danger of injuring themselves,
and thereby of introducing the body into suffering,
and of bringing discredit on the cause itself.
It is from the pen, not of a learned man, but of an experienced Christian.

[.embedded-content-document.epistle]
--

[.salutation]
Dear Friends, servants and children of God,
whom he has called and chosen out of the world:

Be faithful, all of you, in his counsel.
Wait for his power, to guide you in all your thoughts, words, and works,
in his pure fear and in obedience to his will.
I charge you in his presence, be valiant for your freedom,
dwelling in the power of the living God:
that he may arm you against the fiery darts of the devil, to resist him in all his wiles,
who goes about like a roaring lion, to draw you away,
seeking to get your minds from that which is pure, into visible things,
there to captivate your affections,
to satisfy your wills in created and perishing objects,
or in the knowledge of the truth in fleshly wisdom.
These feed with the swine upon the husks, the form and image of what you have enjoyed,
or what you see, but do not enjoy in the possession,
and speak in words without knowledge.
With these, there sits a painted beast, the will at liberty, out of the cross.

You whose condition this is, are the foolish virgin, turned from the pure wisdom of God,
the light of Christ that convinced you of sin;
and you now appear in the outward formality,
in the sight of men with a lamp like the wise virgins;
but not dwelling in the power of God,
lacks the oil of joy and gladness in the power of his love.
This, the wise virgins have in their lamps,
which exercises their consciences and keeps all their
affections in order unto the Spirit of Truth,
which bridles their tongues not to utter vain words before the Lord;
but in true silence to wait upon him, until his spirit moves them to declare his mind,
from the living power which the soul possesses and enjoys in Christ,
the husband of the wise virgins.
He by his power trims the lamp of his bride, the Lamb`'s wife,
she always breathing and thirsting for him to manifest
his power to take away sin and renew the image of God;
and in Christ Jesus, the soul`'s life, to witness Him to reign in her forever.

And you are beloved who hunger and thirst after righteousness;
for you are the children of the kingdom of my Father.
With you my life is bound up; and to you this is the word of the Lord,--fear not,
lift up your heads, and wait in the light with boldness.
In it, look up to Christ, your King:
he will appear as the lightning from the east unto the west,
and you shall behold him subjecting your wild nature to himself.
He will heal your infirmities, satisfy your thirsty souls,
and give you the end of your hope, the salvation of your souls.
You shall sit down with him in the kingdom of the Father,
to rejoice in the power of eternal love and life,
which is in his presence forever and ever: this is the children`'s bread,
that comes down from heaven.

But you foolish virgins, who sit in the outward form and profession of the truth,
your lamps are empty of the power of God,
which should cast down your wills and keep them in the daily cross.
Thus you are possessed with a drowsy, earthly, careless spirit,
which is weary of waiting on the Lord in silence.
You have no oil in your lamps;
you are turned from the light that would lead you to the power of God,
which would preserve in true thirsting,
to wait for the refreshment that is in his presence.
Thus, while you are sitting in a silent meeting among the wise virgins,
who feed on the bread which comes down from heaven, the flesh and blood of Jesus,
you are imprisoned and starved for lack of food, which daily strengthens them,
the wise virgins, in the power of God, and gathers all their hearts together in one,
where the union is in the invisible Being, in silence, rejoicing together in the Lord.

To the consciences of you foolish virgins, I speak:
you are strangers to the life which the wise virgins enjoy.
Though you come among them, your life is in beautifying the outside of the lamp,
in words quickly spoken; but the fear of God is not before your eyes,
and your wills are out of the cross.
A false joy arises in you, speaking what you do not possess,
glorying in other men`'s lines, and contending for the truth,
with the mind that is out of the truth.
So you become as trees, with leaves and blossoms, which bear no fruit;
and here your folly is made manifest; while you speak to others,
yourselves are under reproof, in that you are strangers to the life of God.

I charge and command you to silence the flesh.
Speak not before the Lord, you foolish ones, while the worker of iniquity reigns in you,
whom the Lord will destroy, unless you repent.
Therefore, all Friends who make mention of the name of the living God,
examine your hearts, search them, and try your ways in the light that comes from Christ,
and with it, read your condition in the book of conscience.
There, you will see how you stand in the presence of the living God;
whether in the state of the foolish virgins, who are turned from the light of Christ,
which convinced them of sin, and are gone into the form of the truth,
but are enemies to the cross, making shipwreck of faith and a good conscience;
or whether you be in the state of the wise virgins, who love the light,
and dwell in the power which chastises that nature,
which would draw from the light and defile your garments.
In the daily cross your souls are kept pure and chaste,
to follow the Lamb wherever he goes;
and you enter with him into the rest prepared for the people of God,
where the foolish virgins shall not come, until they, from their foolish wisdom,
return into true obedience to the Father of light.

Dear children of the Lord, be valiant, bold,
and faithful in your measures that in the life and power of God,
you may stand in the day of great trial,
which the Lord will bring upon all that make mention of his name.
For power will be given to the beast to exalt his horn, even to the host of heaven,
for the clearing of the sanctuary of the Lord.
Then will the foolish virgins, that are enemies to the cross of Christ,
who have defiled the sanctuary of the living God,
come before him among his saints and children.
From among them shall they come, trembling before the power of the beast,
when he utters his voice and commands all to worship his image.
But then shall all you, children of God, whom he has called to be faithful to him,
rejoice in his eternal power; who will keep you at that day in rest and peace,
in the Ancient of Days;
who will sit to judge in righteousness all that withstand the rising of his glory.
And of his dominion there shall be no end.

Friends, meet together in the true silence of your spirits;
wait in the light for the unlimited Spirit of the Lord, to manifest his power in you,
and bruise the serpent`'s head in all his appearances,
and put an end to sin and bring in everlasting righteousness.
That, in Him you may grow, who is God over all, blessed forever.
Amen.
God Almighty keep you all faithful in his eternal power,
to bear his name in righteousness; that his name may be written in your foreheads,
and all that see you, may witness you to be the righteous seed whom the Lord has blessed.
His power and presence keep you in the unity of the spirit and bond of peace,
where I am with you in the unchangeable love and life.

[.signed-section-signature]
W+++.+++ D.

[.signed-section-context-close]
1655

[.postscript]
I desire you to let this be read in your meetings, with a good understanding,
in the fear of the Lord;
for this is the day in which '`I will make a separation between the wise and the foolish,
between those that fear the Lord,
and those that fear him not,`' says the Lord God Almighty.

--

At the time of the court sessions, which were held the 21st of the fifth month,
William Dewsbury was called to the bar, his name being associated with six others,
who were imprisoned under similar charges.
Seeing the prisoners standing before him with their hats on, the judge, Edward Atkins,
after a short pause, asked the jailer, if those were prisoners.
On being answered in the affirmative, the judge asked him,
if it were his practice to bring prisoners before the court in that manner,
and told him he deserved to be fined ten pounds,
for bringing them before the court covered.
The jailer replied, "`If you command me, I shall take off their hats.`"
This being done, and having ascertained which of the prisoners was Dewsbury, for,
it appeals, both now and on the previous trial,
that his preaching had produced a great sensation in
those parts of the country where he had traveled,
the following examination took place.

[.discourse-part]
__Judge.__--What are you here for?

[.discourse-part]
__Prisoner.__--The court order will express what I was committed for,
but I am denied a copy of it by the keeper of the jail.

[.discourse-part]
__Judge.__--What is your name?

[.discourse-part]
__Prisoner.__--Unknown to the world.

[.discourse-part]
__Judge.__--Let us hear what that name is, that the world knows not.

[.discourse-part]
__Prisoner.__--It is known in the light, and not any can know it, but he that has it:
but the name the world knows me by, is William Dewsbury.

[.discourse-part]
__Judge.__--What countryman are you?

[.discourse-part]
__Prisoner.__--Of the land of Canaan.

[.discourse-part]
__Judge.__--That is afar off.

[.discourse-part]
__Prisoner.__--No, it is near.
For all that dwell in God, are in the holy city, the new Jerusalem,
which comes down from heaven.
There the soul is in rest, and enjoys the love of God in Christ Jesus,
in whom the union is with the Father of light.

[.discourse-part]
__Judge.__--That is true.
But are you ashamed of your country?
Is it any disparagement for you to be born in England?

[.discourse-part]
__Prisoner.__--No. I am free to declare that my natural birth was in Yorkshire,
nine miles from York, towards Hull.

[.discourse-part]
__Judge.__--You pretend to be extraordinary men,
and to have an extraordinary knowledge of God.

[.discourse-part]
__Prisoner.__--We witness the work of regeneration to be an extraordinary work,
wrought in us by the Spirit of God.

[.discourse-part]
__Judge.__--But the apostles wrought with their hands in their callings.

[.discourse-part]
__Prisoner.__--They had callings in the world, some were fishermen, Paul a tent-maker;
but when they were called to the ministry of Christ,
they left their callings to follow Christ,
where he led them by his spirit to preach the word.
I had a calling in the world, as they had, and in it did abide,
until the Father revealed his Son in me, and called me from my calling in the world,
to preach the eternal word he had made known to me, in the great work of regeneration.

[.discourse-part]
__Judge.__--Why did you not abide in your own country, and teach people in those parts?

[.discourse-part]
__Prisoner.__--I did stay there,
until I was called from there to go where I was led by the Spirit of the Lord.
And as many as are led by the Spirit of God, they are the sons and daughters of God,
and they that have not the Spirit of Christ are none of his.

[.discourse-part]
__Judge.__--You say well;
for we must in charity conclude that every one
in this place has the Spirit of God in them;
but how do you know that you are guided by the Spirit of God?

[.discourse-part]
__Prisoner.__--They that have the Spirit of God are known by their fruits.
And he that believes in Jesus Christ and is guided by his spirit,
has the witness in himself.

[.discourse-part]
__Judge.__--That is true; yet, notwithstanding, I see by your carriage,
that what my brother Hale did at the last court sessions,
in requiring bonds for your good behavior, he might justly do;
for you are against magistrates and ministers.

[.discourse-part]
__Prisoner.__--Make manifest wherein we are against them.

[.discourse-part]
__Judge.__--(To Robert Grey, Clerk of the peace,) What have you against these men?

[.discourse-part]
__Grey.__--Here is an information, given in upon oath by Mr. Robert Beeton,
that William Dewsbury, on the 29th of December 1654,
did go into the church at Wellingborough,
and stood with his hat on in the time of sermon and prayer.
And after the minister had done, he spoke these words, "`The priests preach for hire,
and the people love to have it so: but what will you do in the end thereof?`"
with other railing words, which made a disturbance among the people.

[.small-break]
'''

The judge was then proceeding to examine some of the other prisoners,
having first threatened what he would do before he left
the town against those who disturbed the ministers,
when William Dewsbury said, "`It is the liberty of the law of this nation,
that any one who is brought a prisoner, before those who sit to judge his cause,
may speak for himself,
to witness the truth against the false information given against him;
and that liberty I take,
to manifest the cause of my going into the steeple-house at Wellingborough.
He then related how the priest Andrews had attacked him in the public street,
which he told the judge had given occasion to his visit to the public meeting-place,
asserting his conduct to have been no breach of any law of this nation.
The conversation was then resumed as follows.

[.discourse-part]
__Judge.__--But in that you are found wandering in the country, you break the law;
for there is an old law,
that if any did go from their dwellings to travel in
the country without a certificate from some justice,
they were to be taken as wandering persons.

[.discourse-part]
__Prisoner.__--If there be any such law, read it to us.
And if there be such a law, you know in your conscience it is contrary to the Scriptures.
For the apostles and ministers of Christ went to and fro in the country,
preaching the word of eternal life,
and there were added to the church daily such as should be saved:
and the number of saints and brethren was daily increased.
And the law which is in force in this nation
does allow all who profess faith in Jesus Christ,
to have free liberty to walk in the faith which is according to the Scripture.

[.discourse-part]
__Judge.__--You have an eloquent tongue, and you are proud of it,

[.discourse-part]
__Prisoner.__--Pride I deny; but the truth I witness, which will judge pride,
and torment all who live in it, until it be destroyed.

[.small-break]
'''

To this the judge made no answer, but proceeded to examine the other prisoners; who,
without any accuser appearing against them, and without proof of the breach of any law,
were required to enter into bonds for their good behavior.
As this not only involved an acknowledgment of their guilt,
but was intended as a check to those proceedings,
in which they believed it to be their religious
duty and calling to be diligently engaged,
they refused to do it.
They were accordingly remanded to prison, and detained until the eleventh month, 1655,
a period of nearly six months, subjected also to the aggravated trial,
of their friends being denied the liberty of visiting them.
As they were leaving the court, William Dewsbury, turning to the judge, spoke as follows:
"`With what measure you measure to us, it will be measured to you again.
The Lord God of heaven and earth will judge between you and us,
and will give unto you and every one of you, according to the works you have done,
and in that day you shall know what is now declared to be the truth:
the Lord has spoken it, in whom we trust, and he will deliver us.`"
The names of the other prisoners were, Joseph Storr, Flenry Williamson, John Whitehead,
Marmaduke Storr, Thomas Cockett, and Francis Ellington.
