== Chapter 9

[.chapter-synopsis]
* Epistles
* laborers increase
* State of the prisons
* Sufferings of Friends
* The Cause: Faithfulness to their calling
* Evidences that it was not of man
* Sewel`'s testimony.

The following short epistles are introduced to the reader,
in expectation that they will prove both interesting and profitable.
They appear to have been written during the period of suffering,
some particulars of which have just been related.
They contain, as well as the preceding ones,
strong indications of the writer`'s character,
and evince both his tenderness and watchful care over the flock of Christ,
and the sharpness which he was capable of exercising,
when circumstances appeared to require it.
"`To the tender,`" says one who knew him well, "`he was exceedingly tender;
but to the stubborn and lofty he was sharp and plain, admonishing them,
and declaring the righteous judgment of God against that state.`"
In each of the addresses there are expressions, from which we may gather,
that some for whose eye they were intended,
had a zeal not altogether according to knowledge,
which was displayed in an aptitude to give
utterance to feelings under apprehension of duty,
when silence would have been more consistent with a sound judgment,
and more profitable to the body.

[.embedded-content-document.epistle]
--

[.salutation]
All saints and children of the most high God:

Abide in the calling whereunto you are called:
which call is the measure of light given unto you,
which witnesses against all the deceitful twisting of the serpent within you,
and seals up to your spirits the love of God,
in the free covenant of life in Jesus Christ.
As you have received of the Lord, walk faithfully with him;
so will you be preserved pure, and blameless before him, and be fortified by his power,
against all the deceit, subtlety,
and windings of the serpent within you and without you.`"

I charge you in the presence of the Lord,
to abide with God in what he has communicated to you,
and run not out from the witness of the eternal spirit,
that has in measure sealed you up in the power of his love.
You that do run out to speak further than you witness,
are as a drunkard that lavishes out himself without the fear of the Lord;
and so spend and waste; and the plagues of the Lord are your portion,
for no drunkard or lustful person shall inherit the kingdom of God.`"

All you children of the Lord, abide in the eternal spirit, which will pass judgment,
and bruise the head of the serpent in you.
So will you be armed against all the appearances of the serpent without,
and keep him out of the Scriptures.
And the least of you in the truth of God, will overturn priests,
and the men of the world, who dwell in the serpentine wisdom,
and make a trade of the Scriptures, speaking and disputing of the saints`' conditions,
as the devil did about the body of Moses,
but cannot witness the Scriptures sealed to their souls by the eternal spirit.
You that dwell in the truth will see such to be houses built upon the sand,
tall cedars aspiring into the air,
sturdy oaks that stand in the pride of their own conceits, but have no root.
Therefore let them not speak of the Scriptures merely, but bring them to the witness,
which can witness to them of the Scriptures: so will the Spirit of the living God,
speaking in you, raze the sandy foundation.
Thus will the sturdy oaks and the tall cedars fall;
and the serpent in all his windings and twistings, be bruised,
and all deceits overturned, and your souls preserved pure and clean;
and the name of the Lord honored,
who does accompany the witness of the spirit with his own power.
And abiding in his power, you shall reign as kings upon the earth.

The Lord God Almighty be with you all, you sons and daughters of the Most High,
and carry you on in his power, faithful unto the end,
that you may receive the crown of eternal glory,
which is laid up for you in the Lord Jesus Christ, and there you will fare well,
and I shall remain with you forever in the Lord.`"

[.signed-section-signature]
W+++.+++ D.

--

[.embedded-content-document.epistle]
--

[.salutation]
Dear Friends,

Meet often together in the name and fear of the living God.
And take heed of words; see that the witness speaks,
which will cut down your own wills and minister to the witness in others,
to the slaying of their wills.
And take heed of watching over one another with an evil eye,
to spy out one another`'s weaknesses and to declare it
to others and discover their nakedness.
You that are here, are in the same nature as cursed Ham;
and the wrath of God will be revealed upon you.
But watch over one another with a pure, single eye.
And if you see the pure mind in any one in bondage,
whisper you not behind their back to others.
But let the witness in you which sees the deceit,
and suffers with the pure mind that is pressed down by it,
declare the mind of the living God against the deceit: and it will cut it down,
and the pure, holy Seed will be set at liberty;
and your conscience will be kept clean unto the Lord, in discharging your duty.
Thus will your captive brother or sister be
restored again out of the hand of the destroyer,
and then you will have unity in that which is pure.

The God of power keep you all, his dear children, in his pure wisdom,
to walk faithfully with him and one with another.
And the blessing of the Lord be with you all forever.
Amen!

[.signed-section-signature]
William Dewsbury

--

[.embedded-content-document.epistle]
--

[.salutation]
My dear Friends,

This is the word of the Lord to you all,
whom my Father has chosen out of the world in his love, to make known his power in you;
look not back, but judge that mind with his pure word,
wherewith he enlightened your consciences,
for the exercising them towards him and towards men.

And stand in His pure counsel and look up to Him;
and He will accompany you with His power, and will make the way plain before you,
in bringing down that which is untoward within you and disobedient to His will.
So his ways will not be burdensome, nor his commandments grievous to you.
Cast off whatever he has let you see is offensive to his will,
that so your souls may rest in the bosom of his love,
that he may carry you on in the arms of his power, faithful unto the end,
and crown you with glory, which he has laid up for you in the Lord Jesus.

Slight not his counsel, but be valiant and bold for the glory of his name;
and be not hasty to utter words before him:
but let your words be few and savory at all times,
ministering grace to all that hear you; that his name may be honored in you all,
in all your words and actions.
Then he will accompany you with his presence,
and will make you a terror to all evil doers,
'`one to chase a thousand and two to put ten thousand to flight.`'
So will he get himself a glorious name, in the manifestation of his power in you,
who stand faithful in his counsel and walk in his fear;
and your souls shall be refreshed in the fountain of his love in the Lord Jesus.

Meet often together to wait upon him, in the fear of his name,
and watch over one another in love; and he will be with you,
to order you in his pure wisdom, to the praise and glory of his great name.

Written from the Spirit of the Lord, to be sent abroad among Friends,
to be read at their meetings

[.signed-section-signature]
William Dewsbury

--

It was no slight proof of the reality of that power,
which attended these witnesses for a true, entire, and glorious reform,
that their attacks upon wrong things relating to religion,
should have been so signally crowned with the divine blessing;
that their exertions in faithfully laying open
the prejudices and corruptions of their day,
should have been attended with such remarkable effects.
At quite an early period,
we find that a large number of laborers were called into the field,
eminently gifted for their work,
and furnished with an unconquerable willingness
to suffer shame for the cause they had espoused,
and to expose themselves to the fury of persecution.

In the year 1654, as Sewel informs us,
there were above sixty ministers of the word raised up among Friends,
who traveled in the work and service of the Gospel,
laboring diligently "`to turn people from darkness to
light and from the power of Satan unto God.`"
But their sufferings kept full pace with the increase of their numbers;
of which all of these were more or less partakers.
In the preceding year, George Fox was cast into Carlisle dungeon;
and such was the malice of his persecutors, that they contemplated his destruction.
But their design coming to the knowledge of the parliament, it was arrested.
The state of the prisons too,
in which so many Friends passed a large portion of their time,
as Clarkson informs us in his "`Portraiture of
Quakerism,`" was not easily to be conceived;
some for filth and pestilential noisomeness,
and others for exposure to the inclemency of the elements.
Indeed, the condition of these prisons previous to the latter years of the last century,
was a disgrace to any civilized community; not only on account of their filthy,
unwholesome, and neglected condition, but equally so,
because of the indiscriminate association to
which all classes of prisoners were subjected.
It was common for Friends, mostly men of the better order,
often of reputable or wealthy families, to be cast into those dismal dungeons,
one of which is now preserved at Warwick jail, and is shown as a relic of former times.
I remember visiting it myself in 1810;
and the impression I then received will never be effaced.
Howard, in his description of this jail, says,
"`The night-room of the felons is an octagonal dungeon,
about twenty-one feet in diameter, down thirty-one steps, damp and offensive;
the jailer on going down took a preservative.`"
Basil Montagu, whose name is so honorably associated with the subject of prisons,
prison-discipline, and the punishment of death for crime,
in his account of a visit he paid to the same prison in 1815, says,
"`This offensive vault, which may now be seen in the prison,
is eighteen feet ten inches under ground.
In the middle is a cess-pool;
on the side is a stream for the prisoners to slake their thirst.
There is a large heavy chain now in the dungeon,
that passed through a link in the chains of each of the felons,
which was then carried up the steps and secured to the outer door of the vault.
The only light and air admitted, is through an iron grate on the top, and nearly,
even with the surface of the ground.`"

These are the dismal cells in which Friends were often made to suffer,
in company with the most abandoned characters; and in which,
as these sufferings abounded, their consolation did often much more abound;
under a sense of which, they sang praises to God in their bonds,
and with William Dewsbury esteemed the locks and bolts as jewels.

It was in Warwick jail, that William Dewsbury was imprisoned nineteen years of his life,
four years of which he was a close prisoner; whether in the pit or not is not stated.
Nor should we have known that this was the fact respecting his
confinement in Northampton jail from any statement of his own;
for he suffered too cheerfully to lay much stress on the vile durance he underwent.
But it was, as stated by others, in a dungeon twelve steps under ground,
among the worst of felons, that he was there imprisoned.
In such a dungeon as we have been describing,
George Fox was confined for six months at Derby, "`in a lousy, stinking place,
without any bed, among thirty felons.`"
Let any person read the account he gives of the dungeon wherein he lay at Launceston,
and he will hardly believe that such dreadful cruelties and
oppressions could even then have been practiced in England,
the boasted land of liberty and Christianity.
"`This place was so noisome, that according to common observation,
few ever came out of it in health.
It was over the shoes in mire of the most filthy description,
and had not been cleaned for years.
And though the liberty was entreated for,
it was long before Friends were permitted to cleanse it themselves.
They were allowed neither beds nor straw to lie on.
And this was not sufficient cruelty upon the Friends;
but the prisoners lodging over head, encouraged by the jailer,
poured filth through the floor on the heads of those beneath.
This dungeon was called Doomsdale, The head jailer had been a thief,
and was burnt both in the hand and shoulder, and his wife in the hand;
and the same distinctions had also been conferred on the under-jailer and his wife.`"

Numerous other instances might be adduced of the woful state
of the prisons at the period we are now considering,
and of the lamentable suffering, often to death, which Friends endured in them.
It is, however, to the credit of the present more enlightened time,
in which the successors of those sufferers may
fairly claim their share of congratulation,
that the state of the prisons is now widely different.

Some remarks have already been made, relative to the unsettled state of the government,
at the period in which Friends were first gathered into a distinct church;
and it has been hinted, that the political as well as the religious ferment, into which,
from various causes, the whole community was thrown,
was one source of the sufferings which this people had to endure.
In addition to this, it cannot be concealed,
whatever difference of sentiment may exist as to the propriety of the circumstance,
that it was the zealous protest of Friends against the
prevailing customs and character of the day,
to which they were impelled from a sense of religious duty,
that mainly laid them open to the persecutions which followed them in their course.
But on the other hand, it may be said with equal truth,
that the apostles and early Christians did the same thing,
and had to endure a similar ordeal from rulers and others, who,
in the darkness of their minds,
were not able to admit the validity of that divine authority,
under which true believers have always acknowledged them to have moved.
They were said to turn the world upside down;
and a charge of this nature necessarily attaches in a greater
or less degree to reformers of every age and class.
Believing, and that not without sufficient reason, in the divine mission of George Fox,
William Dewsbury, and others associated with them,
such will have no hesitation in asserting,
that when those laborers were called into the Lord`'s vineyard,
they were furnished according to the service laid upon them.

The particular portion of labor which fell to their lot,
was that of carrying on the great work of the reformation,
in some points of religious faith,
to a much further extent than was laid upon the reformers of the fifteenth century.
And, although the early Friends were charged with being deniers of the Scriptures,
because they preached boldly a revelation of divine knowledge to the mind of man,
they did this as moved by the holy Spirit, upon Scripture authority itself,
and upon the ground of their own blessed experience.
In the spiritual view which they were led to take of the Christian dispensation,
they were indeed true believers in and supporters of the Scriptures;
because they bore a fuller testimony to the scope and intent of those sacred writings.
They not only acknowledged them, with as much sincerity as others,
to be preeminently depositories of revealed truth,
but they never shrunk from bringing those matters among
the various sects which called for reformation,
as well as their own doctrines and practices, to the test of Scripture,
after the example of all true reformers.
But in so doing,
they were never suspected of an intention of overlooking the important fact,
that the Sacred Volume itself needs a holy interpreter.
Indeed, it was no other than this interpreter himself, as they believed,
opening the Scriptures to the subjected understandings of the early Friends,
that pointed out to them those things among the churches, which in that day required,
and which still demand, the hand of reform,
and against which they were called to bear so public and unflinching a testimony.

Nor were they left destitute of sufficient evidences of various kinds, spiritual,
supernatural, and providential, intended no doubt for the confirmation of their belief,
that the Lord himself was with them in their labors.
In what manner the great work of individual repentance
and regeneration was carried forward in their own minds,
we have an instance before us in the case of William Dewsbury,
who was only one among a large number,
who were favored to arrive at the same enlarged experience.
But "`the evil heart of unbelief,`" under very specious forms of reasoning,
is at all times endeavoring to shake the faith of the weak and the unwary;
often by insinuating,
that the superstructure of the heavenly building is not
to be of the same materials as the foundation.
But this we know and are assured, is neither scriptural,
nor was it the belief of the early Friends.
The same divine work, according to what they learned and what they taught,
requires at all times the same divine power to carry it on.

Time has made no such change of circumstances,
as to invalidate the truth of this position.
The natural man is the same in all ages;
and he is not more able at one day than at another,
to comprehend savingly the things of the Spirit of God,
for they will ever continue to be "`foolishness unto him,
and he cannot know them because they are spiritually discerned.`"
In regard to the evidences above alluded to,
and which are abundantly scattered through the writings of the early Friends,
I introduce the following statement of facts from the pen of George Fox,
to show the encouragement he derived from such
experience as tell within the sphere of his own labors.
He says,
"`Many great and wonderful things were wrought by the heavenly power in those days.
For the Lord made bare his omnipotent arm,
and manifested his power to the astonishment of many; by the healing virtue whereof,
many have been delivered from great infirmities,
and the devils were made subject through his name;
of which particular instances might be given,
beyond what this unbelieving age is able to receive or hear.
But, blessed forever be the name of the Lord, and everlastingly honored,
and over all exalted and magnified be the arm of his glorious power,
by which he has wrought gloriously;
and let the honor and praise of all his works be ascribed to him alone.`"
The preceding quotation is no enigma;
it bears a faithful testimony to the facts of that day, although neither he,
his companions, nor their successors in belief,
have ever laid great stress on such occurrences however true;
and have avoided insisting on them as proofs of their ministry.
And although Friends in the early times did, with George Fox and with William Dewsbury,
as the reader will find when he arrives at the closing scene,
acknowledge such instances of the marvelous extension of divine
regard to be consistent with Scripture and sound reason,
they concluded it to be proper in these latter ages of the church,
to receive them simply as collateral assurances,
that the Lord`'s power is the same in one day as another,
rather than as essential evidences or as requisite fruits of true faith.

Many have found it difficult to reconcile the
bold and inflexible conduct of the early Friends,
in bearing their open and public testimony against the
errors of the prevailing sects and parties in religion,
as though none were right but themselves.
That this was actually the case with William Dewsbury,
we shall see when the transactions of his life are further laid open before us;
and it was the same with George Fox, and with the Friends in general.
There is little doubt,
but that such as were well satisfied with the established religion,
or such as had dissented from it into various sects and shades of difference,
must have thought it highly obtrusive and presumptuous in any,
though not altogether without precedent,
thus publicly to call in question their principles or practices,
especially if those persons were in the majority of instances but simple, illiterate men.
Neither do I wish to be understood as justifying every act
which was the product of their generally well-directed zeal.
But I am ready to affirm it as my belief,
that the manner of their appearance was well suited to their day;
that the amount of the benefit to the nation and to the church,
resulting from their labors and sufferings, has never yet been fully calculated,
and that they were the means of establishing
certain precious principles in the minds of men,
for which, the more they become developed in practice,
the greater will be the gratitude of mankind.
The question therefore, in regard to their early practices,
is not as to what might be agreeable or seem decorous or otherwise;
but whether the Lord of the vineyard, did or did not,
see it fit to send laborers into his vineyard after such a peculiar manner;
and whether he did, or did not, require this especial service at their hands,
however repulsive their appearance might be to the
carnal and hypocritical professors of those times.
Many of these professors were very soon manifested not to be what they would pass for,
some by the eager persecution they raised against the truth,
others by their cowardly compliances to shun persecution.
On the other hand, we know beyond contradiction, that under this ministry,
unmodish and unacceptable as it was to the worldly-minded,
thousands were turned from the evil of their ways;
for we are informed by the testimony of authenticated records,
which the whole history of the Society proves,
that such a wonderful power attended the early preaching of this people,
as for hundreds to be overcome by it at one time,
and to be convinced of the truths which they heard.
So that unpleasing as such instances of interference might be to the natural, impatient,
unregenerate mind, the true Christian, the spiritual man,
can have no doubt that the ministry of this
people was a fresh display of that dispensation,
which is love from God to his creatures.

We have seen under what kind of impressions William Dewsbury moved, in various instances,
from very early life, and how by revelation the mystery of unrighteousness,
and the mystery of the Gospel, which is according to godliness, was made known to him;
and by what means he became an able minister of the New Testament, not of the letter,
but of the spirit.
When he received, what he most surely believed to be,
and what the event proved without contradiction,
to be a divine gift and call to the work of the ministry, the word to him was,
"`What I have made known to you in secret, that declare you openly.`"
If under such clear impressions of duty,
and it was equally the case with others his brethren, these men went forth,
as with their lives in their hands, to publish the Gospel of peace,
to show the people their errors,
and to make known to them what they themselves had both seen, and tasted,
and handled of the word of life,
it requires considerable caution how we permit our preconceived notions,
or our unsubjected wills and reasonings,
to rise up in judgment against such a dispensation.
"`

"`Thus,`" as Sewel informs us, "`it may be seen, by what means the Quakers so called,
grew so numerous in those early times.
As on one hand there were raised zealous preachers,
so on the other there were abundance of people in England, who having searched all sects,
could nowhere find satisfaction for their hungry souls.
And these, now understanding, that God by his light was so near in their hearts,
began to take heed thereunto,
and soon found that this gave them far more victory over the corruption of their minds,
under which they had long groaned, than all the self-willed worship which,
with some zeal, they had performed for many years.
Besides those who were thus prepared to receive
a further manifestation of the way of life,
there were also many, who being pricked to the heart,
and by the Christian patience of the despised Quakers brought over,
became as zealous in doing good as formerly they had been in working evil.

"`Perhaps some will think it was very indecent, that they, the Friends,
went so frequently to the steeple-houses, and there spoke to the priests:
but whatsoever any may judge concerning this,
it is certain that those teachers generally did not bring forth the fruits of godliness.
This was well known to those who themselves had been priests,
and had freely resigned their ministry to follow Christ in the way of his cross.
These were none of the least zealous against that society,
among whom they had formerly ministered with upright zeal.
Yet they were not for using sharp language against those teachers,
who according to their knowledge feared God;
but they leveled their aim chiefly against those who were rich in words only,
without bringing forth Christian fruits and works of righteousness.
Hence it was that Thomas Curtis, who was formerly a captain in the parliament army,
but afterwards entered into the Society of the people called Quakers, wrote +++[+++as follows,]
in a letter to Samuel Wells, priest of Banbury, and a persecutor:--'`To your shame,
remember, I know you to be scandalous.
How often have you sat evening after evening at cards, sometimes whole nights,
playing and compelling me to play with you for money;
yet then you were called of the world a minister; and now are you turned persecutor,
etc.`'
None, therefore,
need think it strange that those called Quakers looked upon such teachers as hirelings.
And that there were not a few of that sort,
appeared plainly when King Charles II. was restored.
For, in many instances, those who had formerly cried out against Episcopacy,
and its liturgy, as false and idolatrous, then became turncoats, and put on the surplice,
to keep in possession of their livings and benefices.
But by so doing, these hypocrites lost not a few of their auditors;
for this opened the eyes of many,
who began to inquire into the doctrine of the despised Quakers,
and saw that they had a more sure foundation,
and that it was this that made them stand unshaken against the fury of persecution.`"
