== Chapter 11

[.chapter-synopsis]
* 1658+++.+++ William Dewsbury in Scotland
* Epistle
* Trials from false brethren
* John Perrott`'s case
* William Dewsbury`'s labors with these
* Restoration of many
* Self-renunciation required of Friends
* William Dewsbury, at a meeting in Warwickshire
* Disturbance and violent treatment of Friends
* He is imprisoned in York Castle, with five hundred more, where five die
* He is released
* Writes Epistles of encouragement to Friends.

By the date of William Dewsbury`'s next epistle, we trace him to Scotland.

From the few scattered notices which are preserved of his labors in that nation,
it appears that they were eminently blessed to
the religious establishment of many persons,
in whose hearts the work of preparation had been going on for several years.
When Friends in the capacity of ministers had their
steps first directed among the people of that nation,
the word preached was truly glad tidings to their souls.
We are informed by John Barclay,
in his "`Memoirs of Friends in Scotland,`" that "`in the south of Scotland,
as in the north, there were individuals,
whose minds had been for some years weary and heavy laden,
under a sense of their manifold short-comings, yet who believed there was to be known,
a more purely spiritual way of worship, and of life and conduct, than that which they,
or any with whose profession they were acquainted, had arrived at.
Deeply burdened with the formality, superstition, and will-worship prevalent around them,
and under which the various public preachers too generally detained their hearers,
these serious inquirers had separated from the several congregations of the people;
and at length some of them began to meet together by themselves,
waiting upon God in a holy silence and awful humility of soul,
for ability to draw nigh unto him in true spiritual worship.
On these occasions, they were at times made sensible of the quickening virtue, power,
and life of the holy Spirit,
enabling some of them to speak forth the praises of the Almighty,
and from an inward experience of his goodness,
to extend instrumentally a hand of help to others.`"

"`To a people thus situated,
it appeared to be consistent with the mind of the great
and good Shepherd to extend his merciful regard;
and between the years 1653 and 1658, when Willam Dewsbury paid them his first visit,
the feet of many Gospel messengers were turned in that direction.
We are further informed in the Memoirs, that the Gospel messages of these,
and other zealous witnesses, +++[+++who had already occupied the ground]
reached the consciences of many who heard them; yet,
with regard to Aberdeen and the district thereabouts,
no open espousal of the tenets of the people called Quakers took place,
until towards the end of the year 1662;
when William Dewsbury was drawn in love to these prepared and panting souls,
to proclaim among them '`the acceptable year of the Lord,
'` even deliverance from the bondage of corruption,
by the law of the spirit of life in Christ Jesus.
Thus was the remarkable work of convincement,
which had been secretly going on in some of their hearts for several years,
through many deep conflicts of spirit, helped forward to such a point,
that they were made willing, even in all things, to take up the daily cross,
though in various respects as bitter as death,
and to follow the guidance of Christ by his spirit within them,
whithersoever he should be pleased to lead.`"

Thus much is known of William Dewsbury`'s labors as regards Aberdeen.
But the epistle above referred to is dated Leith, at an earlier period, namely,
the 24th of the seventh month, 1658, and refers to his first visit to Scotland,
respecting which I have not been able to discover particulars
from any other source than the epistle itself.
On this account, and because of its intrinsic worth,
I have concluded to lay it before the reader.
It is as follows.

[.embedded-content-document.epistle]
--

[.salutation]
Dear Friends,

In the name of the Lord Jesus Christ walk,
so as to reign over all that is contrary to the light; that,
in the light and glory of God, you may all shine forth,
living witnesses of the name of the everlasting, holy, pure God,
who has looked upon you in his tender love, to gather you to stand against all deceit,
in his everlasting power.
Blessed are you who are faithful in obeying the light of Christ,
who follow him in the cross and the straight way of self-denial.
You are my brethren and sisters in the Lord Jesus, our Captain.
He will crown you with his mighty power to stand over all +++[+++temptations]
to follow him in faith and patience, until every tongue that lifts up itself against you,
shall fall in judgment, together with all that stumble at Christ Jesus,
our light and life, who will gather a large people to himself.
In that country, many shall come in, who are yet wandering upon the mountains,
where they find no rest.
Blessed are all you that abide and walk faithfully with the Lord,
whom he has called and chosen to be the first fruits.
Whatever arises contrary to the light, within or without, watching in the light,
you will discern; stay your hearts upon the Lord, holding fast your confidence in him.
He will deliver you out of all that is contrary to the light,
and cause you to rejoice in the daily cross,
crucifying you to the world and the world to you.
Over the world He will cause you to rejoice,
and you shall stand over it in the power of God, with all its pomps and glory,
and the evil therein, to his praise and glory.
Even so be it with you all, in the mighty power of God,
in which my soul salutes you that faithfully and humbly walk before the Lord,
in obedience to his counsel.

Dear lambs, called to lie down in the safe fold of rest, in Christ our life,
in tender love I beseech you,
that you be faithful in meeting together in the name of the Lord Jesus Christ;
and diligently watch to know your own measure of grace in Christ,
to feel him in you to judge your thoughts, and every vain imagination,
that you may reign over them, and delight in the refreshing of his presence.
And all take heed of many words; at all times let them be few,
and from the savory spirit of life, in Christ.
In him, the blessing of the Lord rest on you all forevermore;
there to farewell with me in the everlasting love of the Father in Christ, Amen.

[.signed-section-signature]
William Dewsbury.

[.postscript]
====

Let copies of this be carefully written and sent to the churches,
to be read among them, when they are met together in the fear of God.

====

--

[.offset]
+++[+++Since this volume has been in the Editor`'s hands for publication,
he has met with a letter written by William Dewsbury, from the same place, Leith,
only the day before the above communication was penned: it is addressed to Margaret Fell,
and is as follows.]

[.embedded-content-document.letter]
--

[.letter-heading]
To Margaret Fell

In the everlasting power and life in Christ, the light and righteousness,
over all God blessed forever!--in his power, which keeps the faithful, dear sister,
I have been and am refreshed in my travails, which in measure you know what they are,
for the Seed`'s sake.
Dwell in the power, in which the Lord has chosen you to bear his name in righteousness;
even so the Almighty God keep you,
your tender children and family a refreshing to the Israel of God.
My dear sister, your care I have often felt, bearing the burden for the Seed`'s sake,
and much for the poor oppressed seed in Scotland;
the care of which has been much upon me.
My tender Father, after six years`' travel in England, has freed me to come into Scotland,
which was on the 13th day of the sixth month.
At Berwick I left my horse, and one Samuel Thornton was moved to come with me.
I bought shoes at Berwick, and came on foot into Scotland with great joy.
On the first day`'s journey, I met with hundreds of people, it being the time of harvest,
who in the fields and highways heard the truth in much tenderness.
The 15th, being the first-day of the week,
I was at the meeting at Edinburgh--I stayed three meetings;
God much appeared to his own glory.
The 19th day, I journeyed towards the west; the 22nd day,
being the first-day of the week, I was with Friends at Badcow,
through the country to the garrison of Air;
the 29th I came to the meeting of Friends at Heads;
Friends in measure are come into the simplicity of the Truth.
Then I journeyed to Hamilton, Glasgow, Stirling, and to the castle of Bandallo.
In the fields and highways, many hundreds heard the word of eternal life,
many being very tender where I have been led.
The 12th of the seventh month, being first-day, I returned to Edinburgh,
where I have had many meetings and pretty many came: here has been as yet no opposition,
the Lord has much appeared, many clearly convinced of the Truth;
Carttan is resolved to follow the Lord in obedience; he is of the baptized people.

Dear sister, in a short time, the Lord led me on foot,
some hundreds of miles with much joy, for the Seed`'s sake;
my bread I am casting on the waters, assured I am, I shall find it in the time appointed.

The everlasting God keep all in his power and wisdom, every one in their places,
to his praise and glory.
Amen!

[.signed-section-closing]
Farewell! your dear brother,

[.signed-section-signature]
W+++.+++ D.

--

From the date of another of his epistles,
we learn that William Dewsbury was in London in the eleventh month, 1659.
This year was one of cruel persecution to the Society of Friends, then,
rising into considerable importance,
through the diligence of the numerous laborers engaged
in testifying the Gospel of the grace of God.
The boldness with which they asserted their peculiar belief,
together with the power which attended their preaching,
tended greatly to add to their numbers, notwithstanding their suffering lot,
and the persecutions which awaited them.
It is however evident, from some of the epistles of this Friend,
both of early and later date, that all who were convinced of the truth,
did not abide faithful to their testimony.

Notwithstanding the address,
which William Dewsbury with so much wisdom made to the Society as early as 1653,
on the subject of discipline,
no regular system appears to have been organized previous to the year 1666;
when it was accomplished under the zealous, enlightened,
and judicious exertions of George Fox,
who believed himself to have received an especial call to proceed with that work.
In the meantime, as already related,
some attempts were made to meet the exigencies that arose;
and it does appear from an answer which William Dewsbury returns to an adversary,
who had opposed him in some of his writings,
that the address in question had subsequently been followed up,
either by the regular appointment of overseers, or by the exercise of that office.
It was however too much to expect,
without something more than ordinary to account for it,
that a society so numerous and so extensive as Friends had now become,
should conduct its affairs in all respects harmoniously,
or remain wholly free from the incursions of that spirit,
which by means of his agents takes pleasure in sowing discord among brethren.
Accordingly, about this time,
one John Perrott became the author of much confusion in this Society;
more especially among those, who, having recently joined it, were but weak in the faith.
Of this number, I find the truly honorable name of Thomas Ellwood;
and from whose journal, such information may be gathered on the subject,
as is proper to precede the relation of some facts,
which William Dewsbury has left us in one of his
epistles relative to the part he took in the affair.

John Perrott joined the people called Quakers, about the year 1658,
and being of a forward, conceited, and what may be truly called a fanatical spirit,
he soon took upon himself the ministerial office,; and being great in his own opinion,
nothing less would serve him than to attempt the conversion of the pope.
Soon after his arrival at Rome, he was cast into Bedlam, and his companion Luv, or Love,
as George Fox writes his name, into the Inquisition.
The reputed madman, though not the best man, had the better chance, as it turned out,
for he lived, and succeeded in returning to England, while the other died in prison,
not without well-grounded suspicions of having been murdered.

On his return to England, Perrott,
by magnifying his sufferings and putting on the appearance of great sanctity,
so won upon the tender and compassionate feelings of Friends,
as to procure a place in their affection and esteem which he in no wise deserved.
This made way for propagating his peculiar error,
of keeping on the hat during public or private prayer.
Improbable as it may appear at this day, many sincere minds were taken with the bait,
and great confusion was the result.
Ellwood, with all the ingenuousness of a man of real worth,
relates his own case with full confessions of his error, which he publicly condemned.

In an epistle addressed by William Dewsbury, "`to all the faithful in Christ,`" etc.,
bearing the date of 1663, he thus describes the progress of this error,
as it took possession of the minds of those who were the leaders in its propagation.

[.embedded-content-document.epistle]
--

In that which tries and weighs your own spirits, in coolness and singleness of heart,
try and taste what spirit they are of who come among you at this day;
wherein many come forth with us as to the owning of truth in their judgments,
who regulate the outward man in some respects like the children of truth.
Some of them have felt the stroke of the judgment of the Lord +++[+++for sin,]
which has caused them to forsake some things in which formerly they delighted;
and in some measure of zeal they have borne a testimony to the light,
enduring stripes and imprisonments, both in this nation, and some beyond the seas.
While they stood in the fear of the Lord,
he for his name`'s sake delivered them from the winter storms they suffered under;
yet for lack of watchfulness,
the mystery of iniquity has wrought and drawn them from
the light into the pride of their hearts,
to deck themselves with the jewels and gifts,
which the Spirit of God gave unto them when they were humbled before him.
But, departing from the redeeming judgment of God, the deadly wound was healed again,
and instead of giving glory to God for their deliverance, they in this time of rest,
took their flight as on the sabbath day, upon the mountains of high imagination,
and did sacrifice on the high places... And having gone from the light,
they neither regarded the glory of God nor the good of his people.

--

Such as these became a source of much trouble and concern to their brethren;
and after having succeeded in unsettling the minds of many, fell off from the body,
drawing away their adherents after them.
Further on, in the same epistle, the author writes as follows:

[.embedded-content-document.epistle]
--

Oh! how did my bowels yearn for the preservation of John Perrott, in doing what I could,
to draw and separate him from that spirit which gave forth the
paper that propagated the keeping on of the hat in prayer,
and reflected upon those that called upon the
name of the Lord with their heads uncovered.
But after much counseling of him in tender love, to stop that paper from going abroad,
but he would not be separated from that spirit that gave it forth,
I cleared my conscience in the word of the Lord.
And now, in my freedom in God, I declare to the children of Zion,
what the judgment is that did arise in my heart, to this purpose:--'`John,
if you propagate what you have written in this paper, you will wound more hearts,
and cause more trouble of spirit among the tender-hearted people of the Lord,
than when the temptation entered James Nayler: who deeply suffered,
but the Lord restored him again by true repentance.
And as to my particular,
it is not my nature to be found striving with you or any upon the earth;
but having declared the truth to you, I will return to my rest in the Lord;
and let every birth live out the length of its day,
and let time manifest what is born of God.
For that spirit that stands up in self-striving, will weary itself, and die,
and end in the earth.
And this will certainly come to pass upon all
those that do not diligently wait in the light,
to judge the outgoings of their minds, +++[+++yielding]
in true self-denial to be lead in the footsteps,
where the flocks of Christ`'s companions delight to walk, serving one another in love,
and every one with the spirit of love and meekness,
seeking to restore another out of what any have done,
through the violence of temptation or weakness.

--

Such was the amiable and discriminating line of conduct which William Dewsbury pursued,
in the wisdom that was given him to rule in the church of God,
and such the harmless and lowly authority which he exercised.
Although, at this period, trials and afflictions sorely proved the Society from within,
as did persecutions from without,
there was from time to time a degree of faith administered to such steadfast spirits,
as were numerous among Friends who were the laborers and sufferers of that day,
which made them a match for every occasion wherein they were called to exercise it.
In this faith, which is the saints`' victory, the same writer, in his address,
proceeds to hand them the word of encouragement.
"`Dear brethren, though great be the wrath that withstands the work of our God,
which wrath works openly and mysteriously, to lay burdens upon the innocent,
and to add afflictions to the afflicted;--in the
word of the Lord that arises in my heart,
I declare, they shall but weary themselves, and all their hopes shall fail them,
and their expectations shall come to naught,
who wait for evil concerning you who love the Lord better than your lives,
and delight in waiting to feel his power at all times,
leading and ordering you in the bonds and within the limits of his spirit.`"

This subject must not be concluded,
without presenting the reader with some further information,
relative to the manner in which a very large
proportion of those persons became disentangled,
who had thus been taken in "`the snare of the fowler.`"--"`A
meeting was appointed to be held in London,
through a divine opening in that eminent servant and minister of Christ, George Fox;
for the restoring and bringing in again those who had gone out
from truth and the holy unity of Friends therein,
by the means and ministry of John Perrott.`"
This meeting, or rather these meetings, lasted whole days,
and some who had run out from the truth and clashed with Friends,
were reached by the power of the Lord; which came wonderfully over them,
and made them condemn themselves, and tear their papers of controversy to pieces.
George Fox, who relates the circumstance, had several meetings with them,
and "`the Lord`'s everlasting power,`" as he declares, "`was over all,
and set judgment on the head of that spirit in which they had run out.
Some acknowledged that Friends were more righteous than they;
and that if Friends had not stood, they had been gone, and had fallen into perdition.
And thus, the Lord`'s power was wonderfully manifested, and came over all.`"

"`In this manner,`" Ellwood writes, "`in the motion of life,
were the healing waters stirred;
and many through the virtue and power thereof were restored to soundness; and indeed,
not many lost.
And, though most of these, who thus returned were such as, with myself,
had before renounced the error, and forsaken the practice; yet did we sensibly find,
that forsaking without confessing, in case of public scandal, was not sufficient;
but that an open acknowledgment of open offenses, as well as forsaking them,
was necessary to obtaining complete remission.`"--Ellwood`'s Life, p. 241.

Besides an abatement of numbers in the Society, from the cause now described,
it will not be difficult to believe,
that while persecution did to a certain extent prevent its increase,
there were those also to whom the way proved too narrow,
as it involved greater sacrifices than they were willing to submit to.
Without an unreserved dedication of soul,
such as these would be not unlike the children of Ephraim, who, carrying bows,
turned their backs in the day of battle.
Although they might be said to have the weapons, the knowledge and the profession,
yet lacking that living faith which could alone fortify them with courage and endurance,
they would be unable to stand the brunt of that fiery trial,
which awaited the faithful servants of Christ.
As our Lord said to his immediate followers, "`If any man come to me,
and hate not his father, and mother, and wife, and children, and brethren, and sisters,
yes, and his own life also,
he cannot be my disciple,`" so it was with Friends in that day;
there could be no reserves: those who were not prepared to part with all,
even to the renunciation of lawful enjoyments, for the testimony of a pure conscience,
in which the faith is preserved, could not abide the fiery trial of that time,
but must fall back.
Of this number was not William Dewsbury; he was ready at all times to "`endure hardness,
as a good soldier of Jesus Christ.`"
Such indeed was the deep and abiding effect of that sweet
evidence of the love of God in Christ Jesus to his soul,
with which the Lord was pleased to favor him previous
to his venturing upon the work of the ministry,
and such the evidences vouchsafed of the heavenly power that attended him and Friends,
that according to a testimony which he bore when on his deathbed,
he never afterward played the coward, but joyfully entered prisons as palaces,
telling his enemies to hold him there as long as they could;
and in prisons he sang praises to his God, and esteemed the bolts and locks put upon him,
as jewels; "`and in the name,`" says he, "`of the eternal God, I always got the victory;
for they could keep me no longer than the determined time.`"
When at liberty,
he was an indefatigable laborer in the cause which he
had espoused with so much sincerity and zeal.

On one occasion, about this time,
we find from Besse`'s Collection of the Sufferings of Friends,
that he was at a meeting in Warwickshire, at the house of one William Reynolds,
which was disturbed by a constable accompanied and assisted by a rude multitude,
armed with swords and staves, who pulled the Friends out of the house,
and having beaten and abused some of them,
fell to breaking the windows in the constable`'s presence.
These were the every day occurrences of those lawless and intolerant times.

Towards the close of the year 1660,
William Dewsbury is to be traced to Ouse-bridge prison, in the city of York,
to which he was committed in company with eleven others,
among whom I find the name of William Tuke, for refusing to take the oaths, no doubt,
of allegiance and supremacy.
It may be here remarked, that the practice of that day,
by which the dominant party forced these oaths upon the people,
and thus through the frequent changes in the government made them to swear and forswear,
was a sufficient reason with Friends for refusing to take them,
independently of those strong objections which they entertained, on scriptural grounds,
to all oaths, as unlawful under the Gospel dispensation.
The truth had made them free from the necessity of oaths; they were an upright people;
and for conscience sake, conducted themselves as such,
both privately and to the government,
so far as the laws of man did not infringe upon
the paramount obligations of religious duty.
And their words of promise were more binding to them,
than the oaths of most other people.

From Ouse-bridge prison he was shortly after removed to York Tower,
and from there to the castle, where, by the date of one of his epistles,
I find him in the third month, 1661.
Besse, from whom these particulars have been obtained, informs us,
that the whole number of Friends imprisoned at one time in York castle,
and other prisons in the county, in the two months of which he had been writing,
was five hundred and thirty-six, of whom five hundred and five were in the castle itself;
where five died through the unhealthiness of the place.^
footnote:[It is not the editor`'s purpose here to
enlarge on the subject of these lamentable facts,
or he might readily produce a mass of evidence,
in illustration of the cruelty and wrong inflicted upon
the Society at large during this period.
But an original letter of a Friend, addressed to George Fox, having come to his hand,
dated from the place of William Dewsbury`'s frequent allotment,
"`the dungeon of Warwick jail,`" an extract may serve to show,
that other places were not behind York,
in the entertainment given to his suffering people.--"`Dear George Fox,
my love flows forth unto you in the pure, holy, immortal life; and Friends here,
their dear love is to you, and our love to all faithful Friends in and about London.
There are many of us here imprisoned in Warwick, to the number of one hundred and twenty,
as near as we can judge of it, and among us some women Friends;
and they continue going on in their persecution still.
There were several more brought to prison this morning;
and of what prisoners are at Coventry, and in another place in this county,
we have not certain knowledge; but we heard, that there are above a hundred,
besides ourselves, at Warwick.
We that are here are kept close from coming one to another.
There were some of our Friends, a little time since, put into a close cellar,
where they had not room to lie one by another;
and one of them being near dead for lack of room and air, was brought forth very weak;
and he yet remains sick and weakly.
This cruelty of the persecutors has caused a great cry against them from many in Warwick;
since which time, they have removed the prisoners to a more convenient place;
but they are there kept close, and there is little coming to them many times,
but with much difficulty to bring us necessary things: but sometimes it is otherwise.`"
6th of twelfth month, 1660.]
William Dewsbury was not long detained in confinement after the above date;
for in the postscript to an address, altogether worthy of a Christian minister,
dated the 20th, which he wrote and found means of presenting to King Charles II.,
then newly seated on the throne; he informs the king,
that before the document could be sent to him by a private and safe hand,
he was set at liberty, with some others of his brethren, "`by the late proclamation,
which we own as an act of justice.`"
These latter are his own words.

The act just referred to,
appears to have originated in the circumstance of Margaret Fell, the wife of Judge Fell,
of Swarthmore Flail, appearing twice before the king,
with a view to lay before him the grievous sufferings of Friends.
This was about the time of the rising of the fifth monarchy men,
in whose absurd views Friends, to their cost,
were unjustly supposed to have participated.
The object of Margaret Fell was much promoted,
by an act of justice performed towards the Society in
some of these unhappy and mistaken persons;
who, before the sentence of the law was executed upon them,
publicly cleared Friends of any participation or knowledge of their design.

George Fox also threw in his mite.
He published a declaration against all sedition, plotters and fighters,
asserting Friends to be a harmless people,
whose principles were against wars and fightings.
This timely act,
appears to have had considerable weight with both the
king and council in procuring the desired relief.
William Dewsbury`'s address to the king, will be introduced in a subsequent page;
it is recommended to the notice of the reader,
as a specimen of that true independence of mind,
which Christianity in its genuine nature produces in the character of man.

It has already been intimated, that while under confinement at York,
William Dewsbury wrote several epistles of encouragement to be dispersed among Friends,
exhorting them to steadfastness and faithful adherence
to the testimonies which had been given them to bear,
notwithstanding the trials and sufferings to which they were subjected.
Among these, the following will serve as a specimen of his mind at this juncture.

[.embedded-content-document.epistle]
--

[.salutation]
Dear brethren and sisters in the church of the first-born,

Grace, mercy, and peace be multiplied in and among you,
to whom God revealed what he determined and is now manifesting,
that every one in the life of God might stand single,
out of and over the snares of those whom God lays aside as the broken reeds of Egypt;
that his own name might be trusted in, and his mighty arm alone seen and felt,
in leading and preserving his people to his glory, as witnessed this day,
blessed be the God of our strength and safety.

All dear and chosen vessels of God, whether in bonds or out of bonds,
in the everlasting light and life stay your minds, and lift up your heads,
and be strong in the name of the Lord.
And fear not the wrath of man,
for it is limited and shall turn to the praise of God forever;
who is making up his jewels, and gathering his wheat into his garner,
and the sheep of his pasture into the safety of his power,
that he may lead them and save them with his outstretched arm,
to the confounding of the heathen that know not God.

Dear Friends, gird up the loins of your minds,
and in the faith and patience of Jesus stand still in the light,
and see the salvation of God;
who has caused the mountains and hills that withstood his glorious arising,
to melt like wax, and to vanish as the untimely fruit.
He has divided the waters and turned them on heaps,
and has made a way through them for the ransomed ones to walk in his service,
whereunto he has called them.
He has made the weak as strong as David, before whom the uncircumcised has fallen,
that resisted the God of Israel.

Dear Friends, let the love of God constrain you to trust in him;
and feel the seed of God borne up over all, to feed on the bread of life;
that you may live and rejoice over all hardships, and over all wrath.
All, keep the word of faith in the power of God.
The mountains shall fall before you more and more,
and you shall tread down the pride of the perverse and froward generation,
in the patience and dominion of God.
And let the strong bear the burden of the weak: that all, in the unity of the spirit,
in the power of the love of God, may grow up a holy priesthood,
offering up souls and bodies a living sacrifice,
in faithful obedience to do the will of God.

Dear Friends, in vain is it for man to strive to limit the Holy One of Israel,
or his Spirit in his people.
For if they that seek to oppress and destroy you,
who love God more than anything in the world, yes, than life itself,
were as the sand that is on the sea shore, fear not:
comfort yourselves in the light of his countenance.
For he will arise, and scatter in his wrath, all those that resist his spirit,
as dust before the wind: and his righteousness will he establish in the earth forever.

O Zion, your God reigns!
And you shall see your enemies come bending to the soles of your feet.
Your renown shall go forth more and more over the earth,
your leaves shall heal the nations which shall walk in your light;
and you shall be known in all the earth to be the city of the most high God, yes,
the righteous seed,
when the faces of your enemies shall be covered with
shame,--the mouth of the Lord of hosts has spoken it.

[.signed-section-closing]
Let this be sent abroad among Friends with understanding in the fear of God.

[.signed-section-signature]
W+++.+++ D.

[.signed-section-context-close]
York Tower, 19th of the Twelfth month, 1660

--

Thus was this dedicated servant of Christ, himself a prisoner for his testimony,
enabled "`in the spirit of power and of love and of a
sound mind,`" to encourage the suffering flock.
This was a time, when it may be said with much truth,
that Friends were accounted as little better than sheep for the slaughter,
and when their enemies seemed ready to swallow them up quick.
We who live in this day of ease,
have little conception of the amount and extremity of their sufferings,
and have need to be cautioned against indifference.
We should never forget,
it was through the endurance of such wrongs as have now been related,
though to a far greater extent,
that our present degree of religious freedom has been purchased for us.
