== Chapter 10

[.chapter-synopsis]
* 1655+++.+++ Address to the nation
* William Dewsbury often a prisoner
* Discharged from Northampton jail
* Warning to his persecutors and those in authority
* Travels to London
* Kent
* Land`'s End
* George Fox`'s labors in Cornwall
* Humphrey Lower
* William Dewsbury holds a meeting at his house
* Foresees a storm
* Soldiers arrest him at Torrington
* Brought before the mayor
* His treatment
* Delivered out of their hands
* Writes to the mayor
* Proceeds into Somersetshire
* Bristol
* Wales
* Epistle to Friends about Plymouth.

In William Dewsbury`'s collected works, under the date of 1655,
we have an address to the people of England, containing the following paragraphs,
which were thought to be worthy of the reader`'s attention.

[.embedded-content-document.address]
--

[.salutation]
O England!

Who lies in the fallen and lost estate, separated from the true and living God,
by your iniquities,
notwithstanding all your profession of his name in outward forms and observations;
repent, repent, and turn unto the Lord God Almighty, who waits to be gracious unto you,
and to make you the glory of all the nations of the world,
if you will hearken diligently unto his counsel,--the
light that is in the conscience of every one,
to wait in it upon the Lord God, that he may guide you by his power.

And this which he has made known unto me concerning you, O England,
I have to declare to you from the Lord.
Certain years ago,
when the everlasting covenant of life was confirmed to my soul in the Lord Jesus Christ,
with the assurance, that I should go with the ransomed of the Lord to Zion,
I inquired of my God, to manifest unto me where Zion was,
that I might return there to worship him in spirit and
in truth;--there being so many confused cries in you,
who profess to worship the only true God, some saying, '`Lo,
here is Christ,`' in the Presbyterian practice, so called; and the Independent, so called,
cries, '`Lo, he is here;`' and the Anabaptist, '`Lo,
he is here;`' and others in outward forms, cry saying, '`He is here.`'
As Christ foretold, that the time would come when they should say, '`Lo, here is Christ,
and lo there;`' so it is fulfilled in you.
But Christ says, '`Believe them not, go not forth,
for the kingdom of heaven is within:`' and,
'`as the lightning that lightens out of the one part under heaven,
shines even unto the other part under heaven,
so also shall the Son of man be in his day`'--and this I witness.
And while I was waiting on my God, to make known to me where Zion was,
the word of the Lord came unto my spirit, that Christ was not divided,
and that there was no rent in his garment; for the Lord is one and his people one:
and that all your outward forms of worship, O England,
where you are waiting for Christ in observations, are contrary to his will.
For Christ says,
'`the kingdom of God comes not with observation,`' or as the margin has it,
'`with outward show,`' '`neither shall they say, Lo here! or,
Lo there! for the kingdom of God is within you.`'
And all your strict observing of your outward forms,
is but imitating the saints`' practices, in the Babylonish and heathenish wisdom.
So there is nothing but confusion in you,
and all your outward forms are the outward court, which is without the temple,
that the angel was not to measure: for it is given unto the Gentiles,
and the holy city shall they tread under foot.
And this was made known unto me from the Lord my God,
to be the estate and condition you do stand in, O England,
in your outward forms and observations:--'`having a form of godliness,
but denying the power thereof.`'

Lo, under all your profession, is most cruel oppression; every one,
according to their power, oppressing another, from the highest unto the lowest.
So that the cry of the oppressed Seed, within the hearts of your inhabitants,
and of those that are oppressed in outward oppressions of you,
has entered into the ears of the Lord God of Sabaoth;
and he is coming in power to set the oppressed free, and to bring them to Zion: which,
in the riches of his love, he made known to me, and where Zion was,
according to the desires he had raised in my heart.
And the word of the Lord came to me, saying,
I will gather my people out of all forms and observations, and out of all kindreds,
tongues, and nations, and I will pour my spirit upon them,
and purge away their filth with the spirit of judgment and of burning:
and I will write my law in their hearts, and put my spirit in their inward parts,
and they shall not depart from me; but shall be bound up in union with me,
in the free covenant of life in the Lord Jesus, and one with another in the one spirit,
so shall the Lord be one, and his people one.

And this is Zion, the city of the living God, to which all the promises of the Lord are,
according to the Scriptures of truth;
wherein they need not '`teach every man his neighbor, and every man his brother, saying,
Know the Lord, for all shall know me from the least of them unto the greatest of them;
for I will be merciful to their unrighteousness,
and their sins and their iniquities will I remember no more.`'

Therefore mind the light in your consciences; diligently hearken unto it,
and it will smite your image of forms and observations, and break it to pieces;
and will rend off all your coverings of outward profession,
and will let you see that the woe is unto them who are covered,
but not with the Spirit of the Lord.
To the light in your consciences I appeal, which will witness me.
If you hearken unto it, to be guided by it,
you will never find rest in outward forms and observations,
but in putting off the body of sin, through the obedience of the spirit;
'`that the righteousness of the law may be fulfilled in you,
who walk not after the flesh but after the spirit.`'
'`For they that are Christ`'s, have crucified the flesh with the affections and lusts.`'
And the body is dead in regard of sin, but the spirit is alive unto righteousness.
And this you must witness, or else all your religion is vain, and your souls will perish.

--

So very large a portion of William Dewsbury`'s time was spent within the walls of prisons,
that the materials from which a narrative of his life is to be composed,
are necessarily very scanty,
and in many instances the chain of events respecting him can alone be rendered complete,
by the insertion of little more than dates gathered from epistles,
which at various periods he addressed to his friends and to the churches.
After his liberation from the fifteen months`' cruel imprisonment,
which he endured in the dungeon of Northampton jail,
he was favored to enjoy a considerable respite from suffering in that way;
which allowed him the opportunity of pursuing his religious duties,
according as his great and good Master was pleased to lay them upon him.
But previous to his deliverance from this confinement,
he sent the following animated and solemn warning to such as were in authority,
and involved in the guilt of those persecutions under which Friends were then suffering.
It possesses the peculiar characteristics of the writer`'s mind,
as strongly as anything which is the product of his pen.

[.embedded-content-document.address]
--

To all you rulers and judges of the earth,
who combine against the Lord and against his anointed, and lay your plots in the deep,
and fetch your counsel out of the bottomless pit, that you may ensnare the righteous,
whom the world in scorn calls Quakers;--who, in love to your souls, do warn you,
as you will answer it before the Lord God of heaven and earth,
to give over plotting against the righteous,
and inventing evil devices against the innocent.
For in the light you are seen, and your secret works of darkness are discovered.
And, all you that will not take warning now,
when the Lord calls you to turn to his light, but reject his counsel,
and continue in the evil of your doings,--to you this is the word of the
Lord,--'`your plots and counsels shall not prosper against the righteous;
for he that sits in the heaven does laugh, the Lord shall have you in derision.
For no plot shall prevail against Israel,
nor unrighteous counsel stand before Zion`'s King, who will break you with a rod of iron,
and dash you in pieces like a potter`'s vessel,
you that plot against him to oppose him in his appearance in the hearts of his saints.
For what you do to the least of these, you do it to me, says Christ;
and it were better that a millstone were hanged about your neck,
and you cast into the bottom of the sea,
than to offend the least of those that believe in my name.`'
From the Spirit of the Lord who will not always strive with man,
you are once more warned, now, while you have time, to prize it;
and turn to the light of Christ in your consciences,
which lets you see the secret evil of your hearts.
And wait in the light, for the power of Christ to destroy the wicked, plotting,
inventing mind,
and to guide you in the straight and narrow way of self-denial in the daily cross,
and in perfect obedience to the law of God, lest you perish in your disobedience.
For the Lord God of Israel is arising,
to plead the cause of his persecuted and oppressed people,
and to scatter as dust before the wind all their enemies that plot against them.
For they that plot against the people of God and dig pits for them,
shall fall therein themselves.
No weapon formed against them shall prosper; for all shall know,
that God is with his people, and that the King of glory,
who is the strength of his people, dwells in Mount Zion,
and of his dominion there shall be no end.
In that day, both high and low, rich and poor, who slight the mercy of the Lord,
and continue in enmity against him and his appearance in the hearts of his saints,
will know, that what is declared to you from the righteous Seed,
is to you the word of the Lord God.
He that has an ear to hear let him hear.

--

It was in the twelfth month, 1655, that he obtained his liberty;
and it is reasonable to conclude that no long time would elapse,
before he proceeded to Wakefield to join his wife and children,
after so long and so trying a separation.
Friends in those days, however,
may truly be said to have married as though they married not,
and to enjoy as though they possessed not;
so freely and so sincerely were they given up to serve the cause of Christ,
We accordingly find William Dewsbury, in the third month following,
at a meeting two miles from Northampton,
no mention being made of his having returned home in the interval.
Here again, he narrowly escaped a prison,
and was actually seized at the meeting in company with several other Friends,
who were sent to the very dungeon he had himself so lately occupied,
and were confined there a considerable time.
Among these were John Crook, lately a justice of the peace, and Thomas Stubbs,
a man of education, both persons of some account where they lived.
On this occasion, William Dewsbury`'s detention was only temporary; he was soon dismissed.

[.asterism]
'''

__From the Editor.__--Here a chasm of nearly a year intervenes in the biographical narrative,
which the Editor will not attempt with any exactness to fill up.
But, by a memorandum in the author`'s handwriting, it seems,
that had he been spared to perfect his design,
he would in this place have introduced some notice of the part taken
by William Dewsbury in the affecting and disastrous affair of one who
was a companion with him in labor and a brother beloved.
The case of James Nayler is perhaps as widely known,
both to the public at large and to the Society of Friends,
as any circumstance in our history;
and therefore much need not be here said on the subject itself.
Enmity and prejudice, however,
have contrived from that time to the present to raise false conclusions from,
and even to misrepresent, the plain facts of the case,
although explanations have been abundantly given forth,
clearing the Society and their principles from
the slightest implication in the whole matter.
On this head, J. G. Bevan`'s Life of James Nayler,
with a refutation of some of the more modern misrepresentations of Friends,
may be consulted with advantage.
"`James Nayler,`" says a judicious writer, in a note appended to G. Fox`'s Journal,
"`was a monument of human frailty.
His gift in the ministry was eminent, his experience in divine things truly great.
He fell through unwatchfulness,
but was restored through deep sufferings and unfeigned repentance.
His own writings are the most clear and lively
description of the various dispensations he underwent:
some of them deserve to be transmitted to the latest posterity.`"
It has been said, that upon his restoration to the unity of his Friends,
George Fox was with much difficulty reconciled to him.
That this should have been the case,
is not to be wondered at on several accounts;--and we may also remember,
that the primitive believers could scarcely be prevailed upon to receive Saul,
the persecutor, among them.
From a letter now before the Editor, although without date,
he is induced to consider William Dewsbury as a
principal instrument in bringing this about.
Speaking of a journey to London,
and of the dealings of the Lord with him in the course of it,
he says,--"`who has restored many captives, and brought in many that were turned aside,
in much brokenness of heart, in the sense of his mercy in their recovery.`"
"`I was led of the Lord,`" he continues, "`into London, according to his will,
in the service he had determined at that time in that place.
I was much filled with comfort, to behold his appearance among his people,
who did mightily refresh his babes with his own presence.
The Lord laid it upon me, that dear G. F. and J. N. might meet together:
my travail was great in spirit, until the Lord answered; which, in the day he determined,
was done: mighty was his majesty among his people, in the day he healed up the breach,
which had been so long to the sadness of the hearts of many.
The Lord clothed my dear brethren, George Fox, Edward Burrough, and Francis Howgil,
with precious wisdom; his healing spirit did abound within them,
with the rest of the Lord`'s people there that day, according to their measure:
and the Lord was with J. N., and ordered him by his spirit,
so that the measure of the Lord`'s Spirit in all,
reached to embrace it with gladness of heart.
Then I was set free to pass from London, through Surrey, and so to Bristol,
to be there the first-day after, being the 5th day of the twelfth month.`"

Before giving the reader further extracts from this letter, relative to Bristol,
it will be proper to add something as to William Dewsbury`'s
conduct and dealing with James Nayler himself.
A very judicious communication from the former of these Friends to the latter,
with the reply of the latter, is now in the possession of the Editor;
by which it appears,
that William Dewsbury had watched over and yearned towards his offending brother,
and had seen with clearness the steps by which he had fallen,
and the subtle snares which Satan had laid for his feet.
These he traces out to him,
reminding him how it had been with him in the hour of his temptation,
and telling him where it was the enemy had got entrance,
so as to prevail over him and others--how they
had given way to a spirit of self-exaltation,
by not abiding in the truth, nor in the light, nor in the grace by which we are saved,
and by which alone the soul can be kept out of the reach of all delusion, deceits,
and vain imaginations: and from an undue admiration and respect of persons,
how they had proceeded to cry out against those
who kept their habitations in the power of God;
and at length to separate themselves from such, and to gather adherents about them,
to the stumbling of many whose faces were set towards Zion,
the saddening the hearts of the Lord`'s upright children,
and causing his holy name to be blasphemed.
He speaks of having been moved to come to London in the Lord`'s service;
and that when there,
he had sent for those who had so run out:--"`in tender love to their souls,
I ministered to them, to clear their understandings where they were to return,
that God might heal them; on which, some of them, with others in Essex and Norfolk,
were bowed down while they were with me; and I am clear of their blood,
whom in tender love I have followed,
to gather them as a hen does gather her chickens under her wings.
But if they will not hear, and return to the light, to wait in it to be restored,
their blood be upon their own heads,
with all the unclean spirits that gathered shelter to themselves under you,
in their impudent wickedness, to withstand the counsel of God,
they hoping you will own them in what they do;
which gives them strength desperately to strive in a masterly spirit,
and with feignedness in all subtlety, to utter words and work lying wonders,
to the grieving of the righteous souls and burdening the Seed of God.
If they do not return to the Lord, to receive an understanding,
and to walk with him in faithfulness to his counsel,
they shall certainly wither and perish; the mouth of the Lord has spoken it,
whose spirit will not always strive with man.
And if you allow them in their deceit, as you have, and do not reprove them,
their blood will lie heavy upon you, and you will not be clear.
Dear James, I beseech you, in tender love in the Lord Jesus, wait singly in his counsel,
to give you an understanding to discern the working of this deceitful spirit.
Notwithstanding all feignedness, that ground is to set up a master in the earth,
and so make strife among brethren.
The Lord God has turned his hand against them, and will overturn them,
and all that join with them in that deceitful ground.
As the Lord gives you discerning, and moves you in his everlasting strength,
arise and judge that deceitful spirit that has caused the truth to suffer,
and has wronged you, then will the Lord give you dominion over it;
so will you be clear of their blood, and there are some of them God will restore again,
they waiting in the light to be cleansed through judgment.
And what has been done in the hour of temptation, let the light and life judge it out;
that in the light and life of our God,
the whole body may grow in the unity of the spirit, to bear one another,
serve one another, build up one another; that among all,
there may not be any master but Christ, our head.`"
He adds, "`many wait to hear of your being raised up in the light and life,
to judge down and reign over this spirit,
that has and does seek to make disorder and strife among brethren.`"
This affecting address closes with these pious exlamations in prayer:--"`God
Almighty! restore to a pure understanding all those that have been veiled;
in your life, keep them in unity with all your elect,
to serve you with faithfulness unto the end.
Amen!`"
James Nayler`'s reply manifests throughout,
as clear and becoming a frame of mind as could be desired.

[.asterism]
'''

To return to Bristol.
On the first Friends visiting this place, there were great disturbances from the rabble,
incited by the priests, and encouraged by the magistrates, as Sewel and others relate.
This, it is presumed,
was at furthest only two years previous to William Dewsbury`'s coming there;
and his letter in a lively manner conveys a picture of those times,
and of the preservation and strength vouchsafed to the Lord`'s faithful little ones.

[.embedded-content-document.letter]
--

The sixth and seventh days before we came there, the apprentices, with the rude people,
were running with naked swords in their hands up and down the streets,
so thronged that it was hard to pass through them.
On the first-day I was at the meeting:
the Lord chained them all down with his Almighty power,
in which the meeting was precious, and his people,
comforted with living refreshings in his presence, were preserved quiet, in peace,
and without the least disturbance.
At night, there was a meeting at Dennis Hollister`'s;
many of the rude people with their swords stood in the streets, where they could hear;
the Lord kept them quiet; Friends passed through them, when they gathered,
and did not receive any harm.
The next day they were more rude than formerly, some beating their masters,
and not allowing the shops to be opened, threatening Friends who opened theirs,
not regarding the mayor or any of his officers, but did what was permitted,
as they saw good in their own eyes; many times running into Friends houses,
in this time of the tumult, but had not power, when they came, to do any harm.
In the height of their madness,
the rulers hearing of a meeting on the third-day of the week, being the 7th of the month,
at Edward Pyott`'s, gave out openly among the people in the city,
that they would come and break it up.
When we were met together in the name of the Lord, some of them prepared to come;
one swearing, and blaspheming the name of the Lord God of heaven and earth, said,
he would cut the Quakers as small as herbs for the pot;
and in order to perform his bloody intent, he went for the guard to take a halbert,
that he might satisfy his bloodthirsty spirit.
The God of our safety allowed it to be,
that they of the guard would not let him have the halbert; so strife rose among them,
and the pit he dug he fell into, for he was run through the body;
so God prevented their bloody intent.
The meeting was precious in the life of our God,
in which Friends parted with joy in the Lord.
The rude people were full of madness, and hearing of the largeness of the meeting,
they called one to another, to kill Friends as they went in at the gates;
but the Lord prevented them, so that Friends received no harm.
The Lord bound the hands of the wicked; still the envy remained in them,
and they were full of madness,
that they had missed the opportunity in which they intended to do such mischief.
They came in the night season, about the eighth hour, to Edward Pyott`'s,
certain Friends being there, some out of New England,
who were banished from their wives and children upon pain of death.
We were bowed down before our God, and prayer was made unto him,
when they knocked at the door: it came upon my spirit, it was the rude people,
and the life of God did mightily arise, and they had no power to come in,
till we were clear before our God.
Then they came in, setting the house about with muskets and lighted matches;
and after a season, they came into the room where I was, and Amos Stoddard with me.
I looked upon them when they came into the room, on which they cried out,
as fast as they could well speak, '`We will be civil,
we will be civil:`' I spoke these words, '`See that you be so.`'
On this, they ran forth of the room, and came no more into it,
but ran up and down the house with their weapons in their hands.
And the Lord God, who is the God of his seed,
against whom no weapon that is formed shall prosper
further than he sees shall be for his glory,
and the comfort of his people, caused their hearts to fail; and they passed away,
and not any harm was done to any of us; blessed be the God of our safety!
The next day, it was upon me to go to Bristol,
and walk in the streets among the throng of them, D. H., E. P.,
and Thomas Gouldney being with me.
We passed to George Bishop`'s, and came through where they were gathered together:
the majesty of our God struck their hearts, and they all stood gazing upon us:
little was spoken, but some said, '`That is one of the Quaker preachers.`'
So we had a precious time with Friends,
and I passed away with much clearness and freedom from the city of Bristol,
Friends being very precious in the dominion of the life of God,
in which they eyed his mercy,
who had brought up John Audland and certain brethren among them,
to strengthen them to stand under these trials.

The 10th day of the month, we crossed the water into Wales:
Friends in general are pretty well as we pass.
The 24th, we came to a meeting near Leominster; and the 26th, to Worcester.
The night before we came in, the rude people were up in much madness,
making fires in the streets, and the soldiers suppressing them.
The night we came in, they rose in great rudeness, so that the soldiers, the mayor,
and the rulers of the town were up much of the night to suppress them.
The God of our safety preserved us, and a peaceable meeting we had,
which continued many hours, and the presence of the Lord was mightily among his people.
The next morning Friends met at the meeting place about the eighth hour;
the Lord preciously satisfied the desires of his people with his presence,
in which we parted one from another.

We came to Tewkesbury where there was a serviceable meeting in the evening,
certain Friends being there, who did minister as the Lord moved.
Walter Jenkins, a Welchman, in whom the power of the Lord is moving,
has been pretty much with me; as you are free you may write to him,
he may be of good service among the Lord`'s people in Wales, he abiding in the life,
to be led by it.
A large meeting there was the 28th day of the month, three miles from Tewkesbury,
and the Lord`'s presence refreshed his people; this day a meeting at Evesham,
and the next day at Shipston, if God permit; further, as the Lord orders in his will.
God Almighty be with you, your family, with all the faithful;
and the Lord with his heavenly presence comfort the hearts of all that love him,
and wait in uprightness of heart to do his will.

[.signed-section-signature]
W+++.+++ D.

[.postscript]
====

Remember me to Robert Widders and John Audland; as freedom is,
you may let them know how it is with the Lord`'s people at Bristol and hereaway.

====

--

On the 9th of second month, 1657, William Dewsbury dates an epistle from London;
+++[+++but before this, a letter to Margaret Fell conveys, that he had been through Norfolk,
Suffolk, and Essex on his way.
Few particulars are entered into; but he states,
that he found Friends in their measures preciously grown in the life,
and that there was a great people in those parts.--__Editor.__]
Arrived in London, he appears to have tarried something short of six weeks,
and then moved forward into Kent; from which district,
in an epistle dated the 22nd of third month,
he gives the following hints on spiritual obedience,
and the exercise of gifts in order to the ministry.

[.embedded-content-document.epistle]
--

I lay it upon you, wait for the Lord to seal unto you his mind,
that in his movings you may answer his will in word and works.
The light will guide you to know the intent of every motion, that in it you +++[+++may]
stand approved in the integrity of your hearts to God.
And every one in particular, be faithful in the power of God,
that in all the movings of the spirit of life,
the earthly wisdom with all its reasonings and consultings be judged out;
and all may know the new man in Christ, and the new bottle that preserves the new wine,
which is committed to you in the kingdom of God,
to refresh your souls and make them glad in his presence;
and so minister in his living power and wisdom,
to the refreshment of the weary and oppressed soul,
with the comfort of the spirit of life, in which your souls are made glad in God.
So will you all come to the pure ministry in the life.
And as you are moved of God, be faithful; strangle not the birth,
neither quench the movings; and in the presence of the Lord, I warn you,
wait for an understanding in the life to lead you.
Neither add to, nor diminish;
so will death with all its formality be kept out from among you.

--

[.small-break]
'''

+++[+++Of his visit to Kent,
the only additional vestige is gleaned from the communication to Margaret Fell,
mentioned above, the date of which is near Sandwich, the 3rd of fourth month.
He says, that he has had large meetings since coming into the county,
and that "`the power of the Lord broke in upon many of them;`"
also of his having been on board a vessel in the Downs,
in which were a number of Friends, men and women,
bound for New England in the service of the Gospel: he says,
they were bold in their measure in the power of God; and adds,
"`his everlasting presence keep them in the unity of the life,
and prosper them in his work.`"
The master of the vessel, Robert Fowler,
afterwards gave some account of the hand of Providence being with him in his voyage,
which was called "`A Quaker`'s Sea Journal,`" and was printed.
In it, he makes mention of the refreshment they had from the company of William Dewsbury,
and that he recommended them to the grace of God.--__Editor.__]

[.small-break]
'''

From Kent he traveled westward to the Land`'s End,
preaching the word of eternal life through the southern counties.
There is no account preserved,
of how or where he was particularly occupied between
the above date and that of the 17th of seventh month,
when he writes a letter from the Land`'s End,
in which he relates the particulars of some trials that befell
him previous to his reaching that part of the country.

The year previous to William Dewsbury`'s arrival in Cornwall,
George Fox had traveled through most parts of that county;
so that the ground was already broken up for succeeding laborers.
"`Great,`" says the former, "`was the service of my God in that country.`"
On the first-day of the week, being the 27th of the month,
he was at a meeting at Humphrey Lower`'s, who had formerly been a justice of the peace.
He was one of the many who had been convinced by
George Fox while prisoner in Launceston jail,
where the latter suffered nine months`' confinement,
part of the time under the most revolting circumstances,
in the dungeon of the prison which was called Doomsdale,
some particulars of which have been before related.
This Humphrey Lower, George Fox describes as "`a grave, sober,
ancient man,`" who among others went to visit him while a prisoner there,
and was thoroughly convinced, and so continued to his death.
It was at his house that William Dewsbury`'s meeting was held;
and he was a near neighbor to the high-sheriff of the county, a man,
as William Dewsbury writes, "`who was wicked against the truth of our God.`"
"`It was said, he threatened to break up the meeting;
but in the power of my God I did stand, which chained him,
and the meeting continued precious in the Lord.`"
On the 29th, William Dewsbury was at a meeting at Launceston;
after which he pursued his journey into Devonshire,
his mind having been strongly impressed with an apprehension,
"`as the Lord had let him see,`" that he should meet with a storm in that county,
or near it: which in fact took place at Torrington.
There he was arrested, and under a guard of soldiers,
was brought before the mayor and other functionaries,
who had imbibed the persecuting spirit of the day.
"`Some of them,`" says he, "`were very cruel and wicked against the truth of God,
and did deal very rudely with me.
In great wrath they took my hat off my head, and threw it on the ground,
and committed me to prison, where I was two nights and near three days.`"
He was many times brought before them,
and they accused him of being a Jesuit and a foreigner, and read to him many new laws,
threatening to proceed against him as a vagabond: "`in which,`" says he,
"`the Lord reigned over them.`"
They then read him the oath of abjuration,
the common snare with which Friends were caught at that time;
and they told him he must take it.
This he refused to do,
on account of the testimony he had to bear against all swearing under the Gospel,
no less against the pope and all idolatry, than the other points embraced by the oath.

On the second day of his examination, towards night, he was brought forth,
and they inquired of him how he became a minister of Christ;
which subject had been before alluded to.
It appears to have been a mystery to them,
how a man could be in the way of his duty in leaving
his wife and children in the north of England,
"`to preach the word of eternal life through the southern counties unto Cornwall.`"
And when, in answer to their questions,
he "`was free in the Lord to declare to them how he came to be
a minister of Christ,`" they were so cut to the heart,
that one of the justices wept, and the clerk said, "`If you had spoken thus much before,
here had not been this to have done.`"
But there appears to have been great confusion of purpose and
difference of sentiment among the magistrates,
so that Dewsbury attempting to speak further on the subject was not allowed.
Others offended at his hat, stormed against him for having it on,
and he was sent again to prison.
"`Many times,`" says he, "`I was brought before them, to see if they could ensnare me.
But in the wisdom of God, I stood innocent.`"
The case was difficult,
and there was a power among them to which they were unwilling to be subject,
yet were unable to control.
For although they made out a court order to
commit the prisoner to the common jail at Exeter,
they were so divided that some of them objected to his going there; but the mayor,
"`he who had the chief rule,`" told him,
he should not see his face any more until he was
before the judge at the next assize at Exeter.
"`Do with me what you have power to do,
my innocence will plead for me,`" replied Dewsbury; and he was remanded to prison,
where he lay on the bare floor;
remaining in this condition till the 2nd day of the eighth month.

"`I was then,`" says he, "`brought before them.
My God had pleaded my cause, and changed the heart of man, which failed in them.
For the man who said I should see his face no more,
until I was before the judge at Exeter, pulled the court order in pieces before my face,
and said to me, '`You are free.`'
So did my God set me free, out of the hands of unreasonable men,
according to his promise made to me; praises to his name forever.`"

Before he left Torrington,
he addressed a close and faithful letter to the mayor of the town, telling him,
that he and others in commission had abused their power,
and turned their hands against the innocent; "`whom,`" says he,
"`you wounded as much as you could: in the fear of God consider what you have done.
Is this the fruit of your fasting and humbling yourselves, as you say;
when you have done, to smite with the fist of wickedness,
and instead of entertaining strangers, to use them so barbarously?`"
"`An account you must give to the Judge of heaven and earth.`"
He then refers to some of the latter portions of the 25th chapter of Matthew,
telling them, it will be in vain to say, "`When did we see you hungry,
and fed you not,`" etc. inasmuch as they did it not to the least of the brethren;
and he calls upon them to prize their time,
and not to slight the day of God`'s mercy:--to incline their ear to his counsel,
the divine light in their consciences,
that would discover to them the evil of their hearts,
and their unjust proceeding against innocent men;
that so the Lord might give them repentance unto life,
lest otherwise they should perish in the day of his fierce wrath,
when he will recompense to every man according to his works: and finally takes his leave,
by expressing his desire,
that the Lord would not lay what they had done against him to their charge.

Having thus regained his liberty,
he proceeded without delay on his journey into Somersetshire; and,
on the 4th of the eighth month,
was at a large meeting in that county and tarried a night in Ilchester jail,
with Thomas Salthouse and others, who were imprisoned there;
the next day going forward into Wiltshire, where he held another meeting.
On the 11th, being the first-day of the week,
he was at a meeting which was thought to be attended by two thousand persons:
in reference to which, he says, "`My God was mighty in his power,
to the glory of his name.`"
He then passed through Gloucestershire, and so to Bristol,
which he reached on the 18th of the month.

[.small-break]
'''

+++[+++It is not likely that the termination of his services on this journey was at Bristol;
for, by a letter from his wife to a Friend, it would seem,
that on the 28th of eighth month, he was intending to enter Wales.
There is also a letter from himself, which, though it lacks a date,
may be referred to this period;
by an extract from it we may see how great his
exercises and labors in this district must have been,
and that they were "`not in vain in the Lord,`" his Guide, Counsellor, and Helper.
"`Our God,`" says he, "`in mercy is answering the prayers of his people,
in bringing back again them that have been driven away in the hour of temptation,
and now is seeking the lost, and restoring the scattered of the house of Israel.
Many in Wales and elsewhere return,
with brokenness of heart for what they have done against the Lord, and his servants;
and God pardons them, and restores them in his mercy.
And most of the meetings that were scattered, are in the mercy of our God established:
many of them owned their condemnation openly, for what they had done against the Lord,
to their shame and his glory, who prospers his work in his own hand,
and with his outstretched arm glorifies his name, to our comfort,
whom he has chosen to do his will, to his glory, who is worthy:
blessed be his name forever!`"--__Editor.__]

[.small-break]
'''

The account of this journey shall be closed by the following epistle, dated Cornwall,
1657, which is now for the first time printed.

[.embedded-content-document.epistle]
--

Brethren and sisters in the immortal Seed, whom the Lord has placed in and about Plymouth.
The Lord in his tender love waits to make you a royal priesthood to himself forever.
All watch in the measure of light, believing in it, that the Spirit of God +++[+++may]
arise, to keep your minds stayed upon the Lord.
There you will find the fountain of God`'s living mercy opened to you all,
refreshing your souls, and crowning his own Seed with dominion,
to keep you fruitful in his life, to praise his name forever and ever!
God Almighty keep you in unity in the immortal Seed, to serve the Lord with one consent,
to the finishing of your course with joy, to the praise of his name.
Even so be it with you, in the power of the Lord God!
Amen.

[.signed-section-signature]
W+++.+++ D.

[.postscript]
====

When the church of the living God is met together, let this to be read in his fear.

====

--
