== Chapter 12

1660+++.+++ Epistles--William Dewsbury little known in his domestic
character---He is apprehended at an inn in Warwick,
for giving thanks after supper, and imprisoned,
but shortly after liberated--Arrives in London, and is imprisoned in Newgate.

It is thought, that as the four following epistles illustrate in a beautiful manner,
the care William Dewsbury exercised over the flock,
no apology will be required for introducing them here.
They show, how he endeavored to build them up in our most holy faith,
the faith of the Gospel of Jesus Christ, which is according to godliness;
what the groundwork was,
which he sought to lay for those works of righteousness
which alone are acceptable to the Lord;
turning the minds of his readers, at the same time,
to the unfailing source of all saving help,
deliverance and consolation in the hour of inward conflict and temptation.
They are laid before the reader, under the conviction,
that they will be calculated to comfort, help,
and edify many within the borders of our own Society.
It is also possible, they may prove strengthening to many a wayfaring man,
who in all respects may not walk with us; but who nevertheless,
may be suffering the day of Jacob`'s trouble--may be the
means of encouraging him to persevere in that wrestling,
which in the end shall purchase for him a new name, even that of Israel.

The first in order,
which bears chiefly on the subject of exercising spiritual gifts in the church,
is dated the 10th of the twelfth month, 1660.

Dear Friends and brethren, called and chosen of God, to wait upon him in his light:

Every one in particular, feel the power and life of God,
exercising you in his service whatever he calls you unto.
When the Lord fills the heart of any one of you with his presence,
and his life moves in you, quench not the spirit; I am commanded to lay it upon you,
whosoever you are, from the least to the highest growth.

Dear Friends, wait to be kept in the bond of the spirit,
obedient to its motions:--to cease and stay when it moves not,
as well as to begin any exercise when it moves.
Dear and tender babes, as well as you strong men, retain the pure in every particular,
and let not anything straiten you when God moves.
And, you faithful babe, though you stammer forth a few words in the dread of the Lord,
they are accepted.
And you that are strong, serve the weak in strengthening them; and wait in wisdom,
to give place to the motion of the spirit in them,
that it may have time to bring forth what God has given.
Dear brethren, feed the lambs; and loose the tongue of the dumb,
that praises may arise in and amongst you all, to the glory of God;
that in him you may be a well-spring of life one to another, in the love of God,
in which the Lord God keep you all.

W+++.+++ D.

Dear faithful Friends in God, who have known the day when nothing has been dear to you,
not life itself, that you might enjoy the light of the countenance of God,
which he has now manifested in the everlasting covenant in Christ;
and which now constrains to stand over, and above all flattering tongues,
and all threatenings and wrath of men.
This will be more and more manifest, before this day of trial be over;
and what wrath soever the Lord allows to arise in the powers of the earth,
without he moves, do not any seek to stop it.
Let God have the glory; the wrath of man turns to his praise,
and the remainder he will restrain, while the babes in meekness and patience stand still,
and give glory to God in faithful obedience, with life to death, if the Lord call for it.
He has blessed the labor of all whom he called info the vineyard,
for whom my heart is enlarged, in the strength of the life I have received of the Father.

Oh! feel me, for I am with you, filled with joy in the Lord,
that his birth is brought forth and the captive set free,
the tongue of the dumb loosed and the living power of God raised,
to offer up living praises on the holy altar of God, in the assemblies of his saints.

Oh! lift up your heads, be glad in the strength of the Lord,
in this his day of gathering the good ripe fruit in the vineyard of the Lord.
Now do the vines abound with virtue, laden with clusters of the purest grapes full ripe,
which drop abundantly with wine, renewed in the kingdom of the Father.
Fill your cups, be not straitened in your spirits to receive of the fulness of God.
In whom I am constrained to say unto you in the light,--drink, drink abundantly;
let the thirst of the soul reach forth earnestly,
to draw more and more of the divine life, that it may comprehend you in its power.
That in its strength your hearts may be set free over all below,
and your spirit in the light of life, raised in the heavenly harmony,
to praise and glorify the name of the Lord, to the astonishment of all that know not God.
Whatever he gives, this keeps all that abide in it low in his fear,
so that neither heights nor depths, tribulation nor distress, persecution nor famine,
nakedness, peril, or sword, life nor death, things present nor things to come,
can ever separate them from faithful obedience to Christ Jesus, the Light.

And, dwell over all created enjoyments, in the unlimited power, to guide you,
whether in bonds or out of bonds, so that your words be few and savory at all times,
and minister grace to the hearers.
And be tenderly affectioned one to another in the love of God;
and in unity in him who is blessed forever!
Farewell.

Your brother,

William Dewsbury From the Tower in York, 25th of First month, 1661

The third epistle above referred to,
is thus superscribed:--"`Let this go abroad
amongst all the afflicted and wounded in spirit:`

Dear child, which cries over all the world, and beyond all the pleasure, pomp,
and vanity therein, for the enjoyment of the light and countenance of God;--fear you not,
neither be you discouraged, because of the violent assaults of the enemy,
who seeks to draw you into carnal reasonings, and thus to kindle a fire to yourself,
and causes you to walk in the light of the sparks which you
have kindled;--and this you have at the hand of the Lord,
in going from his counsel you lies down in sorrow.
Few know your great distress; but, to the Lord it is known,
and to those who have walked in the same path.

Oh, you afflicted soul,
who live in the deep sense of the working of the evil one in your mind,
and many times are ready to say,--Never was any like unto me,
nor any sorrow like unto my sorrow;--in this languishing, despairing,
mourning of your soul, all things are made bitter to you as the waters of Marah.
Thus are you driven from all comfort, as a child without a father,
a desolate widow without a husband, and as a stranger whom no eye pities,
in your apprehension: sometimes saying in your heart, in the heat of the temptation,
and of the fire you have kindled.
Oh, that I had been any creature but what I am! or, if it were the will of the Lord,
that he might shorten my days,
that I might not be any longer on earth to sin against him!
For in your own sense and feeling, walking in the sparks you have kindled,
in carnal reasonings, you discern nothing but wrath; on every side, horror, misery,
and distress; secretly crying out in your heart,--Oh,
that I were alone in the wilderness, or in a cave, or den of the earth,
that I might never see nor hear the sons of men any more, but in secret retiredness,
mourn out my days until I die.

Oh, hearken no longer to the enemy, who says,
there has none traveled where you are traveling,
neither drunk of the cup that you are drinking.
He is a liar, who goes about to destroy your precious soul.
I drank the same cup, with my faithful friends who are born of the royal seed:
every one in his measure has traveled in the same path,
and has endured the same temptations, and walked in the light of the same sparks,
and lain down in sorrow, in the sense of the same misery as you mourn under.

No longer lend an ear to the enemy, and to the thoughts of your heart.
Arise, in the light of the covenant, and stay your heart;
and the Lord God will throw down the enemy of your peace,
destroy the carnal reasonings of your mind, and put out the fire which you have kindled.
He will deliver you out of the horrible pit, and set your feet upon the Rock of Ages.
You shall tread down the enemy of your soul,
in the sensible feeling of the love of the Father,
who will manifest himself to be a father to the fatherless,
a husband to the mournful widow, and a comfort to that which mourns in you,
in the uprightness of your heart, to do the will of the living God.
So, in the power of his might, stay your heart; and tread upon all doubts, fears,
despairing thoughts, and reasonings.
Arise over them all in the light of Christ.
He will lead you into the banqueting-house of our God,
where you shall sit down with all the redeemed of my Father,
who are born of the immortal seed, and have passed through great tribulations,
and have washed our garments and made them white in the blood of the Lamb.
This shall be your portion if you diligently hearken to the counsel of the Lord,
who calls you to trust in him.
He will embrace you in the arm of his love, and you shall praise his name forever!

God Almighty, in his light and life, raise up your soul,
and establish your heart in his counsel, steadfastly to wait for his power to lead you,
in the cross, out of all unbelief,
and cause you to lie down at rest in obedience to his will:
where you shall drink the cup of the salvation of God.
Farewell!

W+++.+++ D. York Castle, the 23d of Third month, 1661

It would be gratifying to our natural feelings,
to be able to contemplate the character of such a man as William Dewsbury,
under other circumstances beside those in which we have hitherto found him.
We have been incidentally informed, that his home was at Wakefield,
that he was a married man, and was blessed with a family of children.
On each of those occasions,
when he is permitted to escape from the hands of his persecutors,
and to enjoy his liberty again,
the mind is involuntarily carried to the scenes of domestic life,
prepared to participate in that enjoyment which
all parties must feel on so happy an event.
It would be interesting to us further,
to contemplate this zealous servant and minister of Christ, like Paul the tentmaker,
employed in the pursuit of his trade, and to be able to state his success,
and how far the Lord had blessed him in these his outward affairs,
agreeably to the gracious promise made to him on his setting out in life.
But, though there is no reason to doubt the Lord`'s faithfulness,
such was the devotedness of his servant to the cause of Truth,
and the testimony of Jesus, that little or no mention is made by him of these things;
so that we are at a loss to know, how a man so totally deprived as he was,
of the opportunity of enriching himself by his own exertions in business,
was preserved from having his wife and family reduced to poverty and distress.
We are not even informed, that on his liberation from confinement at York,
he visited his home, however probable it is that such was the case.
So fully engrossed were the minds of Friends in that day,
in the pursuit of the one great object before them,
that worldly affairs appear to have had but very little place.
They felt and saw that the time was short,
and that the fashion of this would passes away, so they were without carefulness;
they that had`" wives were as though they had none,
they that wept as though they wept not, they that rejoiced as though they rejoiced not,
they that bought, as though they possessed not:--they used this world,
as not abusing it.

+++[+++A document has come to hand, since the above lines were penned,
which affords in a few words a striking illustration of
the above remarks as regards William Dewsbury.
Under date of the 10th of fourth month, of this year,
he makes a request to his correspondent, Margaret Fell,
"`a mother in Israel,`" to write to "`my tender children and family.`"
He adds, "`In the life of my God, I have given them up,
with my own life when he will call for it, a free sacrifice:
in his will it is offered up, for him to do what is good in his eyes.`"--Editor]

The following beautiful sentence, which closes one of his epistles about this period,
may also be added:--"`Watch over one another with a single eye,
building up one another in the holy faith,
opening your hearts in the free Spirit of God to them that are in need,
that you may bear the image of your heavenly Father, who relieves the hungry,
and eases the burden, and makes glad by refreshing his, in the time of need;
giving liberally and upbraiding not.
Even so be it with you, in the name of the Lord,
says your brother and companion in the Lord Jesus Christ.
Farewell!`"

In such instances of devotedness as that of
William Dewsbury and many of the early Friends,
and others the servants of Christ,
we are strongly reminded of the words of our Lord to his disciples,
"`My meat is to do the will of him that sent me, and to finish his work.`"
And there is no reason to doubt, that divine support is often, in gracious condescension,
administered under such circumstances,
so as to render the creature for the time indifferent
to the body and its various necessities.

It was about the beginning of the fourth month, 1661,
that William Dewsbury was liberated from York Castle, as has been stated,
by proclamation of Charles the II. In the sixth month we meet with him in Bedfordshire,
at Buckrin`'s Park, the residence of James Nagill,
who with Justice Crutt had been already convinced of the truth by his powerful ministry.
Between this visit and his being in London, where he was confined four months in Newgate,
we find him suffering among other Friends at Warwick,
for giving thanks after supper at an inn, which was called preaching at a conventicle.
The act of preaching under certain circumstances,
had been recently made illegal by the government.
On the present occasion, the Friends were taken before a magistrate at an inn,
who tendered them the oaths, and because for conscience sake they refused to swear,
they were sent to prison under sentence of premunire; where, shameful to relate,
some of them were detained for as long a period as ten years,
and were never brought to any further trial.
Such was the exercise of arbitrary power, under which Friends grievously,
yet patiently suffered.
It appears from Besse`'s relation of the circumstance,
to have been about the eighth month of the year, when this occurrence took place; and as,
in the same month, Dewsbury dates an epistle from Newgate prison, London,
it is evident that he obtained his liberty at Warwick,
and proceeded pretty directly on his journey to that city.
