== Chapter 13

1661+++.+++ Act against conventicles,
under which Friends suffered banishment--Epistles of encouragement--William
Dewsbury is imprisoned in York Castle--General Epistle to the Church.

How, and under what particular circumstances,
this meek and constant sufferer came to be cast into Newgate,
I have not been able to discover.
But it was in this year, that the cruel and intolerant act against conventicles,
which was framed as an instrument of persecution against Friends, first came into force.
By this act it was decreed,
that "`if any person should refuse to take an oath when by law required,
or should maintain the taking of any oath to be unlawful,
or if the persons called Quakers should meet for
religious exercise after the 24th of March,
1661, being thereof convicted, they should forfeit for the first offense, five pounds,
for the second, ten pounds, to be levied by distress; and,
for lack of possessions to allow of such distress, to be imprisoned,
for the first offense three months, for the second six months;
and upon conviction for the third offense, he or she should abjure the realm,
or otherwise the king and council might cause him or them to be
transported to any of the king`'s plantations beyond the seas.`"
These were the acts,
by which the blessed truth was attempted to be crushed in those days;
and under the mayoralty of one Richard Brown,
the leading features of whose character were pride, intolerance and cruelty,
in which he appears to have delighted; for, says Sewel,
"`he would commit cruelty with a smiling countenance,`" the
government had a fit executor in London of this new and barbarous law;
some of the consequences of which will be seen hereafter.
I apprehend, however,
that it was under a first offense of meeting for religious worship contrary to this act,
that Dewsbury with a multitude of others was cast into Newgate.

Among the epistles which he wrote while confined there,
for the edification and encouragement of the church and
of individuals under various circumstances,
is the following; addressed to his dear suffering brethren and companions in tribulation,
and in the kingdom and patience of Christ Jesus.

In him watch and pray, and believe in his name,
that you may keep the word of his patience, and in the will of God,
quietly lie down in your present sufferings for
the word of God and testimony of Jesus Christ.
He numbers the days of your sufferings; and when they are accomplished,
will plead the cause of his people,
in the day in which he will be revealed in flames of fire,
rendering vengeance upon all that know him not,
and obey not the gospel of our Lord Jesus Christ.
Then shall your innocency with all the elect be cleared, in the sight of all people,
and you shall shine as the morning stars in the power of God, to enlighten the nations,
through the brightness of the glory of God that shall rest upon you,
to the gathering of the brethren from far, and the sisters from the ends of the earth;
who shall bless the name of the Lord for you that endure in faithfulness
unto the end,--the crown of glory shall rest upon you forever.

God, in his everlasting power, keep you in the life of his Son, in unity,
to finish your testimony to his glory.
Farewell!

W+++.+++ D. Given forth in Newgate prison, London, the 13th day of the Twelfth month, 1661

P+++.+++ S. Dear lambs, keep in the unity, in the life and power of God;
and let your words be few.

We have also from his pen, during this imprisonment,
the following animated address to his suffering Friends.

Dear Friends,

All in their measure abide in God,
so as to keep your dominion in his heavenly authority during these trying days,
wherein husband is called to forsake wife, and wife husband, parents children,
and children parents, and other created enjoyments, for the testimony of the Lord.
And all you, who are or shall be called to bear your testimony,
prize the mercy of the Lord,
who has made you his chosen jewels and the first fruits among many brethren,
to fill up the measure of the sufferings that are yet behind.
In the name and power of the Lord Jesus arise, whether husband, wife, parents,
or children, in bonds or out of bonds, and take to you the sharp threshing instrument,
which is the power of God, that you may thresh all the mountains of thoughts, fears,
or unbelief,
and every desire and imagination that would draw from a peaceable rest in God.

In the name of the Lord, I lay it upon you, be valiant for your freedom;
and with the powerful instrument of God,
thresh and bruise down the mountains as chaff and dust.
And thresh the head of the old serpent, the devil, spare him not,
and be not afraid of encountering: for mighty is the Lord,
that has called you to conquer him.
So keep his head under; bruise and keep under all that would disquiet you,
or draw you from your rest.
That so, in peace in Christ you may all abide,
in a pure resignation to the will of the Father.
So will your joy flow as a river, and your dominion be in the authority of God,
over all the mountains of this world, to reign in the holy life with Christ.
In the lowly mind and holy fear, sound out the new song with triumph,
over the devil and his angels and the accuser of the brethren;
whom you will see cast down; and you shall tread upon him; and bruise him,
and all that would join with him, with the sharp threshing instrument,
the mighty power of God, which you have received in Christ the Light.

And in all things you do one for another, let love abound in the innocent life,
doing as you would be done unto in the sight of God.
And you that are servants in families, who are in sufferings, I lay it upon you,
be faithful, that the good savor of God be found among you, to the praise of the Lord.
And you that are out of bonds, in what you may, as the wisdom of God leads,
be assistant every way, bearing one another`'s burdens, to fulfill the law of Christ,
who is taking to him his great power to reign forever.

The strength even of the mighty God be with you, and lift up all your heads.
Stand in his authority and keep the word of his patience,
to finish your testimony to the praise and glory of his name, over all, blessed forever.
Of his dominion there is no end; in which you, dear lambs,
may feel and read me in the life which is hid from the world,
but known to you in the secret of God, where our joy and triumph are.
Whatever becomes of the outward man, in the will of God, farewell!--yes, farewell,
in the name of the Lord!

W+++.+++ D. Given forth in Newgate prison, the 3d day of the First month, 1661-2

With a few exceptions as regards some insulated facts,
all that is known of the last twenty-five years of the life of
William Dewsbury might be comprised in a small compass;
and this will necessarily be the case with considerable portions of it.
He was delivered from Newgate prison, in London, early in the year 1662,
and proceeded homewards, where it is probable he continued a few months.
We are informed by Besse, that persecution pursued him there also.
He says, that on the 29th of the fifth month of that year,
he was taken from his own house at Durteen, in the West Riding of Yorkshire,
and committed to York Castle, his old residence,
as a ringleader and preacher among the Quakers.

+++[+++A letter under his hand, dated York Castle, the 3d of the eighth month, states,
that there are upwards of one hundred Friends his fellow-prisoners,
that they meet daily for the purpose of waiting upon and worshipping Almighty God,
and that his presence covers their assemblies,
to their great comfort and the astonishment of their enemies.--Editor.`']

Here he was not idle, but still continued to visit the church by his epistles.
Among those which he wrote during this confinement at York,
the following is one which I should not feel
myself excused in withholding from the reader.
It is addressed "`in the flowings of the tender compassion of the Lord Jesus,
to all the mourners in Zion; and the afflicted, desolate people, who wait for his coming,
as for the morning,
and have no satisfaction in anything but in the
enjoyment of his sweet and comfortable presence.`"

Oh, Jerusalem! who are become the beautiful bride,
how did he seek you in the day of your divorcement,
when you were weeping in the wilderness, as a desolate widow,
who had not any to comfort her;
then your mournings and breakings of heart were your greatest
comfort! and the more your tears were shed for lack of him,
the greater was your satisfaction.
Oh! the weary days you had upon the earth,
because your languishing soul knew not where to meet with your Beloved,
neither did you know how to walk in the steps of the flock of your companions;
who were comforted with His presence whom your soul lacked.
Then, though you knew it not, he was near to you,
enlivening the desires that were towards his name.
And in the accepted time he sent forth whom he had ordained,
to declare unto you the glory of his love, in the light of his own life,
in which he has covered you as with a wedding garment,
and in it you appear comely in his sight, and acceptable in his presence.

And for your sake.
Oh Jerusalem! you city of the living God, what has been endured?
Flow many innocent lambs have suffered for bringing glad
tidings to you of Him whom your soul thirsted after,
is hard to be expressed.
How, in God`'s authority, have the striplings run to and fro on the earth,
willing to spend and be spent in all services of love,
to persuade you to forsake all that has entangled your mind,
and hindered you from enjoying the innocent life of your Beloved.
Your mighty men, with many of the sons and daughters of glory,
have sealed their living testimony with their blood,
in the patience and sufferings of the Lamb of God,
that you may be affected with the excellency of the glory of Him whom your soul desires.

And now, the Lord God requires of every particular son and daughter of Zion,
to watch and pray that none enter into temptation:
and all that have any stain upon their garments,
to come to the fountain which is opened for Judah and Jerusalem to wash in,
which is the heart-breaking love of God manifested in the light of his covenant,
and sealed up to the soul in the blood of Jesus.

Oh! come away, come away, out of all your thoughts, desires, doubts, and unbelief,
which would turn you aside from the enjoyment of the love of God in Christ Jesus.
Let none stand afar off because of your littleness, lameness, blindness, weakness,
or infirmities, who cannot live at peace until you be healed by the blood of the Lamb.

Arise, arise, you necessitated people, in the light of the Lord.
Give up to the drawing spirit of life in the light of Jesus Christ.
He will carry you, who cannot go, in the arms of his compassions;
he will cause the lame to walk; and you, who are sensible of your blindness,
to recover your sight; yes, he will heal you of all your infirmities,
who wait in the light,
to be ordered and guided as a little child by the
washing and sanctifying Spirit of the Lord Jesus;
who is become a husband to the desolate widow, a repairer of the breaches,
and a restorer of the desolate places; in whom the fatherless have found mercy this day,
for his name`'s sake.

Oh! what shall I say of the unspeakable love of God in Christ Jesus,
the Husband of the Bride.
Oh! you sons of the glorious day, read, and feel the unsearchable love,
and you handmaids, drink of the inexhaustible ocean, which flows over all opposition.
This is the Son of the Father`'s love, who has been "`a man of sorrows,
and acquainted with grief.`"
"`He was wounded for our transgressions,
and by his stripes are we healed;`" and this is the work of
the Lord.--Let all crowns be thrown down before him,
he alone shall have the glory, for besides him there is no other.

Therefore, let every son, daughter, and servant of God,
watch and diligently hearken to his counsel:
and whatever the natural man most inclines to, when the temptation besets you,
judge yourselves, look up to the Lord,
and resist the devil with boldness in the first assault,
and the Lord God will give you dominion over them,
and the bond of iniquity shall not have power over you.
In his holy authority, every one stand in dominion upon the head of the first man,
with all his excellency and glory;
that in the perfect freedom every particular individual may reign,
in the measure of the light,
over every thought and desire that is contrary to the will of God; that, in his will,
you may all dwell in the holy faith,
which will arm against all the fiery darts of the devil.
You shall break down Satan under your feet,
and shall overcome through the blood of the Lamb and the word of your testimony;
and continually drink of the rivers of pleasure, the presence of the Lord Jesus,
our light, life, and righteousness forever.
For he is become our Husband, and we are as the wife of his bosom,
in the delight of his glorious love.

Let the mourners in Zion rejoice, and the afflicted among the people be glad,
and fear the Lord.
And let not any who desires salvation in uprightness of heart, say,
The Lord regards me not: for whatever you hunger and thirst for in this life,
you are the heir of it,
and the Lord will satisfy your hunger with his refreshings for his name`'s sake.
And this is the portion of those that are least in their own eyes amongst the people:
the Lord has spoken it.

And all you, inhabitants of the city of the great God,
whom the Lord has prospered in your living testimony,
in what he has called unto,--blessed be the Lord God,
for you retain the sense of your nothingness in self,
and so become poor with the poorest, and weak with the weakest,
and truly make '`self of no reputation,`' but humble it to the cross,
and do not serve self but God and his people, with all his gifts and ornaments,
with which he has adorned you.
Because of the savor which you have in Christ,
the souls of the upright in heart do praise the Lord for you.
Your steadfast, valiant, unwearied travails, labors, and sufferings for the Lord,
cause the hearts of his people to be enlarged with hallelujahs
and high praises in the assemblies of his saints.
You know that your reward is with you; and woe to them that devise mischief against you,
whom the Lord has blessed.

Oh, Zion`'s children, from the least to the greatest, love the Lord Jesus Christ.
And let not a thought of the heart draw you from the light, life,
and love of the Lord Jesus.
Let the day of the resurrection arise upon you,
which will set your souls in perfect love, above all infidelity and unbelief.
Oh! drink.
to the full satisfaction of your souls, of the cup of his salvation,
for it is freely handed to all that love him, who thirst for his mercies,
and tread down the self-working spirit: so that all may be bound down in silence,
that would move in any exercise to utter words rashly before the Lord.

My dear Friends, let us comfort and console our souls together; for this is our Beloved,
we have waited for him, and now he is come with power and great glory,
to deliver his captives, and to establish them in his glorious freedom,
where the evil one shall not prevail against them;
and to marry unto himself the soul that has waited for him as for the morning.
And all, in this union, feel his power abounding in you, to lead into the daily cross,
and to stand over all that would draw from the sweet unity,
which is in the footsteps of the flock of his companions who walk in the light.
Stir up the gift of God in you, in all faithful obedience.
As your hearts are filled with the heavenly power of the Lord,
and broken in the sense of the overcomings of his life,
and moved in the strength thereof, in any exercise in your families,
or in the assemblies of his people,--quench not the Spirit of the Lord, but be obedient,
and keep within the bounds of a broken heart and a contrite spirit,
which sacrifice is acceptable in his presence.
And all feel the love of God enlarging your hearts one to another,
that the strong may bear the burdens of the weak,
and in pure love all may grow fruitful plants in the vineyard,
which God`'s right hand has planted.

And as for our little sister, scattered among the people of the nations,
whose broken cisterns have failed her; what shall we do for her?
In this day which is come upon us, she shall be spoken for,
though at present she cannot draw near, but mourns at a distance,
and cries in secret for lack of the enjoyment of the God of our salvation.
Oh! let your hearts breathe unto the Lord, that he may seal his counsel to her,
and cause her to walk in the light of the Lord,
with us whom he has raised to be the first fruits among many brethren,
to bear his glorious testimony over the heads of
the children of men and above all their wrath,
who withstand the appearance of God; who will cause them to bow before his glory,
in the day in which he will clear the innocence of his beloved people.
Neither by sword, nor spear, nor by the arm of flesh, but with the breath of his mouth,
shall he smite the hearts of them that know him not, and by the brightness of his coming,
who shall spread his fame over all nations, to gather brethren from afar,
and sisters from the ends of the earth.
Yes, the mighty shall bow to his scepter,
and the nations that are saved shall walk in his light, with us,
whom he has made as dear unto himself as the apple of his eye.
Though a woman may forget her sucking child,
yet the Lord will not forget any that fear him.
But he will lead them through all tribulations, with joy in his heavenly power,
until they have finished their course with gladness, to the glory of his name forever.

And this is the portion of the lot of your inheritance,
against whom every tongue that is lifted up shall fall in judgment,
neither shall the weapons that are formed against you prosper.
For the Lord has made you to be a burdensome stone to the nations,
and the praise of the whole earth:
and the desires of the people shall be to the Most High God,
who dwells in the midst of you; who has displayed his banner of love over you,
and has turned away the fury of his wrath from you.
You, who love the light, and bathe your soul in the ocean of his inexpressible mercies,
shall never more lack the fresh springs of life.
The Lord will keep you in safety,
and the gates of hell shall not prevail against any of the
sons and daughters who walk in the light of your city,
O Jerusalem, in whom there is no more curse:
but the throne of God and of the Lamb is in you, and his servants do serve you,
and they behold his face, and his name is written in their foreheads.
There is no night there, neither need of candle, nor light of the sun,
for the Lord God gives them light,
and they do reign forever,--as the Lord has spoken through your brother and
companion in the tribulation and kingdom of patience in the Lord Jesus.

W+++.+++ D. Given forth in York Castle, the 19th of First month, 1663
