== Chapter 14

1663+++.+++ William Dewsbury released from York--imprisoned for near
eight years in Warwick jail--Persecutions of Friends;
the banishment of many--William Dewsbury`'s consolatory
and animating addresses to the sufferers.

William Dewsbury was set at liberty from his
confinement at York early in the following year,
and the scene of his imprisonment was changed towards the close of 1663,
to the common jail at Warwick;
where he was a prisoner from that time until the early part of the year 1671,
a period of nearly eight years.
Thus were "`bonds and afflictions "`meted out to this patient
and cheerful sufferer for "`the Truth as it is in Jesus.`"
As an introduction to some epistles of sympathy and encouragement which he addressed.
during this imprisonment, to Friends under sentence of banishment,
it will be necessary now to give the reader some information relative to the
operation of that cruel and intolerant act of the government already mentioned,
which was evidently intended to crush the Society and to root out
their principles from the land.--The persecution of Friends under the
conventicle act was carried to such an extreme,
that the prisons, in London especially, were continually crowded with them,
and some hundreds were sentenced to banishment
under the stroke of that arbitrary instrument.

William Crouch, a Friend, who lived through that terrible period,
for it was so on more accounts than the one in question, writing of the year 1664-5,
gives us the following information.
"`Now the enemies and adversaries of the church, were in deep counsels and consultations,
utterly to root the Quakers out of England, by banishing them into foreign plantations:
and a law being made,
many of the magistrates and rulers were very intent on executing it;
and many Friends were taken up at our religious meetings and imprisoned,
and at their courts of assize and session were sentenced to banishment,
and put on shipboard to be sent away.
Some were actually carried to the plantations abroad; others who were put on ship-board,
were afterwards set on shore in England by the masters of the vessels.`"
"`But it was not long before the Lord was pleased to manifest his displeasure,
and to put a stop to these unnatural, unrighteous, and inhuman actions,
by those severe strokes of his hand upon the nation, in the years 1665 and 1666.`"^
footnote:[The plague which broke out in London,
and the great fire which followed in the next year--signal tokens of
the divine displeasure with the wickedness of that city.]

It appears from the same author,
that the first proceedings under this act took place at the court sessions at Hertford,
the 12th and 13th days of the month called August, 1664,
where Orlando Bridgman presided as judge.
He passed sentence of banishment against eight Friends, who were then brought to trial.
Seven of these, namely, Nicholas Lucas, Henry Feast, Henry Marshall, Francis Pryor,
John Blindell, Jeremiah Hearn, and Samuel Trahern, were brought up to London,
and on the 14th of the month called September, put on board the Ann,
a packet for Jamaica, Thomas May commander.
But two months afterwards they were set on shore, for the following among other reasons,
given under the commander`'s own hand, and duly witnessed.
"`I, seeing Providence has much crossed me hitherto,
whereby I perceive that the hand of the Lord is against me,
that I dare not proceed on my voyage to carry them, they being innocent persons,
and no crime signified against them,
worthy of banishment,`" etc.--"`for these reasons and many more, I will not carry them.`"
This was certified and given to the sufferers,
to show that they had not made their escape from the ship.

After this, three other Friends, namely, Cannawell Briton, Bartholomew Croker,
and Lewis Rogers, were put on board the ship Mary Fortune, bound for Barbadoes,
John Lloyd, master: who also repented, and on that account refusing to carry them,
set them on shore,
giving them a certificate containing the following among other reasons for his doing so.
After alluding to some causes of detention, he says, "`But now, going to depart,
their cry, and the cry of their families and friends,
are entered into the ears of the Lord God,
and he has smitten us even unto the very heart, saying,
'`Cursed is he that parts man and wife:`' and moreover, '`They that oppress his people,
his plagues shall follow them, wheresoever they go.`'
And assuredly, we do in part partake of them already;
for our consciences will in no wise let us rest, or be in quiet,
for the Lord has smitten us with a terrible fear,
so that we can in no wise proceed to carry them,`" etc.

From Besse`'s account of the sufferings of Friends we learn, that many hundreds of them,
were sentenced to drink of the same cup, but masters of ships,
conscious of the innocence of the sufferers,
generally refused to have any share in "`the, gain of oppression.`"
But three Friends, namely, Edward Brush, James Harding, and Robert Hays, were,
on the 24th of the first month, 1664, taken from Newgate and carried down to Gravesend,
and there put on board ship with little or no warning; and Hays being ill at the time,
soon died, and his corpse was brought back to London and there buried.
The other two Friends were carried to Jamaica, where, under the divine blessing,
they were prosperous; and after having remained a short time in the island,
they returned to England, Edward Brush to his wife and family,
and James Harding with a wife he had married there, and three children,
with which she had presented him at a birth.

The last instance of banishment which it is my intention to lay before the reader,
may be related as follows.
In the year 1664, fifty-five Friends were sentenced to exile,
by judgment passed at Hicks`'s Hall, by Judges Hyde and Twisden.
Thirty-seven men and eighteen women,
They were imprisoned in Newgate until the 4th of the sixth month, 1665, and at this time,
while the plague was raging in London, they were taken from prison;
and the government agents, after much search and many refusals,
having engaged with a man of infamous character to
carry them to Jamaica--the prisoners were put on board,
some of them being ill of the plague at that time.
The ship, called the Black Eagle, the master`'s name Fudge,
was seven weeks before it got to the Downs, within which time twenty-seven Friends, died,
many of whom were buried in the marshes below Gravesend.
Fudge, who had run himself largely into debt in fitting out his ship,
was arrested and cast into prison, and Peter Love was made master in his room.
In the Downs, they were detained many weeks by contrary winds,
as also between that and Plymouth.
After considerable detention, clearing away from that harbor,
the Black Eagle was captured by a Dutch privateer; they then encountered a storm,
which separated the vessels, and carried one of them to the coast of Norway,
but at length it succeeded in arriving at Holland, where all the Friends met.
The Dutch,
finding that their prisoners were not likely to be exchanged for prisoners of war,
granted certificates to such of them and sent them home.
Thus, in this instance, the mercy of an overruling Providence interposed,
to frustrate and to blast the design of these arbitrary and cruel proceedings.^
footnote:[George Fox has left us the following more
circumstantial account of the same extraordinary instance of
persecution.--"`There were great imprisonments in this +++[+++1666]
and the former years, while I was prisoner at Lancaster and Scarborough.
At London, many Friends were crowded into Newgate and other prisons,
where the sickness +++[+++the pestilence]
was, and many Friends died in prison.
Many also were banished, and several sent on ship-board by the king`'s order.
Some masters of ships would not carry them, but set them on shore again:
yet some were sent to Barbados, Jamaica, and Nevis; and the Lord blessed them there.
There was one master of a ship,
who was very wicked and cruel to Friends that were put on board of his ship:
for he kept Friends down under decks, though the sickness was amongst them,
so that many died of it.
But the Lord plagued him for his wickedness.
For he lost most of his seamen by the plague,
and lay several months crossed by contrary winds;
though other ships went out and made their voyages.
At last he came before Plymouth;
and then the governor and magistrates would not
allow him or any of his men to come ashore,
though he lacked necessaries for his voyage.
But Thomas Lower, Arthur Cotton,
John Light and some other Friends went to the ship`'s side,
and carried necessaries for Friends who were prisoners on board.
The master being thus crossed and plagued,
cursed those who had put upon him this freight,
and said he hoped he should not go far before he was taken.
And the vessel was but a little while gone out of sight of Plymouth,
when she was taken by a Dutch man-of-war, and carried into Holland.
When they came into Holland,
the States there sent the banished Friends back to England
with a letter of passport and a certificate +++[+++to show]
that they had not made an escape, but we.re sent back by them.
But, in time, the Lord`'s power wrought over this storm,
and many of our persecutors were confounded and put to shame.`"--Journal,
fol. edit. 1786. p. 384.]

The two epistles immediately following, are those referred to in a preceding paragraph.

For my dear, honorable brethren,
who are or may be sentenced to be transported to the isles beyond the sea,
for the testimony of the name of the Lord Jesus.

My dear Friends, in the suffering of the Lamb, who lives and reigns forever and ever,
and shall overcome all his enemies in the day determined,
when all his enemies shall bow under the soles
of his feet,--then shall all that oppress you,
call you the blessed of the Lord.
O my dear brethren! lift up your heads in the light and life of Jesus,
for whom you suffer; abide in his light: reign over your thoughts,
either of wife or children, or whatever would trouble your minds,
for giving up freely in this your testimony.
The Lord is with you,
and thousands shall bless the name of the Lord for your faithful testimony,
which shall sound over nations, to gather the people.

O, my dear brethren, triumph in the face of all your enemies! it shall be well with you,
wheresoever the Lord allows you to be carried; and as to your wives and children,
the Lord has said, it shall be well with them;
the blessing of the Lord shall rest upon them and with you,
to the comfort of the isles that wait for his law.
Therefore, in the peaceable power of the Lord, go on,
you chosen brethren of the suffering seed, which the Lord has blessed.
Blessed be the day, that the Lord called you by his power,
to stand faithful in what he requires of you; in which living testimony,
your memorial shall never perish, but preach to ages and generations,
to the glory of the name of our God!
Go on with gladness, for it is to bring in the seed from the ends of the earth,
that our brethren may come from far, and our sisters from the ends of the world.

O, mighty God! cover your faithful servants with your glorious power,
and cause them and their families to rejoice, in your disposing of them!
Amen.

My life in the suffering spirit go with you,
in the name of the Lord!? My dear companions in bonds salute you in the love of the Lord.
Farewell!

W+++.+++ D.Warwick common jail, 10th of the Eighth month, 1664

[.asterism]
'''

For those,
from whom the Lord has allowed or shall allow their dear and
tender husbands to be separated beyond the seas or elsewhere,
for the testimony of the Lord Jesus Christ.

Dear handmaids, whom the Lord has, counted worthy to part with your dear,
and tender husbands, for his name--assuredly,
many put their shoulders to help to bear the burden of your trials this day.
O, the tears and breakings of heart,
that are poured forth before the Lord for your dear husbands,
and you and your tender children!
You are families of many prayers,
and assuredly shall be known to be families of many mercies.
Be content with your cup, handed forth to you; and bless the name of the Lord,
that you are accounted worthy to be the first fruits.
What could the Lord do more for you, than count you worthy to suffer in this nature,
and give you such husbands, who are set as lights in the face of all people;
let it be seen that you love the Lord Jesus more than your dear husbands.
Stand over the affectionate part,
and solace your souls in the love and life of the Lord Jesus,
your eternal husband and the comforter of your earthly husbands.
He will make us all rejoice in whatever he calls us unto,
we diligently watching and judging ourselves,
and resting in the light and in the will of God.
In which, the Lord establish you,
for whom the soul of your brother breathes daily to the Lord,
to strengthen you and your dear husbands and all that love the Lord Jesus Christ;
in whom, fare you well!

W+++.+++ D. Warwick common jail, 10th of Eighth month, 1664

The following epistle belongs to this period;
and it is subjoined for the information and satisfaction of those,
who have faith to receive it as an evidence, in addition to those which have preceded,
that the flock of Christ is not left alone and comfortless in the day of trouble,
affliction, and distress.

To all faithful and suffering members in all holes, prisons, and jails,
for the word of God and testimony of Jesus Christ; with the rest of the faithful,
wherever scattered.
T

Dear brethren and sisters!
Hear the word of the Lord:--thus says the Lord,
though you now drink the cup of adversity, and eat the bread of affliction,
and are trampled upon as though you were not worthy to live upon the earth, yet,
notwithstanding all the fury of men, you are resolved in the strength of his spirit,
forever to be deprived of the sweet enjoyments of wife, husband, tender children,
parents, and outward possessions, liberty and life, +++[+++rather than]
deny the testimony of his name before the sons of men.

Oh! you dear and tender children, who love not your lives unto death this day,
that you may finish a good testimony for the glory of the Lord God;
lift up your heads in the light of his covenant, and believe in his name,
for he is near you, even the mighty God of safety.
And let not any weight or burden lie upon you;
for He will be more than a husband to wife, and more than wife to husband,
or parents to children, or children to parents; yes, He will be a husband to the widow,
and a father to the children who are deprived of
their tender parents for his name`'s sake.
He will enlarge your borders in the life of righteousness.
You that suffer in true innocency, will he refresh with the depth of his mercies.
Yes, he will guard you with the angel of his presence,
and all that devise mischief against you,
shall be confounded before the glory of his power,
with which he will keep and preserve you in the word of his patience, in safety,
in his presence.

Therefore, dear children, who drink the deepest in sufferings, think it not hard;
for it is his purpose unto you all, that have not any eye to self,
but alone seek his glory in all that you do, to make you more and more honorable,
and double his blessings upon you and yours.
For he has beheld your integrity, and is mightily moved in compassion towards you.
Therefore he is risen for your sake, to declare unto you,
that not a hair of your head shall perish,
neither shall you be detained in prisons and desolate holes
any longer than he has determined shall be for your good,
and the glory of his name.
Therefore stand faithful; resist every evil thought,
or whatever would cause you to murmur,
or desire anything but what you know will advance the glory of his name,
and the exaltation of his truth, over all that rises up against it;
in your being truly subject to the measure of light and life,
that will not let any seek pre-eminence or esteem amongst men.
Neither let self-striving nor self-serving have power in any; but in true humility,
love and meekness, watch one over another; and let the strong take the weak by the hand,
that you may all gently, in love, meekness, and holy fear,
serve one another and dread his name; that your love may be manifest one unto another,
in the simplicity of your spirits.
Then will he make his dwelling amongst you, and with you;
and his glorious presence you shall feel mightily in you and amongst you,
moving in the exercise of his spirit, to the renown of his name,
and the comfort one of another.
And he will crown you with heavenly blessings; and you shall praise his name forever,
that ho made you his jewels,
and counted you worthy to suffer for the testimony of his name.
He will go before you, through all the waters and floods of afflictions;
and will appear with you before the councils of men;
and his saving power shall compass you about in your hot and sharp afflictions,
all you who have your confidence alone in the Lord your God.

Therefore trust in his name, and cast all your care upon him.
And if any of you joyfully suffer the spoiling of your goods,
he will supply what is needful for you and yours.
And if any of you seal your testimony in the word of his patience with your blood,
he will take care of your tender wives and children, or parents,
for whom your souls have been poured forth in prayers for their good.

Therefore hear the word which is sounded unto you.
Rejoice not too much in spirits being made subject,
but throw down your crowns before him, that there be not a self-seeking,
self-serving spirit in the family of his people.
But feel the birth immortal raised up in the resurrection of life in you all,
which truly makes self of no reputation; so that all loftiness be laid low,
and all haughtiness bowed down in every one.
Thus the Lord God, may be loved, obeyed, and exalted in you all:
who is taking to him his great power, to exalt the meek upon the earth,
and to reign over all the pride of the children of men,
who are exalted above the witness in their consciences;
so that his sons may be brought from afar, and his daughters from the ends of the earth,
in the sight of all people; whom he will make to confess, in subjection to his power,
that you are the people of God, and of the righteous seed which the Lord has blessed.
Not any weapon that is formed against you shall prosper, but come to naught,
which will be hastened and certainly performed, according to what is here declared,
to your comfort and joy.
And you shall assuredly know, that the mouth of the Lord has spoken it.

The word of the Lord, before expressed, came to me in the prison-house at Warwick,
the 13th day of the first month, 1664;
which constrained me to send it to be read amongst you, dear, faithful,
and suffering people of God,
in whom I remain your brother and companion in tribulation and
kingdom of patience in the Lord Jesus Christ.

W+++.+++ D.
