== Chapter 15

Grounds on which Friends were willing to endure such sufferings--
Statement of their principles--Additional testimony from Penington.

In the last chapter we have seen,
how the malice of the grand adversary of mankind was exercised towards those,
who in that day, by the powerful efforts they were making,
threatened to shake his kingdom to its very foundation.
Friends had taken their station in the front of the battle,
in which the nation was then engaged for the security of its rights and liberties.
They, however, fought not as others did.
They wrestled not with flesh and blood, neither were the weapons they wielded carnal.
With spiritual weapons they contended against principalities and powers,
against the rulers of the darkness of this world,
and against spiritual wickedness in high places.
No instrument could have been easily constructed,
to put the constancy of this faithful band more fully to the test,
than the act against conventicles; which, to the infliction of fine and imprisonment,
now added confiscation and banishment; with the determination, if it had been possible,
to bend their steadfast wills under the despotism of the prevailing power,
and make them bow to the image of the day.
Friends saw that the stake was great, and that the trust confided to them was no less so.
The cause was the Lord`'s, not their own; and their success,
through his faithfulness who stood by and protected them,
was beyond anything that mere human energy could have accomplished.

But such of my readers, as look upon the views of Friends to have been merely sectarian,
may still be disposed to inquire what the object was,
the attainment of which the Quakers proposed to themselves,
that could possibly afford them an equivalent, either present or future,
in return for the dreadful sufferings they thus patiently and perseveringly endured.
I answer, they suffered for the testimony of a good conscience,
and many of them were Christian martyrs, in the comprehensive sense of the word.
Their cause was identified with the broad principles
and catholic spirit of Christianity itself,
and was by no means sectarian.
But to satisfy an inquiry of this kind, it will be necessary to speak more in detail,
and to define with some precision, though briefly,
those points in the religious opinions and practices of that period,
in which their consciences were so deeply involved.

They laid it down as a principle of paramount importance,
that no earthly power ought to be allowed to interfere in matters of conscience.
With this fundamental principle once established in their minds,
they hesitated not to show by an open, decided, and intrepid line of conduct,
that they were sincere in asserting to be truth,
whatever was thus solemnly and clearly impressed upon their minds as such,
however greatly it might be opposed to prevailing notions,
or at variance with human laws and long established custom; provided always,
that it did not contradict any of those doctrines or
principles which are revealed to us in the holy Scriptures;
to which writings they at all times appealed,
for a confirmation of the ground on which they acted.

Unjust laws, together with anti-christian practices,
and even those in private or common life that were vain or sinful,
were things against which they kept up a continual warfare;
refusing compliance with the former, and zealously reproving the latter,
on all occasions, and without respect of persons,
as they were led by the Spirit of Truth:
patiently enduring whatever sufferings they might be obnoxious to,
from thus exercising themselves to have a conscience
void of offense towards God and towards man.
For the greater part of forty years they persevered, through grievous persecutions,
in their resistance to man`'s usurpation of a prerogative over conscience,
to which he has no real claim; until they saw their desires in some measure answered,
by a considerable alteration in the laws,
as well as a manifest amelioration in public feeling.

With regard to their religious opinions, they may be briefly stated as follows:
they asserted it to be a doctrine clearly deducible from Scripture itself,
that unless the truths of the Gospel are by revelation
of the divine spirit sealed to the mind of man,
he must remain without a true perception of their import,
and so fail to obtain that saving knowledge of the truth,
which those writings are intended to impart.

While they asserted this as regards the holy Scriptures,
they were strenuous in affirming it as their belief, upon a foundation no less solid,
that the love of God to man is such and so universal,
that he has provided for the salvation of all his creatures,
if they on their part do not willfully reject the offers of his love in Christ Jesus.
That Christ,
being the "`true light that enlightens every one that comes into the world,`" and
by whom all things that are reprovable are made manifest,--believing in the light,
is virtually believing in Christ, and following the light which teaches temperance,
righteousness, and godliness, is following Christ,
although he may never have been heard of by the outward ear.^
footnote:[By this it is not intended to exclude
or undervalue the belief in the outward coming,
sufferings, death, resurrection, ascension, mediation or atonement of the Lord Jesus,
a sincere faith in these precious truths,
and in all that is recorded concerning him in the holy Scriptures,
being obligatory on all those who have the blessing of these invaluable records.
On this subject R. Barclay, in the fifteenth section of his fifth and sixth Propositions,
says,
{footnote-paragraph-split}
"`We do not hereby intend any ways to
lessen or derogate from the atonement and sacrifice of Jesus Christ;
but on the contrary, do magnify and exalt it.
For as we believe all those things to have been certainly transacted,
which are recorded in the holy Scriptures concerning the birth, life, miracles,
sufferings, resurrection and ascension of Christ;
so we do also believe that it is the duty of every one
to believe it to whom it pleases God to reveal the same,
and to bring to them the knowledge of it;
yes we believe it were damnable unbelief not to believe it, when so declared;
but to resist that holy Seed, which, as minded,
would lead and incline every one to believe it as it is offered unto them,
though it reveals not in every one the outward and explicit knowledge of it,
nevertheless it always assents to it ubi declaratur, where it is declared.
Nevertheless, as we firmly believe it was necessary that Christ should come,
that by his death and sufferings he might offer
up himself a sacrifice to God for our sins,
who his own self bare our sins in his own body on the tree;
so we believe that the remission of sins which any partake of,
is only in and by virtue of that most satisfactory sacrifice, and no otherwise.
For it is by the obedience of that one that the
free gift is come upon all to justification.
For we affirm, that as all men partake of the fruit of Adam`'s fall,
in that by reason of that evil seed, which through him is communicated unto them,
they are prone and inclined unto evil,
though thousands of thousands be ignorant of Adam`'s fall,
neither ever knew of the eating of the forbidden fruit;
so also many may come to feel the influence of this holy and divine seed and light,
and be turned from evil to good by it,
though they knew nothing of Christ`'s coming in the flesh,
through whose obedience and sufferings it is purchased unto them.
And as we affirm it is absolutely needful,
that those do believe the history of Christ`'s outward appearance,
whom it pleased God to bring to the knowledge of it; so we do freely confess,
that even that outward knowledge is very comfortable to such as are subject to,
and led by the inward seed and light.
For not only does the sense of Christ`'s love and sufferings tend to humble them,
but they are thereby also strengthened in their faith,
and encouraged to follow that excellent pattern which he has left us,
who suffered for us, as says the apostle Peter, 1 Pet. 2:21. leaving us an example,
that we should follow his steps:
and many times we are greatly edified and refreshed with the
gracious sayings which proceed out of his mouth.
The history then is profitable and comfortable with the mystery, and never without it;
but the mystery is and may be profitable without the
explicit and outward knowledge of the history.`"
+++[+++Editors of F. Library.]]

That, as it is this divine light which reproves the heart of all individuals for sin,
so it would work out the salvation of all, if not resisted:
nor is it less universal than the seed of sin; being the purchase of his blood,
who "`tasted death for every man.`"
Thus, all among the heathen who are saved, are accepted for Christ`'s sake,
in their obedience to that measure of light and grace, however small,
which they have severally received.

Consistently with the foregoing statement, respecting "`the true light,
that enlightens every man that comes into the
world,`" they believed it to be one with Him,
who, in the Revelation of the apostle John, is called "`the faithful and true Witness,
the beginning of the creation of God;`" and therefore,
that all who desire to experience a being created anew in Christ Jesus,
must be found walking in the light, as he is in the light,
in which alone is to be enjoyed that holy fellowship, which is with the saints in light,
and that cleansing from all sin which is by the blood of the everlasting covenant.
Thus, without defining the order in which the great work is accomplished, regeneration,
including sanctification and justification, is truly experienced.

On these general principles were based some of those particular views
which made Friends so offensive in their early days.
By these were regulated their opinions, or rather their conclusions,
on the subject of Gospel ministry; which excluded pay for preaching,
and human appointments or acquirements, as necessary for this important work.
They were strenuous in their belief,
that true Gospel ministry was a thing very different
from that which passed for it in the world.
From Him who instructed them they learned,
agreeably with the testimony of the holy Scriptures, that Gospel ministry,
can only be exercised by virtue of a gift received from Christ,
and under the immediate influence of his spirit; and that therefore,
no unregenerate person can ever really be one of his ministers.
And although multitudes intruded themselves into that sacred office,
under the sanction of prevailing opinions and established systems,
Friends bore a decided, a conscientious, and a living testimony,
against all exercise of ministerial functions, unless authorized as above.
They also deprecated in the strongest terms any system of maintenance,
whether of tithe or otherwise, which, by instituting a stipendiary ministry,
tended to pervert the Gospel of Christ, to annul his express injunction,
"`Freely you have received,
freely give,`" and to sanction the practice of trading in holy things.
This they were taught to consider as wholly unscriptural and anti-christian,
and therefore embracing within itself the principles of its own destruction; inasmuch as,
if incurring divine disapprobation, though the system might be long permitted,
the purposes of the Almighty would ultimately be fulfilled,
as his will prevails through the earth, in its utter extinction.

With opinions such as these, not lightly taken up,
but under exercises of no ordinary character,
the early Friends went forth as sheep in the midst of wolves;
and it is not too much to say of a large proportion of them,
that they were wise as serpents and harmless as doves.
When George Fox at the Lord`'s command went forth,
as a minister of the everlasting Gospel, "`the world,`" says he, "`was like a briary,
thorny wilderness.`"
And again, "`When I came, in the Lord`'s mighty power with the word of life,
into the world, the world swelled and made a noise like the raging waves of the sea.
Priests and professors, magistrates and people, were all like a sea,
when I came to proclaim the day of the Lord amongst them,
and to preach repentance to them.`"
And it was no matter of surprise that such should have been the case.
Those views,
which he and the early Friends were led to take of Christian
doctrine and the principles of individual practice,
were such, as to make them appear not only very singular,
but their zealous and public reproof of what they justly esteemed to be evil,
whether in the root or in the fruit,
made them "`seem to be opposed to existing institutions and enemies
to all sorts of men;`" but it was "`for the Lord`'s sake.`"^
footnote:[Isaac Penington]

Having a testimony given them to bear against "`a hireling
ministry,`" they found it to be their place to resist,
passively, the payment of all demands of an ecclesiastical nature;
as well as to endeavor, in the most active and zealous manner,
by their preaching and by their writings,
to open the eyes of the people to the deception by which they were beguiled,
and the bondage which enthralled them.
This they were enabled to do, through the faithful exercise of their several gifts,
in a very powerful and effectual manner;
and it was one main source of the sufferings which the early Friends had to endure.

Another branch of that ministry which was committed to them,
was that of drawing people off from a dependence upon those
forms and ceremonies so much insisted upon in religion,
and directing their attention to the substance,
to that "`ingrafted word,`" which is able to save the soul.
With this view they testified to all kinds of professors,
that "`the incorruptible seed and word of God,
that lives and abides forever,`" is that by
which the great work of regeneration is begun,
carried forward,
and perfected in the souls of men,--and only in proportion as there
is a co-operation therewith by obedience to its manifestations.
This exposed them to much obloquy, and gained them many enemies; among those,
more especially, who were either selfishly interested in, or superstitiously attached to,
what are called the ordinances of religion:--such as placed
all their hopes upon the practice of outward observances,
though in connection with a belief in Christ and a reliance upon his merits,
yet to the virtual exclusion or undervaluing of that inward work,
the being born again of the spirit, without which,
our Savior himself has expressly told us, we cannot see the kingdom of God.
In conformity with these views,
they found themselves called upon to lay aside both
water baptism and the use of the bread and wine,
called the sacrament;
feeling their minds engaged rather to press after and
by all means to hold up that spiritual baptism,
and also that union and communion with Christ as the bread of life,
which is essential and complete in itself.
"`Verily, verily, I say unto you, except you eat the flesh of the Son of man,
and drink his blood, you have no life in you.`"
"`Behold I stand at the door, and knock; if any man hear my voice, and open the door,
I will come in to him, and will sup with him, and he with me.`"

They saw to the end of all wars and fightings, and were called to renounce them,
together with the root from which they spring.
In the same way, they laid aside all oaths,
agreeably with the command of Christ and his apostle,
and in conformity with an evidence which they felt in themselves,
that the bond of an oath was no longer necessary where the truth of
the Gospel has become the governing principle of the soul.
This became the fruitful source of suffering to Friends in the early times.

Those matters which relate to their outward deportment, dress and address,
were the incessant occasion of persecution and abuse.
As these wounded the pride of men,
so they excited the contempt and malice of the corrupt nature.
The refusing to take off the hat, for instance,
excepting as a sign of worship to Almighty God,
was one of the things that in those days put to the proof the spirit,
by which professors and others were too much actuated.
For although it is in itself a small matter,
it was grievously offensive to the proud nature of man;
and on that account occasioned Friends as much reproach and persecution,
as some things of far greater moment, in which they were led to differ from other men.

The reader is now in possession of the chief particulars
wherein Friends became so obnoxious to their contemporaries;
and by means of which they drew upon themselves that large amount of suffering,
they had for so long a period to endure; this, however,
eventually purchased for the community at large, as well as for themselves,
much of the liberty they have since enjoyed.
The following short paragraphs, from a writer already quoted,
setting forth and more clearly defining the moving
principle which actuated the early Friends,
will serve to illustrate the depth of those feelings,
under which they were made willing to become as signs and wonders in their day.

He says, "`Our work in the world, is to hold forth the virtue of Him that has called us;
not to own anything in the world that God does not own.
To forget our country, our kindred, our father`'s house,
and to live like persons of another country, of another kindred, of another family,
+++[+++for Christ`'s sake.]
Not to do anything of ourselves, and which is pleasing to the old nature;
but all our words, all our conduct, yes, every thought in us is to become new.
Whatever comes from us, is to come from the new principle of life in us,
and to answer that in others; but we must not please the old nature at all,
in ourselves or in any one else.
Thus walking faithfully with God, we have a reward at present, and a crown in the end,
which does and will countervail all the reproaches and
hardships we can meet with in the world.`"

"`We are also to be witnesses for God, in the world: to be instruments in his hands,
to bring others out of death and captivity into true life and liberty.
We are to fight against the powers of darkness everywhere, as the Lord called us forth.
And this we are to do in his wisdom, according to his will, in his power,
and in his love, sweetness, and meekness.
We are not to take ways according to our own wisdom,--there must be a
strict watch set in the life lest that get up again;--nor must we
speak such words as man`'s wisdom would call wise;
nor may we go in our own will to seek any; but the Lord must go before.
Nor may we make use of our own strength, but feel his arm in our weakness.
Nor may we go forth in that love, sweetness, or meekness,
which is pleasing to the fleshly mind; but we must be true to God,
handling the sword skillfully and faithfully,
judging and cutting down the transgressor in the power and authority of God.
And when the meek, the lowly, the humble spirit is reached and raised,
then the true love, the sweetness, the tenderness, the meekness must go forth over that.
The Lord God is rough with the transgressor,
and all along the Scripture hews and judges him; and if we come forth in the same spirit,
we shall find the same leadings where we meet with the same thing.
For the Lord God will never be tender there, nor can that which comes from him,
lives in him, is led by him, be tender there, where he is not.`"
--Penington`'s Works, vol. 1. p. 91, 92.
