== Chapter 16

[.chapter-synopsis]
* 1672+++.+++ William Dewsbury discharged from Warwick jail
* Travels to Bristol
* John Roberts; Anecdote respecting him, his wife, and William Dewsbury
* Letter to George Fox from the north of England
* George Fox in Worcester jail
* Tried before Judge Hale
* His opinion of George Fox
* Extract from an epistle
* William Dewsbury visited by John Whiting
* Popish plot,
* Friends suffer under a charge of being Jesuits
* William Dewsbury confined six years at Warwick.

William Dewsbury was released from his long confinement in Warwick jail in the year 1672.
At that time,
there lay in prison throughout England and Wales
above four hundred of the people called Quakers,
many of them under sentence of premunire and banishment.
Soon after the declaration of Indulgence was published,
in consequence of an interview which George Whitehead
and other Friends had with the king in council.
When their grievously oppressed condition was laid before him,
he was induced to issue an order for their discharge,
and the remission of all pains and penalties adjudged against them.
Under this instrument, William Dewsbury was set at liberty.

During the interval of several years which elapsed between this date
and that of the epistle at the close of the last chapter,
it can hardly be expected that many incidents would
occur calculated to fill up the chasm in this history.
This protracted imprisonment furnishes one out of many instances, which show,
that the faith and constancy of Friends, though closely proved,
were sufficient to preserve the sufferer from fainting under his trials.
It should, however, be stated, that from what we may gather in two of his epistles,
his mental suffering was so great at one time while under durance at Warwick,
on account of the danger many Friends were in,
from dissensions which had arisen in the Society, that his spirit was deeply wounded,
and his bodily health impaired.
His life on this occasion appears to have been in imminent danger;
for his strength was so reduced that he was hardly able to speak,
and to all appearance for several weeks his end was approaching.
"`But,`" says he, "`God in his mercy restored strength in his appointed time.`"
We have, however, reason to conclude, notwithstanding these facts,
that he bore this imprisonment,
aggravated as it probably was beyond most other occasions,
with the same cheerful resignation as heretofore; and in proof of it we find,
that he was enabled to write various animating addresses for
the encouragement of other Friends under like suffering,
whom the rage of persecution or the floods of temptation continued to assail.
Several of these must be omitted; but I will not hesitate to add the following,
which was written at the time when his detention was drawing towards a close.
It is dated the 5th of the third mouth, 1671; and is as remarkable for its brevity,
as for its fulness.

[.embedded-content-document.epistle]
--

[.salutation]
My dear Friends,

In these trying days, be not afraid of what man can do, whose breath is in his nostrils;
but look up to the all-sufficiency of Almighty God, to stay your minds on him,
who has counted you worthy to suffer for him.
In all humility, walk faithfully before him unto the end: he is your reward,
and will give unto you a crown of Life forever.
Even so be it with you, in the name of the Lord,
is the breathing of my soul for you whom my soul loves.
And keep your meetings in the authority and life of the meek and patient Spirit,
which wears out, and overcomes all things that are not of its own nature.

[.signed-section-closing]
Read this in the fear of the Lord among Friends.

[.signed-section-signature]
W+++.+++ D.

--

During the interval of liberty which followed his deliverance from this imprisonment,
John Whiting, who was personally acquainted with him, informs us,
that his travels were extensive in several parts of England,
particularly in the west and north, of which no detailed account has been preserved.
From Bristol, the 7th of third month, 1673,
he addresses a letter to George Whitehead and Alexander Parker,
and other brethren concerned in the general meeting then about to assemble in London;
in which he excuses himself from being with them on the ground
of the Lord having disposed of him in another way.
"`I am ordered otherwise,`" says he, "`having much upon me while the door is open.`"
In a postscript he informs them,
that "`Friends are generally in a sweet state
with God in this city and where I have passed,
both to my comfort and yours in the Lord: blessed be his name forever.`"

The following circumstances, narrated by Daniel Roberts of his father, John Roberts,
in some very interesting memoirs which he has left respecting him,
ought perhaps to have been introduced at a period somewhat earlier.
Although the latter part only relates to William Dewsbury;
yet as the point of the anecdote would have been
lost by separating it from the narrative,
and as it well illustrates some particulars peculiar to the early Friends,
the reader will not object to my presenting him with the whole.

"`In the year 1665, it pleased the Lord to send two women Friends out of the north,
to Cirencester; who inquiring after such as feared God, were directed to my father,
as the likeliest person to entertain them.
They came to his house, and desired a meeting.
He granted it, and invited several of his acquaintances to sit with them.
After some time of silence, the Friends spoke a few words, which had a good effect.
The meeting being over, my father endeavored to engage them in discourse;
but they said little, only recommended him to Richard Farnsworth,
then prisoner for the testimony of truth in Banbury jail, where they were going.
Upon this recommendation, my father went shortly after to the prison,
in order to converse with Richard,
where he met with the two women who had been at his house.
The turnkey was denying them entrance, and telling them,
he had an order not to let in any of those giddy-headed people;
and therefore if they did go in, he would keep them there.
But, upon my father`'s desire, they were admitted along with him,
and conducted through several rooms to a dungeon,
where Richard Farnsworth was preaching through the grating to the people in the street.
Soon after they came in, he desisted; and after a little time of silence,
turning to them, spoke to this purpose: That Zaccheus being a man of low stature,
and having a mind to see Christ, ran before, and climbed up into a sycamore tree:
and our Savior knowing his good desires called to him, Zaccheus, come down,
this day is salvation come to your house.
Thus Zaccheus was like some in our day who are climbing up into the tree of knowledge,
thinking to find Christ there.
But the word now is, Zaccheus,
come! come down! for that which is to be known of God is manifested within.
This, with more to the same purpose, was spoken with such authority, that,
when my father came home, he told my mother, he had seen Richard Farnsworth,
who had spoken to his condition as if he had known him from his youth.
From this time, he patiently bore the cross.
Afterwards, perhaps in the year 1673,
when it pleased God to communicate to him a
portion of the knowledge of his blessed truth,
a necessity was laid upon him, one first-day morning,
to go to the public worship house in Cirencester at the time of worship,
not knowing what might be required of him there.
He went; and standing with his hat on, the priest was silent for some time;
but being asked, Why he did not go on, he answered,
He could not while that man stood with his hat on.
Upon this, some took him by the arm, and led him into the street,
staying at the door to keep him out.
But after waiting a little in stillness, he found himself clear and passed away.
As he passed the market-place, the tie of his shoe slackened;
and while he stooped down to fasten it, a man came behind him,
and struck him on the back a hard blow with a stone, '`There,
take that for Jesus Christ`'s sake.`'
He answered, '`So I do;`' not looking back to see who it was, but quietly going on his way.
A few days after, a man came and asked his forgiveness; telling him,
he was the unhappy man who gave him the blow on the back,
and he could have no rest since he had done it.

"`Not long after, three Friends came that way, who found the like concern, namely,
Robert Sylvester, Philip Grey, and Thomas Onyon.
These, standing in the steeple house with their hats on, though they said nothing,
the priest was silent: and being asked if he was not well, he answered,
he could not go forward, while those dumb dogs stood there.
Whereupon the people dragged them out: and the priest afterwards informing a justice,
that they interrupted him in divine service,
they were bound over to the quarter sessions.
My father, at their desire accompanied them to the sessions: and when they were called,
and the priest had accused them, the bench, in a rage, without asking them any questions,
ordered their court orders to be made out.
This unjust and illegal proceeding kindled my father`'s zeal; insomuch that he,
stepping forward, called to the justices, saying,
'`Are those who sit on the bench sworn to do justice?
Is there not a man among you that will do the thing that is right?`'
Whereupon John Stephens, of Lypeat, then chairman, cried out, '`Who are you, sirrah?
What is your name?`'
My father telling him his name, he said, '`I am glad I have you here: I have heard of you:
you deserve a stone doublet: there is many an honester man than you hanged.`'
'`It may be so,`' answered my father,
'`but what do you think becomes of those who hang honest men?`'
The justice replied, '`I`'ll send you to prison:
and if any insurrection or tumult be in the land,
I`'ll come and cut your throat first with my own sword; for I fear to sleep in my bed,
lest such fanatics should come and cut my throat.`'
And snatching up a ball of wax, he violently threw it at my father,
who avoided the blow by stepping aside.
Their court orders were then made out, and they were all sent to prison.

"`The same evening my +++[+++great]
uncle Solliss, who was one of the justices on the bench came to the prison,
and calling for my father, asked him,
If he was willing to have his liberty to go home to his wife and family:
'`Upon what terms, uncle?`'
said my father.

[.discourse-part]
__Justice.__--'`Upon such terms, that the jailer open the doors and let you out.`'

[.discourse-part]
__John Roberts.__--'`What! without entering into any recognizances?`'

[.discourse-part]
__Justice.__--'`Yes.`'

[.discourse-part]
__John Roberts.__--'`Then I accept of my liberty; but I admire, uncle,
how you and several others could sit upon the bench, as with your thumbs in your mouths,
when you should speak a word in behalf of the innocent.`'

[.discourse-part]
__Justice.__--'`You must learn to live under a law, cousin;
and if you will accept of your liberty till next sessions, you may have it: if not,
stay where you are.`'

[.small-break]
'''

So they parted; and on the morrow my father went home, having also the jailer`'s leave.

"`In the night, a concern came upon him with such weight,
that it made him tremble till the bed shook under him.
My mother asking the reason of it, he answered, '`The Lord requires hard things of me:
if it would please him, I had rather lay down my life,
than obey him in what he requires at my hands.`'
To which my mother replied, '`If you are fully persuaded the Lord requires it of you,
I would not have you to disobey him:
for he will require nothing of us but what he will enable us to go through:
therefore we have good cause to trust in him.`'
On which he said, '`I must go to this John Stephens, who is my great enemy,
and sent me to prison, where he said he would secure me;
and as my uncle Solliss in kindness has given me leave to come home,
I can expect no more favor from him,
if I now go and run myself into the mouth of my adversary.
But I must go, whatever I suffer.`'
He arose and prepared for his journey; but dared eat or drink nothing.
When he mounted his horse, the command of the Lord was to him, '`Remember Lot`'s wife;
look not back.`'
So on he rode very cheerfully eight or nine miles,
till he came within sight of the justice`'s house; and then he let in the reasoner,
who reasoned him out of all his courage,
presenting to his mind that his uncle Solliss and all his neighbors would say,
he had no regard for his wife and family,
thus to push himself into the hands of his greatest enemy.
This brought such a cloud over his mind, that he alighted off his horse,
and sat down upon the ground to spread his cause before the Lord.
After he had waited some time in silence, the Lord appeared and dissipated the cloud,
and his word was to him.
Go, and I will go with you, and I will give you a threshing instrument,
and you shall thresh the mountains.`'
Now he was exceedingly overcome by the love of God; and I have often heard him say,
he was filled like a vessel that needed vent; and said in his heart,
'`Your presence is enough.`'
Proceeding to the house with great satisfaction, it being pretty early in the morning,
and seeing the stable door open, he went to the groom,
and desired him to put up his horse.
While this was doing, the justice`'s son and his clerk came up, who roughly said,
'`I thought you had been in Gloucester castle.`'

[.discourse-part]
__John Roberts.__--'`So I was.`'

[.discourse-part]
__Clerk.__--'`And how came you out?`'

[.discourse-part]
__John Roberts.__--'`When you have authority to demand it, I can give you an answer.
But my business is with your master, if I may speak with him.`'

[.discourse-part]
__Cleric.__--'`You may, if you will promise to be civil.`'

[.discourse-part]
__John Roberts.__--'`If you see me uncivil, I desire you to tell me of it.`'

[.small-break]
'''

"`They went in; and my father following them, they bid him take a turn in the hall,
and they would acquaint the justice with his being there.
He was soon called in; and my father no sooner saw the justice,
but he believed the Lord had been at work upon him:
for as he behaved to him with the fierceness of a lion before,
he now appeared like a lamb, meeting him with a pleasant countenance,
and taking him by the hand, said, '`Friend John, how do you do?`'
My father answered, '`Pretty well;`' and then proceeded thus:
'`I am come in the fear and dread of heaven,
to warn you to repent of your wickedness with speed,
lest the Lord cut the thread of your life, and send you to the pit that is bottomless.
I am come to warn you with great love, whether you will hear or forbear,
and to preach the everlasting Gospel to you.`'
The justice replied, '`You are a welcome messenger to me;
that is what I have long desired to hear.`'--'`The everlasting Gospel,`' returned my father,
'`is the same that God sent his servant John to declare,
when he saw an angel fly through the midst of heaven, saying with a loud voice.
Fear God, and give glory to his name, and worship him who made heaven and earth,
and the sea, and the fountains of water.`'
The justice then caused my father to sit down by him on the couch, and said,
'`I believe your message is from God, and I receive it as such.
I am sorry I have done you wrong: I will never wrong you more.`'
After much more discourse,
he offered my father the best entertainment his house afforded;
but my father excused himself from eating or drinking with him at that time,
expressing his kind acceptance of his love; and so in much love they parted.

"`The same day, William Dewsbury had appointed a meeting at Tedbury, where my mother went.
But she was so concerned on account of my father`'s exercise,
that she could receive little benefit from the meeting.
After the meeting was ended, William Dewsbury walked to and fro in a long passage,
groaning in spirit; and by and by came up to my mother;
and though she was a stranger to him, he laid his hand upon lier head, and said, '`Woman,
your sorrow is great; I sorrow with you.`'
Then walking a little to and fro as before, he came to her again, and said,
'`Now the time is come, that those who marry must be as though they married not,
and those who have husbands as though they had none;
for the Lord calls for all to be offered up.`'
By this she saw the Lord had given him a sense of her great burden;
for she had not discovered her exercise to any.
And it gave her such ease in her mind, that she went home rejoicing in the Lord.
She no sooner got home, than she found my father returned from Lypeat,
where his message was received in such love as was far from their expectation:
the sense of which much broke them into tears, in consideration of the goodness of God,
in so eminently making way for and helping them that day.`"

The following letter addressed to George Fox, although there is no date attached to it,
belongs to this period.
In the absence of further particulars respecting the journey to which it alludes,
it is considered to be worthy of a place here,
not only on account of the information it contains, but for the evidence it affords,
of that sweet fellowship and harmony which subsisted between the two Friends,
both of them leading characters and eminent in their day.
It also conveys a very pleasing testimony to the estimation in
which George Fox was held among his brethren.

[.embedded-content-document.letter]
--

[.salutation]
Dear brother,

In the covenant of life, in Christ our Head, my soul salutes you,
and sympathizes with you in your exercise in your bonds;
with breathings to the Lord to sweeten all our ways,--
what he calls us unto,--with his living presence,
to the perfecting of his glory forever.
Amen.

Dear George Fox, I have been through many counties in the north country,
and the comfortable presence of the Lord did manifest
itself in all the assemblies of his people,
to all our comfort in him our head and life, blessed forever!
All was very peaceable; and a great resort of all sorts of people to Friends`' meetings;
and not any opposition, but all meetings separated in peace.
It would be too tedious to mention the names of those who minded their love to you,
through all the counties where I traveled:
but generally all the ancient Friends in Cumberland, Northumberland, Bishopric, +++[+++Durham,]
and Yorkshire, Derbyshire, Nottinghamshire, Leicestershire, and in this town,
+++[+++the name nowhere mentioned]
desired to have their dear love remembered to you.
The deep sense of your labor and travail is fresh upon their spirits;
which causes many prayers to be poured forth before the Lord,
if it be his good will and pleasure, to give you strength of body and liberty,
to travel among them to their great comfort as in days of old and years past.
But in the will of our God our souls rest with you, in the pleasure of our God,
in whom I remain,

[.signed-section-closing]
Your dear brother,

[.signed-section-signature]
W+++.+++ D.

--

If the foregoing letter be correctly placed as to date,
the "`bonds,`" to which it refers, and under which George Fox was then suffering,
answers to his imprisonment in Worcester jail.
In that prison he was confined nearly twelve months,
and was at length by habeas corpus brought up to London,
to await his trial in the court of King`'s Bench.
In this case again.
Sir Matthew Hale was his judge,
who had now learned how to estimate the character of such men as George Fox.
For, after the decision of the court had been given in the prisoner`'s favor,
some of his . adversaries knowing the consequences of his refusing to swear,
used their endeavors to persuade the judges to tender
to him again the oaths of allegiance and supremacy,
on the pretended ground of his being a dangerous person to be at liberty.
Judge Hale, whose character stands so preeminent, replied,
That he had indeed heard some such reports of him,
but he had also heard many more good reports;
he therefore with the other judges ordered him to be set free by proclamation.

The epistle from which the subsequent extracts are taken,
is dated the 14th of the eleventh month, 1675;
and the portion selected being very much of a general character,
is thought to be too valuable to be excluded from this volume.

[.embedded-content-document.epistle]
--

[.salutation]
Dear Friends,

Whom the Lord has visited in this his glorious day,
and plucked as brands out of the fire to wait upon him, in his light,
that his great work of regeneration may be perfected in you, to your eternal comfort,
and the glory of the name of our God forever.
My dear Friends, seeing that many are called and few chosen;
many convinced who are not converted; and many come forth with us who are not of us,
as by sad experience has been witnessed;--from
the deep sense of this working of the enemy,
I am constrained to send this epistle among you;--
knowing the kingdom of God is compared unto ten virgins,
five wise and five foolish, who all had lamps, and slumbered in the secure mind,
until they were awakened to enter in with their Lord.
Then were the foolish virgins made manifest, who, though they had lamps like the other,
yet lacking the oil, they neither did nor could enter in.
Oh! dear and tender Friends, let all dread the Lord,
who make mention of his name in the light of Christ; for this parable is to you,
unto whom the Lord has sent, to preach to you and in you the word of his kingdom.

And this is on my spirit in the word of the Lord, to you all,
convinced of the precious truth of our God,
that you may have a certain knowledge how it is with you,
and how you escaped the subtle wiles of the enemy,
which have hindered so many from the possession of the life of truth.
Examine and search your hearts, with the light of Christ,
that you may truly discern how the enemy draws into foolish conceitedness,
in the outside and formal profession of the truth, feeding upon the knowing part,
and so stops the hunger that should reach the life.
And then in an exalted mind to say, I see, know, am clothed, and lack nothing,
when such are blind, naked, miserable, and lack all things.
And this is the state of the foolish virgins, who dwell in the outward court,
and place all their confidence in the form and outside, and in the profession of truth,
and so have lost the sense of that heavenly hunger,
which must possess the life '`hid with Christ in God,`' or mourn out its days in sorrow.

Therefore, all dear Friends, watch diligently in the heart-searching light,
that you may all discern this mystery of iniquity;
that so the enemy may not prevail against you,
to turn you aside either to the right hand or to the left.
Wait upon the Lord for strength to preserve you
out of whatever he has convinced you to be evil,
and thus answer God`'s witness in the regulation of your conduct,
and in the uprightness of your hearts stand clear before the Lord,
that you are ready to do and suffer whatever he calls you to.
And when you have done all this, be you watchful in the heart-searching light,
that the enemy draw not your minds,
to place confidence in the work of righteousness you have done,
as the ground and hope of your calling in Christ; and lacking faith in him,
cause you to rest in your services: and so, come short of the hidden life,
enjoyed through faith in the light and life of Christ, our righteousness.

I beseech you, dear Friends, wait to know this great mystery.
The entrance to it is by the strait gate and all the foolish virgins,
though their lamp in the outward profession be never so glorious,
yet through pride in their attainments, never enter into this rest;
for this is the furthest that ever any come who make a profession of the truth,
and go from us, but are not of us.

You, tender Friends, that truly seek God`'s glory,
and so love his light that you are willing to give up life and all to do his
will,---when the enemy would draw you to rest in what you have done,
and so take the jewels of God, and play the harlot and deck yourselves,--dread the Lord,
and in his light you +++[+++will]
see more light.
You +++[+++will]
see, that all you have done is but your duty and your reasonable service,
which you must do, or otherwise perish eternally.
And thus,
your poor souls travel on in the footsteps of the flock of the mournful companions,
who are weeping in secret and inwardly seeking the Lord God,
to be married unto him in that hidden life, which is hid with Christ in God.
And, until you enjoy the marriage union, wait in deep humiliation, in the light,
for the Lord to create you to a lively hope in Christ Jesus, the second Adam.

--

In the year 1676, John Whiting, who lived at Nailsey, in Somersetshire,
in the course of a visit which he paid in some of the midland counties,
went to see William Dewsbury at Warwick; who, although not then a prisoner,
had permanently removed his residence from Yorkshire to that town.
I conclude that, previous to this time, his wife died,
as no mention is made of her in the narrative given by John Whiting, which is as follows:
"`William Dewsbury then dwelt in his own hired house,
with whom I had pretty much discourse, in his garden,
of many things to my great comfort and satisfaction:
for he was very free and open to me beyond what I could expect, being a young man,
and a stranger outwardly to him.
He told me some things I shall never forget.
He was an extraordinary man in many ways, and I thought,
as exact a pattern of a perfect man as I ever knew.
He gave me an epistle to carry to Friends, and coming to the door with me,
when I came away the last time, told me, at taking leave of him,
that the blessing of the Lord would be with me if I was faithful:
which was an encouragement to me, and through the Lord`'s goodness, I have found it so,
beyond my desert; blessed be his holy name forever!`"

We have already seen that the rising of the Fifth
Monarchy men was made a pretext for exercising,
or rather for augmenting the cruelties already practiced on the Friends;
and now in the year 1678, the time of the Popish plot,
they were made to suffer under the charge of being Jesuits;
a plea that was more than once resorted to, as a sanction for persecution.
On this plea, William Dewsbury was this year cast into Warwick jail,
and although the notorious Titus Oates gave a certificate
under his own hand to clear him from that odious charge,
it was in vain.
He was confined there for a period of at least six years,
and was at last set at liberty on the general proclamation of James II.,
which was dated the 18th of April, 1685.
