== Chapter 17

[.chapter-synopsis]
* 1680+++.+++ William Dewsbury loses his little granddaughter and attendant in prison, Mary Samm
* Particulars of her illness and death
* Address, suggested by the event
* Reflections on his character in reference thereto
* William Dewsbury finally discharged from prison
* Epistle.

It was during the time of his imprisonment, early in the year 1680,
that this meek and patient servant of the Lord was visited
with domestic affliction in the decease of his granddaughter,
Mary Samm, a child of twelve years and four months old, who had come from Bedfordshire,
where her parents lived, to reside with her grandfather, while prisoner in Warwick jail.
William Dewsbury had two daughters married in that county, one to John Samm;
the other to John Rush.
This we learn from George Fox, having in the year 1677, as mentioned in his Journal,
met with William Dewsbury, then on a visit to his son-in-law, Rush: on which occasion,
the former was accompanied by the latter to several meetings in that neighborhood.

The following is the account which William Dewsbury
himself gives of the last hours of his granddaughter,
Mary Samm, who dwelt with her grandfather`' William Dewsbury, at the Sergeant`'s Ward,
in Warwick jail,
where he was and is prisoner for the testimony of the Lord Jesus Christ.`"

On the 1st day of the second month, 1680,
it pleased the Lord to afflict her with a violent fever,
that brought her very low in a little time.
Great had been her exercise of spirit, as to her condition and state with God;
weeping many times when she was alone.
Her aunt, Joan Dewsbury, asked her, why, when she was well,
she walked so often alone in the garden, and was so sorrowful?
She answered, "`Dear aunt,
I am troubled in my conscience for lack of a full assurance of my eternal salvation.
For, not any one knows my exercise, but the Lord alone,
that I have gone through since I came to Warwick.
It was begun a little before I came, but it was only a little.
Since I came to Warwick, this was my exercise;--I thought I should not live long,
and that if I died, l did not know where my soul would go.
But, I hope the Lord will give me satisfaction before I die.
It is but hope; yet, for this hope my soul shall praise the name of the Lord forever.`"
She continued, at that time, praising the name of the Lord,
and making melody with joyful sounds, many times in her great affliction.

The next day, some Friends being in the room with her, she was much opened,
in declaring the dealings of the Lord with her in time past.
"`I have been twice in my days,`" said she, "`nigh unto death,
but the Lord in his tender mercy prolonged my life,
that I might seek his face in the light of Christ,
and come to be acquainted with him before I go hence.`"
Adding, "`If this distemper do not abate, I must die;
but my soul shall go to eternal joy,--eternal and
everlasting life and peace with my God forever!
Oh! praises, praises to your majesty,
O my God! who help me to go through with patience what I am to endure.`"
After some time, she said, "`Friends, we must all go hence, one after another,
and they that live the longest, know and endure the greatest sorrow.
Therefore, O Lord, if it be your will, take me to yourself,
that my soul may rest in peace with you.`"--"`Oh! praises, praises,
be to your holy name forever, in your will being done with me, to take me to yourself,
where I shall be in heavenly joy, yes, in heavenly joy forever and forevermore.`"

The day following she desired all to go forth of the room, for she wished to be alone.
And after a considerable time, when we heard her groan upon her sick bed,
her mother and grandfather went to her, when she said to them,
"`I have now received full satisfaction of my eternal salvation; it is now done,
it is now done!
And, dear mother, when you or any of my sisters die,
I desire the Lord may go along with you.
For I am very willing to die, that the Lord may glorify his name this day,
in his will being done with me.`"--Many times would she be praying to the Lord,
day and night; "`O Lord,
lay no more upon me than you give me strength to bear and go through with patience;
that your will may be done,
that your will may be done;`" (many times repeated.) "`Oh! help me, help me,
O my God! that I may praise your holy name forever.`"

Thus she continued, very often praising the name of the Lord with joyful sounds,
and singing high praises to his holy name forever and forevermore.
And being much spent with lifting up her voice in high praises to God,
through fervency of spirit, and her body being very weak,
her grandfather went into the room, and desired her to be as still as she possibly could,
and keep her mind inward and stayed upon the Lord,
and see if she could have a little rest and sleep.
She answered, "`Dear grandfather, I shall die,
and I cannot but praise the name of the Lord while I have a being.
I do not know what to do to praise his name enough while I live.
But while there is life, there is hope;
but I do believe it is better for me to die than live.`"
Thus she continued speaking of the goodness of the Lord from day to day,
which caused many tears to flow from the eyes of those who heard her.
Her grandfather coming to her, asked her how she did;
she replied to him and to her mother,--"`I have had no rest this night nor to day.
I did not know but I should have died this night, and very hardly I got through it:
but I shall die today, and a grave shall be made, and my body put into a hole;
and my soul shall go to heavenly joy, yes,
to heavenly joy and everlasting peace forevermore!`"
Then she said, "`Dear grandfather, I do believe you will not stay long behind me,
when I am gone.`"
He answered, "`Dear granddaughter,
I shall come as fast as the Lord orders my way.`"--Then she praised
the name of the Lord with high praises and joyful sounds for a season;
and then desired her mother to let her be taken up for a little time, saying,
"`It may be it will give me some ease.`"
They sent for her grandfather, who said to her, "`If this be your last day,
and whereon you are to die, it is not safe for you to be taken forth of your bed.
Dear Mary, you shall have all attendance that is convenient; as,
to set you up in your bed and to lay you down again; but to take you up,
we are not willing.`"
She replied, "`Well, grandfather, what you see best for me I am willing to have so.`"
When her mother and aunt set her up in her bed,
she said it did refresh her and gave her some ease,
and as they were ordering what was to be done about her bed, she said,
"`Oh! what a deal of ado is here in ordering a bed for one who is upon her death bed.`"
Her aunt said, "`Mary, do you think you are upon your death bed?`"
She answered, "`Yes, yes, I am upon my death bed; I shall die today,
and I am very willing to die, because I know it is better for me to die than live.`"
Her aunt replied, "`I do believe it is better for you to die than live.`"
She said, "`Yes, it is well for me to die.`"

Her mother then said to her, "`Mary,
are you well satisfied in leaving me and your sisters,
and coming to Warwick to your grandfather?`"
She answered, "`Yes, mother, I am very well satisfied:
for I saw my way was made clear for coming to Warwick.
My grandfather and I have lived so comfortably together,
that I am fully satisfied as to my coming to him.
I have been very well, as to any matter of sickness, until this sickness came upon me.
Dear mother, I would have you remember my love to my dear sisters, relations and friends;
and now I have nothing to do, I have nothing to do.`"
A friend answered, "`Nothing, Mary, but to die.`"

She desired her mother to give her a little drink, "`Then,`" said she,
"`I will see if I can have a little rest and sleep before I die.`"
When the drink came, she took a little,
and desired her mother to give her a little to wash her mouth.
After which she asked what time of day it was.
It being the latter part of the day, her grandfather said, "`The chimes are going four.`"
She said, "`I thought it had been more;
I will see if I can have a little rest and sleep before I die.`"
And so she lay still, and had sweet rest and sleep.
Then she awoke without any complaint; and in a quiet peaceable,
frame of spirit laid down her head in peace, when the clock struck the fifth hour,
on the 9th day of the second month, 1680.

[.embedded-content-document.paper]
--

"`We whose names are underwritten,
were eye and ear witnesses of what is before expressed, as near as could be taken,
and it does not vary much from what she declared, as to the substance,
though many more sweet and comfortable expressions passed from her, but for brevity sake,
we who stood by her when she drew her last breath, are willing to publish this only.

[.signed-section-signature]
William Dewsbury, her grandfather.

[.signed-section-signature]
Mary Samm, her mother.

[.signed-section-signature]
Joan Dewsbury, her aunt.

[.signed-section-signature]
Hannah Whitehead, a friend.

--

The preceding account had prefixed to it by William Dewsbury, the following address,
from which it will not be unprofitable to subjoin an extract:

[.embedded-content-document.address]
--

[.blurb]
=== An exhortation to all people, to prize their time, in making their calling and election sure, before they go hence and be no more.

From the deep sense of your own nothingness and your need of the help of Christ Jesus,
the true Light and blessed Savior, to whom you cry and pray continually,
that he would perfect his great work of regeneration,
in leading you in the footsteps of the tribulated companions,
who go weeping and seeking the Lord their God, asking the way to Zion,
with their faces there;--no more let your eyes slumber in peace,
nor your eyelids have rest, until you be assured that the Lord is your God:
that he has blotted out your sins, and done away your iniquities for his name`'s sake,
and has accepted of you in his new and everlasting covenant of mercy in Christ Jesus.
So, you that were afar off in your rebellious nature, of which you are now ashamed,
through true repentance and obedience to the light, are made nigh by the blood of Christ;
which gives you full assurance of your eternal salvation,
and purges your consciences from dead works to serve the living God.
And whoever you are,
who come to witness this blessed work of regeneration wrought in your hearts,
as before written, being created to a lively hope in Christ Jesus,
(mark,) you are to watch and pray, that in the exercise and improvement of this hope,
you may receive strength to purify yourselves as he is pure.
Thus, all who are worshippers of the Father, come to worship him in spirit and in truth,
for the Father seeks such to worship him.
And these are they whom he perfects forever through the sanctification of his spirit.
So is this Scripture fulfilled in you, '`He that does truth comes to the light,
that his deeds may be made manifest that they are wrought in God.`' John 3:21.
And these are his children who walk in the light,
and have their fellowship with the Father of light in Christ Jesus, their blessed Savior,
and one with another in his humble, meek, pure, and blessed nature;
and so become his chosen jewels and citizens of Zion,
who walk in the light of the New Jerusalem, as it is written in the Scriptures of truth,
'`The nations of them that are saved shall walk in the light thereof.`'

--

It might not be difficult to draw an affecting picture of the
forlorn condition of William Dewsbury at this time,
now rendered more so by the decease of his little granddaughter,
his prison companion and attendant.
Nor is it natural or probable,
that she should have been thus removed while
filling an office at once so cheering and useful,
without a sensible mind like his feeling some pangs of suffering.
At the same time,
such had long been the habitual piety and resignation of spirit in this real Christian,
that we are of necessity bound to contemplate him in his true character.
We must view him, yielding to this as to other painful dispensations and privations,
which in the ordering of unerring wisdom had through life been meted to him,
with that holy submission which breathes the language of "`Not my will but yours be
done;`" and rejoicing in the manifest foretaste of that glorious state,
which one so young was thus called to inherit.
We may conclude that our friend had now attained
to the age of somewhat beyond threescore years,
and that his infirmities were such as to render his own
further tarriance here extremely uncertain.
He would therefore himself be looking towards a future state,
with feelings in unison with those of the apostle, when he told the Ephesians,
he had a desire to depart and to be with Christ,
which he assured them was far better than to remain:
and William Dewsbury with such feelings would regard
the early flight of his grandchild as an event,
to her transcendently happy.

We are informed by himself, that during the nineteen years of his confinement at Warwick,
in four of them only was he a close prisoner: and I think we have reason for concluding,
that the latter period of his imprisonment there,
was rendered less irksome by that extension of liberty which such information implies.
Still it is painful to contemplate the circumstance,
excepting as regards his patient endurance of the wrongs thus heaped upon him,
that his bonds were continued to so late a period of his life,
and that the king`'s proclamation, by which he was finally enlarged,
came when the full enjoyment of his liberty was no longer in his power;
being then not only advanced in years,
but greatly disabled through a series of imprisonments and sufferings for so many years.
In the year 1686, about eighteen months before he died,
towards the conclusion of one of his epistles to Friends,
we find the following affecting paragraph.

[.embedded-content-document.epistle]
--

My dear Friends, through the sharp persecutions that were endured in the heat of the day,
and many long imprisonments; being nineteen years a prisoner in this town of Warwick,
and four of them kept a close prisoner,
it has pleased God to permit my health to be impaired,
so that many times I am forced to rest two or three times,
in going to the meeting in the town, not being of ability to travel as in years past.
I do, in the love of God, visit you with this epistle,
desiring it may be carefully read in the fear of the Lord,
in the assemblies of his people,
that peace and unity may be among you in the name of our Lord Jesus Christ.
Amen.

--

The following "`General epistle to Friends,
from this ancient servant of Christ,`" may here be introduced.

[.embedded-content-document.epistle]
--

[.salutation]
My dear Friends and brethren,

Who are called out of the world,
and plucked as brands out of the fire, by the heavenly power of God,
who has convinced you of his everlasting truth, in the light of Jesus Christ:
as you have received the truth in some measure, watch and pray,
and believe in the name of Christ;
that you may feel his power in the heavenly inspiration of his blessed spirit,
to lay judgment to the line and righteousness to the plummet,
that all that is not obedient to the light of Christ, may be kept down,
and buried in the heavenly baptism under the sentence of death;
as it was and is with all the children of God,
who have received the sentence of death in ourselves,
that we may have no confidence in ourselves, but trust alone in the living God.
This will keep you all in the sweet, seasoned, savory spirit of life, in all your words,
trading, and dealings among the children of men.
Then will you, who retain the savor of the heavenly life in the blessed truth,
be manifest and known to all people as the salt of the earth;
so that every one according to your measure may be felt, upon all occasions,
continually flowing forth, in the savory spirit of life,
to the comfort of your own families, and the city of God,
who over all is blessed forever!

And, my dear Friends, I desire all to be watchful,
that not any come short of what is required of them,
both rulers of families and parents of children.
While you have a day to be with them, call your families together to wait upon the Lord,
in the fear of his name.
Certainly, the Lord will answer the end of your endeavors,
by causing the savory life to flow through you, to season your servants and children;
that the church of God may be in every particular family and habitation of his people.

Great is the concern upon my spirit for the children of
all who profess the blessed truth of God,
that all parents may stand in their places,
and bring up their children in the fear of the Lord.
And that while in their minority and tender years, and under their tuition,
they may not be too indulgent to them or allow the spirit of the world to rule in them,
or let them have their own wills,
and do those things which are not according to the truth of God; and connive at,
instead of reproving their children, and crossing the spirit of the world in them,
and causing them to be content with such things as are according to the truth of our God.
For lack of this carefulness in parents,
the spirit of this world is strengthened in children,
when it should be kept down by the heavenly authority
and power that the Lord has given to parents,
to rule over them.
And all walk in the wisdom of God, with moderation in all things,
clothed in modest apparel, and laying by all superfluity,
so that your good examples may reach the witness of God in your children.
But for lack of this care in some parents,
and being too indulgent and full of lenity to their children, they grow rude, stubborn,
self-willed and disobedient to parents,
to the wounding of their hearts who have thus neglected their duty.

Therefore I desire and beseech you,
that you slight not the opportunity God gives you in this weighty concern,
to be in all things good examples to all who live with you, both children and servants,
that by your godly conversation and heavenly exhortations,
you may raise up the witness for God in them; exercising the power God has given you,
to keep down the evil nature, while they live with you.

When your children grow up, take them to meetings; and keep your eyes over them,
that they behave themselves soberly according to your exhortations.
Encourage them in well-doing;
so will the Lord bless your sweet and heavenly behavior in your families;
and servants will bless God that ever it was their lot to come into your families,
in that their spirits were sweetly seasoned with the truth,
by your heavenly care over them.
Your children, also, will magnify the name of the Lord for your blessed care,
heavenly instructions, and godly endeavors every way, for their good in this world,
and their eternal happiness in the world to come.
This will crown the hoary heads of parents with joy,
to see their endeavors sanctified to their children,
and their offspring made the offspring and children of God.
Blessed be his name forever, who hears the prayers of his people,
who are exercised daily in the heavenly inspiration of his holy Spirit,
to call upon his holy name, not only for enemies but for a blessing upon their families,
and for all that love the truth of our God.
These are the families that are a sweet savor unto the Lord,
whom he guards with the angel of his presence,
and will make them manifest and known to all people, that they are his chosen jewels,
whom he will preserve in the day when he will pour
forth his vengeance upon the heathen that know him not,
and upon the families that call not upon his name.

And if any of these children of heavenly-minded parents,
when removed from under their tuition, for lack of watchfulness,
grow careless and turn their backs on the blessed truth of God,
and trample all the care and good counsel of their parents under their feet,
to satisfy their own wills in the pride and vanity of this evil world,
to the wounding of the hearts of their careful and loving parents,
they will be clear of their blood; while they +++[+++such children]
shall reap the fruits of their doings except they repent.

And all you, young and tender people, with others that come among Friends,
through the education of your careful parents, masters or mistresses,
I have a concern upon my spirit to write to you,
that you do not rest in an outward profession of the truth, received by education,
but watch unto the heart-searching light of Christ in you,
which will let you see that you must be regenerated and born again,
and so be made real and faithful Friends,
by the heavenly inspiration of the powerful spirit of God in you.
And if you be carefully upon your watch,
you will see judgment upon all in you that is not obedient to the light of Christ,
in whose light you will see more light,
even your great necessity for the enjoyment of the life that is hid with Christ in God.
This will cause you to pray without ceasing,
that the Lord would enable you to loathe and abhor the pride, pomp,
and pleasure of this evil world, and give you assurance of God`'s love to your souls.
And until you enjoy it, in all places of your retirement,
you will pour forth your supplications with tears to the Lord,
as the blessed and heavenly travelers and companions did and do,
who could not find the kingdom of God in outward observations,
though none were more careful in observing what
is made known to them to be the will of God.
But the kingdom of God consists not in outward observations, therefore,
in the light press forward, according to your spiritual hunger and thirst,
in true poverty of spirit, weeping and seeking the Lord your God, asking the way to Zion,
with your faces thitherward, that you may enjoy salvation for walls and bulwarks.

Oh, you blessed children of the Lord! lift up your heads,
and stay your minds upon the Lord, waiting patiently upon him.
He will turn your sorrows into everlasting rejoicing,
and seal you up with his holy Spirit of promise, in the marriage union with himself;
and will give you assurance of your eternal salvation.
Then will you certainly know the kingdom of God to be within you,
and the anointing to teach you,
which will enable you to delight in taking up the cross daily,
in true obedience to the light of Christ,
all the days you have a being among the children of men.
Then will you, in the name of the Lord, trample upon all the pride, pomp, pleasures,
and vanity of this evil world; to the great comfort of your dear and careful parents,
masters and mistresses, whose tuition you were under in your tender years,
and of all that walk in the precious truth of our God, who is over all blessed forever.
Amen.

And all dear Friends and brethren, seeing the Lord,
who turns the hearts of men as the rivers of waters,
and in his lovingkindness so orders those in authority,
that the prison doors are opened once more in our day,
and we enjoy peace and quietness according to his blessed will;
praises be to his holy name forever.
I have a concern upon my spirit that all Friends and
brethren have their hearts affected as mine is,
to live in the sense of the mercies of the Lord.
And, for the time to come,
every one endeavor to prevent the enemy making disunion among Friends and brethren,
as of late years he has been doing, by public opposition in some, and others,
not patiently keeping in their places, have also separated.
The difference being so public,
has caused many a sorrowful heart and given cause to the enemies of God to rejoice.
This has been a greater exercise and trouble to me,
than all the sharp persecutions and imprisonments I have endured for
the word of God and testimony of our Lord Jesus Christ.

Therefore in the love of God, I beseech and entreat you all,
who have been or are concerned in what is before written,
to let the love of God so abound,
that in it all labor for peace and unity in Christ the Prince of peace,
who in love laid down his life for us, when we were enemies:
and in our age he has called many of his children to
give up their lives in the heat of the day,
weeks, months, and years, to gather enemies to the knowledge of God and union with him.
Therefore wait for the heavenly wisdom, to bear one with another; that if any,
who are conscientious to God, and blameless in their conduct,
having a concern upon their spirits to edify the people,
do declare the truth in public assemblies, I beseech you in the love of God,
that not any through disaffection show at least any public opposition.
But rather, if there be occasion for the party to be spoken to, speak to him in private.
So will the enemy be prevented from casting stumbling
blocks in the way of tender-spirited people,
who come in love to be comforted in the meeting.
And in so doing it will cause love and unity to abound among Friends,
and in the love of God all will be restored and
brought into unity again who have been scattered;
and to meet all together in the everlasting truth, to feel the healer of breaches,
who is the restorer of the desolate, exalted to reign in his kingdom in all your hearts;
and to offer up a peace-offering, in passing by all offenses, that have caused disunion:
and to bind you all up in the unity of the spirit and bond of everlasting peace.
And meet all together, you who profess God`'s blessed truth, to praise his holy name,
all as one and one as all, while we are in these mortal bodies,
and forever when time here shall be no more.
Even so be it with you all, says my soul, in the name of the Lord,
to whom are my prayers, that all may be accomplished as above written.
And, until it be so with you,
I shall remain your exercised brother in tribulation and in
the kingdom and patience of our Lord Jesus Christ.

[.signed-section-signature]
William Dewsbury

[.postscript]
====

Given forth in the movings of the peaceable spirit and word of reconciliation,
in the Lord Jesus Christ; to whom are my prayers,
that all who are convinced may wait to be made of the number of the slain of the Lord,
and conformable to Christ in his death.
That they may witness his quickening power to raise them up in the resurrection of life,
to enter into the gates of Zion, to dwell in the city of New Jerusalem,
where peace is within her gates,
and quietness among all that have their habitation therein,
having salvation for walls and bulwarks; and such are blessed of the Lord,
preserved by him, to the honor of his name forever, Amen.

====

[.signed-section-signature]
W+++.+++ D.

[.signed-section-context-close]
Warwick, 4ih of Tenth month, 1686

--
