== Chapter 18

[.chapter-synopsis]
* 1688+++.+++ William Dewsbury visits London
* Attends Gracechurch street meeting
* Sermon and Prayer.

Notwithstanding William Dewsbury`'s age, declining state of health, and great infirmities,
feeling himself a little strengthened,
and having an ardent desire once more to visit
the great city and to labor among Friends there,
he had faith to venture from home,
arriving in London in the third month of the year 1688.
He also entertained the hope of attending the Yearly Meeting of Friends,
which was to be held there on the 4th of the following month.
Soon after his arrival in the metropolis, namely, on the 6th of the third month,
he attended a meeting for worship at Gracechurch street,
where he preached the following powerful and impressive Sermon,
the only one of his which has been preserved.
It is given in Sewel`'s History, 8vo. vol.
ii. p. 456.

[.centered]
=== You Must Be Born Again

My Friends, Except you be regenerated and born again,
you cannot inherit the kingdom of God.
This is the word of the Lord God to all people this day.
This lies not in airy profession, and in vain imagination,
and whatsoever else it is that you deck yourselves withal:
you must every particular man and woman be born again,
else you cannot enter into the kingdom of heaven.
This was the doctrine of Christ,
in that prepared body wherein he appeared in the world and preached to Nicodemus.
This is a standing doctrine to this moment of time,
and will be so while any man breathes upon the earth; there is no other way,
no other gate to enter into life, but by this great work of regeneration.
Now, to enforce people to come to this great work,
and to set forward from earth to heaven--all being driven out
of paradise by the cherubim set with a flaming sword,
there is no returning to that blessed life,
but by the loss of that life that did grieve the Spirit of God,
and which caused man to be driven out.
There is no other way of return again, but by this new birth.
As you are all driven and forced out of paradise,
and the flaming sword and the cherubims are set to keep the way of the tree of life,
so you must return into the favor of God again, by the light of Christ.
You have line upon line, precept upon precept, here a little, and there a little,
to direct your minds to the light of Christ Jesus.
As the first Adam was made a living soul, so the second Adam is a quickening spirit.
This know for certain, no man or woman can be quickened,
and raised up into the life of the second Adam,
until the life of the first Adam be taken away.

So now, let every one of you deal plainly with your own hearts, +++[+++and inquire]
how you came to be slain to the life of the first Adam,
in which life there was a working of the mystery of iniquity in every part of man.
One cries '`Lo, here is Christ;`' another, '`Lo,
there is Christ;`' and every one is following his own
imagination about the letter of the Scripture;
this is still but the vain spirit of man, running and striving to recover himself;
and this is the cause there is so much profession of God,
and so little of his nature appearing among the sons and daughters of men.
Now, all that come to be regenerated, must come to the light of Christ;
there is no other way to it.
He will search your hearts, and try your reins, and set your sins in order before you,
and trace out the iniquities that compass you about.
You must see yourselves a lost people, a sinful people,
and so come to feel the weight of your sins upon your consciences;
there is no other way to come to life.
You will never complain of sin till you are burdened with it,
till you have a trumpet sounding in your ears, to awaken you,
that you may arise from the dead, that Christ may give you light.
There is no other way, dear people: you must bring your deeds to the light of Christ,
and abide the sentence of condemnation.
If you save your lives, you lose them; if you will lose your lives for Christ`'s sake,
there is no danger of your eternal life.
John the Baptist, Christ`'s forerunner declared,
'`I indeed baptize you with water unto repentance,
but he that comes after me is mightier than I,
the latchet of whose shoes I am not worthy to unloose,
he shall baptize you with the Holy Ghost and with fire; whose fan is in his hand,
and he will thoroughly purge his floor, and will gather his wheat into his garner,
but the chaff he will burn with unquenchable fire.`'
Are you the better for reading the Scriptures, if you know not this fiery baptism,
which all must know who are regenerated?
Deceive not yourselves: Christ will appear in flaming fire,
and take vengeance on all them that know not God,
and that obey not the Gospel of our Lord Jesus Christ.

I stand here as a witness of the Lord of life this day:
there is no way for people to come to salvation,
but they must know Christ revealed in their hearts.
What is he doing, but rendering vengeance upon the carnal mind, self-pleasing,
and all inordinate affections;--he comes with vengeance to take away your life;
he will baptize you with the Holy Ghost, and with fire.
If you know not this, you are not a true Christian,
you will never look death in the face with joy, nor go down to the grave with triumph.
If you live at home in the body, and flee for your life,
and will not be willing to lose your life for Christ, if you are called to it;
and if you will not have Christ to wash you, some for shyness,
and some for self-love will refuse this--if Christ does not wash you,
you have no part in him.
You must come to Christ, to purify you in the fiery furnace:
the day of the Lord shall burn as an oven, as the prophet speaks.
This is a dreadful day, a day of vengeance, the day of the Lord Jesus Christ,
who redeems his people from their sins.
Zion is redeemed with judgment, and established with righteousness.
Do not make the way to heaven easier in your minds and imaginations than indeed it is;
and think it not sufficient to live in an outward observance of the ways of God.
If your own wills be alive, and your corruptions remain unmortified,
the judgment of God will be your portion: therefore, in the Lord`'s name,
come along with me; I am come to declare what I have heard and seen of the Father.
Come and examine your conscience: have you brought your deeds to the light?
Then you have received condemnation upon yourself, and your haughtiness is bowed down,
and laid low, and you see yourself a poor miserable wretch, before the eternal God.
Whatsoever you know of the mind of God, have you reformed your ways?
Come along with me, and tell me what is the ground of your faith and your confidence.
Is it your obedience and qualifications?
Because your obedience is right, and your qualifications right,
what use do you make of them?
Read the book of conscience: have you no ground for your faith?
You have put on the reformed faith, and lives an unreformed life:
search and try yourself, man or woman.
Do you watch over yourself, and keep in a sense of your dissolution,
notwithstanding all your qualifications and partial reformation?
Do you strive to enter in at the strait gate, and the narrow way?
Here is the lost sheep you seek, the life of your will, the life of the first Adam.
The justice of God will not allow you to make a savior of your duties and qualifications;
and to take God`'s jewels and deck yourself with them;
you cannot be saved without the righteousness of God in Christ Jesus.
What says your conscience,
are you brought to this change of your mind and of your conduct?
Are you all willing to part with your sins, with your pride and haughtiness?
are you willing to part with your vile affections?
This is the work of God`'s grace upon you.
Do you place your confidence in your duties and qualifications,
and take God`'s jewels and ornaments and deck yourself with them?
You took my jewels, says the Lord, and did play the harlot.
If you return to the Lord, and humble yourself, and get through this difficulty,
you will be happy forever.
This judgment of God, this flaming sword that turns every way,
will keep you from returning to sin, and bring you to Christ,
and cut you off from all hope of salvation but by him,
and make you to see the absolute need of a Savior,
and that your life is hid with Christ in God.

It is God`'s infinite goodness to men, that he will hide pride from them,
and humble them under his mighty hand.
This is the condition of poor creatures who are slain by the hands of the Most High.
How may I know when I am slain and baptized, and come to have sincerity?
They that have this baptism, enter into the heavenly life;
if you love the light of Christ Jesus, it will be thus with you.
God will make short work in the earth.
He will set your sins in order before you, and make you watchful unto prayer,
and lead you to holiness of life and conduct, and make you abhor yourself,
and despise all the pomps and pleasures and vanities of this world.
When he has adorned you with his graces, then watch,
and in the light of Christ you shall see light, and that all you have done, and can do,
is but your duty.
All this you ought to do; you are God`'s creature,
and all this will not justify you in order to your eternal salvation,
for these services you owe unto God.
If you diligently wait you shall see more light;
then the sword that proceeds out of the mouth of Christ,
who is called '`the Word of God,`' will cut you off from
all hopes of salvation from anything you have done,
from any of your qualifications, from anything that you can do;
so that you will be a hopeless soul, nothing in your own sense and apprehension.
The power of the first Adam must die before him, and you will cry out, '`I am a dead,
lost, and undone creature: yet there is a life hid with Christ in God for me,
but I can never have it, till I be slain into the will of God,
and become as a little child, stripped of all my own excellency that I have attained.
I must come to a sense of my own misery, and fall down at the foot of God.
When I am become as a little child,
humbled and slain as to my own will and confidence in my own righteousness,
I will not then question but I shall live a holy life,
but I will give all that life I had,
for that life which is hid with Christ in God:`' O! there are none come so far,
that ever miss of eternal life.
All shuffling people, that would have salvation by Christ,
and yet will not let him exercise his heavenly power, his princely,
glorious power to baptize them into his death, come short of salvation:
but all those who yield themselves up to Christ to be redeemed through judgment,
and are become as little children, these are in a happy state.
You know that our Lord Jesus Christ took a little child in his arms, and said,
'`Whosoever becomes not as a little child, cannot enter into the kingdom of heaven.
You must all become as little children, and depend upon the mercy and free grace of God;
you must all come to a holy resignation of your wills to God`'s disposal.
If you come to Christ as little children, and depend upon him,
you cannot miss of salvation; it is entailed upon such souls as hear the voice of Christ,
'`they that hear the voice of the Son of God shall live.`'

I stand here as a witness for the God of heaven,
I never heard the voice of Christ as his follower, until I was slain and baptized,
and lay as a little child under his heavenly chastisement.
As soon as ever my soul was brought to this, O! then,
the dreadful judgment was taken away, and the book of life was opened unto me,
and the Lord spoke comfortably to me, '`I have loved you with an everlasting love.`'
I was made a Christian through a day of vengeance, and of burning as an oven;
and the haughtiness and pride of man in me was brought low.
Now in this conformity to Christ`'s death, people may die into life,
and blessed are the dead that die in the Lord, for they rest from their labors,
and their works do follow them.
Away with all your own wills, and your pride, and haughtiness;
and your hypocrisy and deceit, and all dependency upon any qualifications of your own:
you must come to have your life separated from you, else you will all perish.
To those that will die with Christ, and be willing to die for him,
he is revealed as a Savior.
He was before us in the days of his flesh, and complied with his Father`'s will;
he was nailed to the cross.
The Son of God, when he was come to the depth of his sufferings, cried out, '`My God,
my God, why have you forsaken me!`' This was for your sake, and my sake,
and every man`'s and woman`'s sake that do believe in him;
he drank the cup which his Father gave him to drink.
If it was done thus to the green tree, what shall be done unto the dry?
He went before us, and when he comes again, he will take us to himself,
and take us from the filth of sin, that we may be made new creatures.

Except we be born again, we cannot enter into the kingdom of God,
and there is no becoming new creatures, until we be slain to the old man.
You must be slain to your pride, and haughtiness, and the corruption of your own will,
and all selfishness: you must have God to burn it up in you.
The Holy Ghost will destroy, and burn up nothing in you,
but that which will bring an eternal fire upon your soul.

Show me, you whom my soul loves, where is the path of life,
the footsteps of the flock of your companions?
Why should I be as one that goes aside?
Every one that lives at home in the bosom of self, take this with you,
though you profess the truth, and live in an outward conformity thereunto,
yet if you secretly indulge your corrupt wills, and live a flesh-pleasing life,
and consult with flesh and blood, and are not rent off from your lusts,
you cannot enjoy the Lord of life: '`while I am at home in the body,
I am absent from the Lord.`'

The body of sin is a loadstone to draw you from the life of God,
and from glorying in the cross of Christ: this is flesh and blood,
and flesh and blood cannot inherit the kingdom of God.
For the Lord`'s sake, for your soul`'s sake, and for the sake of your eternal happiness,
put not off this work, but pursue it, and it will be perfected.
See how Christ is revealed in you by the Holy Ghost, and with fire.
God will redeem you by the spirit of judgment and burning:
it is not ranging abroad in your minds +++[+++will do]
but you must '`know that Christ is in you except you be reprobates.`'
If he has set your eyes and hearts upon himself,
and made you to water your couch with your tears; if he has broken your sleep,
so as you have cried out, '`I shall be damned,
and never come to salvation;`' this will be your cry, it was once my cry;
O let not your eyes slumber, nor your eyelids take any rest,
till you be sure the Lord is your God.
If you find these qualifications, you are on your way,
otherwise you will be like a deceitful bow, and never abide in judgment.
If you reject the counsel of God against yourselves,
and refuse to be crucified with Christ, and to be baptized with his baptism,
you will never have life; but by his baptism,
and through the heavenly operation of his Spirit, if you have faith in Christ`'s name,
you shall be married to him in everlasting righteousness.
Salvation shall be brought to us, and eternal life be bestowed upon us;
even that life which is hid with Christ in God he will give to
every poor mournful soul that submits to his blessed will,
and believes in the Lord Jesus Christ.
This is not a faith of our own making, nor a garment of our own embroidery,
but that which the Lord has given to us.
O happy man or woman, that obtain this gift of God!
O! who will not lose their lives for this everlasting life?
Who will not die for this eternal life?
Now, the matter lies in the death of your own wills: when you have done the will of God,
then watch that your own wills be slain, and that cursed self take not the jewels of God,
and his bracelets and ornaments, and bestow them upon self,
and paint and deck cursed self: and take not the members of Christ,
and make them the members of a harlot.
If you be dead to your own wills, you are risen with Christ,
and shall receive a resurrection to eternal life.
Crucify self, and set the world at naught, and trample upon it, and all the things of it,
and count them as dross and dung in comparison of Christ,
whom the Father has revealed to be our life, in the days of our sorrow and mourning,
in the day of our calamity, in the day when we cried, '`Our hope is lost!`'

Thus it has been with the holiest people on earth.
It is not by works of righteousness of your own that you can be saved.
Christ comes to cut all these down, that you may be ingrafted into him,
and justified by his grace.
Do not make this matter of talk, and say, I have heard this and that;
but look into your own hearts, and see what heavenly workings are there;
what there is of the power of the Lord Jesus, that has made you to loathe this world,
and the inordinate love of the creature,
that you may enjoy all these things as if you enjoyed them not.
When we are slain and crucified to this world, we cannot but say, '`My life is in Christ.`'
Then we come to ascribe nothing to ourselves, and all to Christ.
Here is a blessed harmony, broken hearts, melted spirits, and yet joyful souls;
poor creatures, who were mourning, and sighing,
and crying before the Lord in retired places, and yet rejoicing in Christ Jesus.
'`I am risen with Christ.`'
I said, '`My hope is cut off, I will lie down in your will, O God;
do what you will with me, it is in your sovereign pleasure and free gift,
whether you give me life or deny it to me.`'
There must be a resignation of ourselves to the will of God;
it was so with the Lord Jesus and it is so with every true saint of God.
You must be humbled as little children, before the judgment be taken away,
and the lovingkindness of God sealed upon your souls.
If you seek this work of God, you will find it; if you seek it upon your beds,
in all your labors and concernments, in all your stations and relations;
if you press after the new birth, you must use this world as though you used it not,
and live a married life as if you were unmarried,
for the fashion of this world passes away.
This is not rantism.

But, let me tell you, a new world comes by regeneration.
A man is not lifted up in his own mind, but laid low in his own eyes:
he waits for the wisdom of God to govern him, and he is as a steward of the grace of God,
to give to them that stand in need.
When a man is regenerated and born again, he is as contented with bread and water,
as with all the enjoyments of this world:--What is the matter?
His own will is gone,
and put under his feet with whatsoever gives life to his vain desires and affections.
There is a harmony of all within, a man praising God, and blessing his holy name.
No entanglements shall draw away the heart from serving God and seeking his glory;
and if God shall call the husband from the wife, or the wife from the husband,
for the glory of his name, there is no complaining and crying out,
but giving them up and praising and blessing God,
when they are called to such an exercise.
If they are not called to that,
then they set their hearts to glorify God in their several places and stations;
they have full content in a blessed resignation.
Here their wills are slain, but they praise God they have no desire but, '`Lord,
your will be done!`' always praising God,
always having the fear and the glory of God before their eyes.
All the mischief is hatched in pleasing men`'s own wills this
is the counsel of every heart that Christ does not govern.
Will you live as the Quakers?
Then you must live contemptibly, the mistress and the maid are '`hail fellows well met.`'
Every one must walk in humility, and live in acquaintance with the God of heaven.
She that is wrought upon by the same Spirit,
must with all diligence behave herself as becomes a servant of the Lord.
Here is now a new world, and the fashions of the old world are gone; pride, haughtiness,
crossness, and trampling upon one another, are all gone,
all slain through the operation of Christ.

What remains now,--Christ is in me, and we are all one in him.
Christ laid down his life for you and me; now he reigns in me,
and he has prepared my body to die for the truth,
as his prepared body was laid down for my sin.
It is a foolish profession, to make profession of Christ, and yet live in covetousness,
profaneness, sensuality, and the like.
They that are come to this heavenly birth,
seek the things that are above--you can do no other: make the tree good,
and the fruit will be good.
You must be ingrafted into the vine of God`'s righteousness:
O slight not the day of your visitation.
What was it to me to read of any being born again, until I was slain,
and knew the heavenly baptism of Christ Jesus?
Until I saw the flaming sword ready to slay me in every way, in every turning?
The light of Christ convinced me of sin, and his righteousness justified me,
and those works were abominable to me, which hindered my soul`'s passage to Christ.
Christ Jesus in marrying my soul to himself, did work effectually in me.
There is the testimony of Christ in me,
that he has sealed up my soul to the day of my redemption.
Here is a certain passage, and a certain way which never any miss of,
who lose their lives for Christ.
If you be not ready and willing to lose your lives for Christ, you shall never come here:
the gate is strait, and the way is narrow,
none come here but those that die into a heavenly oneness with Christ.
O Friends! let us empty ourselves, that Christ may fill us;
let us be nothing in our own eyes, that we may be all in him, and receive of his fulness.

I commend you to God`'s witness, that you may remember what has been spoken among you:
but consider, if you do not hearken to it, it will follow you,
and be a plague to you to all eternity.
If you will not yield up yourselves to Christ, to this day that burns like an oven,
this fire you must dwell with when out of the body,
there will be no quenching of this fire forever.
If you be so wise as to resign yourselves up to Christ,
and come to him as little children, this will not hinder your earthly concerns.
Though the world may account you a fool, yet you have that part of heavenly wisdom,
to do what you do as unto God.
You carry yourself to your wife, as in the sight of God,
that she may be sanctified to you, and you to her;
and you carry yourself becomingly to your children and servants,
and you will abound in grace, and in every good work,
which will be for your eternal welfare.

O, I beseech you, people, for the Lord`'s sake, wait for the light of Christ to guide you:
learn of him to be meek and lowly, then happy are you; for he dwells with the humble,
but he beholds the proud afar off.
This new birth, which is a true work, a sincere and heavenly work will make you +++[+++happy]
forever.
O make room for Christ in your hearts, or else he is never likely to dwell with you;
he loves to dwell with the poor and humble and contrite spirit, but abhors the proud;
he will empty your souls, that he may fill them.

I commend you to God.
I have been long held in durance under great weakness; and I was restless,
until I could come up to this great city of London,
to preach the everlasting Gospel among you.
Pray, every one of you, turn inward; let not these words, passing through a mean vessel,
be as a bare empty discourse of truth to you, which you only hear;
and take no further care of your salvation.
Take heed of despising the light that shines in the midst of you:
press forward in the heavenly work, in the power of Christ Jesus,
even through judgment into death,
and then he will give you eternal life.. The Lord confirm this,
that it may rest upon your hearts, that you may be dead to the things of the world.
We are not come to Mount Sinai, that genders to bondage, but '`we are come to Mount Zion,
the city of the living God, the heavenly Jerusalem,
and to an innumerable company of angels,
to the general assembly and church of the first born which are written in heaven,
and to God the judge of all, and to the spirits of just men made perfect,
and to Jesus the Mediator of the new covenant, and to the blood of sprinkling,
that speaks better things than that of Abel.`'
This is the inheritance of the redeemed of the Most High; blessed be the name of the Lord!
Let us rest in hope, till he bring us to humility and lowliness of mind,
that he may clothe us with heavenly glory, according to his promise,
'`I will beautify my house with glory,`' says the Lord.
This is the portion of a poor people, who cast themselves down before the Lord,
that he may lift them up and be all in all to them,
in whose blessed presence they shall have joy,
and rivers of pleasures at his right hand forevermore!

[.offset]
+++[+++The following is the prayer, which he offered up after the preceding testimony.+++]+++

Blessed and glorious God! Your presence and power is with your people everywhere,
and you are stretching forth your almighty arm, for the salvation of your chosen ones.
You are influencing their souls with your grace and Spirit in their solemn assemblies.
We desire to extol and magnify your great and excellent
name for all your mercies and blessings.
We pray you, bow down your heavenly ear,
and hearken to the cries and supplications of your people,
who are breathing forth the desire of their souls unto you.
You are a God hearing prayers; supply their needs and establish their spirits,
and uphold them with your free Spirit.
Crown all your chosen ones with your lovingkindness and tender mercy;
rend the cloud of darkness that hangs over us and take away the veil: bow the heavens,
and visit us with your salvation, and reveal the mysteries of your Truth unto us,
and in all our ways let us acknowledge you, and do you lead us in the way everlasting.
Righteous God of love! while we live on earth, let our citizenship be in heaven,
where Christ our Mediator sits at your right hand; let us follow his example,
who was holy, harmless, and undefiled, that we may sit in heavenly places with him.
Be a sun and shield to us in our earthly pilgrimage.
Whom have we in heaven, but you; and there is none on earth that we desire besides you.
Let us walk before you in sincerity and truth,
and do you conduct us in the way of truth and righteousness, by your blessed Spirit.
Blessed be your name for the light of your saving truth, that has shined in our minds;
and the light of your countenance that has been lifted up upon us in our meetings.
You have furnished a table for your people as in the days of old:
we cannot but admire your great love and condescension towards us,
and extol and bless your holy name for your abounding
mercies and the riches of your goodness to us.
We desire to give you honor and renown,
and praise and thanksgiving for your renewed
mercies and spiritual blessings in Christ Jesus,
for whom we bless you, and in whom we desire to be found,
not having our own righteousness.
To Him, with yourself, and your holy eternal Spirit, be glory forever.
Amen!
