== Appendix

[.chapter-subtitle--blurb]
Letters of William Dewsbury

[.letter-heading]
To King Charles the Second

[.salutation]
Oh, King!

Hear the word of the Lord God,
which came unto me about the sixth hour in the
morning of the 20th day of the third month,
1661.
Thus says the Lord through his servant.

Oh! fear and dread the name of the eternal God, who has created and preserved you,
by his mighty power, and saved you in the hollow of his hand,
in the day of your great distress, when he corrected your family and all the nation,
that they might walk humbly before him.
And those who did humble themselves before him, his presence appeared with them;
but when they departed from the lowliness of his spirit, and promised fair things,
and did not perform in the uprightness of their hearts, according to their words,
though they were never so invincible for strength,
and clothed with the policy and wisdom of this world, the Lord has,
and will break them down by the arm of his mighty power,
and he catches them in their own craft, and overthrows them in their own devices,
and not any can deliver themselves out of his mighty hand.
He breaks them as the potsherds of the earth,
and makes their names to rot and perish among men,
and stink in the nostrils of the upright in heart.
Thus he sets up, to try if man will give him the glory of his works;
and when he kicks against his Maker, he breaks him down in his wrath, and overthrows
him in his fierce displeasure.
And this is the work of the mighty God, who has preserved you in safety,
while destruction and calamity were on every side;
that now you have seen a cloud of witnesses before your eyes.

You are set on the throne, wherein he is trying and proving you, that you may,
by what you have seen, dread his name, and wait in his counsel, the light of his spirit,
which is his law in your heart and conscience, that lets you see you are but dust.
And if you watch unto it, and wait upon him in it,
you will see the secret evil of your heart.
If you look up to him in the light of his spirit,
and in the uprightness of your heart judge the evil in you,
and in it wait on him to be guided in true lowliness and humility of spirit,
to seek alone his glory, and nothing for yourself,
but wait upon him to be an instrument in his hand,
that he may govern and order you in all his ways;
then will he enlighten your understanding, and seal unto you his secret counsel,
and give you to see through all that profess his name and know him not,
and what his true worship is.
And he will let you see what is idolatry,
and what is the worship in which his presence shall
accompany all who are found faithful therein,
and which he will defend with his power against all opposers.

None shall prosper who devise mischief against them
that are faithful to him in this his worship;
this is declared to you to be pure obedience to his spirit,
which cleanses the heart and purifies the conscience.
And this is his worship he has determined in his unchangeable
and heavenly decree to establish in the earth,
and over all nations it shall stand.
He shall scatter all as dust, who seek to oppress his people,
and resist the rising of his glory,
and you shall certainly know the mouth of the Lord of hosts has spoken it.

And if you turn your mind within, to his counsel in you,
and in diligent watchfulness incline your ear to his pure spirit,
that calls for righteousness in your heart and conscience,
and be obedient with boldness to walk in the strait way of the daily cross,
and deny the evil, and answer his requirings, which he makes known to you;
then will he guard you with the power of his heavenly and dreadful presence,
and will make you a terror to evil doers,
that a liar or an unclean person shall not be found in your house,
nor any worker of iniquity shall be able to stand before you;
he will clothe you with wisdom,
and you shall be able to judge all causes that are brought before you in righteousness.
Then will you put away all sports, plays, pastimes, drunkenness, uncleanness,
and whatever grieves his spirit, out of your sight, and cleanse the land of it,
through your faithful walking with God,
who has made you a son of affliction from your youth,
that you might learn to fear his name.
If you do these things he will make you a terror to all nations round about,
that devise mischief against you;
the angel of his presence will pitch his tent about you, you standing in his counsel,
and giving liberty to his sons and daughters, as he moves them by his spirit,
to walk in his service.

The mighty God requires of you,
that you do not lay a bond upon the spirits of his people in matters of worship,
to force all to uniformity.
You have seen before your eyes, that the kings and princes of this world,
who have sought so to do, have brought much innocent blood upon them,
who have been seeking by their outward power to establish Zion with blood,
and Jerusalem with iniquity.
Thus have his people been slain from day to day,
in the nations that have been building Babel,
in whom is found the blood of the saints and martyrs of Jesus,
and all that are slain upon the earth; for whose sake he is now risen,
to plead the cause of those that fear him, and walk humbly before him.

And this he requires of you, in all things to mind his law in your heart,
to do unto others as you would be done unto,
if you were in their places and they in yours;
and let mercy be found in your hands to all people,
as you have found mercy at the hands of the Lord, yes to your enemies; and,
in what you may, live in peace with all men.
And in all your undertakings seek not yourself;
let the glory of God be the object of your mind,
and wait to feel his hand leading you in what you do.
If you stand in his counsel, to do as he requires of you,
to mind your place and to keep the people in peace, and punish sin and wickedness,
and give free liberty for the Lord,
by his spirit to rule in the consciences of his people,
as he orders them to meet in his fear, and witness forth his mind where he leads them,
without restraint; and no more to be given like lambs to the slaughter,
and driven to prison like sheep to the fold,
but to have free liberty in their peaceable lives to serve
their God;--then will he raise his name in your father`'s house,
and make you a nursing father unto his people,
and you shall partake of the blessings with them that fear him,
and all the world shall be amazed to hear of his dreadful
appearance for his people that obey his spirit in this nation,
which shall convince both Jew and Gentile,
that the mighty God is risen to manifest his power to
them that fear him in these northern countries.
And the day is very near, wherein it shall be no more said,
"`The Lord lives that brought up the children of Israel out of the land of Egypt;
but the Lord lives that brought up and led the seed of
the house of Israel out of the north country.`"

Oh king! let his goodness constrain you, and all your family,
to humble yourselves before him.
What could he have done for you more than he has done?
Has he not been your relief in your greatest straits?
Let his goodness engage you to answer what he requires of you;
then will he make you one of the number of his elect and chosen,
and your days will be full of gladness,
and your soul shall live forever in the kingdom of
glory with all the redeemed who are led by his spirit.
But, if you reject his counsel, his law in your heart,
and will not regard his spirit in your inward parts,
but hearken to the counsel of your own heart,
and the wit and policy of the spirit of this world, and so set up yourself on high,
and rob God of his glory;--and give up his people, as they have been,
to be pulled out of their peaceable meetings, and haled to and fro,
as sheep that are slaying all the day long, in tumults, distresses, afflictions,
stonings, stripes, prisons, and death;--and set up proud covetous men, who know not God,
to be teachers in the land, which draw people into idolatry,
worshipping they know not what; so, the blind leading the blind,
they both fall into great wickedness, which grieves the spirit of God,
and liberty is given to plays, sports, and pastimes, which draw people into drunkenness,
uncleanness, and great abomination.

If these things be not reformed by you,
but allowed to go on as they have been;--this will be your
portion:--as he has multiplied on you his mercies to the
astonishment of the people and nations round about,
so will he stretch out the arm of his power against you, and get himself the glory,
in his mighty judgments which shall be revealed in the
great and terrible day of his fierce wrath,
wherein he will cleanse the land of all that rob him of his glory,
and reject his counsel, the light of his spirit in their consciences.
You shall certainly know the mouth of the Lord has spoken it through his servant, who,
in faithfulness to your soul, oh king! has not hid the counsel of God from you,
but greatly desires your eternal welfare,
and in patience waits that righteousness may be established in the earth,
who is known by name, William Dewsbury,
prisoner at the date hereof in the common jail at York,
for the word of God and the testimony of Jesus Christ.

[.small-break]
'''

P+++.+++ S. Before this could be sent unto you with a private and safe hand,
I was set at liberty, with some other of my brethren, by your late proclamation,
which we own as an act of justice.
Now, if you let bonds be no more laid upon the consciences of the people of God,
but that, as before written, they may serve their God in the liberty of his spirit,
you will then find a hiding-place in this terrible day of vengeance,
which will be manifest in England, to the astonishment of all the world.
For there is no man that lives contrary to God but shall roar
under the heavy judgments of the wrath of the Lamb of God,
whom the Father will reveal in flames, rendering vengeance upon all that know him not,
and obey not the Gospel of Jesus Christ.
For God will make England as the garden of Eden, and wickedness shall not reign therein;
then shall it be a blessing; to ail nations; and you shall know assuredly,
that he is faithful and true who has revealed these things to his servant,
that desires your everlasting felicity and happiness in your obedience to Christ Jesus,
the Light who enlightens every man that comes into the world;
and now is the Father revealing him,
to judge every one according to the deeds done in the body.

[.signed-section-signature]
W+++.+++ D.

[.blurb]
=== A general Epistle given forth from the Spirit of the Lord, to be read in his fear in the assemblies of Friends, gathered in these northern countries, and in all countries and islands wherever the people of the Lord are scattered over the face of the earth.

[.salutation]
Dear Friends,

Called in the light of the Lord to stand living witnesses for
him upon the earth among the children of men:
oh! the love of the Lord which is in my heart to you, that when I was nigh unto death,
to the sight of all who saw me, as to the outward man, and scarcely able to speak,
I was constrained to give forth the substance of what is now sent among you,
for a perfect discovery of your conditions.
Seeing that many are called but few chosen, and many convinced who are not converted;
therefore are these lines written, that you may truly know whether you be born again,
and redeemed from the earth, yes or no.

And in order thereunto,
let every man and woman search their hearts with the light of the Lord,
and it will truly manifest whether you be born again, and so feed upon the tree of life,
or whether you rest in outward formal conformity to the Truth,
having the heart in the earth, for that spirit will turn against Truth, as it has done.
Some others are drawn to delight their hearts in the gifts, parts, and knowledge,
which the Lord has given them, more than in the Lord, the fountain from which they come;
and so abuse the gift, and feed upon the fruit of the tree of knowledge which puffs up,
and makes man wise in his own eyes, and to say in his heart,--"`I am wise and rich,
and see, and lack nothing,`" when they are blind, miserable, naked, and lack all things.
Whatever any profess, as to the service of God, who are in this condition,
they have an end to themselves in what they do, which grieves the Spirit of the Lord.
When men and women in a discursive spirit take upon them to declare the Truth,
when the Lord neither calls them nor speaks by them,
the children born of the royal seed are burdened; for such have turned against the Truth,
and the children born of it, whom the Lord will ease in the day determined,
when all mouths shall be closed in silence, but those which are opened by him,
and not any voice be heard, but his own Spirit speaking in and through his own children,
born of him, who alone seek his glory, and not anything for themselves,
which must be denied.

Therefore, seeing the enemy`'s wiles are great and many, let all dread the Lord;
and those who have been led astray, wait in the heart-searching light,
to see where the mystery of iniquity led them forth, and return to the light,
to judge down proud exalted self which has turned against the Truth,
and to bring into true poverty and abhorring of self; waiting at the throne of grace,
for the Lord to raise you up in the resurrection which raised up Jesus from the dead.
In this life, contentious self is buried in death, and the true unity is known,
where the Lord alone is exalted in purity, joy, love, and peace in all his,
from the least to the highest growth, and all flesh is abased before him,
who is worthy of all obedience, praise, and glory forever, Amen.

And all dear Friends and brethren, love the light,
and rejoice in the judgments of the Lord, to have subtle self buried in death,
that whatsoever gifts of the Spirit, the Lord gives unto you,
if the enemy tempts you ever so strongly to puff you up in a self-priding spirit,
in what you have received of the Lord; yet his fear may be minded by you,
which keeps you in a true sense of your nothingness and emptiness in yourselves,
which causes you to wait in true self-denial, for the daily assistance,
and renewal of your strength in the resurrection of life in the Lord Jesus;
and the more he manifests his power with you,
the more empty and nothing you appear in your own eyes.
Thus is the true birth known, which makes self of no reputation,
that the Lord may be exalted in his unlimited power,
in manifesting himself in the poverty, emptiness,
and nothingness of his people who are born of him, that no flesh may glory before him;
but that all in truth say,--"`The Lord does all in me, and through me,
and the Lord shall have the glory.
I will sit in the dust at his feet to serve him and his people, in what I may,
while I have a being among the sons of men,
through whom we are raised up to sit in the heavenly places in Christ Jesus,
to the glory of his name forever.`"
This is the state of the true disciples of Christ who
cannot feed on the fruit of the tree of knowledge:
although in your journey and travels, you see the tree of knowledge to be good,
where it stands in its place, yet the fruit is not good to eat and feed upon,
because knowledge puffs up, but grace makes humble.

Therefore, dear brethren and sisters, who cannot live in any enjoyment,
but as you enjoy the life and presence of God,
from whom every good and perfect gift comes; although some of you be, in your own eyes,
the meanest among the people of the Lord; yes, sometimes your trials are so great,
that you are ready to account yourselves unworthy to be
numbered among the people of the Lord,
and yet you dare not disobey him, neither can you live without his presence;--O,
dear children of God! lift up your heads over
all temptations and accusations of the enemy;
for your groans and cries are entered into the ears of the Lord,
who in his love and mercies does constrain me to proclaim his
tender compassion to all who are truly poor in your spirits.
O! blessed are you among the children of men, for yours is the kingdom of God.
Therefore be not weary of waiting upon the Lord,
for in his own time he will turn your sorrows into joy,
and give to you the spirit of praises for the spirit of heaviness,
as he has done to many who have endured the like temptations, trials, and sufferings,
under which you wait this day for deliverance; and the Lord will be the same to you.
Be of good comfort; for as the serpent was lifted up in the wilderness,
so is the Son of Man lifted up in the light and covenant of life, to heal your wounds,
and save you from sin, and to give you victory over the enemy in all his appearances.
Through faith in the name of Christ, making war in righteousness,
and fighting the good fight in keeping the faith,
you will be made more than conquerors through his love shed abroad in your hearts,
which will cause you to speak of his goodness, and praise his name for all his mercies.

And all dear children of the Lord,
who witness in measure that you are truly baptized into his death,
and so are made partakers of his resurrection which is the life,
who worship him according to his own will,
and so are truly accepted of him,--watch and pray,
that you may be guided in the power of his spirit in all your ways.
Be careful that none be hasty to utter words before the Lord,
neither allow any sighs or groans, or anything to be heard to pass through you,
but as you have the seal of the spirit of the Lord, that he requires it of you.
This I am commanded to lay as a charge upon you,
that so all flesh may be truly silent before the Lord, and no voice be heard,
but the living spirit of the Lord speaking in his people, which,
you that wait in the fear of the Lord, and mind his leadings, may truly know.
As it is written, so do his children witness,--"`He that has my word,`" says the Lord,
"`let him speak my word faithfully;
is not my word like a fire and a hammer that breaks the rock in pieces?`"

Therefore, all mind to feel the word of the Lord speaking in you,
that the pure life of the spirit may be tasted and felt, in whatsoever you be exercised,
that so you may be fully assured it is not your own work, as man speaking of God,
but the Lord alone uttering his own voice in the power of his own spirit,
in what you are exercised in, whether it be to pray in sighs, or groans, or in words,
or to speak in exhortation or praises.
You are not to quench the spirit of the Lord in this his day,
in which he is come and does appear, giving various gifts unto his people,
as he did among his disciples who waited at Jerusalem
for the pouring forth of his spirit from on high.
But they that were strangers to the work of the spirit,
could not taste the life that spoke in them, but said, they were mad,
and full of new wine, etc.; but the Lord justified them,
it being the work of his own spirit; and although he gave unto them various gifts,
yet all in the unity of himself, in which they sacrificed,
in returning to the Lord his own with advantage, to the glory of his great name,
as his children do this day.

Blessed be his name forever, that out of the mouths of babes his praise is declared,
in their measures, as it is with those of higher growth in the Lord.
Thus the faithful laborers reap the fruit for which they travail,
that all the people of the Lord may be filled with his spirit,
and in the exercise and leadings thereof, become a body of living ministers,
and a family of prophets; the strong leading the weak by the hand,
and in tender love building up one another in their most holy faith,
which gives the victory over the world, to reign in the heavenly dominion.
This causes the children of the Most High, in the authority of the Lord,
to say to the greatest persecutors,--"`O man! do what you have power to do,
the God whom we serve is able to deliver us out of your hand; but if he will not,
we are resolved in his strength to allow what he permits man to do.`"
This is the holy resolution of all that are born again,
and cannot hide your heads in the time of persecution,
because you are born of the royal seed, and have overcome the beggarly, cowardly,
earthly spirit, through the blood of the Lamb, and the word of your testimony,
and no more love your lives unto death.

And all dear chosen vessels of the Lord,
seeing he has manifested his grace so largely to you,
be obedient with all diligence in walking answerably to his love and mercy received;
that as living witnesses for God,
you may shine forth in the beauty of holiness in all your ways.
And be careful in keeping your meetings at the time appointed,
every one endeavoring to be the first at the meeting,
that none give way to a careless spirit, as some have done,
and come to meetings when others have been a considerable time together,
and so become a burden to the diligent and obedient servants of the Lord.
Thus, the meetings are not so profitable to your comfort,
as when you meet diligently at the time,
waiting in the fear of the Lord to feel his sweet presence,
which will keep you awake in the life of his own spirit, to the glory of his name,
and the comfort of one another,
which will cause you to prize the opportunities God gives to you,
not knowing how soon you may be deprived of them.
And be tender one over another, and watch over one another with a pure single eye,
and every one see the beam cast out of your own eye,
before you go to spy a mote in others.
If any brother or sister offend, you that know, speak to them privately,
in all tenderness, to restore them; and this know,
"`whoever turns a sinner from the error of his ways, saves a soul from death,
and hides a multitude of sins.`"
But if they will not hear, take two or three more,
and speak to them again in the spirit of meekness, waiting,
and seeking the Lord for their recovery; but if they will not hear,
but persist in wickedness, then acquaint the church,
whom the Lord in his wisdom will order to deal with them for his own glory.

And in all things you do, I beseech you, do unto others,
as you would be done unto yourselves, that so you may all in your measures,
stand as saviors upon mount Zion, to the glory of the Lord,
in the power of his own spirit, which will cause the whisperer, backbiter, false accuser,
and tale-bearer to be driven away, and cast out of the house of the Lord.
Thus, in the good order of the holy Spirit of our God, we may all live;
that he alone in his dominion may reign in us, and among us,
whose government is upon his shoulders,
and all the crowns of the glory of man cast down at his feet,
that he may be exalted in ordering every member of the body in their place and service,
to his everlasting praise and glory.--Even so,
dear Father! carry on your work in all the churches of the saints,
scattered over the face of the earth,
that in the unity they may be established in the Lord, being one, and his name one,
and all the contrary swept away with the breath of your mouth,
and brightness of your coming:--so come,
Lord Jesus!
Take to you your great power,
and reign in your authority in and among your dear children,
to the astonishment of the nations, and all people that are not born again,
and to the exaltation of your own name and kingdom over all, who are worthy to reign,
blessed forever, and of whose dominion there is no end!

And all you faithful laborers in the Gospel of Christ,
who in true innocency travail in his strength,
and seek not anything for yourselves in what you do,
but to glorify the Lord in establishing his people in the living
unity in his own spirit:--O! blessed are you among the people;
my soul praises the Lord for you, and blesses his name,
that ever he raised up such a spirit in you; that in all the riches of the spirit,
God gives to you, yet you remain truly poor in yourselves,
and in deep humility become servants to his people for the Lord`'s sake; and being poor,
you make many rich in that which will abide fresh and green in the winter storms,
and will not fade away in the terrible blasts
which will come for the trial of his people,
and cause all hearts to fail, but what are born of his own nature.
Oh! dearly beloved brethren, feel my enlarged love,
which flows to you in the life received and enjoyed through death,
where there is no variableness nor shadow of change.

I remain your brother, in the word of his patience, to endure the suffering,
according to his determination, with all that love the Lord better than their lives.

[.signed-section-signature]
W+++.+++ D.

[.signed-section-context-close]
Warwick Jail, 14th of Tenth month, 1668.

[.letter-heading]
William Dewsbury to Friends

[.salutation]
Dear Friends,

In the light of Christ wait upon him,
to renew you in the spirit of your minds to serve the living God.
My dear Friends, mind your calling, unto which you are
called, to wait in the light, to retain God in your knowledge,
to feel the work of regeneration perfected in you;
that you may truly learn to take up the cross daily,
and to feel the heavenly power manifest itself,
to raise you up in the life that makes self of no reputation,
and dries up the tongue of the Egyptian sea,
and brings all flesh to true silence in you before the Lord.
Then will not any be hasty to utter words before him,
but all in true watchfulness and prayer wait for
the heavenly inspiration of his holy Spirit,
to overcome your spirits, and to sanctify you,
in making you obedient to the heavenly government of Christ Jesus in you.

He will lead you out of your own thoughts and wills,
in a humble subjection to his blessed will, which will order you in all faithfulness,
to walk with God in your families, to be good examples by your good conduct;
that so you may have a testimony in the consciences of your children and servants,
and all with whom you have to do,
in having all your words and works seasoned with
the good savor of the spirit of the Lord;
that he may give you an assurance that the church of God is in every particular family,
and that you are his dwelling-place among the children of men.
Then will the angels of his presence pitch their tents about you,
in the day when this Scripture shall be fulfilled, as it is written,
"`Pour forth your vengeance, O Lord! upon the heathen that know you not,
and upon all the families that call not upon your name.`"

Dear Friends, be watchful in prayer always, that you may enjoy the heavenly life,
to exercise you in all faithfulness; strive to exceed in humility and carefulness.
In the name of the Lord Jesus Christ meet together, that he may exercise, guide,
and order you in all services for the blessed truth of our God; that,
in the meek spiritual life and love, you be subject to serve the Lord,
and one another in all tenderness of heart,
in doing unto others as you would have them do unto you.
Then will the Lord take delight in you,
and make you manifest to be his chosen jewels and saviors upon Mount Zion,
in repairing the breaches, and restoring the desolate,
and in love bringing back again those that have been driven away, or turned aside,
either to the right hand or to the left, in the hour of temptation and days of trial.

O, you meek, humble-spirited people of the Almighty God! lift up your heads,
and keep your minds stayed upon the Lord,
to help you to keep your habitations of peace within the gates of Zion,
where we have salvation for walls and bulwarks; whose confidence is in the Lord alone.
In him, I beseech you, live in the endeared love of Christ Jesus,
who gave his life to redeem us to himself,
and gives strength to his redeemed ones to forsake wife and children,
to give up our lives daily, in tumults, stripes, bloodshed, with cruel sufferings,
both in prison, and when at liberty, to bring enemies out of enmity,
in the light to be in union with God.
Oh! be entreated to seek the Lord,
to subject all your minds to the love of God in Christ Jesus, to rule in you;
then will the desire of my soul be answered, in your restoring and gathering to God,
as is before written,
who will then build you up in the unity of the spirit and bond of peace,
which will enable you with patience and meekness,
to weary out and overcome whatever is contrary to his pure,
peaceable and blessed nature:--the mouth of the Lord has spoken it,
through your brother and companion in the kingdom of
patience and tribulation in the Lord Jesus Christ.

[.signed-section-signature]
W+++.+++ D.

[.signed-section-context-close]
Warwick jail, the 10th of the Twelfth month, 1680

[.blurb]
=== A general epistle to be read in the fear of God, in and among the assemblies of his people.

[.salutation]
My dear Friends,

In the light of the Lord, all watch and pray,
that you may receive power through faith in the name of
Christ to reign over your own thoughts and wills.
Then will you delight in taking up the daily cross and mortifying the earthly members,
that your conduct may be as becomes the Gospel of our Lord and Savior Jesus Christ.
This will make you manifest to the witness of God in every conscience,
that you are the salt of the earth, that have kept your state and habitation in God,
and retain the sweet savory spirit of life, which seasons all your words and works,
and ministers grace to all with whom you have any concern,
to the exalting of God`'s blessed truth over all that watch for evil,
which will cause their eyes to fail, and frustrate their expectations forever.
Amen.

And, dear Friends, I beseech you,
be faithful upon all accounts for the service of the blessed truth of God,
to meet together in his holy fear;
that you may receive the holy inspiration of his spirit,
to exercise you in what service God is pleased to call you unto,
whether in prayer to God,
or in exhortation to build up one another in your most holy faith;
to raise up the life in all,
that every one who is overcome with the powerful and heavenly motions,
cast their mite into God`'s treasury, and give him his own.
Thus will you feel the increase of his government in you that are faithful,
in the true measure of light and life; and more and more he will give unto you,
to the edifying of one another in love.
You will become epistles written in one another`'s hearts,
with the pure spirit of the living God,
which will bind you up in the unity of the spirit and bond of peace;
and what exercise soever is met with, while you are in the mortal body,
pray to the Lord to keep you in the life of his own spirit,
that patience may have its perfect work; that if you be smitten on the one cheek,
turn the other cheek to the smiter also; and if you be reviled, revile not again,
but in deep humility and patience, wait in the pure, meek,
peaceable spirit of our Lord Jesus,
who was made perfect through sufferings;--so are his dear and chosen jewels,
who bear his name in righteousness, and have their eye to the God of their help,
and their confidence is in the Lord alone.

O you blessed of the Lord! be glad in his name,
who will not let any whose confidence is in him alone,
allow more than he will give strength to bear,
and will sweeten the cup of your tribulation with his blessed presence,
which will cause your hearts to rejoice, and sing in all your trials;
and will give you your portion forever with the blessed assembly,
that John spoke of in the 7th of the Revelations--a number that no man could number,
that had passed through the great tribulation,
and washed their garments and made them white in the blood of the Lamb;
therefore are they before the throne of God,
and serve him day and night in his holy temple;--and he
that sits on the throne shall dwell among them,
and feed them, and lead them to the living fountains of waters,
where God shall wipe away all tears of sorrow from their eyes, forever.
This is your portion, dear children of the living God, who in true love to him,
have waited upon him in the light of Christ,
to be buried with him in his spiritual baptism and made conformable to him
in his sufferings and death--and in the deep sense of your present strait,
being made conformable in measure to our Lord and Savior,
you cry as he did upon the cross, when he bore the sins and transgressions of his people,
"`My God, my God, why have you forsaken me?`"
Even so do you his dear children, in your measure,
passing through the great tribulations,
being made of the number of the slain of the Lord.

Here is first a passing through the great tribulation,
to be made of the number of the slain of the Lord; and,
being truly humbled into his blessed will, in a deep sense of poverty of spirit,--there,
wait upon the Lord, until he create you to a lively hope,
and give you a possession of his blessed life, that is hid with Christ in God,
and so marry you to himself in his own righteousness,
which he gives you for your wedding-garment.
The love of God constrains you to walk in all strict
observations that are required of you to be done;
but no more to lean upon them for life,
but have all your obedience accepted of God through faith in the light, life,
and name of Christ, in whom you now are the righteousness of God forever,
in giving up freely to be guided by his spirit in faithfulness to the end.

O! ever blessed and happy people, who do witness fulfilled in you what is here written;
lift up your heads and rejoice in the Lord, and in his humble, meek, and pure spirit,
which makes self of no reputation;
but through your obedience to Christ Jesus the true Light,
in whom you come to witness the Lord to be one,
and his name one--and you that never had power to believe in his name,
until he gave you power to believe;--you are one in the Lord forever.
And here is the joyful unity with the Father in the Son,
and one with another in the love of Christ, who bought us with his blood,
which the gates of hell can never prevail against.

And all you, my ancient brethren and sisters,
who have obtained this blessed dominion and
everlasting inheritance,--I bless God for you,
who I do believe will take care to answer the desire of my soul,
for the comfort of the young and tender babes;
for whose sake I had this concern upon my spirit,
to lay before them the true passage into the footsteps,
where the tribulated companions have traveled that are married to the Lord of life,
and have upon them their wedding-garment,
that they may not come short who are upon their travel
towards the same inheritance in Christ the true light.
I dearly beseech you, whom God has sealed up with his holy Spirit,
to your full assurance of God`'s everlasting love in Christ Jesus,
that you watch over the tender and tribulated ones, and in what can possibly be done,
strengthen their faith;
that they may come into the heavenly unity with the Father in the Son,
and sit down with all them who have been made
conformable to Christ in his sufferings and death;
and that, in the heavenly resurrection, blessed and everlasting peace,
they may sing hallelujah and high praises to the Lord their
God,--over all the wrath that is in the children of men,
which will come to an end, and vanish away like smoke,
before you whom the Lord has called, in meekness, and patience,
to bear his name in righteousness, in the sweet savory spirit of Jesus Christ, over all,
blessed forever, Amen.--In which, the Lord keep you all, with my soul,
faithful unto the end,
is the breathing of the spirit of your brother and companion in
tribulation and in the kingdom and patience of the Lord Jesus Christ.

And further, I have this to communicate to my friends and brethren:
that what has come to pass these late years,
has been for lack of watchfulness to be guided by the spirit of the Lord.
Love has been quenched in many, in whom offenses have entered, and separation followed;
which has deeply wounded my spirit, having endeavored,
to the utmost of my power in the love of God, to prevent such proceedings;
and so have I done in many years past, by preventing papers ready to be printed,
from being published, that were of a tendency to quench the love of one towards another.
And when Jeffery Bullock`'s papers were published in print,
which would appear to the reader of a tendency leading to the breach of unity,
which would cause the enemies of God to rejoice; it did so wound my spirit,
that for many weeks those who saw me did not
expect that I should continue long in the body;
but God in his mercy restored strength in his appointed time.

And when I heard,
that some in the west intended to publish in print against some Friends,
I bore my testimony against such proceedings, and told one who favored what was intended,
that I would have my hand cut off before I would exercise it in such undertakings;
and desired him to speak to W. R. +++[+++William Rogers,]
that he would not proceed in publishing anything of that nature; for if he did,
it would be a prejudice to truth, and would produce very sad consequences,
and my spirit would be deeply wounded, as it is this day, through these proceedings,
of those who voluntarily, through lack of love,
cast away the judgment that is given to the
saints to keep all sweet and savory among us,
into the hands of the enemies of God, as an inlet for them to come into the midst of us,
to sit as judges and trample upon us.

So this is written to clear my conscience of all false reports cast upon me,
as that I have encouraged what is brought forth of this kind, and to satisfy all Friends,
that I have labored according to the ability God has given me,
to prevent the publishing all things of that nature, as aforesaid.
And I have admonished all concerned that I could meet with,
to have a care of watching for evil, lest they provoke one another to wrath,
and so quench love; but rather to look at the good in one another, and,
in the love of God,
labor to preserve them out of any weakness which they saw lay near to attend them;
that so the pure, holy Spirit of life and love, which first gathered us into itself,
to be a people in God,
and in his authority to reign over what is contrary to his blessed nature,
may again restore, where it is lacking,
in the universality of its blessed power,--making up the breaches,
and restoring the desolate ones,
and causing every one that professes the blessed truth of God,
to love their neighbor as themselves; and so to do unto all,
as they would have others to do unto them.
Thus, all concerned in this exercise,
who seek the peace of his people in the measure of the grace of God in Christ,
may stand as saviors upon Mount Zion, to the honor of the name of the Lord our God,
and the comfort of all who love not their lives unto death, serving the Lord,
and his dear and chosen people, in the meek, patient,
and peaceable spirit of our Lord Jesus Christ.

In which, the Lord keep you all with my soul; that, in his pure and peaceable dominion,
we all may throw down our crowns before his throne, and unanimously sing,--All glory,
honor, praises, thanksgiving, and dominion be given to him,
who is found worthy to sit upon his throne in all our consciences, Christ Jesus,
the true light, and hope of our glory! even so be it,
with all that profess his blessed truth, says my soul in the name of the Lord.

[.signed-section-signature]
W+++.+++ D.

[.signed-section-context-close]
From Warwick, the 8th day of the Third month, l683

[.letter-heading]
William Dewsbury to Friends in Bristol

My dear, faithful, suffering brethren and sisters in Bristol, Gloucester, and elsewhere,
for the word of God, and testimony of our Lord and Savior, Jesus Christ: Oh,
lift up your heads,
you whose days are prolonged to see this blessed day which was
sounded in your ears above twenty years by-past,
and are counted worthy to receive this crown of his suffering spirit.
All you that freely resign to suffer for his name in true sincerity,
shall reign forever with him in eternal glory.
Therefore, in the name of the Lord, I beseech you all, convinced of God`'s blessed truth,
not to lend your ear to any counsel in you, or without you,
that would cause you to fly sufferings, and so deny the suffering Jesus before men;
for if you do, you know it is written, that he will deny you before his heavenly Father, etc.
But all you who so love the Lord, that you dare not but do as godly Daniel did,
walk with your God as at other times, with the hazard of both estate, liberty,
and life--oh! blessed be the day that ever the Lord crowned you with
this frame of spirit in receiving Jesus to be your guide.
Even so, the Lord keep you, and lead you to the living fountain of water,
which in the light is opened in you.
Give not way to your own thoughts,
but in the light judge them down as fast as they appear;
then will you be kept out of the straitness of your own bowels,
in heavenly enlargedness in the will of God, whose thoughts are good and not evil,
to give you all an expected end, in answering the desires he has raised up in you,
to do his will.

Therefore arise in the pure, peaceable spirit of the Lord;--cast your care upon him;
he will arm you with patience to endure the tribulation,
which will cause the beholders to admire,
as it is written in the Scriptures of truth:--
behold the patience and faith of the saints,
which will overcome all that withstands the rising of his glory,
who is the God of our help,
over all blessed forever--here is the rest of your tribulated
brother in the kingdom and patience of Christ Jesus.

[.signed-section-signature]
W+++.+++ D.

[.signed-section-context-close]
Warwick, 17th of the Fifth month, 1682

[.letter-heading]
William Dewsbury to Edward Nightingale of York

[.salutation]
My ancient Friend!

Whom the Lord, counted worthy to receive his blessed truth,
with many in that city and county, when he sent forth his servants,
and called me to forsake wife and children, and to give up my life daily unto his will,
to endure stripes and bruises in many tumults, with the rest of my faithful brethren,
who loved not our lives to death for your sakes,
to gather you and all that received the truth,
that you might enjoy the presence of the Lord.
And among many others, we counted you worthy to receive his servants,
who meet together in the heavenly unity in the truth; for which, both you and I,
with many of the servants of God, were put into prison,
as many of his servants are this day.
And the blessed presence of God kept, and does keep,
them that truly fear his name in sweet unity and peace in himself and one with another,
to their everlasting comfort, and to the confounding the enemies of God,
who beheld their steadfast standing,
and entire union in bearing their faithful testimony in
whatever they were called unto for the truth of God.
This did not only confound God`'s enemies,
but many were convinced and received the truth in the love of it,
beholding the unity of faithful Friends, to their comfort,
and the honor of the name of the Lord; which caused my soul,
with the rest of the faithful laborers, to praise the name of the Lord,
in having blessed the travail of our souls,
and given us to see the fruit of our labor in his vineyard,
and the peace and unity of his people.

But, of late I have heard that you, my ancient friend, Edward Nightingale and John Cox,
with some others in that city,
do meet together in a separating spirit apart from the rest of Friends in the city,
which casts a stumbling-block in the way of many.
And, instead of gathering people to receive the truth, you scatter and drive them away;
and it gives great advantage to them that watch for evil, and is of a bad savor,
and wounding to the spirits of them that truly fear the Lord.
I can truly say, your meeting in that separating spirit,
which is such an evil savor in the nation, has been,
and is more afflicting to me than all the persecutions
and imprisonments I have endured unto this day.

Therefore, I entreat and beseech you, my ancient friend, Edward Nightingale,
with all that meet in the separation from the rest of Friends in the city,
to turn your minds to the light of Christ in you,
which will let you see you have not done well,
and with it judge that which has led you to separate from Friends;
and return to meet with them in the city, in the sweet concord, love,
and unity in the life of the blessed truth, as in the days of old and years past.
I am a witness with the rest of faithful Friends, that in all our meetings,
whether in the prison or in the city, we never lacked the sweet appearance of Christ,
our life, in us and among us, according to his promise and to our comfort.
And so it is now, with all that meet in his name, and in unity with his people,
as we did in those days.

It was many years before the enemy could get any entrance to
make a breach among those that profess God`'s blessed truth,
to draw some into a self-separation, as he has done you and too many more elsewhere.
I do assure you, it is the work of the enemy of your souls.
You should not have separated, but have kept your places among Friends;
and not have taken offense because they saw there might be some
service for truth in meeting twice on the first-day of the week.
It is very likely, that some in that city who had a love to truth,
might get an opportunity to come to one of those meetings.
It is very much to me, how you let the enemy so get over you,
as to cause you to separate from Friends;
whereas had you kept your places in meeting with them,
you in time might have seen a service in meeting twice a day as well as they.
You may be sure that separation neither restores any to the love of truth,
nor gathers any to God,
but rather scatters and drives away some that were gathered in love to truth
by the painful and faithful laborers who were sent of the Lord.
Therefore, in the yearnings of the love of God to you, I once more beseech you,
that in humiliation you wait in the light of Christ,
and he will let you see how the enemy led you out of your places,
when you separated from meeting with Friends; and in yielding obedience to the light,
it will bring you into your places again, to meet with Friends to your comfort,
and the honor of the name of the Lord, according to the counsel of the Lord in my heart,
here sent unto you.

But if you reject the counsel of the Lord in these lines,
which in his love I am moved to send unto you, then shall I lament your condition,
because of the evil consequence your separation will produce to your sorrow,
and the wounding of many whom God would not have
wounded;--for which you must give an account.
And before you lay down your heads in peace, you will remember me,
who have not hid from you the counsel of the Lord.

[.signed-section-signature]
W+++.+++ D.

[.signed-section-context-close]
Warwick, 21st of Eleventh month, 1684

[.letter-heading]
William Dewsbury to Friends

Dear, precious, and beloved Friends,
called in the light of the Lord to stand living witnesses for God,
in the midst of a crooked, wicked, perverse, and untoward generation.

Dear Friends, in the pure and meek spirit of the Lord, enter into the chamber of rest,
which God has prepared for you in his unlimited power.
Stay your minds, and keep your confidence, and hold fast your faith,
that so the door may be shut,
that not anything may enter which would produce feebleness of mind, faintness of spirit,
or in the least measure cause you to stagger at the promises of the Lord,
who has promised he will never leave us, nor forsake us.
Then, what trial soever any of us be called unto, who love the Lord,
and have given up our names unto him, he will not allow one hair of our heads to perish,
but what shall be to the glory of his name, and the comfort of our souls forever.
Many of us are witnesses of the faithfulness of our God,
in making our passage pleasant through all trials and
sufferings that have been unto this day;
which is now manifesting itself, as was proclaimed among you in times past.

Therefore, I beseech you all, dear Friends, put not the day of the Lord afar off;
for a general trial will come on all who make mention of the name of the Lord,
that it may be known, who are truly born of God and who are not;
that his precious jewels may be made up,
who shall more and more shine forth in the brightness of his glory,
being established in his light, life, and love,
against which the gates of hell cannot prevail,
because the Lord is the strength of all that are born again.
And for their sakes, he is making a short work in the earth,
to hasten his peculiar people through these trials,
according to the determination of his own will, for the glory of his name,
and the comfort of the righteous seed which the Lord has blessed; that so,
he may establish peace in the earth, and purity and holiness among the children of men,
which will be the end of all these tribulations.

Therefore, wait in the faith and patience, and be faithful in obedience,
as at other times, with the loins of your minds girt up to the Lord,
to rest in his unlimited power, and reign in a quiet still mind,
giving up both goods and life freely; casting all your care upon the Lord;
who will answer the expectation of his people, and work a mighty deliverance,
neither by sword nor spear, but by his own outstretched arm,
in the day of his dreadful vengeance, which he is hastening upon the earth,
that shall cause all hearts to fail who know not God.
The wicked shall confess to his righteous judgments,
and the righteous shall bow before him, and the heathen shall know he is our God,
and that we have not trusted in his name in vain;
for he will judge righteously upon the earth,
and give unto every man according to the deeds done in the body.

Then, woe to the proud and wicked, it shall go ill with them!
Ah! but, you dear suffering innocent people of the Lord, lift up your hands and rejoice,
for the Lord is tender over you as towards the apple of his eye,
and great is the reward of the faithful;
it is you who shall reap the fruit of your doings, and shall rejoice,
when the wicked shall howl, in the sense of his fierce wrath,
for he will get him self a glorious name,
in consuming his enemies with the breath of his mouth, and the brightness of his coming.

Even so, hasten your work, oh Lord! it is the breathing of my soul, with all yours,
that your dear children may be delivered from their oppressors,
that in your power and life they may be kept by you,
to the perfecting your glory forever!--where is the rest of your dear brother,

[.signed-section-signature]
W+++.+++ D.

[.letter-heading]
William Dewsbury to Friends in Yorkshire.

[.salutation]
My dear Friends, who are convinced of the blessed truth,

Wait in the light,
that you may truly experience Christ in you, baptizing you with the Holy Ghost and fire,
rendering vengeance upon all in you that obeys not the Gospel of our Lord Jesus Christ,
and so you will come to witness you are of the number of the slain of the Lord,
and conformable to him in his sufferings and death.
And you that are in the sense of your miserable and lost estate, wait upon the Lord,
weeping and seeking the Lord your God,
asking the way to Zion with your faces thitherward,
until the Lord cause your souls to hear the voice of the Son of God,
and they that hear his voice live, but not in themselves, nor to themselves,
but the life you then live is Christ in you, and you in him.

Oh! blessed are you that witness what is here written;
for you are the true members of the body of Christ, who abhor yourselves,
and admire the Lord with all his saints, in whom he is admired.
Oh! praise the Lord all you his dear children for his wonderful works,
in leading you in his narrow way, and through his strait gate, which so few find.
The Lord keep you by his mighty power, that you may contend for the faith, and keep it,
which the Lord has delivered unto his saints,
that through faith you may have victory over your own wills, and over the world,
with all the pomp, pride, and pleasure of it, and so delight in the daily cross,
to be the well-seasoned, savory people, in all your words and works,
to glorify our Father which is in heaven:--even so be it with you,
is the prayer of your ever-loving brother,

[.signed-section-signature]
William Dewsbury

[.the-end]
The End
